DFE-Digital/schools-experience

- app/views/schools/placement_dates/configurations/new.html.erb
- config/locales/en.yml
- features/schools/placement_dates/primary_and_secondary_school_configuration.feature
- features/schools/placement_dates/secondary_school_configuration.feature
- features/step_definitions/schools/placement_dates/placement_date_steps.rb
This is hopefully simpler and more direct without losing any meaning
N/A
This is how the radio buttons used to look:
It seemed a bit clunky, we tried to streamline it slightly
Still make sense? No typos?
> Try rewording the experience type radio buttons

- app/views/candidates/home/index.html.erb
- features/step_definitions/candidates/landing_page_steps.rb
SE-1835
Link to manage schools isn't obvious
Make it more obvious. Also reword 'primary and secondary' to 'primary or secondary' so it makes sense.
Do the changes make sense?
> Add manage schools link to candidates home page SE-1835

- features/support/database_cleaner.rb
- lib/database_cleaner/prevent_disabling_referential_integrity.rb
SE-1934
Currently Database Cleaner in CD is very slow - which makes all the cucumber tests slow. This is caused by the slow truncate support on Azure hosted Postgres.
1. Use a truncate strategy at the start of a test run
2. Use delete strategy to wrap individual tests
3. Remove the disabling of referential integrity since this isn't supported with the database account used
4. Added a manually maintained list of tables and the order to delete_all on them.
2. Opinion on manually maintained list of tables to clean - seems a fair trade off to me and may become more beneficial if we increase release frequency.
> SE-1934 Use deletion strategy for Database Cleaner

- app/services/candidates/registrations/personal_information.rb
- config/locales/en.yml
- spec/services/candidates/registrations/personal_information_spec.rb
SE-1966
The date of birth validation message only accounts for the possibility that a candidate is too young
Split the validation so being too young and too old are checked separately.
The upper age limit is 100 years old 👵🏼👴🏻
> Improve the validation messages for date of birth SE-1966

- app/models/bookings/placement_date.rb
- config/locales/en.yml
- features/schools/placement_dates/new.feature
SE-1969
Two validation messages appear when no date is entered, one of them hasn't been overridden
Separate the validations out (a missing date isn't invalid) and add some improved text for the missing date error
Ensure changes make sense
> Improve placement date missing date validation SE-1969

- app/controllers/schools/placement_dates_controller.rb
- features/schools/placement_dates/new.feature
- features/schools/placement_dates/primary_school_configuration.feature
Until capped dates have been implemented there's no need to show the
configuration screen for primary dates. Currently when the capped flag
is disabled the screen is entirely empty. Also mark the associated
features as @wip for the time being
SE-1989
> Skip configuration for primary dates

- app/controllers/candidates/registrations/subject_and_date_informations_controller.rb
SE-1986
If the Candidate goes back to edit their subject from the Summary screen, they are then taken through the personal info and contact info steps.
This is caused by the #edit screen for SubjectAndDateInfo sending a POST not a PATCH, that in turn is caused by the controller not loading existing date for the #edit and #update actions.
1. Change edit action to load from current_registration
2. Change update action to load from current_registration
Note: This PR contains only the code fix. Tests will follow on in separate PR but those are going to take longer to write and I want to get this through for QA
1. Code review
> SE-1986 incorrect flow after date change

- config/locales/en.yml
N/A
There was no validation message when duration was blank, it reverted to Rails' default
Set the validation message
Ensure it's sensible
> Add missing duration validation message when blank

- config/locales/en.yml
Typo fix, the revealing panel on degree stage was using the incorrectly spelt field name :shame:
Added text to the local file for the field with the correct spelling
> Fix typo'd label

- app/controllers/schools/placement_dates_controller.rb
- app/models/bookings/placement_date.rb
- app/models/bookings/school.rb
- config/locales/en.yml
- features/schools/placement_dates/primary_and_secondary_school_configuration.feature
- features/step_definitions/schools/placement_dates/placement_date_steps.rb
- spec/models/bookings/school_spec.rb
SE-1981
When failing to enter a placement date, when the form is re-rendered the `supports_subjects` flag had been already set by `#create`.
Now instead of setting the flag in the previous manner regardless of the
situation it's only set if validation has passed and there's a new
validation rule that ensures it's been set manually if the school
supports primary and secondary phases (ie has at least one phase that
does support subjects and one that doesn't)
Do the changes look sensible? Could the new methods on `Bookings::School` be better named? They look ok to me without being too wordy, but perhaps I've overlooked something
> Improve supports subjects validation SE-1981

- app/services/bookings/gitis/contact.rb
- app/services/bookings/gitis/entity.rb
Now we use ActiveModel attributes, we can rely on its behaviour to assign the defaults when creating new Contacts.
1. Use `:default` on attributes instead of custom code in the initializer
1. Code review
> Use defaults feature on Active Model

- app/services/candidates/registrations/application_preview.rb
- app/views/schools/placement_requests/show.html.erb
If the user has entered something in this field make sure it is surfaced
in the preview, emails, and when the school views the placement request.
SE-1967
We weren't surfacing this field in the ui
Complete the candidate registration wizard choosing other as a degree stage, expect to see the degree stage explanation on application preview. Finish the wizard, view the placement request as the school, expect to see the degree stage explanation on the placement request show view
> Display degree_stage_explaination (sic)

- azure-pipelines.yml
Currently if dependencies get updated on master, a new cached base image is
created but if the are updated on development, than one is not.
Normally dependencies are updated on master but if a new version of the form
builder is merged to development than development, and subsequent branches, will
remain uncached until the dependency change makes it out to master.
> Use development branch images for docker cache

- app/notify/notify.rb
- spec/notify/notify_spec.rb
SE-1994
A school was receiving duplicates emails as they had entered the same email address for primary and secondary contact.
De-dup email recipients before sending emails
> Remove duplicates before sending emails

- app/services/schools/dfe_sign_in_api/client.rb
SE-1955
Relates to deploying earlier work around the DfE Sign In API - currently we error if env vars are not set, but just disable features if they are blank.
1. Just disable features if all required env vars are not set.
1. Code review
> SE-1955 Handle unset env vars

- app/forms/schools/placement_requests/add_more_details.rb
- config/locales/en.yml
- spec/forms/schools/placement_requests/add_more_details_spec.rb
SE-1979
We were falling back to the default rails validations in a few spots on
the create booking wizard.
Also we were missing a validation to ensure the format of the contact_email is
correct.
Add missing error messages to locales file. Add validation for format of contact email
Should look sensible and have correct spelling!
> Add missing validation text

- app/controllers/schools/confirm_attendance_controller.rb
SE-1936
If the user hits the back button in the browser then resubmits the form
then some of the bookings in the params might not be in the
unlogged_bookings collection, causing an error to be thrown in the
School::Attendance object.
Reject any params that don't correspond to an unlogged_booking.
Testing.
From the confirm attendance screen, mark some bookings as attended or not, submit the form, hit back in the browser, re submit the form, expect there to be no error.
> Ensure the params match the bookings

- app/helpers/schools/placement_requests_helper.rb
- app/views/schools/placement_requests/_cancellation.html.erb
- app/views/schools/placement_requests/show.html.erb
- app/views/schools/withdrawn_requests/show.html.erb
- features/schools/placement_requests/show.feature
- features/schools/withdrawn_requests/show.feature
- features/step_definitions/schools/placement_request_steps.rb
If the request has been withdrawn/rejected display that information when
viewing the placement request show page.
SE-1727
placement_request/show wasn't displaying the cancellation details for cancelled requests.
Display cancellation information on cancelled placement requests.
Add missing bread crumbs on placement_request show
Reject and withdraw a placement request. Visit the placement request show page, expect to see the correct details. Visit the withdrawn requests page expect to see the correct details.
Check spelling
> Se 1727/show cancellation reason on placement request show

- app/services/bookings/gitis/contact.rb
SE-2002
Currently we attempt to update the users second preferred teaching subject. If that has been updated to 'no subject' though we attempt to set it to blank which Gitis wont accept
1. As a stop gap, just don't update the second preferred teaching subject.
> SE-2002 Stop updating secondary teaching subjects

- app/models/bookings/placement_request.rb
SE-2003
The recent scoping change was causing in-flight placement requests to fail as their subject couldn't be found
Remove the scoping from `#requested_subjects`
Ensure everything still works. This shouldn't cause any further problems because `#requested_subject` is only really used for display purposes
> Add unscoped to the Bookings::Subject find

- app/services/bookings/gitis/contact.rb
- app/services/bookings/gitis/entity.rb
- spec/services/bookings/gitis/entity_spec.rb
SE-2002
As part of a latent bug we're potentially attempting to assign Preferred Teaching Subjects to null which isn't valid.
1. Reverted earlier solution of skipping all updates odata.bind's for contacts
2. Just skip the assignment for now if its null
1. Code review
> SE-2002 Dont assign odata.bind to null

- app/views/schools/dashboards/_manage_dates.html.erb
- app/views/schools/dashboards/_no_availability_info_warning.html.erb
- app/views/schools/dashboards/_no_placement_dates_warning.html.erb
- app/views/schools/dashboards/show.html.erb
SE-1990
The no dates/availability warnings were being displayed in the dates section which is half way down the dashboard
Move the warnings up to the top of the dashboard
> Move no date warnings up to top of dashboard

- app/controllers/schools/base_controller.rb
We've been getting a number of Invalid authenticity token errors on
production due to a null origin header being present.
Looking in sentry this seems to have only effected schools, the most
likely explanation is due to their firewall settings or some type of do
not track plugin.
Disabling this check so schools can continue to use the service.
SE-1947
Set the Origin header to 'null', make a post request in the schools namespace, expect not to be shown the session expired page.
> Disable forgery protection for schools namespace

- app/controllers/candidates/registrations/educations_controller.rb
- app/services/candidates/registrations/application_preview.rb
- spec/controllers/candidates/registrations/educations_controller_spec.rb
SE-1998
Started off as adding a missing dash to the degree stage explanation row, this uncovered another bug where users can go back and change their degree stage and the explanation remains in
Add the dash to degree stage explanation on the check answers screen and unset the degree stage explanation when a option that doesn't need an explanation is picked
> Fix degree stage explanation display SE-1998

- app/helpers/candidates/school_helper.rb
- app/models/bookings/school_search.rb
- app/models/bookings/subject.rb
- spec/helpers/candidates/school_helper_spec.rb
SE-1917
It wasn't clear which subjects had been selected from filters when looking at the results
Make the filtered subjects bold in the school listing
Ensure the changes look sensible
> Embolden matching subjects SE-1917

- config/initializers/active_record_invalid_error.rb
- spec/models/bookings/booking_spec.rb
- spec/models/bookings/placement_date_spec.rb
2021
Currently we are loosing the fieldnames in the RecordInvalid exceptions which
makes it hard to debug the source of the error.
The exception messages is not surfaced to the user so changed the definition of
RecordInvalid to include a lower level representation of the error messages
with more complete information.
1. Behavioural test - do the errors in forms still come out correctly
2. Sanity check - its not the nicest solution but should have very limited scope for problems at this point and does provide us with the information we need.
Longer term will need to change the form builder to not use the full messages methods, then those can be revert to actually being full messages
> Patch ActiveRecord::RecordInvalid exception to bypass translations

- app/views/schools/placement_dates/edit.html.erb
- features/schools/placement_dates/edit.feature
2030
The page title is currently misleading - it implies the user can amend the Placements date when in fact they can only amend other details of the Placement Date
1. Amended the page title
> SE-2030 Title change on edit placement date

- app/controllers/schools/on_boarding/dbs_requirements_controller.rb
- app/views/schools/on_boarding/dbs_requirements/_form.html.erb
- features/schools/onboarding/dbs_required_toggling_fees.feature
- features/schools/onboarding/dbs_requirements.feature
- features/step_definitions/schools/onboarding_steps.rb
SE-1839
The text box that appears when school admins pick 'No' for whether a DBS check is required isn't necessary
Remove the check box and references to it in the test.
Ensure it looks sensible. We should probably think about removing the field at some point too, but we need to make a decision based on the data held.
> Remove explanation text field for no DBS required SE-1839

- spec/factories/bookings/school_factory.rb
Currently we now have enough tests that the school factory is automatically generating the magic URN of 11048 used for some tests. This can then potentially result in a clash depending upon ordering.
1. Don't offset URNs in order to avoid the clash.
2. Do the tests pass
> Use lower URNs for test schools to avoid clash

- spec/models/candidates/school_search_spec.rb
Whilst debugging a separate issue I encountered an ordering bug in a different test - its assuming results will appear in a certain order but doing nothing to ensure that is the case.
1. Stop checking for specific order
2. Do tests still pass
> Fix for ordering bug in array comparison

- app/models/bookings/subject_sync.rb
- spec/models/bookings/subject_sync_spec.rb
SE-2032
Synchronising subjects with Gitis is currently erroring. This is caused by the change to exclude subjects from the default scope. 
1. Use unscoped for retrieving the list of subjects
1. Code review
2. Does the new test pass
3. Observe once it reaches staging
> SE-2032 Gitis subject sync

- app/forms/schools/placement_dates/subject_selection.rb
- app/views/schools/placement_dates/configurations/new.html.erb
- app/views/schools/placement_dates/subject_selections/new.html.erb
- config/locales/en.yml
- features/schools/placement_dates/secondary_school_configuration.feature
- features/schools/placement_dates/subject_selection.feature
- features/step_definitions/common_steps.rb
- features/step_definitions/schools/placement_dates/placement_date_steps.rb
- spec/forms/schools/placement_dates/subject_selection_spec.rb
Reopening #1227 due to some Github weirdness
SE-1996
The 'All subjects' box at the top of the subject checkbox list when adding/configuring a placement date was superfluous, it was re-asking the same question as the previous page.
Remove the 'All subjects' checkbox and the specialised logic that made it work, now it's just a plain collection of check boxes.
> Remove all subjects checkbox SE-1996

- app/controllers/concerns/candidates/registrations/current_registration.rb
- config/routes.rb
- features/candidates/registrations/verify_your_email.feature
- features/step_definitions/candidates/registrations/verify_your_email_steps.rb
SE-1992
Previously registrations were held in session. They were then migrated to go straight to Redis, with the session only containing the key for the data in Redis.
Compatibility support for legacy sessions is no longer needed now all sessions will have migrated.
1. Remove the legacy route
2. Remove the legacy session support
1. Code review
2. Do the tests still pass
> Removed old unneeded verification route

- spec/factories/candidates/registrations/registration_session_factory.rb
- spec/services/candidates/registrations/registration_session_spec.rb
- spec/support/stubbed_candidates_school_context.rb
Within the specs, the RegistrationSession factory was creating PlacementDates against different
schools than the RegistrationSession was against
1. Use the supplied URN in the factory
2. In stubbed school context, try to find the school first before blindly creating one with the potentially clashing URN.
2. Do the tests still pass
> Use correct URN in RegistrationSession factory for PlacementDate

- app/views/pages/dfe_signin_help.html.erb
- app/views/schools/show.html.erb
- config/routes.rb
SE-1768
The help text around DfE Sign-in was clunk and not especially useful (see JIRA ticket)
Make the text simpler and more informative
Ensure the new guidance makes sense
> Added DfE Signin help page, link from schools home

- Gemfile
- Gemfile.lock
- azure-pipelines.yml
- docker-compose.yml
N/A
Currently test failures end up just dumped into the logs, leaving the developer trying to wade through the console output. This is a nuisance with RSpec but a real faff with more extensive  cucumber output.
1. Upload test results from each stage of testing to Azure DevOps. These are then accessible from the DevOps interface
1. See the tests tab for the following runs
a) 20191121.9
b) 20191121.13
c) 20191121.17
2. Does the pipeline still run correctly
> Upload test failures into CI

- app/views/candidates/schools/_access_needs_statement.html.erb
- app/views/candidates/schools/_phase2.html.erb
- features/candidates/schools/show/full_school_details.feature
- features/schools/onboarding/school_profile.feature
- features/step_definitions/candidates/schools/show_steps.rb
- features/step_definitions/schools/onboarding_steps.rb
N/A
We had a discussion about the ordering of the school profile and this is a quick (20 minute) shuffle. Not intended to be merged yet but up for discussion when we're all back in the office
* Move the dates/subjects list _above_ the map
* Move accessibility info to the right hand column
* Move the phases to the top of the right hand column and format as a list
Discuss. Does the profile look better overall? Is the restructuring of the right hand column sensible? Does it feel more balanced? Does the dates/subjects list being above the map always make sense?
> Reorganising school profile content

- app/helpers/text_formatting_helper.rb
- app/views/candidates/schools/_phase2.html.erb
- spec/helpers/text_formatting_helper_spec.rb
Added conditional_format helper for use in definition lists. Only uses
paragraphs when necessary.
SE-1463
The experience details field had got missed in the original work to maintain formatting
1. Maintain the formatting of the experience details
2. Added helper to only apply p tag formatting if text is actually multiline
1. Code review
2. Does the output look right
> Format experience details field

- config/locales/en.yml
- spec/services/candidates/registrations/personal_information_spec.rb
SE-1966
The 'Enter a valid date of birth' part of the error message is unnecessary
Remove it
Sense check
> Remove 'enter valid date' from date of birth error

- app/views/schools/rejected_requests/index.html.erb
- app/views/schools/rejected_requests/show.html.erb
- features/schools/rejected_requests/index.feature
- features/schools/rejected_requests/show.feature
- features/step_definitions/schools/rejected_requests_steps.rb
SE-2039
The new rejection reason hadn't been added to the rejected requests index or show pages
Add it where required and ensure presence via features
Ensure everything makes sense
> Add rejection reason to rejected placements index SE-2039

- app/jobs/bookings/reminder_builder.rb
- app/jobs/cron/reminders/next_week.rb
- app/jobs/cron/reminders/tomorrow.rb
- app/models/bookings/booking.rb
- app/notify/notify_email/candidate_booking_reminder.b3e75ee5-61cf-49c5-a145-c0710c54347d.md
- app/notify/notify_email/candidate_booking_reminder.rb
- app/services/bookings/reminder.rb
- spec/jobs/bookings/reminder_builder_spec.rb
- spec/jobs/cron/reminders/next_week_spec.rb
- spec/jobs/cron/reminders/tomorrow_spec.rb
- spec/models/bookings/booking_spec.rb
- spec/notify/notify_email/candidate_booking_reminder_spec.rb
- spec/services/bookings/reminder_spec.rb
SE-1953
Currently there's no contact between the service and candidates from the point the booking is accepted until it begins.
Every morning at 02:30 and 02:35 jobs will run automatically that select all uncancelled bookings that are due one week and one day in the future, and for each of these jobs a reminder email (currently closely matching the confirmation email in terms of content) will be queued.
The queuing is wrapped in a transaction meaning that if it fails for some reason no reminders will be sent rather than some.
Does it look sensible? The populating the queue stage _could_ be further refined but in order to run it incrementally and repeatedly we'd need flags or events (`weekly_reminder_sent: true`) and build that into the query. At our quantities that might be …
> Reminders SE-1953

- app/services/candidates/registrations/personal_information.rb
- config/locales/en.yml
- spec/services/candidates/registrations/personal_information_spec.rb
SE-1977
Gitis only allows 50 chars for firstname and lastname fields.
1. Added length validation (max: 50) for firstname on PersonalInformation
2. Added length validation (max: 50) for lastname on PersonalInformation
> Validate length of firstname and lastname

- docker-compose-chrome.yml
- docker-compose-firefox.yml
SE-2042
There seems to be a bug (possible memory issue) in the latest release
of the selenium-chrome and possibly selenium-firefox images. We 
should be using specific versions anyway since it will make it easier to 
isolate problems when we upgrade the version.
1. Change docker-compose.yml to use a specific version
1. 15 successful runs in CI with this branch - previous failure rate was somewhere around 1/3 or 1/4
2. 3 successful runs in CD - previous failure rate was 100%
3. This doesn't resolve the underlying question of why cucumber is failing with new versions of selenium-chrome but that can get investigated off on its own branch.
3. Sanity check
> Use earlier selenium-(chrome|firefox) docker release

- Gemfile
- Gemfile.lock
- config/database.yml
- config/environments/test.rb
- config/initializers/redis.rb
- spec/controllers/candidates/registrations/confirmation_emails_controller_spec.rb
For Christmas I bring you faster (parallel) test runs - lets make use of those cores!
1. Added `parallel_tests` gem
2. Change to swap the Redis DB according to the process being run
3. Fixed a latent randomisation bug - with `rspec --seed=3374` one of the tests would fail because it assumed the Redis key wouldn't exist, when actually it might (depending upon ordering of specs)
1. `bundle exec rake parallel:create`
2. `bundle exec rake parallel:prepare`
3. `bundle exec rake parallel:spec RAILS_ENV=test`
4. `bundle exec rake parallel:features RAILS_ENV=test`
Behold 12 sec rspec runs and 40 sec cucumber runs !!
> Enable parallel tests

- app/controllers/healthchecks_controller.rb
- config/routes.rb
- spec/controllers/healthchecks_controller_spec.rb
SE-2037
At deployment time, we want to check nothing has been changed around API configuration which will interfere with the successful running of the website
1. Added and API Healthcheck endpoint, protected by deployment env vars for security
2. Note the DFE Sign In API checks are tied to whether the service is enabled, so they'll only run at the point we roll that service out
2. Do the tests pass
> SE-2037 Added API health checks endpoint

- config/initializers/canonical_redirect.rb
- config/routes.rb
- spec/requests/canonical_url_redirection_spec.rb
SE-2037
We have a working API healthcheck endpoint but this cannot work on the staging slot because of the canonical redirection. More over, this is a potential future 'trap' for other developers who may be hit by the same issue.
1. Move the healthcheck url to be nested under the '/healthchecks' path
2. Allow any paths under `/healthchecks/` to bypass the canonical redirection
3. Added test to verify generic `/healthchecks/*.txt` can bypass canonical redirection
> SE-2037 Allow healthchecks to bypass canonical redirect

- app/controllers/schools/placement_dates_controller.rb
- app/models/bookings/booking.rb
- app/models/bookings/placement_date.rb
- app/models/bookings/placement_request.rb
- app/presenters/candidates/school_presenter.rb
- app/views/schools/placement_requests/acceptance/confirm_booking/new.html.erb
- app/views/schools/placement_requests/acceptance/make_changes/new.html.erb
- app/views/schools/placement_requests/show.html.erb
- spec/factories/bookings/placement_request_factory.rb
- spec/factories/bookings/school_factory.rb
- spec/models/bookings/placement_date_spec.rb
- spec/models/bookings/placement_request_spec.rb
SE-1922
The logic around booking dates is duplicated in several places - each replicating logic for whether there is a fixed date, and whether that date is in the future.
1. Change scope from future to be whether a placement date is bookable
2. Moved logic out of view and into placement_request model
3. Renamed #in_future? test to be #bookable?
4. Use the delay constant on Booking to determine whether a Placement Date is bookable?
> SE-1922 Dry out booking date rules

- app/models/bookings/placement_date.rb
- spec/models/bookings/placement_date_spec.rb
SE-1875
Currently dates from today onwards are listed but a school cannot confirm a
booking which is on today, they will need to amend and set a date from
tomorrow onwards.
Instead just don't show todays Placement Dates to users.
> SE-1875 Cannot confirm booking for today

- app/views/candidates/schools/_placement_dates.html.erb
SE-2058
When there were primary dates but no secondary dates then the 'no dates' message
would be incorrectly shown to the candidate on the schools profile.
1. Changed conditionals to only show the error if neither primary or secondary dates
> SE-2058 Fix incorrectly showing 'No dates' warning on profile

- app/views/schools/confirmed_bookings/date/uneditable.html.erb
SE-2060
Return links on the bookings date 'uneditable' page used referer but if the page was accessed via a PATCH request than referer will generate a GET request to the wrong controller action.
1. Use explicit links
> SE-2060 Dont rely on referer in uneditable template for links

- app/notify/notify_email/candidate_booking_confirmation.rb
- spec/notify/notify_email/candidate_booking_confirmation_spec.rb
SE-2067
Currently we are trying to send nil booking.placement_details through to notify which is triggering an error.
1. When booking.placement_details is nil just cast it to a blank string
> SE-2067 Step1 prevent errors

- Gemfile
- Gemfile.lock
Keep gems up to date, will help with the upcoming Rails 6 upgrade
1. Switch to webdrivers gem to stop deprecation warnings
2. Update any outdated Gems which can be updated
> Gem updates Jan 2020

- app/helpers/candidates/school_helper.rb
- app/views/candidates/schools/_phase2.html.erb
- spec/helpers/candidates/school_helper_spec.rb
SE-2072
The fields on the school profile are showing as normal definition lists instead of inline ones. Separately the individual requirements are not showing as bullets.
1. Revert the definition lists to being inline lists
2. The individual requirements are shown as bullets
> SE-2072 Fix layout on phase2 template

- app/views/candidates/schools/_placement_dates.html.erb
SE-2070
Currently we don't show the duration of primary dates when candidates are viewing the School's Profile
1. Show the duration of a primary schools placement dates
> SE-2070 Show duration information for primary dates

- app/helpers/schools/dashboards_helper.rb
- app/views/schools/dashboards/_manage_dates.html.erb
- features/schools/dashboard.feature
SE-2063
Currently the 'edit dates' link on the schools dashboard only shows if the school is using fixed dates and has dates available. Instead this should show, irrespective of whether there are dates available.
1. Removed helper method for detecting whether to show link 
2. Just use the flag on the school model in the view template
> SE-2063 Always show edit dates link if school is using fixed dates

- app/jobs/cron/reminders/next_week_job.rb
- app/jobs/cron/reminders/tomorrow_job.rb
- app/jobs/cron/sync_subjects_with_gitis_job.rb
- spec/jobs/cron/reminders/next_week_job_spec.rb
- spec/jobs/cron/reminders/tomorrow_job_spec.rb
SE-1953
Reminders are not sending - this is caused by the Job classes not being appropriately named so not getting scheduled.
1. Renaming the reminder Job class
> SE-1953 Fix reminders not sending

- app/controllers/schools/placement_dates_controller.rb
- app/views/schools/placement_dates/edit.html.erb
- app/views/schools/placement_dates/new.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/servertest.rb
- config/environments/test.rb
- config/routes.rb
We've now released the subject_specific date feature and it is not possible to disable it now. 
1. Remove the feature flag from the code base to simply the code.
> Removed feature_flag for subject specific dates

- app/jobs/cron/reminders/next_week.rb
- app/jobs/cron/reminders/tomorrow.rb
- app/jobs/cron/sync_subjects_with_gitis_job.rb
- spec/jobs/cron/reminders/next_week_spec.rb
- spec/jobs/cron/reminders/tomorrow_spec.rb
Reverts DFE-Digital/schools-experience#1309
This doesn't seem to have resolved the problem so remove from the release to avoid scheduling the job until the problem is fully understood.
> Revert "SE-1953 Fix reminders not sending"

- app/views/schools/placement_requests/acceptance/make_changes/new.html.erb
SE-2076
The view assumes that because the school is currently using fixed dates, that
the placement request was created with fixed dates.
1. Reordered the nested if clauses to be a single layer, checking first if a dates is bookable (which always fails for flexible dates), then if it even is a fixed date, and finally showing the flexible dates section.
2. Remove use of whether the school is using fixed dates to determine whether the PlacementRequest was created with fixed/flexible dates.
> Fix assumption in view template

- features/support/database_cleaner.rb
Previously you couldn't run rspec after cucumber without first creating the
test db and its data.
1. Run a Database clean with truncation at the end of cucumber
> Leave the test database in a clean state after a Cucumber run

- config/locales/en.yml
SE-2074
If a school supports both Primary and Secondary placements, and the School experience phase field (`supports_subjects`) is left blank - the user see's the rails default error message.
1. Added a translation for this field which is clearer for the user
> Added missing validation translation to placement_date#supports_subjects

- app/controllers/concerns/dfe_authentication.rb
- app/controllers/schools/base_controller.rb
- app/helpers/application_helper.rb
- spec/controllers/concerns/dfe_authentication_spec.rb
- spec/views/schools/dashboards/show.html.erb_spec.rb
SE-2094
Currrently every page in the Schools Dashboard is doing an API request to DFE Sign In to determine whether users organisation list.
1. Query the organisation list lazily
2. Cache the results in the session - this gets removed when the session expires or the user logs out.
3. Moved the logic from the Base controller to the DfE Authentication module
> Restructure DfE Sign In api requests to only do check once at sign in

- app/controllers/schools/placement_requests_controller.rb
SE-2083
Currently duplicate API calls are made for the organisation URNs list. 
1. Removed the separate query of the organisations urn list
2. Avoid changing the list after its retrieved.
> Don't modify the organisation URNs list

- app/controllers/concerns/gitis_access.rb
- app/controllers/schools/base_controller.rb
- app/controllers/schools/confirm_attendance_controller.rb
- app/controllers/schools/confirmed_bookings_controller.rb
- app/controllers/schools/placement_requests_controller.rb
- app/controllers/schools/previous_bookings_controller.rb
- app/controllers/schools/withdrawn_requests_controller.rb
- app/models/bookings/booking.rb
- app/models/bookings/placement_request.rb
- app/models/bookings/placement_request/cancellation.rb
- app/services/bookings/gitis/api.rb
- app/services/bookings/gitis/missing_contact.rb
- app/views/shared/failed_gitis_connection.html.erb
- lib/apimock/gitis_crm.rb
- spec/controllers/schools/placement_requests_controller_spec.rb
- spec/services/bookings/gitis/missing_contact_spec.rb
- spec/support/bypass_fake_gitis.rb
If Gitis stops responding, we should show a page to the user that explains why they are seeing the screen, that it is anticipated to be temporary and to try again later.
1. Added custom exception handler for gitis errors
2. Added a 'gitis retrieval error' page
3. Populate missing contacts on listings pages with stub objects, this avoids a single missing contact making the entire page unavailable
4. Removed the duplicated instances of bulk fetching gitis contacts
1. Code review
2. Testing - 
a. try with an invalid gitis hostname
b. change the guid on a candidate to be something new from `SecureRandom.uuid` - any `index` page showing that contacts data should still work
> SE-1302 Render custom page for failed gitis retrieval

- spec/controllers/schools/placement_requests_controller_spec.rb
It was testing ordering but not enforcing both components had the same order.
1. Just compare array contents instead.
> Fix for test which sporadically failed

- app/controllers/schools/confirm_attendance_controller.rb
- app/models/schools/attendance.rb
- app/views/schools/confirm_attendance/show.html.erb
- spec/controllers/schools/confirm_attendance_controller_spec.rb
- spec/models/schools/attendance_spec.rb
SE-2080
Currently we've had a couple of reports of schools attempting to update Attendance for Bookings but getting it taking no effect.
1. All updates are wrapped in a transaction so if any update to a booking fails then all updates are rolled back
2. Models are revalidated at point of save - which requires they remain valid even with new validations running against older data.
2. No errors are reported, and if the Attendance#save fails we would get a render error - since #save always returns true this isn't a problem at present
1. Remove the transaction - a couple of problematic updates shouldn't block all updates
2. Report errors for any bookings which could not be updated
3. Ensure we get exceptions reported for the invalid bookings which should help with identifying the root cause of …
> SE-2080 Failing updates to attendance records

- config/locales/en.yml
2022
The DBS Requirements field only gives a generic error message
1. Expand the error message to provide more clarity to the user
> Expanded error message for blank DBS requirements field

- azure-pipelines.yml
CI Is currently failing on lint check, this is non vital so disable till I can identify cause - looks like a potential race condition when creating configs
> Disable lint check till I find why its failing

- app/controllers/concerns/dfe_authentication.rb
SE-1684
When we hand across to DfE Sign In, we include a couple of tokens which are
held in session data
Currently we assign these prior to the redirect - this creates a scenario where
multiple pages failing the check will end up in a race assigning the tokens
(eg browser restoring multiple tabs for our dashboard). The last restored tab
assigns the token but if that is not the one the user signs in through then the
token we have in session, does not match that returned by DfE Sign-in
1. Use existing tokens when they are already assigned
> Don't re-assign OIDC nonces if already assigned

- features/support/feature_helper.rb
Remove default page delay because it may no longer be required
> Changed default page delay in cucumber to be 0 seconds

- azure-pipelines.yml
We've been getting back docker builds from the hosted Azure Pipelines agents
1. Switch to use 18.04 builders instead of the default 16.04
> Switch to use ubuntu-18.04 for docker builds

- Dockerfile
We've have been encountering sporadic failures from our CI pipeline, appearing to relate to a compilation error. I think I've tracked this down to an issue in the Sassc gem.
The sassc gem compiles using -march=native which produces a non-portable c lib
of sassc. In a Docker environment, the built image may be run on a different
system than the one it is compiled on - potentially resulting in a segfault.
This looks to be the issue we have been encountering over the last week.
2.2.1 is supposed to fix this but does not actually remove the -march=native
optimisation and I believe continues to exhibit this problem.
1. Update the docker file to prevent the usage of `-march=native`
> Ensure compiled sassc gem is portable

- app/assets/stylesheets/pagination.scss
- app/controllers/schools/confirm_attendance_controller.rb
- app/views/schools/confirm_attendance/show.html.erb
SE-2105
Currently we show an unconstrained number of Bookings on the 'Confirm Attendance' screen. This will potentially result in requesting more Candidate records from Gitis than Gitis can support in a single request.
1. Use pagination on the screen to constrain the maximum number of records requested from Gitis at any one time.
> SE-2105 Added pagination to Confirm Attendance screen

- Gemfile.lock
We are getting sporadic failures from cucumber whilst it interacts with Selenium.
This have increased in greatly frequency in the last week.
1. Upgrade FFI to 1.12.2 to hopefully resolve the errors
> Upgraded FFI to 1.12.2

- app/notify/notify.rb
- app/notify/notify_email/candidate_booking_date_changed.rb
- app/notify/notify_email/candidate_booking_reminder.rb
- spec/notify/notify_email/candidate_booking_date_changed_spec.rb
- spec/notify/notify_email/candidate_booking_reminder_spec.rb
- spec/notify/notify_spec.rb
SE-2067
We do not validate supplied personalisation when we schedule emails with notify. This means invalid data causes the notify job to fail but this is asynchronous and the user gets no feedback that this has failed.
1. Change the notify class to reject scheduling email deliveries if the personalisation is invalid
2. Ensure the various emails personalisation does not include nil values
> SE-2067 Step2 prevent scheduling invalid notify jobs

- app/controllers/schools/placement_requests/acceptance/confirm_booking_controller.rb
- app/controllers/schools/placement_requests/acceptance/make_changes_controller.rb
- app/models/bookings/booking.rb
- app/models/schools/attendance.rb
- app/views/schools/placement_requests/acceptance/confirm_booking/new.html.erb
- features/step_definitions/schools/placement_requests/confirm_booking_steps.rb
- spec/models/bookings/booking_spec.rb
SE-2125
Historical bookings do not necessarily have a contact name/number/email - these fields were requested but not required.
We now require these fields to be supplied, which means some older bookings are no longer valid under the current rule set.
This is preventing schools from marking attendance on these 'historical' bookings.
1. Remove duplicate error messages for the contact number/email when left blank
2. Make the required validations only run on the screen they apply to
3. Send all booking confirmations through the MakeChanges controller which can show error information in the scenario a booking is invalid, allowing the user to correct it.
4. Make the attendance validations only run on the Attendance screen.
> SE-2125 Marking invalid attendances

- app/notify/notify_email/candidate_booking_confirmation.rb
- app/notify/notify_email/candidate_booking_confirmation_v2.f66aaa08-df33-4be6-95b6-7e1cf8595a2b.md
- app/notify/notify_email/candidate_booking_date_changed.rb
- app/notify/notify_email/candidate_booking_date_changed_v2.3c1fd380-db1c-4efb-8e98-f3a0ef3e2661.md
- app/views/schools/placement_requests/acceptance/email_preview_sections/_school_experience_details.html.erb
- spec/controllers/schools/confirmed_bookings/date_controller_spec.rb
- spec/factories/bookings/bookings_factory.rb
- spec/notify/notify_email/candidate_booking_confirmation_spec.rb
- spec/notify/notify_email/candidate_booking_date_changed_spec.rb
SE-2127
There are a few issues with the emails which go out to candidates confirming bookings.
1. The emails to candidates do not include the 'candidate experience' information from the schools profile, they instead include the old phase 1 information.
2. The candidate instructions added as part of the Accept a Booking process are never sent to the candidate.
3. The subject is not included in the email
4. The layout of the preview email doesn't accurately reflect the email the candidate receives.
1. Include Subject, and Candidate Instructions
2. Re-order the layout to reflect the email preview screen
3. Use the profile candidate experience instead of the old Phase 1 info on both the preview screen and on the email screen.
> SE-2127 Candidate instructions getting excluded

- app/models/bookings/booking.rb
- spec/models/bookings/booking_spec.rb
SE-2107
Previously I'd changed the validations to not check for presence of email or phone number when marking Attendance on bookings. Turns out we have some historical bookings with phone numbers present but invalid.
1. Don't validate the format of phone numbers or emails when marking attendance
> Dont validate format of contact_email and number when recording Attendance

- app/views/candidates/registrations/educations/_form.html.erb
SE-2132
The education details step on the Candidate application process is missing a page title.
1. Added missing page title
> Include page title on education form

- app/controllers/schools/placement_requests/acceptance/confirm_booking_controller.rb
- config/routes.rb
SE-2125
The work for SE-2125 orphaned a route on the ConfirmBookings controller. This code was left in place to avoid 404's for anyone midway through confirming a booking but can now be safely removed.
1. Removed unused route
2. Removed unused controller action
> Removed dead code and route

- app/controllers/schools/sessions_controller.rb
- app/models/bookings/school.rb
- app/services/schools/dfe_sign_in_api/roles.rb
- spec/controllers/schools/session_context.rb
- spec/services/schools/dfe_sign_in_api/roles_spec.rb
SE-2135
Previously this was doing its own translation (and caching) of the Schools
organisation id. Instead use the organisation id provided by DfE Sign-in and
avoid caching these in the database.
This resolves a bug where if the DfE Sign-in user belonged to organisations
which were not part of the service, than the database could not update the
cached copy of the organisations uuid.
1. Changed the API check to use an dfe sign-in org uuid instead of urn
2. Remove the URN <-> Org UUID translation code
> Simplified Dfe Sign-in role check

- config/routes.rb
SE-1378
Service updates feature was added but support for the pre-existing route hadn't been updated even though the existing page had been removed. This resulted in errors when attempting to access the missing page.
1. Update the legacy route to point to the new ServiceUpdates#index
> Fix for legacy service update route

- app/models/bookings/booking.rb
- spec/models/bookings/booking_spec.rb
SE-2138
Currently we only check for the presence of date on create, which means we try (and fail) to insert a null booking date into the database
This appears to be a hangover from when the date's 'futureness' was part of the same validation as the check for presence.
1. Make the presence check always run, irrespective of context
> Always check for presence of date, not only on create

- app/controllers/cookie_preferences_controller.rb
SE-2097
If the user has left the page open for an extended period of time, then it is
likely the token will expire. If they then return and click 'accept' they will
see an unexpected session expired message.
The update action only sets a cookie on the users web browser so it is safe to
not check the authenticity token, I am disabling it to avoid the user seeing
the error unnecessarily.
1. Disable the authenticity token check on the cookie preferences controller
> Skip verify_authenticity_token for cookie preferences

- app/controllers/schools_controller.rb
- app/views/schools/show.html.erb
- spec/controllers/schools_controller_spec.rb
SE-2142
In the event the DfE Sign-in service is unavailable it is desirable to explain this to our users and not present them with an login button which wont work
1. Add support for replacing the sign in button with a message explaining the service is disabled, controlled via an environment variable
> SE-2142 Allow de-activating DfE Sign In logins

- app/models/feature.rb
- spec/models/feature_spec.rb
SE-1955
Building block for SE-1955
Allow adding feature flags from environment variables
Format is FEATURE_FLAG='first_flag second_flag'
2. Does staging still work
> Allow adding feature flags from FEATURE_FLAGS env var

- app/controllers/schools/base_controller.rb
- spec/controllers/schools/dashboards_controller_spec.rb
SE-2116
Prior behaviour cast the blank school urn #to_i, which resulting in a 0. This
meant the user saw the 'School not registered' error instead of the No school
error which appears to be a stub screen.
1. Instead redirect the user to the insufficient privileges screen which has more
useful information on it for resolving the users issues.
> Changed redirection path

- app/controllers/schools/base_controller.rb
- app/controllers/schools/sessions_controller.rb
- app/services/schools/dfe_sign_in_api/client.rb
- app/services/schools/dfe_sign_in_api/roles.rb
- spec/controllers/schools/change_schools_controller_spec.rb
- spec/controllers/schools/sessions_controller_spec.rb
- spec/services/schools/dfe_sign_in_api/client_spec.rb
- spec/services/schools/dfe_sign_in_api/organisations_spec.rb
- spec/services/schools/dfe_sign_in_api/roles_spec.rb
- spec/support/sign_in_api.rb
SE-2139
If calls to the DfE Sign-in API fail, we should initially retry in-case of network flakiness then fail but fail gracefully with an error message giving the user an opportunity to retry the login process.
1. Add automatic retry on all API calls
2. Add a shorter timeout in case the connection has just hung
3. Raise custom exceptions when calls fail
4. Show the Auth Failed screen allowing the user to retry
5. Minor refactor of `enabled?` logic to make different API call classes responsible for whether they are enabled
> SE-2139 DfE Sign-in API robustness

- app/services/schools/dfe_sign_in_api/roles.rb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/servertest.rb
- config/environments/test.rb
- spec/services/schools/dfe_sign_in_api/roles_spec.rb
SE-2139
The recent change to use RoleCheckedOrganisations means we always use role
checks if the API is enabled. A subsequent change to make the Roles#enabled?
return false if the config is disabled breaks the API usage so removing the
option to toggle just this specific API.
The actual issue is Roles#enabled? will now trigger a ApiDisabled error in the
attempt to call response in parent DFESignInAPI::Client class.
1. Remove support for disabling the Roles API separate from the main usage of DfE Sign-in API, its either all on or off.
> SE-2139 Removed support for invalid config

- app/services/bookings/gitis/store/write_only_cache.rb
- spec/services/bookings/gitis/store/write_only_cache_spec.rb
The cache implementation of a Gitis store doesn't implement the `write!` method which was implemented in a parallel PR
1. Add a write! implementation
> Added missing write! method in Gitis cache implementation

- app/views/schools/dashboards/show.html.erb
If the user belongs to only one school, the Change school screen is still useful because it sign posts the user to where they can apply for access to another school
> Always show change school if request approval enabled

- app/services/bookings/gitis/contact.rb
- app/services/bookings/gitis/contact_fuzzy_matcher.rb
- app/services/bookings/gitis/crm.rb
- lib/apimock/gitis_crm.rb
- spec/services/bookings/gitis/contact_fuzzy_matcher_spec.rb
- spec/services/bookings/gitis/contact_spec.rb
- spec/services/bookings/gitis/crm_spec.rb
Currently we treat all contacts in Gitis equally. We would prefer a match for a candidate who we already know about though.
1. Refactored some of the logic
2. Look up matched contacts against the Candidates we have, and prioritise those contacts we have Candidate records for.
1. Code review
> SE-1596 Prefer gitis contacts we already know

- lib/tasks/gitis/metadata.rake
Some times I need to download the metadata file when updating our CRM integration code. This script maybe more broadly useful so adding to codebase as a rake task
1. Add simple rake task to download the metadata (schema) from Gitis
> Added Rake task to download all Gitis metadata

- app/models/feature.rb
- app/services/schools/dfe_sign_in_api/client.rb
- spec/services/schools/dfe_sign_in_api/client_spec.rb
We need to enable the role check again
1. Fixed use of env vars to control feature flags
2. Use `rolecheck` feature flag to enable role check
> Use feature flags to control role check

- azure-pipelines.yml
- script/image_tags_and_ipaddress.sh
SE-2108
Fixing warnings during deployment. We were copying a script out of the repo via the artifact publishing into the CD pipeline. Part of this process was loosing the execute permissions on the script.
1. Removed unused script - it is now included in the devops repo
2. Removed publishing of the script from `azure-pipelines.yml`
> Removed script thats been moved to the devops repo

- Gemfile
- Gemfile.lock
Fixes CVE-2020-10663
Ruby 2.6.5 bundles v2.1
> Force use of at least JSON 2.3

- Dockerfile
SE-1932
It is desirable to use a smaller base image with lower dependencencies
1. Switch use use the alpine-3.11 variant of the Ruby base image
> Switch to Alpine 3.11, Ruby 2.6.5

- app/models/bookings/candidate.rb
disables gitis_uuid update on assign contact process to guard against duplicate key errors
> disable gitis_uuid update on assign contact

- app/models/bookings/candidate.rb
- spec/models/bookings/candidate_spec.rb
- spec/services/bookings/gitis/contact_fetcher_spec.rb
Updating the `gitis_uuid` on receiving a merged record means that it is possible to create several records with duplicate uuids breaking the uniqueness constraint on the database.
> Do not update gitis_uuid on contact assignment

- app/views/candidates/schools/_phase1.html.erb
- app/views/candidates/schools/_phase2.html.erb
We're not showing the experience type information on on style school profiles
1. Show the experience_type on phase1 profiles
2. Tweaked the definition lists used on phase2
> Show school experience type on phase 1 profile

- app/notify/notify_service.rb
- config/environments/development.rb
- config/environments/servertest.rb
- config/environments/test.rb
Loading alternative notify clients without eager loading (ie RAILS_ENV=development) was broken in the Rails 6.1 upgrade. I think this is because the `app` folder is no longer in the autoloading path, or autoloading is no longer enabled, at configuration.
1. Changed to hold a string of the notify client class in the config value and constantize on instantiation of the NotifyService singleton.
> Fixed loading custom Notify clients

- app/models/bookings/placement_request.rb
- spec/factories/bookings/placement_request_factory.rb
- spec/models/bookings/placement_request_spec.rb
Discovered as part of the CSV work - if a booking is only partially completed than any screen relying on PlacementRequest#status will show as booked when its not.
I think this hasn't been noticed because, prior to now, this method is only used on screens for 'completed' bookings.
1. Check a booking is completed before marking it as booked
> PlacementRequest#status should ignore partially completed bookings

- app/controllers/application_controller.rb
https://trello.com/c/k8W6moMq
We don't need to be showing the candidate alert notification anymore
1. Disable the candidate notifications
> Turn off candidate alert notification

- data/service_updates/20210222.yml
https://trello.com/c/k8W6moMq
The last service update referenced turning off the service and will be confusing once we turn it back on.
1. Add a new Service Update explaining we've turned the service back on.
> Added Service update for 22 Feb 2021

- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/candidates/registrations/resend_confirmation_emails_controller.rb
- app/controllers/schools/base_controller.rb
- app/controllers/schools/sessions_controller.rb
- app/jobs/notify_job.rb
- app/models/schools/attendance.rb
- config/environments/production.rb
- config/initializers/sentry.rb
- spec/jobs/notify_job_spec.rb
https://trello.com/c/r0Z1xkv3
The sentry-raven gem is outdated and looks to have a bug in reporting delayed job errors in the last release.
1. Switch to the Sentry Ruby error reporter, including both `sentry-rails` and `sentry-delayed_jobs` plugins
> Switch to sentry-ruby gem

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/candidates/registrations/resend_confirmation_emails_controller.rb
- app/controllers/schools/base_controller.rb
- app/controllers/schools/sessions_controller.rb
- app/jobs/notify_job.rb
- app/models/schools/attendance.rb
- config/environments/production.rb
- config/initializers/delayed_job.rb
- lib/delayed_notification_plugin.rb
- spec/controllers/candidates/registrations/resend_confirmation_emails_controller_spec.rb
- spec/jobs/notify_job_spec.rb
https://trello.com/c/r0Z1xkv3
Now we've got Sentry publishing to Slack we no longer need exception notifier to do the same.
1. Remove use of ExceptionNotifier
> Drop ExceptionNotifier

- azure-pipelines.yml
Our builds are broken whilst the mimemagic gems are yanked.
1. Use cached builds on `master` until this is resolved
> Use cached builds on master as a stopgap fix

- Dockerfile
We've upgraded to Rails 6.1.3.1 which no longer depends upon mimemagic
1. Removed installation of `shared-mime-info` package
> Removed no longer needed dependency on shared-mime-info library

- app/views/schools/errors/insufficient_privileges/show.html.erb
- spec/views/schools/errors/insufficient_privileges/show.html.erb_spec.rb
https://trello.com/c/zOe6LLEu
Users who logout with the wrong DFE Sign-in account currently cannot sign back out again.
1. Show a logout button on the insufficient priviledges page
> Include logout button on insufficient priviledges page

- Gemfile
- Gemfile.lock
- app/controllers/candidates/registrations/personal_informations_controller.rb
- app/controllers/candidates/registrations/placement_requests_controller.rb
- app/controllers/candidates/registrations/sign_ins_controller.rb
- app/controllers/concerns/gitis_authentication.rb
- app/models/bookings/candidate.rb
- app/models/bookings/registration_contact_mapper.rb
- app/models/candidates/verification_code.rb
- app/services/bookings/gitis/contact.rb
- app/services/candidates/registrations/personal_information.rb
- app/views/candidates/registrations/sign_ins/show.html.erb
- config/initializers/flipper.rb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/candidates/registrations/personal_informations_controller_spec.rb
- spec/controllers/candidates/registrations/placement_requests_controller_spec.rb
- spec/controllers/candidates/registrations/sign_ins_controller_spec.rb
- spec/factories/api_factory.rb
- spec/factories/bookings/candidates_factory.rb
- spec/models/bookings/candidate_spec.rb
- spec/models/bookings/registration_contact_mapper_spec.rb
- spec/models/candidates/verification_code_spec.rb
- spec/services/bookings/gitis/contact_spec.rb
- spec/services/candidates/registrations/personal_information_spec.rb
- spec/support/candidate_signin.rb
- spec/support/stubbed_api.rb
[Trello-65](https://trello.com/c/gYVyBCMH/65-spike-matchback-for-gse)
We want to migrate the application so that it calls out to the Get into Teaching API instead of interfacing with the Dynamics365 instance directly (reducing complexity in the application and making the integration consistent with our other services).
The PR is large, but should be reviewable by-commit -- arguably the commits could each be an individual PR, however this grouping is the minimum set of changes for a successful end-to-end sign up via the API.
- Run Flipper against memory store in test env
We use the same Redis instance for our unit tests as development, which causes the features to be enabled in test that are enabled in dev.
Instead, we want to by default have all features off in test - we achieve this by …
> Integrate with GiT API for sign up process

- app/models/healthcheck.rb
- spec/controllers/healthchecks_controller_spec.rb
- spec/models/healthcheck_spec.rb
The healthcheck tests connectivity to the CRM; instead of doing this directly we can call the API which, in turn, will test connectivity to the CRM.
Unlike the other services (which can function when the API is in a 'degraded' state) Schools Experience requires the CRM to be online in order to accept any new sign ups, so we check for this service explicitly in the health check response.
- Update healthcheck to run CRM check via API
> Update healthcheck to run CRM check via API

- Gemfile.lock
- app/services/bookings/reminder.rb
- spec/factories/api_factory.rb
- spec/services/bookings/reminder_spec.rb
When sending reminders the app calls out to retrieve a contact record by its guid; this is now available in the API and so the reminder feature can be updated with `git_api` feature flag support.
- Bump API client to include full_name attribute
The API was updated to return the candidate's full name, which exists on the current `Bookings::Gitis::Contact` however wasn't present on `GetIntoTeachingApiClient::SchoolsExperienceSignUp`. Adding it means we don't have to update a number of references to `full_name` with a helper.
- Integrate reminder functionality with API
> Integrate reminder feature with GiT API

- Gemfile.lock
- app/controllers/schools/rejected_requests_controller.rb
- spec/controllers/schools/rejected_requests_controller_spec.rb
Instead of calling the Dynamics instance directly to retrieve candidate information by a collection of ids we can now go to the GiT API when the `git_api` flag is enabled.
- Update RejectedRequestsController to interface with GiT API
> Update RejectedRequestsController to interface with GiT API

- app/services/bookings/gitis/event_logger.rb
- spec/controllers/candidates/registrations/placement_requests_controller_spec.rb
- spec/services/bookings/gitis/event_logger_spec.rb
- spec/support/stubbed_api.rb
When the candidate performs certain actions within the SE app it updates their `contact` record with log lines to record whats happening. We want to send these updates via the API instead of to Dynamics directly as part of the work to integrate with the GiT API.
- Bump api client version
Update to remove client-side validation on ClassroomExperienceNote that was using an incorrect regex.
- Update EventLogger to write via API
Instead of constructing the log line in the app this is now deferred to the API, which accepts POST request containing a
`GetIntoTeachingApiClient::ClassroomExperienceNote`.
The class is a little misleading in that `write_later` will not queue the request to the API, however the …
> Integrate classroom experience requests to the GiT API

- Gemfile.lock
- app/models/bookings/candidate.rb
- app/services/bookings/gitis/contact.rb
- app/services/bookings/gitis/contact_fetcher.rb
- spec/controllers/candidates/registrations/personal_informations_controller_spec.rb
- spec/controllers/candidates/registrations/placement_requests_controller_spec.rb
- spec/controllers/candidates/registrations/sign_ins_controller_spec.rb
- spec/controllers/healthchecks_controller_spec.rb
- spec/controllers/schools/rejected_requests_controller_spec.rb
- spec/factories/api_factory.rb
- spec/models/bookings/candidate_spec.rb
- spec/models/healthcheck_spec.rb
- spec/services/bookings/gitis/contact_fetcher_spec.rb
- spec/services/bookings/gitis/contact_spec.rb
- spec/services/bookings/reminder_spec.rb
- spec/support/stubbed_api.rb
The `ContactFetcher` contains complex logic to traverse `contact` records in the CRM in order to obtain the 'master' record. This needs to work against the API instead of Dynamics directly. Once the API migration is finished it would make sense to push this logic into the API to simplify it.
- Bump API client to add master_id support
- Add master_id field to Contact
This makes the `Contact` model consistent with the `SchoolsExperienceSignUp` so that we can use them interchangeably in the `ContactFetcher`.
- Update ContactFetcher to work against API
The SE app has fairly complex code around getting back to the 'master' contact record in the CRM (a contact has a 'master' when the record has been …
> Support calling the API in the ContactFetcher class

- spec/models/schools/csv_export_row_spec.rb
- spec/models/schools/csv_export_spec.rb
- spec/support/stubbed_api.rb
The CSV exporter uses the `ContactFetcher` to retrieve contacts associated with placement requests prior to exporting them. Now that the `ContactFetcher` has been updated to support retrieving contacts via the API, it makes sense to test the exporter functionality as well when the `git_api` feature is enabled. 
As the legacy code will be removed eventually I opted to duplicate the test cases instead of extracting them to keep it DRY.
- Test CSV exporter retrieving contacts via API
> Test CSV exporter retrieving contacts via API

- app/services/bookings/gitis/store/dynamics.rb
- spec/services/bookings/gitis/store/dynamics_spec.rb
If the `git_api` feature is enabled all requests should be going via the `GetIntoTeachingApiClient`. To ensure this is the case, the existing `Dynamics` module that handles reading/writing to the CRM currently will raise a message to Sentry if its ever called when the `git_api` feature is on.
- Raise a message to Sentry on unexpected direct call to CRM
> Raise unexpected direct calls to the CRM when `git_api` feature is enabled

- app/controllers/schools/base_controller.rb
- spec/controllers/schools/placement_requests_controller_spec.rb
Rescue from Faraday connection errors and any ApiError to display the standard service unavailable page. This should mimic the behaviour of the direct integration error-handling.
- Handle API/Faraday errors
> Handle API/Faraday errors

- app/models/bookings/subject_sync.rb
- app/services/bookings/gitis/teaching_subject.rb
- spec/factories/api_factory.rb
- spec/models/bookings/subject_sync_spec.rb
- spec/services/bookings/gitis/teaching_subject_spec.rb
When the `git_api` feature is enabled we want to sync via the GiT API and not directly.
Add attribute aliases to `TeachingSubject` to achieve parity with `LookupItem` models so that they can be used interchangeably in the sync job.
Update sync job to call out to the API when the `git_api` feature is enabled.
- Update SubjectSyncJob to support git_api feature
The tests for the sync job have been duplicated for when the `git_api` feature is enabled - the legacy tests will later be removed.
> Update SubjectSyncJob to support `git_api` feature

- app/helpers/gitis_contact_helper.rb
- app/views/schools/confirmed_bookings/date/edit.html.erb
- app/views/schools/placement_requests/_personal_details.html.erb
- app/views/schools/placement_requests/show.html.erb
- spec/helpers/gitis_contact_helper_spec.rb
As we are removing `Bookings::Gitis::Contact` we need to decouple the view references to any attributes that are not present on `SchoolsExperienceSignUp`.
Replace direct calls to a `gitis_contact` with helper methods that can operate over both models.
- Replace view calls to Booking model with helpers
> Replace view calls to Booking model with helpers

- app/controllers/candidates/registrations/sign_ins_controller.rb
- app/controllers/candidates/sessions_controller.rb
- app/models/candidates/verification_code.rb
- app/views/candidates/registrations/sign_ins/show.html.erb
- app/views/candidates/sessions/create.html.erb
- config/routes.rb
- spec/controllers/candidates/registrations/sign_ins_controller_spec.rb
- spec/controllers/candidates/sessions_controller_spec.rb
- spec/models/candidates/verification_code_spec.rb
We perform matchback against the API in two scenarios; registering for experience (which we already have migrated) and as a 'candidate sign in' function. This appears to be behind a feature flag/under development, but we should support it via the API for completeness/so we can remove more of the legacy code later.
- Update VerificationCode model to support exchange/issue
It turns out we have multiple ways a candidate can matchback; off personal information via a registration or as part of a candidate 'sign in'.
As the candidate sign in doesn't persist the matchback data to a session (which does happen in the registration matchback) we need the `VerificationCode` model to support the matchback …
> Support candidate sign up via the API

- spec/controllers/candidates/registrations/sign_ins_controller_spec.rb
- spec/controllers/candidates/sessions_controller_spec.rb
- spec/factories/api_factory.rb
- spec/features/candidates/api_registrations_spec.rb
- spec/models/candidates/verification_code_spec.rb
- spec/support/stubbed_api.rb
We want to replicate the existing set of feature specs for when the `git_api` is enabled, so that we have the same coverage.
- Add feature spec coverage to registration
This is a lift & shift of the current registration feature specs; I've tried to keep them as unchanged as possible.
> Add feature spec coverage for when `git_api` is enabled

- app/views/schools/on_boarding/profiles/show.html.erb
https://trello.com/c/4Ozq9AQQ
When a school administrator is editing a schools profile and they view the 'Check your answers' page - they see the contact details shown both at the top of the page (uneditable) and lower down, where they are editable. This is confusing for the user because they think it needs changing twice.
Remove the duplicate uneditable contact details from the top of the page.
| Before | After |
| - | - |
| <img width="1005" alt="before" src="https://user-images.githubusercontent.com/951947/119972057-a8f5ee80-bfa9-11eb-96d5-ad4a41aa9ac1.png"> | <img width="987" alt="after" src="https://user-images.githubusercontent.com/951947/119972068-ad220c00-bfa9-11eb-9f47-744ae3dbfc7b.png"> |
> Remove duplicate fields in the update school profile page

- app/views/candidates/registrations/sign_ins/show.html.erb
- config/locales/en.yml
- spec/features/candidates/api_registrations_spec.rb
Updates the copy on the 'enter your verification code' page, retaining the existing copy when the `git_api` feautre is not enabled.
| Feature Enabled      | Feature Disabled |
| ----------- | ----------- |
| <img width="1349" alt="Screenshot 2021-06-01 at 11 04 30" src="https://user-images.githubusercontent.com/29867726/120305845-259a0d00-c2c9-11eb-8c1d-f26eb4088268.png">     |  <img width="1349" alt="Screenshot 2021-06-01 at 11 04 45" src="https://user-images.githubusercontent.com/29867726/120305872-2d59b180-c2c9-11eb-8110-ee8b12c9b80a.png">       |
> Update copy on enter verification code page

- app/views/pages/_8da7ae80-82f2-ea11-a815-000d3a44afcc.html.erb
https://trello.com/c/fMj2szXM
The cookies link at the bottom of the Privacy Policy page is wrong, causing 404s.
Use the correct link `/cookies_policy`
> Fix the cookies link in the privacy policy page

- app/models/bookings/registration_contact_mapper.rb
- spec/controllers/candidates/registrations/placement_requests_controller_spec.rb
- spec/features/candidates/api_registrations_spec.rb
- spec/models/bookings/candidate_spec.rb
- spec/models/bookings/registration_contact_mapper_spec.rb
- spec/support/stubbed_api.rb
We serve a static privacy policy to users and mark the latest in the API as the one they accept against their candidate record, which is fine whilst they’re both one and the same but if the policy changes in the CRM and we don’t reflect it in the app then they could be marked as accepting a policy they haven’t read
Make it explicit which privacy policy number is being sent to the API.
> Register the current privacy policy number in the candidates records

- .env.production
- Gemfile
- Gemfile.lock
- app/controllers/errors_controller.rb
- app/views/errors/too_many_requests.html.erb
- bin/rspec
- config/application.rb
- config/initializers/exclude_cloudfront_ips.rb
- config/initializers/rack_attack.rb
- config/routes.rb
- db/seeds.rb
- lib/cloud_front_ip_filter.rb
- spec/controllers/errors_controller_spec.rb
- spec/lib/cloud_front_ip_filter_spec.rb
- spec/requests/rate_limiting_spec.rb
- spec/support/rate_limiting_support.rb
https://trello.com/c/XAIC00Le
We want to protect the app from hostile bots which pollute our db with spam and can also cause DDoS attacks.
Add Fail2Ban to ban hostile bots and Rack::Attack to throttle requests to transaction endpoints.
The ban is set to 5mins per ip and the throttling to 5 req/ip.
If a user encounters a rate limit, the app will redirect the request to a 'Too many requests' error page.
> Add DDoS protection

- app/helpers/candidates/school_helper.rb
- app/views/candidates/schools/_phase1.html.erb
- app/views/candidates/schools/_phase2.html.erb
https://trello.com/c/ONryUTqi
The school page displays `VIRTUAL` experience type when it's actually set to `IN SCHOOL`. 
Use the `format_school_placement_locations` helper that is also used to display the correct experience type in the school search page.
Finally, delete the `format_school_experience_type` helper as there's no obvious reasons it should exist.
> Display the correct experience type in school pages

- app/views/candidates/placement_requests/cancellations/_show_placement_request_cancelled_by_candidate.html.erb
When candidates cancelling their SE request, we display the cancellation page which has a typo in the `What happens next` section.
Move the `at` preposition in front of the school name.
> Fix typo in the cancellation page

- app/models/bookings/registration_contact_mapper.rb
- spec/models/bookings/registration_contact_mapper_spec.rb
We were combining `address_line1` and `address_line2` for the `street` field, but we already show `address_line1` in the `building` field, so if you went through the experience registration process multiple times (matching back) you ended up with your building number prepended to the address again (and again).
> Fix address number being duplicated

- Gemfile
- Gemfile.lock
- app/controllers/candidates/feedbacks_controller.rb
- app/views/feedbacks/_form.html.erb
- config/initializers/invisible_captcha.rb
- spec/features/feedback_spec.rb
https://trello.com/c/ahEcacjs
At the moment, bots can easily submit the feedback form. We want to prevent that, so to get only real submissions.
Add invisible captcha protection to candidates feedback form.
Fill in the honeypot field and submit the form to trigger the bot protection. An empty page with 200 status code will be returned instead of the "Thank you" page.
> Add invisible captcha protection to candidates feedback form

- app/models/healthcheck.rb
- app/services/schools/dfe_sign_in_api/client.rb
- spec/models/healthcheck_spec.rb
When the api is unreachable the app raises Rack Timeout exceptions which lead to 500 responses.
https://trello.com/c/izJNTyfl
We want to prevent the 500 responses when the dfe api is unreachable
Taking two extra measures to handle the timeouts:
1. Add the Rack::Timeout::RequestTimeoutException to faraday's retry
exceptions to give it a second chance to succeed
2. Rescue the Rack Timeouts and return false to prevent the 500s
> Handle gracefully the dfe sign in healthchecks

- app/controllers/cookie_preferences_controller.rb
- spec/features/cookie_preferences_spec.rb
https://trello.com/c/ADa84TYk
Before accepting the cookies, we store the HTTP referer, in order to redirect the users back to the page they were at. However there are cases where the referer is not a GET path, causing 404s because there's nothing to render.
- Set the redirect link to root path when the referer is not recognised as a GET resource
It's utilising the `Rails.application.routes.recognize_path()` which by default tries to recognise GET paths. If a route is found, then we assume it's safe to redirect to, otherwise the homepage is used as a fallback.
- Remove the `cookies_policy` from the REFERER_BLACKLIST. 
Accepting the cookies from the `/cookies_policy` page, will now keep the users on the same page and won't redirect them to the edit cookies page.
- Rename the misspelled …
> Redirect non GET referers to root_path

- app/models/healthcheck.rb
- spec/models/healthcheck_spec.rb
https://trello.com/c/Exs5eBFu
Sentry has caught `Errno::ETIMEDOUT` exceptions raised by the Redis health checks, which cause error 500.
Rescue the exception and return false as the Redis status.
> Rescue timeouts when health checking Redis

- terraform/paas/provider.tf
The statuscake provider errors if the defaults are not set, so
changed it to a more stable provider.
> Changed the Provider

- .github/workflows/deploy.yml
- Dockerfile
- app/models/healthcheck.rb
- spec/models/healthcheck_spec.rb
- tests/confidence/healthcheck.sh
The health check script is disabled. We should get this working.
- The file the sha is kept in has the wrong name, this isn't too important but it does not make sense so corrected it.
- When the docker container is built the file /etc/school-experience-sha is populated.
- Change the test script to work for the returned details
- SHA now displaying https://review-schools-experience-1787.london.cloudapps.digital/healthcheck
- Health check now working
> Get Healthchecks to display SHA

- app/models/healthcheck.rb
- spec/controllers/healthchecks_controller_spec.rb
- spec/models/healthcheck_spec.rb
https://trello.com/c/vMG7Hdpq/
The current healthcheck is ambiguous as to what API checks. 
It also reports false positive results for the dfe signin check, when the DfE api is either disabled in our end or the credentials are missing.
* Remove the guard clause that checks if the dfe auth is ok and let the actual request decides the results. Also, change the returned values to boolean.
* Rename the auth and the api labels in the healthcheck results to be more explicit
Visit `/healthcheck`
Before
```
{"deployment_id":"Prod-7166","app_sha":"sha-","auth":{},"api":true,"db":true,"cache":true,"healthy":true,"status":"OK"}
```
After
```
{"deployment_id":"Prod-7166","app_sha":"sha-","dfe_auth":true,"gitis_api":true,"db":true,"cache":true,"healthy":true,"status":"OK"}
```
> Healthcheck

- app/views/schools/change_schools/show.html.erb
- spec/views/schools/change_schools/show.html.erb_spec.rb
https://trello.com/c/AkG0Yv9F
The current link `Remain logged in as current school` in not very clear to the users.
Update the copy to make it clear it will lead the users to the dashboard and to also indicate which school they are logged in as.
1. sign-in using a user with multiple schools
2. choose a school
3. click the `change school` link
| before  | after |
| - | - |
| ![cs-link-before](https://user-images.githubusercontent.com/951947/125788786-3c45feca-6252-4897-86f8-c7c3dc977dd1.png)| ![cs-link-after](https://user-images.githubusercontent.com/951947/125788800-04da562c-2b3f-4e79-9583-2ab2bc1b9632.png) |
> Update the dashboard link in the change school page

- app/views/candidates/registrations/sign_ins/show.html.erb
Making this apostrophe of the typesetter variety (') instead of typewriter (’) for consistency.
> Change typewriter apostrophe to typesetter

- .postcssrc.yml
- package.json
- yarn.lock
https://trello.com/c/IIl2adTC
The postcss-cssnext was deprecated in favour of postcss-preset-env
Replace the postcss-cssnext with postcss-preset-env. Also remove the .postcssrc.yml file.
> Replace the deprecated postcss-cssnext with postcss-preset-env

- app/services/bookings/gitis/missing_contact.rb
- spec/services/bookings/gitis/missing_contact_spec.rb
The old `Contact` method had `firstname` and `lastname` but our new API model as `first_name` and `last_name`. As the `MissingContact` is used in its place in certain situations we need to have parity with the attribute names.
I'm leaving in the original attributes for now as other models still use that naming convention and I don't want to inadvertently break it elsewhere. 
I'll go through and do a repo-wide rename of these attributes in a future PR.
> Alias firstname/lastname on MissingContact

- app/jobs/cron/sync_subjects_with_gitis_job.rb
- spec/jobs/cron/sync_subjects_with_gitis_job_spec.rb
The `SyncSubjectWithGitisJob` code was removed in an early PR, but the job itself was already in the job queue. It is now failing because it can't find the handler class any longer.
Re-introduce the handler class and override `#schedule` to remove all active instances of the job from the queue. As jobs are scheduled on deployment we should be fine to deploy this then remove it immediately.
> Remove SyncSubjectsWithGitisJob instances

- app/notify/notify_email/school_request_confirmation_link_only.2a5a54b8-17cb-4da8-94ce-1647d6bf1da3.md
- app/views/pages/schools_privacy_policy.html.erb
The `school confirmation` email and the `school privacy policy` page are still using the old help and support email address
Update the email address to the new one.
- For the `School privacy policy` page, visit: https://schoolexperience.education.gov.uk/schools_privacy_policy
- For the `School confirmation` email, do the following:
- Request a School experience as a candidate to trigger the School confirmation email
- See the Help and support paragraph in the email
> Update the Help and Support email address

- config/environments/development.rb
- config/environments/production.rb
- config/environments/servertest.rb
- config/environments/test.rb
- doc/env-vars.md
As we now integrate with the CRM via the API client we no longer need these CRM-related secrets.
> Remove unused env vars for direct CRM integration

- terraform/paas/staging.env.tfvars
The application environment setting variable was not overriden in staging.
> Fix Application Environment Setting

- Gemfile
- Gemfile.lock
- bin/delayed_job
Currently we run the workers with `bundle exec rake jobs:work` which is not ideal for production.
Add the delayed_job script which can be used to:
- daemonize the processes
- spawn multiple processes
- restart the processes
Then we can start the workers with `RAILS_ENV=production bin/delayed_job start`
> Add the delayed_job script

- terraform/paas/application.tf
- terraform/paas/data.tf
- terraform/paas/provider.tf
- terraform/paas/route.tf
- terraform/paas/staging.env.tfvars
- terraform/paas/variables.tf
There is a back ground on School Experience called Delayed_jobs which sends confirmation emails. This job needs to be running when the application is redeployed.
The job is a background task and needs to be fired off, manually. 
Run the docker image a second time, with a different name. Do not allow the application (PUMA web server ) to start. but run the 'delayed_jobs' service.
The job does not have to run on review applications, and probably in development. so there is a flag that defaults to 0 which prevents the service starting. 
The flag is overriden in staging to start the service.
> Create a Second Container to Run Delayed Jobs

- app/views/schools/change_schools/show.html.erb
https://trello.com/c/oDqI6nt7
There's a typo in the change school page when the access is denied.
Remove the typo.
> Fix typo in the approver access denied page

- .github/workflows/build.yml
Sonarcloud is not importing the code coverage report, it seems that the paths change and that causes an error.
Forcing the path to remain constant.
> Sonarcloud Code Coverage 

- terraform/paas/application.tf
- terraform/paas/production.bk.vars
- terraform/paas/production.env.tfvars
- terraform/paas/variables.tf
Terraform needs to create the production environment, with the HA settings.
Although this is the production terraform, it will be pointing to the Staging Secrets until the Key Vault is created
> Terraform For Production

- .github/workflows/build.yml
- .github/workflows/deploy.yml
When running the deployment the name of the process must be unique and
reflect the name of the job.
> Change Name of Process

- config/locales/en.yml
- features/step_definitions/schools/onboarding_steps.rb
https://trello.com/c/OqYRD1pR
Some users are confused from the example we provide and try to type the word `miles` in the "maximum distance from school" field.
Remove the word `miles` from the label to make it a bit more clear that the field expects a number value.
> Update the form label for the maximum_distance_from_school field

- config/initializers/content_security_policy.rb
- config/webpacker.yml
https://trello.com/c/vWT6CZmd/
The local dev env is failing to connect to the webpack-dev-server because 
1. it tries `https://localhost:3035`, but the server uses `http://`
2. the CSP is blocking the connections
Start the server with ssl and update the CSP to allow the connections.
Visit https://localhost:3035/sockjs-node/ and accept/allow the self-signed certificate. Then open visit the app and check there are no related errors in the browser's dev console.
> Allow connections to webpack dev server

- app/helpers/application_helper.rb
- app/views/layouts/application.html.erb
- spec/helpers/application_helper_spec.rb
https://trello.com/c/fr2sSkra
Currently the top site header is linked to the homepage, driving the school managers away from the school dashboard when clicking it. Making it context dependent will keep the candidates on the main website and the school managers in the school dashboard.
Add a helper method to return the school dashboard root path for the school dashboard pages and the root path for any other page.
Clicking the "Manage school experience" header from any page in the school dashboard, should send you in the school dashboard root page.
> Make the site header link context dependent

- app/views/layouts/application.html.erb
https://trello.com/c/alpK0OGh
Many schools reported that finding support was more difficult than it should have been
Add a `Contact us` link in the footer of the schools dashboard pages
The link should be in the footer of the school dashboard pages, but not in any candidates related pages
> Add the Contact us link in the school dashboard footer

- Gemfile
- Gemfile.lock
Snyk created the #1898 #1899 PRs which update the `Gemfile`, but not the `Gemfile.lock`.
This PR replaces both of them.
> Update Gemfile to reduce vulnerabilities

- app/notify/notify_email/candidate_request_rejection_nopiii.74f84226-539a-43b0-b887-d8ffc9348965.md
- app/views/candidates/schools/_expanded_search.html.erb
- app/views/schools/confirmed_bookings/cancellations/_letter.html.erb
- app/views/schools/placement_requests/cancellations/_letter.html.erb
- app/views/shared/candidates/_alert_notification.html.erb
- features/step_definitions/candidates/schools/results_steps.rb
https://trello.com/c/cKz8j36p
GSE is using old urls to link to GIT service, but they still work because GIT has redirects in place.
Update the links to GIT based on the GIT redirects.
> Update the links to GIT

- package.json
- yarn.lock
This reverts commit e5f19501e9059189faf9d0f5e803744e34f13b54.
webpack-dev-serve 4.x is not compatible with Webpacker 5.x. Need to revert and wait for the Webpacker 6.x stable to be released.
> Revert "Bump webpack-dev-server from 3.11.2 to 4.1.0"

- app/views/schools/change_schools/show.html.erb
- features/schools/signin.feature
- features/step_definitions/schools/signin_steps.rb
https://trello.com/c/lawfXBty/196-dev-update-the-change-school-button-to-say-select-school
Users find the `Change school` button confusing when there's only one school list. Changing it to `Select school` will hopefully make it less confusing.
Update the submit button in the Change school page
|before|after|
|-|-|
|![before](https://user-images.githubusercontent.com/951947/133096488-e3a17f39-31d3-478d-a816-d13fa58fb17e.png)|![after](https://user-images.githubusercontent.com/951947/133096514-8152f34e-ff46-45f0-b59f-68801daa12b2.png)}
> Rename the Change school button to Select school

- app/views/schools/on_boarding/profiles/show.html.erb
Linked to this: https://trello.com/c/C5P1oX2U
This is a stopgap until certain changes are made on the check answers page. I am creating this PR as I'm going to send guidance to schools for re-starting their profile. I want to head off any issues with profile changes not saving.
> Adding warning text to check answers page as stopgap

- app/controllers/schools/change_schools_controller.rb
- app/views/schools/change_schools/show.html.erb
- config/locales/en.yml
- features/schools/signin.feature
- features/step_definitions/schools/signin_steps.rb
- spec/controllers/schools/change_schools_controller_spec.rb
- spec/views/schools/change_schools/show.html.erb_spec.rb
https://trello.com/c/pSezDoaD
Users are not clear about the role of the select your school page, and are suffering a number of issues. 
We've settled on this new design as it helps make clear the different options for the page, either selecting a school, or requesting access to it.
> Update the change school layout

- app/views/cookie_preferences/edit.html.erb
- config/locales/en.yml
https://trello.com/c/0JRIkXZE
Migrate the cookie preferences form from the deprecated `govuk_elements_form_builder` to `govuk_elements_form_builder`
Update the localisation file and use the `govuk_elements_form_builder` helpers to render the form
Visit the cookie page. Should look and behave exactly the same with before.
> Migrate the cookie preferences form to govuk_design_system_formbuilder

- app/views/feedbacks/_form.html.erb
- config/locales/en.yml
https://trello.com/c/oXzEM7Qz/181-migrate-the-feedback-form
Migrate the feedback forms from the deprecated `govuk_elements_form_builder` to `govuk_elements_form_builder`
Update the localisation file and the feedback form partial
Visit the candidate and school feedback pages.  They should look and behave exactly the same with before.
> Migrate the feedback forms to govuk_elements_form_builder

- app/controllers/schools/on_boarding/confirmations_controller.rb
- app/controllers/schools/on_boarding/previews_controller.rb
- app/controllers/schools/on_boarding/profiles_controller.rb
- app/views/schools/on_boarding/previews/show.html.erb
- app/views/schools/on_boarding/profiles/show.html.erb
- app/webpacker/stylesheets/application.scss
- app/webpacker/stylesheets/school-preview.scss
- features/schools/onboarding/preview.feature
- features/schools/onboarding/school_profile.feature
- spec/controllers/schools/on_boarding/confirmations_controller_spec.rb
https://trello.com/c/C5P1oX2U/199-change-the-on-boarding-preview-step-to-be-optional
The problem is that school managers believe they have published their school profile changes when they see the summary page and they skip the preview and confirmation steps.
In order to make it less confusing, we are changing the workflow to allow school managers to publish their changes from the summary page instead.
- move the confirmation action that publishes the changes, from the preview page to the summary page
- make the preview page optional with enhanced visuals to spot the preview content easier
> Move the school changes confirmation to the summary page

- app/views/layouts/application.html.erb
https://trello.com/c/hIRbGJtt
In the footer of the school dashboard we link the `privacy policy` to the latest policy (fetched from the CRM), but there's another policy for the schools which is already used in the on boarding process and probably should be used in the footer as well.
Use the school privacy policy in the school dashboard footer.
> Use the schools privacy policy in the school dashboard

- app/controllers/pages_controller.rb
- app/views/pages/_request_organisation_access.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/servertest.rb
- config/environments/staging.rb
- config/environments/test.rb
N/A
We have many user difficulties with where they have been added/associated to a school, but do not have the School Experience service on DfE Sign In.
To rectify this, I've added some help text to a page where users are likely to experience the error.
@leoapost I need you to take this PR and ensure the link to DfE Sign In's add services to my account page: This is the pre-prod link: https://pp-services.signin.education.gov.uk/approvals/select-organisation?services=add
Can you make it so that it's formatted for Ruby in one of the link helpers?
> Adding help text for a common error

- app/views/candidates/home/index.html.erb
- app/views/schools/dashboards/_account_admin.html.erb
- app/views/schools/dashboards/_manage_dates.html.erb
- app/views/schools/dashboards/_new_requests_and_bookings.html.erb
- features/schools/dashboard.feature
Following prototype by Gary. Link here: https://get-school-experience-prototype.london.cloudapps.digital/reduce-rejection/start-page#
Removed one bullet point on advice from policy officials.
The aim of this is to reduce rejection rates by being clearer upfront on some of the requirements.
---
Also, updating some indentation from a previous PR.
> Update start page - new copy PLUS amends to content dashboard

- app/views/candidates/registrations/application_previews/show.html.erb
- app/views/candidates/registrations/background_checks/_form.html.erb
- app/views/candidates/registrations/confirmation_emails/show.html.erb
- app/views/candidates/registrations/contact_informations/_form.html.erb
- app/views/candidates/registrations/educations/_form.html.erb
- app/views/candidates/registrations/personal_informations/_form.html.erb
- app/views/candidates/registrations/placement_preferences/_form.html.erb
- app/views/candidates/registrations/sign_ins/show.html.erb
- app/views/candidates/registrations/teaching_preferences/_form.html.erb
- app/views/candidates/school_searches/new.html.erb
https://trello.com/c/J3LSsBPq
Some candidate flows were missing <back breadcrumbs. This adds them in.
> add back links

- app/helpers/schools/dashboards_helper.rb
- app/views/schools/dashboards/_account_admin.html.erb
- config/locales/en.yml
- features/schools/dashboard.feature
- features/schools/toggle_enabling_and_disabling.feature
- spec/helpers/schools/dashboards_helper_spec.rb
Comments from content designer to improve consistency and clarity of pages related to candidate requests.
Also merged #1989 into this following @peteryates comments on that.
> Content improvements and update tests (requests on/off pages)

- app/views/schools/dashboards/_your_school_is_disabled.html.erb
- features/step_definitions/schools/dashboard_steps.rb
This is an update to mirror the new language on Profiles being 'on' instead of 'enabled'. Our error messages should be reflective of this new language.
> update error message and tests

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- script/get_next_mapping.sh
- terraform/paas/application.tf
- terraform/paas/route.tf
- terraform/paas/variables.tf
When using Review Applications the name of the application constantly changes, and therefore does not match a DFE_SIGNIN Url, there is no API for DFE_SIGNIN.
So there are two solutions:
1. Dummy the DFE_SIGNIN .. This has been dismissed as a lot of development and this application requires data from DFE_SIGNIN and would need every condition stubbing.
2. Create a set of 10 static URLS and link the Review to the first available free one.
1.  On review deployment, 
2. cf cli installed
3. script executed that finds current or latest available static address
4. address passed to terraform
5.  terraform applies it on build and sets DFE_SIGNIN_BASE_URL
6. after deployment comment added to github
> Add Routine to get next available static route

- .github/workflows/build.yml
- README.md
Comments in Readme changed, to force a job to run through with no change to the application, but allow a full pipeline test of a review apps and the static DFE Sign in routes.
So it seems terraform will create a route and map it to an application, but if the route is removed it may just be unmapped. to help overcome this we are running delete-orphaned-routes prior to the deployment.
> Comment about Review Applications

- app/views/schools/dashboards/show.html.erb
- features/schools/dashboard.feature
N/A
We want to update the font size for some of the new dashboard, this ups the size of 'Help and Support' to match everything below the main features.
Amending `low-priority` class on dashboard to `medium-priority`. Also amending the tests.
> Font size change for help and support

- app/services/candidates/registrations/personal_information.rb
Date of birth was kept here to support users who were part-way through their sign up journey at the time the change to remove date of birth was merged. We can safely remove it now.
> Remove date of birth

- app/controllers/application_controller.rb
- app/controllers/candidates/schools_controller.rb
- spec/controllers/application_controller_spec.rb
N/A
The robots.txt was updated recently to include `allow` rules for all the enabled schools, but the robots still won't crawl them because the `X-Robots-Tag` header is set to `none`.
Set the header value to `all` when visiting profiles of enabled schools.
Check the headers when visiting a disabled/enabled school profile.
> Set X-Robots-Tag header to all when visiting school profiles

- app/helpers/candidates/maps_helper.rb
- app/views/candidates/registrations/educations/_form.html.erb
[Trello](https://trello.com/c/QBfndLQ4)
In Stimulus.js 2.0, we need to include the controller name in the data target attributes. 
This was showing up as a warning in the development console. 👇 
- Update Stimulus.js data target attributes
> Update Stimulus.js data target attributes

- app/controllers/pages_controller.rb
- app/views/pages/robots.txt.erb
- app/views/pages/sitemap.xml.builder
- config/routes.rb
- spec/controllers/pages_controller_spec.rb
https://trello.com/c/KBsWDeyO
The robots.txt was recently updated to allow the enabled school profiles to be crawled, however there are no links in the service to these pages. Adding a sitemap.xml will help robots find them.
Add the controller method, view and route to create the `sitemap.xml` dynamically on each request.
Visit the `/sitemap.xml` and it should include records for the enabled profiles
> Add sitemap.xml

- app/views/candidates/registrations/application_previews/show.html.erb
- app/views/candidates/registrations/personal_informations/_form.html.erb
- app/webpacker/controllers/prevent_double_click_controller.js
- app/webpacker/packs/application.js
[Trello](https://trello.com/c/zfyJ8gFM)
Our CSP policy was blocking the prevent double click inline JavaScript from executing.
We could use a hash or nonce for this, but the CSP policy and the project's JavaScript will be easier to maintain if moved into a Stimulus.js controller.
- Move prevent double click JavaScript into a Stimulus.js controller
> Move prevent double click JavaScript into Stimulus.js controller

- app/controllers/application_controller.rb
- spec/controllers/pages_controller_spec.rb
N/A
Google console can't read the sitemap, but Bing parsed it just fine. We suspect it's because the `X-Robots-Tag` header. 
Include the `/robots.txt` and `/sitemap.xml` in the CRAWLABLE_PATHS which will set `X-Robots-Tag` to `all`
> Make the /robots.txt and /sitemap.xml crawlable

- app/views/pages/robots.txt.erb
N/A
Google console fails when parsing the robots.txt and annotates the `Disallow: /*` rule.
Add `Allow` rules for the robots and sitemap paths in the robots.txt
> Add Allow rules for the robots and sitemap paths

- app/jobs/cron/sync_schools_job.rb
- spec/jobs/cron/sync_schools_job_spec.rb
N/A
The Job runs off hours and started failing few days ago when downloading the csv file with Invalid URI error, but the job works fine when we manually run it during working hours. We suspect the file may not be ready early in the morning anymore, so we want to schedule it few hours later and see if it will fail again.
Set the job to run at 7.30am
> Change the schedule time of the sync school job

- Gemfile
- Gemfile.lock
- app/views/candidates/home/index.html.erb
- app/views/candidates/schools/show.html.erb
- app/views/layouts/application.html.erb
- spec/controllers/candidates/home_controller_spec.rb
- spec/controllers/candidates/schools_controller_spec.rb
https://trello.com/c/Qyi2xcFU
We want to add meta descriptions to improve the GSE's SEO
Install the meta-tags gem
Add meta description to Homepage and school profiles
Visit the Homepage and some school profiles and look for the meta tags in the source of the pages.
> Add meta description tags

- app/models/candidates/verification_code.rb
- spec/controllers/candidates/registrations/contact_informations_controller_spec.rb
- spec/controllers/candidates/registrations/sign_ins_controller_spec.rb
- spec/factories/api_factory.rb
- spec/factories/bookings/candidates_factory.rb
- spec/factories/candidates/registrations/gitis_registration_session_factory.rb
- spec/helpers/gitis_contact_helper_spec.rb
- spec/models/bookings/candidate_spec.rb
- spec/models/bookings/registration_contact_mapper_spec.rb
- spec/models/candidates/verification_code_spec.rb
- spec/models/schools/csv_export_row_spec.rb
- spec/services/bookings/gitis/contact_fetcher_spec.rb
- spec/services/bookings/reminder_spec.rb
- spec/services/candidates/registrations/gitis_registration_session_spec.rb
- spec/support/candidate_signin.rb
- spec/support/stubbed_api.rb
https://trello.com/c/Ua10iIgf
Some DFE services now allow candidates to register in gitis without a name, but GSE still needs it so it fails when these candidates try to confirm their school experience requests.
Update the candidate name in gitis when missing to ensure the CRM contact always has a name
> Update the gitis candidate name when missing

- app/models/bookings/school.rb
- app/views/candidates/schools/_phase1.html.erb
- app/views/candidates/schools/_phase2.html.erb
- spec/factories/bookings/school_factory.rb
- spec/models/bookings/school_spec.rb
https://trello.com/c/OvwmD6hw
We want to display the `Start request` button only in school profiles of enabled schools that offer flex or fixed dates
Display the button only for enable schools with available fixed dates or flex dates with description.
Visit the page of a:
1. disabled school
2. enabled school without dates
3. enabled school with unavailable dates
4. enabled school with available dates. 
The button should appear only in the profile of the enabled school with available dates.
> Hide request button

- app/views/candidates/schools/show.html.erb
- spec/factories/bookings/school_factory.rb
- spec/views/candidates/schools/show.html.erb_spec.rb
https://trello.com/c/41scHves
https://trello.com/c/VKcPBKd5
The goal is to inform the candidates that the school they are looking is either not onboarded yet or it doesn't offer any placements at the moment and point them to the Search page.
Add inset banners in the school profile page
> Add banner in school profiles to promote the search page

- app/views/candidates/schools/_phase1.html.erb
- spec/views/candidates/schools/show.html.erb_spec.rb
https://trello.com/c/0EOQv5td
There's a bug that displays the `placement` details (experience type and availability info) in profiles of non-onboarded schools.
Hide the placement details for non-onboarded schools
> Hide the placement details for non-onboarded schools

- app/views/application/_google_analytics.html.erb
- spec/requests/google_analytics/presence_spec.rb
[Trello](https://trello.com/c/CEMSsELU)
When `auto` is specified for the Google Analytics cookie domain (which it is in the recommended snippet), then it will be set to the highest possible domain level. For School Experience, this will be `.education.gov.uk`. 
However, Rails ActionDispatch::Cookies defaults to the full domain including subdomains (`schoolexperience.education.gov.uk`).
This meant that we were adding the Google Analytics cookies on `.education.gov.uk`, but trying to remove them from `schoolexperience.education.gov.uk` when the user opts out. The domains must match, so the cookies weren't being removed.
Removing the `auto` setting means that the cookies use the default value of the full domain instead.
- Remove Google Analytics automatic cookie domain configuration.
> Remove Google Analytics automatic cookie domain configuration

- app/views/application/_google_analytics.html.erb
- spec/requests/google_analytics/presence_spec.rb
[Trello](https://trello.com/c/CEMSsELU)
Using the default value for the Google Analytics cookies domain includes a leading dot (`.schoolexperience.education.gov.uk`) which doesn't match the other cookies. Instead, use `document.location.hostname`.
- Use `document.location.hostname` for Google Analytics cookies domain
> Use `document.location.hostname` for Google Analytics cookies domain

- app/views/application/_google_analytics.html.erb
- spec/requests/google_analytics/presence_spec.rb
There is a domain option `none`, which sets the cookies to host-only (no leading dot). This has been tested locally by editing `etc/hosts` to have a proper domain name.
> Set Google analytics domain options to `none`

- app/controllers/schools/placement_requests/cancellations/notification_deliveries_controller.rb
- app/notify/notify_email/candidate_request_rejection.rb
- app/notify/notify_email/candidate_request_rejection_nopiii.74f84226-539a-43b0-b887-d8ffc9348965.md
- spec/controllers/schools/placement_requests/cancellations/notification_deliveries_controller_spec.rb
- spec/notify/notify_email/candidate_request_rejection_spec.rb
- spec/support/fake_get_into_teaching_api_client.rb
N/A
We want to greet the candidates with their name when sending the request rejection email.
Add the `candidate_name` placeholder in the email template and provide the candidate's name to the template when sending the email.
> Add the candidate name in the request rejection email

- app/webpacker/controllers/prevent_double_click_controller.js
We recently fixed some JavaScript that disables buttons so that a user can't submit a form multiple times.
However, pages don't reload fully when navigating back using the browser's back button, so the button remains disabled.
We can add an event listener for the "pageshow" event to re-enable the button when this happens.
- Re-enable buttons when navigating to page with browser back button
> Re-enable buttons when navigating to page with browser back button

- app/services/candidates/registrations/behaviours/teaching_preference.rb
- spec/factories/bookings/placement_requests_factory.rb
- spec/services/candidates/registrations/teaching_preference_spec.rb
[Trello](https://trello.com/c/P8NMlBNb)
Currently, a candidate can choose the same subject for their first choice and second choice. 
Add some validation to prevent this.
- Validate that candidate second subject choice is different than first
Is this better? Is the message okay?
> Validate that candidate second subject choice is different than first

- app/controllers/schools/archived_placement_requests_controller.rb
- app/controllers/schools/placement_requests_controller.rb
- app/models/bookings/placement_request.rb
- app/views/schools/archived_placement_requests/index.html.erb
- config/routes.rb
- spec/controllers/schools/archived_placement_requests_controller_spec.rb
- spec/controllers/schools/placement_requests_controller_spec.rb
- spec/factories/bookings/placement_dates.rb
- spec/factories/bookings/placement_request_factory.rb
https://trello.com/c/C6leT8zo
Schools received some placement requests ages ago which they don't want to trigger the emails by accepting/rejecting the, so they just sitting in the manage requests page.
To make this a bit more manageable for the school managers, we want to move placement requests that expired more than a month ago to their own page. 
Keep displaying recently expired requests (no more than a month ago) in the placement requests
Create a new archive page to display unprocessed requests that expired a month ago
Add a message in the placement requests page to inform the school managers about the new changes that also includes a link to access the archive page
> Create a page to display the expired requests older than a month

- app/models/bookings/placement_request.rb
- spec/controllers/schools/archived_placement_requests_controller_spec.rb
- spec/controllers/schools/placement_requests_controller_spec.rb
https://trello.com/c/k9pjFIne
We recently moved the old expired placement requests for fixed dates to the `archived` page, so to help declutter the `manage requests` page for schools that have many old requests that don't want to process.
Schools with flex dates now have the same problem, so we want to move requests for flex dates that are unprocessed for longer than two months in the `archived` page as well.
Expand the model scopes to include flex dates too and also mark them as expired in the UI.
> Archive flex request that are unprocessed for two months

- app/views/candidates/registrations/placement_requests/show.html.erb
N/A
Following Adam's review of DAC report from 2019, this was a small usability fix of changing a H3 to a H2. We had a H1, but no corresponding H2. It's potentially jarring to hop straight from H1 -> H3.
Usability fix of H3 -> H2 on Request confirmation page.
> Usability fix of H3 -> H2

- features/schools/attendances/index.feature
- features/schools/confirm_attendance.feature
- features/schools/confirmed_bookings/editing_a_date.feature
- features/schools/confirmed_bookings/index.feature
- features/schools/confirmed_bookings/show.feature
- features/schools/previous_bookings/index.feature
- features/schools/previous_bookings/show.feature
- features/step_definitions/schools/attendances_steps.rb
- features/step_definitions/schools/bookings_steps.rb
- features/step_definitions/schools/previous_bookings_steps.rb
- spec/factories/bookings/placement_requests_factory.rb
N/A
#2106 broke some feature tests because certain placement requests use the Chemistry subject which doesn't exist in the school subjects.
Add the schools subjects step in the failing tests which creates and associates three subjects to the school and use one of them as the second subject choice in the placement requests.
> Fix the broken feature tests

- app/controllers/schools/placement_requests_controller.rb
- features/schools/placement_requests/index.feature
- features/step_definitions/schools/placement_request_steps.rb
- spec/controllers/schools/placement_requests_controller_spec.rb
- spec/factories/bookings/placement_request/cancellations_factory.rb
https://trello.com/c/kKDRkiFJ
Displaying the rejected requests in the manage requests page is a bit confusing, especially when they have their own page.
Use the `unprocessed` scope when retrieving the placement requests in the manage requests page.
> Do not display rejected requests in the manage requests page

- app/models/bookings/placement_request.rb
- spec/models/bookings/placement_request_spec.rb
https://trello.com/c/aV8OpoWy
Placement requests for flex dates are expired the next day after they are created, which is confusing for the school managers. 
We want to mark them as expired when they are archived (2 months after they are received).
Update the placement request `#flex_date_expired?` to return true after two months of the created_at date.
> Expire flex requests only when they are archived

- app/webpacker/stylesheets/subject-and-date-information.scss
https://trello.com/c/B6HExWgC
Currently, we display fixed dates at the bottom of the subject lists when we ask a user to select a date and subject, making it hard for the user to see the dates when the school offers placements dates with long subject lists.
Change the vertical alignment of the date to top.
|before|after|
|-|-|
|![before](https://user-images.githubusercontent.com/951947/145189563-3f164e4f-e0c4-4fc1-8a54-db6fd9e120de.png)|![after](https://user-images.githubusercontent.com/951947/145189576-9fde8276-298e-4676-96e9-50c612ab5b5a.png)|
> Improve dates position for long subject lists

- app/helpers/application_helper.rb
- app/views/shared/application/_phase_banner.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/servertest.rb
- config/environments/test.rb
- features/schools/landing_page.feature
- features/step_definitions/schools/account_steps.rb
https://trello.com/c/J44GrRUH
It's not expected the GSE users to be using the switch service function often given that they're are using the service to manage school experience and not anything else.
Remove both links appearing in the phase banner when school managers are logged in and logged out.
> Remove the DSI service list links

- app/controllers/schools/rejected_requests_controller.rb
N/A
Bullet caught a N+1 problem with the subjects in the rejected requests page.
Eager load the `subject` association
> Fix N+1 in the rejected request page

- app/controllers/schools/placement_requests/acceptance/make_changes_controller.rb
- app/models/bookings/booking.rb
- app/views/schools/placement_requests/acceptance/make_changes/new.html.erb
- config/locales/en.yml
- features/schools/placement_requests/acceptance/confirming_a_request_with_a_future_date.feature
- spec/models/bookings/booking_spec.rb
https://trello.com/c/lvDPPg6S
Schools can offer placement dates which can last multiple days, however the booking duration always defaults to 1 day when they accept requests.
The booking duration should be as long as the placement dates are and also allow the school managers to change it when making changes during the acceptance process.
- Update the booking model to inherit the placement date duration for fixed placement dates.
- Add a number field to allow to change the duration in the `acceptance/make_changes` page
1. Accept a request for a fixed date
2. Click `Make changes`
There should be a duration field under the date field, which should have the placement date duration prefilled and allow you to update it.
The changes should be reflected in the confirmation email preview.
> Inherit the booking duration from the placement date

- app/notify/notify_email/candidate_booking_confirmation.rb
- spec/notify/notify_email/candidate_booking_confirmation_spec.rb
https://trello.com/c/CJUzMsIa
Some schools don't provide any experience details since it's optional, but 
the acceptance confirmation email fails because it expects non-nil values.
Call `to_s` on the experience_details attribute to get an empty string when it's nil.
> Prevent the confirmation email from failing when the experience_details is nil

- app/controllers/schools/on_boarding/profiles_controller.rb
- app/views/schools/on_boarding/profiles/show.html.erb
- config/routes.rb
- features/schools/onboarding/school_profile.feature
- features/step_definitions/common_steps.rb
- features/step_definitions/schools/profile_steps.rb
- spec/controllers/schools/on_boarding/profiles_controller_spec.rb
- spec/factories/bookings/school_factory.rb
https://trello.com/c/vnLofAdF
We want to remove the checkbox for Providers that are 'updating' their profile and instead display a publish button.
- Add a new route and a method in the school profile controller to publish profile changes for onboarded schools
- Update the profile page to display the publish button instead of the confirmation box for onboarded schools
> Remove the profile confirmation container for onboarded schools

- app/models/bookings/placement_request/cancellation.rb
- config/locales/en.yml
- features/schools/placement_requests/cancelling.feature
- features/schools/rejected_requests/index.feature
- features/schools/rejected_requests/show.feature
- features/step_definitions/schools/placement_requests/cancelling_steps.rb
- features/step_definitions/schools/rejected_requests_steps.rb
https://trello.com/c/6lM3d3W2
One of our researches showed that we could help schools by adding some new rejection reasons into the decline/reject email. 
We also want to refresh the content of some of the current reasons.
- Update the content of the current reasons
- Add the new reasons in the Cancellation model and en.yml
1. Visit the school dashboard
2. Click Manage requests 
2. View a placement request by clicking the View action
3. Click Reject request to see the rejection form
4. The form should have the new reasons
5. Chose one of the new reasons and click the preview button
6. The preview page should display the chosen reason
7. Click Send rejection email
8. The confirmation email should include the chosen reason
9. The chosen reason should also be displayed in the rejected …
> Update the reasons list in the rejection form

- app/controllers/schools/availability_info_controller.rb
- app/controllers/schools/base_controller.rb
- app/controllers/schools/placement_dates/configurations_controller.rb
- app/controllers/schools/placement_dates/subject_selections_controller.rb
- app/controllers/schools/placement_dates_controller.rb
- features/schools/availability_information/edit.feature
- features/schools/placement_dates/new.feature
https://trello.com/c/zpLjmwOV
Disabled or newly on-boarded schools need an extra step to enable their profile after adding availability, but we want to make their journey shorter and more seamless by auto-enabling them.
Add a method in the schools base controller to update the school's `enable` attribute and call it when adding availability.
1. Turn off the profile the school
2. Confirm the "profile is turned off" warning message is displayed in the dashboard
2. Add availability (either fixed or flex dates)
3. The school should be enabled and the warning message should not be in the dashboard anymore
> Auto-enable school when adds availability

- app/helpers/gitis_contact_helper.rb
- app/models/bookings/registration_contact_mapper.rb
- app/views/schools/confirmed_bookings/date/edit.html.erb
- app/views/schools/placement_requests/_personal_details.html.erb
- app/views/schools/placement_requests/show.html.erb
- spec/controllers/candidates/registrations/contact_informations_controller_spec.rb
- spec/factories/api_factory.rb
- spec/helpers/gitis_contact_helper_spec.rb
- spec/models/bookings/registration_contact_mapper_spec.rb
- spec/services/candidates/registrations/gitis_registration_session_spec.rb
https://trello.com/c/ILVGaw8n
Currently, if primary phone number or primary email address has a value in the CRM, we update secondary phone number or email instead.
This was a decision made in phase 1, but following a discussion with the CRM team, we have decided that we should change the behaviour and overwrite primary phone number after a matchback, so that the contact information is always up to date (email won't actually be affected because we don't allow candidates to update their email following a matchback).
I have removed everything expect `telephone` and `email address` from the API sign up request.
- Remove non-primary phone numbers and email address
I have done a sign up and matchback. The candidate details seem to be fine in the Manage section.
> Remove non-primary phone numbers and email address

- config/locales/en.yml
https://trello.com/c/6lM3d3W2
We recently updated the rejections reasons and added full stop marks at the end of them, but missed some.
Add full stops to the rejection reasons that don't have.
> Add full stops in the rejection reasons

- .github/workflows/clean_reviews.yml
After each review app is finished with it, it is destroyed and the application is deleted.
However, there are the odd conditions where this fails, usually with dependabot changes.
It isnt such a difficult job to delete them manually, but it is better practice to have checks in place so a script I wrote to clean this up has been put into github_actions so that it can be run by the team, and even periodically if deemed necessary
> Introduce Periodic Review Apps Cleaner

- Gemfile.lock
- app/controllers/concerns/gitis_authentication.rb
- app/models/candidates/verification_code.rb
- app/services/bookings/gitis/event_logger.rb
- app/services/candidates/registrations/personal_information.rb
- config/initializers/git_api_client.rb
- spec/features/candidates/api_registrations_spec.rb
- spec/models/bookings/registration_contact_mapper_spec.rb
- spec/models/candidates/verification_code_spec.rb
- spec/services/bookings/gitis/event_logger_spec.rb
- spec/services/candidates/registrations/personal_information_spec.rb
- spec/support/fake_get_into_teaching_api_client.rb
- spec/support/stubbed_api.rb
[Trello-2777](https://trello.com/c/oYLSzOTp/2777-monkey-patch-api-client-models-to-support-snakecase-attributes-in-initializer?filter=member:rossoliver15)
The API client v2 uses `snake_case` attributes in the initializers instead of `camelCase`; this updates all the references.
- Update to v2 of the API client
> Update to v2 of the API client

- app/views/schools/on_boarding/profiles/show.html.erb
- config/routes.rb
- features/schools/onboarding/school_profile.feature
- spec/controllers/schools/on_boarding/profiles_controller_spec.rb
N/A
Since we need to support browsers with disabled javascript, the profile publish route needs to be changed to GET for the publish button to work.
Update the route and the button
1. Go to school dashboard 
2. Click update profile
3. Make some changes to the profile
3. Click publish changes
4. Should take you to the confirmation page
5. Go back to the profile to confirm it's updated
> Change the profile publish route to GET

- app/views/candidates/registrations/application_previews/show.html.erb
- app/views/candidates/registrations/background_checks/_form.html.erb
- app/views/candidates/registrations/contact_informations/_form.html.erb
- app/views/candidates/registrations/educations/_form.html.erb
- app/views/candidates/registrations/personal_informations/_form.html.erb
- app/views/candidates/registrations/placement_preferences/_form.html.erb
- app/views/candidates/registrations/sign_ins/show.html.erb
- app/views/candidates/registrations/subject_and_date_informations/_form.html.erb
- app/views/candidates/registrations/teaching_preferences/_form.html.erb
- config/locales/en.yml
- spec/features/candidates/api_registrations_spec.rb
- spec/views/candidates/registrations/personal_informations/_form.html.erb_spec.rb
[Trello-177](https://trello.com/c/CxfaV95I/177-migrate-the-candidates-registrations-forms)
Updates the main candidate registration flow steps to use the GOV.UK form builder components.
- Use GOV.UK form builder for sign in step
- Use GOV.UK form builder for personal informations step
Add missing translations for first/last name (the old form builder must have inferred these from the field names).
Checked readonly/disabled state still behaves and double click prevention is still firing.
- Use GOV.UK form builder for contact information step
Adds missing translations.
Checked conditional logic around street label appearing on validation errors.
- Use GOV.UK form builder for education step
Moved translation to work correctly with legend.
Checked various states/errors work as certain fields …
> Update candidate registration flow to use GOV.UK form builder

- app/views/schools/on_boarding/confirmations/show.html.erb
- features/schools/onboarding/school_profile.feature
https://trello.com/c/qCHStwuY
The current profile setup confirmation page has outdated content that needs to be updated.
Update the confirmation page
1. Visit the dashboard of a non-onboarded school
2. Complete the profile and click the set up profile button
3. The new content should be displayed in the confirmation page
> Update the onboarding confirmation page

- app/views/candidates/placement_requests/cancellations/_new_booking.html.erb
- app/views/candidates/placement_requests/cancellations/_new_placement_request.html.erb
[Trello-176](https://trello.com/c/KcjjK7R1/176-migrate-the-candidates-placementrequests-cancellations-forms)
Update cancellation forms to use GOV.UK form builder.
- Use GOV.UK form builder for cancellation forms
To view these two forms you need to:
1. Create a booking and hit the cancel link in the email.
2. Create a booking, login as the school and accept it, then click the cancel link in the subsequent confirmation email.
> Update placement cancellation forms to use GOV.UK form builder

- app/views/candidates/sessions/create.html.erb
- app/views/candidates/sessions/new.html.erb
[Trello-179](https://trello.com/c/DUHn6X5u/179-migrate-the-candidates-sessions-forms)
Update the candidate sign in forms to use the GOV.UK form builder components.
- Use GOV.UK form builder for candidate sign in forms
These forms don't appear to be accessible in production, but I was able to access them in development (they are behind the `phase` configuration).
> Update candidate sign in forms to use GOV.UK form builder

- app/views/schools/placement_dates/configurations/new.html.erb
- app/views/schools/placement_dates/edit.html.erb
- app/views/schools/placement_dates/new.html.erb
- app/views/schools/placement_dates/subject_selections/new.html.erb
- config/locales/en.yml
- features/step_definitions/form_steps.rb
[Trello-186](https://trello.com/c/PULJYgGN/186-migrate-the-schools-placementdates-forms)
We want to use the new GOV.UK form builder for all the forms in SE.
- Use GOV.UK form builder on edit placement date
- Use GOV.UK form builder on new placement date
The `false` label text is manually mapped as the form builder doesn't seem to map it to the `false` key correctly, I'm not sure why.
- Use GOV.UK form builder for subject selections form
- Use GOV.UK form builder for placement dates configuration form
The placement dates subject selection and configuration paths are feature switched off in production. You can access them at:
```
/schools/placement_dates/:id/subject_selection/new
/schools/placement_dates/:id/configuration/new
```
> Update placement dates subject selection/configuration to use new GOV.UK form builder

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/destroy.yml
Github now provideds a concurency group option. so rather than use turnstyle I am going to try concurency checks to prevent deployments to the same environment
> Concurency Check

- app/views/schools/availability_info/edit.html.erb
- app/views/schools/availability_preferences/edit.html.erb
- config/locales/en.yml
[Trello-182](https://trello.com/c/ndMLK0xG/182-migrate-the-schools-availabilityinfo-forms)
We want to use the new GOV.UK form builder for all of the school experience forms.
- Use GOV.UK form builder for availability preferences form
- Use GOV.UK form builder for availability info form
Sign in as a school and go to "Change how available dates are displayed" to test these forms.
There's no error summary on one of the forms; instead of adding it I've left it consistent with master for now.
> Update school availability forms to use GOV.UK form builder

- app/views/schools/change_schools/show.html.erb
- config/locales/en.yml
[Trello-183](https://trello.com/c/uGlMsppl/183-migrate-the-schools-changeschools-form)
We want to use the new GOV.UK form builder for all of the school experience forms.
- Use GOV.UK form builder on school change form
> Update school change form to use GOV.UK form builder

- app/views/schools/confirmed_bookings/cancellations/_form.html.erb
- app/views/schools/confirmed_bookings/date/edit.html.erb
- config/locales/en.yml
[Trello-184](https://trello.com/c/KQaVZXmx/184-dev-migrate-the-schools-confirmedbookings-forms)
We want to use the new GOV.UK form builder for all of the school experience forms.
- Use GOV.UK form builder on booking cancellation form
- Use GOV.UK form builder on cancellation date form
Relevant paths:
```
/schools/bookings/:id/cancellation/new
/schools/bookings/:id/date/edit
```
> Update cancellation edit forms to use GOV.UK form builder

- app/views/candidates/school_searches/new.html.erb
- app/views/candidates/schools/index.html.erb
- app/webpacker/stylesheets/school-search.scss
- spec/views/candidates/school_searches/new.html.erb_spec.rb
- spec/views/candidates/schools/index.html.erb_spec.rb
[Trello-178](https://trello.com/c/mLbFqGrn/178-migrate-the-candidates-schoolsearches-forms)
We want to use the new GOV.UK form builder for all of the school experience forms.
- Use GOV.UK form builder on search form
- Use GOV.UK form builder on search results page
Due to the use of `as: ''` in the form call the translations are set manually for these forms (full explanation in the commit messages).
> Update school search forms to use GOV.UK form builder

- .github/workflows/manual.yml
Github have introduced 'TYPES' to their workflow input . 
[Documentation](https://github.blog/changelog/2021-11-10-github-actions-input-types-for-manual-workflows/)
> Github have introduced types on inputs for workflows.

- Gemfile
- Gemfile.lock
- app/helpers/application_helper.rb
- app/helpers/schools/confirm_attendance_helper.rb
- app/views/schools/confirm_attendance/show.html.erb
- config/initializers/govuk_form_builder.rb
- spec/helpers/application_helper_spec.rb
[Trello-470](https://trello.com/c/XC3OdLq9/470-migrate-schools-confirmattendance-form)
[Trello-469](https://trello.com/c/vfob47uo/469-remove-old-form-builder-gem)
We want to use the latest GOV.UK form builder for all of our forms.
- Use GOV.UK form builder on confirm attendance form
- Remove old form builder gem
Testing this one locally was a pain as you need confirmed bookings that are in the past to test success (you can do this by manually modifying the date of a booking to be in the past then confirm it) and to force an error I hacked the model query scopes to allow it to show a confirmed booking in the future and tried to confirm attendance:
The error summary links don't jump to the correct row, but they don't currently in master either.
> Update confirm attendance form to use GOV.UK form builder

- app/notify/notify_despatchers/sms.rb
- config/environments/production.rb
- spec/notify/notify_despatchers/notify_spec.rb
- spec/services/bookings/reminder_spec.rb
- spec/support/notify_email_shared_examples.rb
Currently, in order to test the SMS notifications we have been sending messages from our local Dev environments. However, ideally, we don't want to exceed our quota of free messages. (though a few messages won't really make a difference with the size of the free quota)
To help us stay under this quota, only send SMS in production.
This will also make any reports generated from Gov Notify more accurate, as they won't contain our Dev messages.
- Don't send SMS in non-production environments
> Dont send sms non prod

- Dockerfile
N/A
The docker builds are complaining about using old bundler version to install gems.
Update the bundler version in Dockerfile
> Update the bundler version in Dockerfile

- app/controllers/candidates/schools_controller.rb
- app/helpers/candidates/school_helper.rb
- app/models/bookings/school.rb
- app/models/bookings/school_search.rb
- app/models/candidates/school_search.rb
- app/views/candidates/schools/index.html.erb
- config/locales/en.yml
- db/migrate/20220111121054_add_parking_to_bookings_school_search.rb
- db/schema.rb
- spec/controllers/candidates/schools_controller_spec.rb
- spec/helpers/candidates/school_helper_spec.rb
- spec/models/bookings/school_search_spec.rb
- spec/models/bookings/school_spec.rb
- spec/models/candidates/school_search_spec.rb
- spec/views/candidates/schools/index.html.erb_spec.rb
https://trello.com/c/0mlwwqVl
We want to add a filter for candidates to find schools that provide parking.
Add a parking filter at the bottom of the filters section in the search page.
| before | After |
|-|-|
|![before](https://user-images.githubusercontent.com/951947/148972447-3f822d56-0fdc-42c3-9f81-146e8f5e89d8.png)|![after](https://user-images.githubusercontent.com/951947/148973065-836c58f7-1ded-40fd-8137-3b3433f341f9.png)|
> Add parking filter in the search page

- app/views/candidates/schools/index.html.erb
- app/webpacker/stylesheets/school-search.scss
https://trello.com/c/REYZCid4
Part of the search page redesign is to add grey background to the filters section and change the spacings a bit.
Change the background colour and update the spacing between the filters.
|before|after|
|-|-|
|![before](https://user-images.githubusercontent.com/951947/149125234-e33bd2df-b4fa-4a15-a92b-8d6df272fc08.png)|![after](https://user-images.githubusercontent.com/951947/149125260-c6f95179-75c4-42ce-9826-ebe6735dceba.png)|
> Change the look of the filters section

- app/views/pages/schools_privacy_policy.html.erb
https://trello.com/c/RnkeOZiI
The current Manage School Privacy Policy mentions that we share data with certain private companies, which is not the case anymore and needs to be updated accordingly.
Update the policy
Use the path: `/schools_privacy_policy`
or go to Manage school experience page and click the `Privacy Policy` link at the bottom.
> Update the manage school privacy policy

- app/views/candidates/school_searches/new.html.erb
- app/views/schools/confirmed_bookings/cancellations/show.html.erb
- app/views/schools/on_boarding/fees/_form.html.erb
- app/views/schools/placement_requests/cancellations/_form.html.erb
- config/locales/en.yml
- features/step_definitions/candidates/schools/results_steps.rb
- features/step_definitions/form_steps.rb
https://trello.com/c/pk1uu8mE
Some recent updates have broken the Cucumber tests.
- Fix form when no DBS cost: The value for this currently doesn't work. This means the user will see a validation error, and won't be able to correct it.
- Fix various selectors: Some of the elements are different in the new form builder. Update the Cucumber tests to match.
- Update input types: The cucumber tests weren't finding these inputs because they had the wrong type. It is in the GOV guidance to not use the number type for inputs, so I have left that one as text type.
- Fix labels: Some labels were wrong after the update to the new form builder.
- Use block for button_to: One of the cucumber selectors was looking for a button element. button_to generates an input usually, but generates a button when …
> Cucumber tests

- app/models/bookings/booking.rb
- features/step_definitions/form_steps.rb
Reorder presence validation to be after timeliness At the moment if you enter an invalid date into the edit booking date form it results in the attribute on the model being assigned `nil` (as they date cannot be represented).
If the model is them validated we end up with a `:blank` validation error in addition to an `:invalid_date` error. As `govuk_error_summary` only outputs one error per attribute we see the `:blank` one as its defined first in the model.
Instead, we can get the correct `:invalid_date` error (provided by the Timeliness gem via a shim on ActiveRecord) if we move the presence validator to be last. This way the timeliness error will take presedence.
In an ideal world we could use the `allow_blank: false` option as part of the timeliness validation call, but for some reason …
> Reorder presence validation to be after timeliness

- app/views/schools/on_boarding/descriptions/_form.html.erb
- config/locales/en.yml
- features/schools/onboarding/descriptions.feature
- features/step_definitions/schools/onboarding_steps.rb
https://trello.com/c/z3ILZDc7
We want to update the content in the school description form to help schools write better profiles. Using the complex question pattern seems like a good fit.
We also need to remove the skip as it's the only place we use it and looks unusual. We are keeping the form as optional until we do more tests though.
- Update the content
- Move the error summary page above the `<h1>`
- Apply 200 words limit in the text area
- Remove the skip button
|before|after|
|-|-|
|![before](https://user-images.githubusercontent.com/951947/149323784-049ed0f0-12d4-409e-8031-d3c1114a9918.png)|![after](https://user-images.githubusercontent.com/951947/149323797-511c993a-83d8-4e81-bd59-882900b27e7e.png)|
> Update the school description form

- app/notify/notify_despatchers/sms.rb
- spec/factories/api_factory.rb
- spec/notify/notify_despatchers/notify_spec.rb
N/A
We have seen a couple of production errors from GOV Notify, where we are attempting to send a SMS to an invalid phone number, or a non-mobile phone number. Check whether numbers are valid mobile numbers before despatching.
- Only despatch SMS to valid mobile numbers. Also, sanitise numbers because we saw one the other day with a full stop (something like `07777777777.`)
- Fix test: Noticed that this test would have always passed. Make sure it only passes when the correct code is in place.
> Only attempt sms mobile

- app/controllers/schools/dashboards_controller.rb
- app/models/bookings/placement_request.rb
- app/models/schools/change_school.rb
- app/models/schools/outstanding_tasks.rb
- app/views/schools/dashboards/_history_and_support.html.erb
- app/views/schools/dashboards/_requests_and_bookings.html.erb
- spec/models/bookings/placement_request_spec.rb
- spec/models/schools/outstanding_tasks_spec.rb
[Trello-433](https://trello.com/c/4nJ2DJiv/433-investigate-bug-with-notification-bubbles-not-adding-up)
We show outstanding task counts in several places on the dashboard and a running total on the switch school page. At the moment, the running total doesn't always add up to the total displayed on the dashboard, which is confusing to users. We also see a phantom badge appearing over "Manage requests" - when navigating to that section there is no corresponding request to action.
- Exclude processed requests from those requiring attention
Resolve an issue where a bade was displaying against placement requests but there were no requests in the list when you navigate to it, as they had been cancelled (i.e. processed).
- Add Bookings::OutstandingTasks to easily summarise by school
At the …
> Refactor outstanding task counters for consistency

- config/initializers/date_format.rb
- features/schools/attendances/index.feature
- features/schools/cancelled_bookings/show.feature
- features/schools/confirmed_bookings/show.feature
- features/schools/previous_bookings/show.feature
- features/step_definitions/candidates/registrations/application_preview_steps.rb
- features/step_definitions/candidates/registrations/subject_and_date_information_steps.rb
- features/step_definitions/candidates/schools/show_steps.rb
- features/step_definitions/schools/bookings_steps.rb
- features/step_definitions/schools/confirm_attendance_steps.rb
- features/step_definitions/schools/placement_dates/edit_steps.rb
- features/step_definitions/schools/placement_requests/confirm_booking_steps.rb
- features/step_definitions/schools/previous_bookings_steps.rb
- spec/controllers/schools/confirmed_bookings/date_controller_spec.rb
[Trello-458](https://trello.com/c/CUa33w7D/458-remove-the-leading-zero-in-gse-dates)
In a lot of areas at the moment we use the `%d %B %Y` date format, however GOV.UK recommend omitting the leading 0 for dates such as these.
Update all references to use the `%-d %B %Y` format.
- Make dates GOV.UK format throughout
> Make dates GOV.UK format throughout

- app/presenters/schools/on_boarding/preview_presenter.rb
- app/presenters/schools/on_boarding/school_profile_presenter.rb
- app/views/schools/on_boarding/previews/show.html.erb
- app/views/schools/on_boarding/profiles/show.html.erb
- spec/presenters/schools/on_boarding/preview_presenter_spec.rb
- spec/presenters/schools/on_boarding/school_profile_presenter_spec.rb
https://trello.com/c/9yokR1Ac
The content on review and preview profile pages currently only makes sense in the context of the onboarding journey. It needs to display different content when a school is simply updating their profile.
- Update the content
- Use the SchoolProfile and Preview presenters to deal with the conditional logic
> Update the content in the dashboard profile and preview pages

- app/models/schools/csv_export.rb
- app/models/schools/csv_export_row.rb
- spec/models/schools/csv_export_row_spec.rb
- spec/models/schools/csv_export_spec.rb
[Trello-450](https://trello.com/c/igQuecRO/450-add-second-subject-to-csv-export-function)
As part of the request process, candidates can select 2 subject preferences. We only have one of these as a field int he CSV export, we should add this as a parameter on the CSV export to be helpful for some schools.
- Add secondary subject to the CSV export
It looks like for the primary subject the `Booking` subject takes precedence over the `PlacementRequest`, however we only have the `PlacementRequest` as a reference to the secondary subject so we just directly retrieve it from there.
> Add secondary subject to the CSV export

- app/controllers/schools/placement_dates/configurations_controller.rb
- app/controllers/schools/placement_dates/subject_selections_controller.rb
- app/controllers/schools/placement_dates_controller.rb
- app/forms/schools/placement_dates/close_confirmation_form.rb
- app/forms/schools/placement_dates/configuration_form.rb
- app/forms/schools/placement_dates/subject_selection.rb
- app/models/bookings/placement_date.rb
- app/views/schools/placement_dates/close_confirmation.html.erb
- app/views/schools/placement_dates/edit.html.erb
- app/views/schools/placement_dates/index.html.erb
- app/views/schools/placement_dates/new.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20220119115856_add_availability_offsets_to_bookings_placement_dates.rb
- db/migrate/20220125180747_set_start_availability_offset_to_maximum_for_existing_dates.rb
- db/schema.rb
- features/schools/placement_dates/edit.feature
- features/schools/placement_dates/new.feature
- features/step_definitions/schools/placement_dates/edit_steps.rb
- features/step_definitions/schools/placement_dates/new_steps.rb
- spec/controllers/schools/placement_dates/configurations_controller_spec.rb
- spec/controllers/schools/placement_dates/subject_selections_controller_spec.rb
- spec/controllers/schools/placement_dates_controller_spec.rb
- spec/forms/schools/placement_dates/configuration_form_spec.rb
- spec/forms/schools/placement_dates/subject_selection_spec.rb
- spec/models/bookings/placement_date_spec.rb
https://trello.com/c/1cQIAhsL
https://trello.com/c/9vuYRoqd
We are moving towards a [new manage dates design](https://get-school-experience-prototype.london.cloudapps.digital/manage-dates-mvp/). 
Part of this is to have two new fields which will set an availability window in which the day will be available to applicants - open date x number of days before & close date x number of days before.
Another part of this is to remove the active/inactive checkbox. Now, dates will become active when published, and can be made inactive by following a link in each date page.
When a date is active, it can be closed through this link:
- Add ability to close date a number of days before it starts
- Add ability to open a date a number of days before it starts
- Change active/not active checkbox to a …
> Add ability to open/close date a number of days before it starts

- app/webpacker/analytics/log_accordion_toggle.js
- app/webpacker/analytics/send_ga_event.js
- app/webpacker/packs/application.js
[Trello-487](https://trello.com/c/X8EQIm8R/487-dev-add-gtm-tracking-capability-to-the-website-and-also-update-the-cookies-preference-and-policy-page-to-inform-users-that-gtm-i)
We don't appear to use this event and to avoid migrating it to the new GTM container I'm pulling it out.
- Remove accordion GA event
Also removes globally set `cookie_allowed` variable which doesn't appear to be referenced.
These are the only two pages that appear to have accordions on them:
https://review-school-experience-2242.london.cloudapps.digital/dfe_signin_help
https://review-school-experience-2242.london.cloudapps.digital/help_and_support_access_needs
> Remove accordion GA event

- app/controllers/candidates/schools_controller.rb
- app/models/bookings/school_search.rb
- app/models/candidates/school_search.rb
- app/views/candidates/schools/_england_only_service.html.erb
- app/views/candidates/schools/index.html.erb
- features/candidates/schools/search/results/no_results.feature
- features/step_definitions/candidates/schools/results_steps.rb
- lib/servertest/geocoder.rb
- spec/helpers/candidates/results_helper_spec.rb
- spec/models/bookings/school_search_spec.rb
- spec/rails_helper.rb
- spec/views/candidates/schools/index.html.erb_spec.rb
https://trello.com/c/T7AwPYtZ
1. Use United Kingdom as the search region instead of England: The search region is currently set to England because School Experience is an England-only service. However, when somebody search for a non-England area/address (e.g., Edinburgh), we receive a null result (because 'Edinburgh, England' can't be interpreted by Google Geocoding) and don't log out region and district. Additionally, if they are close to the border and within their chosen radius of any events, the null result means that we won't show these to the user. Update the region to United Kingdom so that we no longer get null results.
2. Update the logger message so it makes more sense.
3. Only show "Sorted by distance" when there are two or more results: It doesn't make sense to show this …
> Extend school search

- app/webpacker/controllers/search_controller.js
- spec/javascript/controllers/search_controller_spec.js
As the search no longer reloads the page we are not registering the change as a page view in GTM.
Send a page view event to GTM when the search is executed.
> Send page view to GTM on search

- app/controllers/schools/placement_dates/subject_selections_controller.rb
- config/locales/en.yml
- features/schools/placement_dates/subject_selection.feature
- features/step_definitions/schools/placement_dates/placement_date_steps.rb
[Trello-441](https://trello.com/c/Dfrl4vGz/441-dev-prefill-the-add-dates-subject-list-to-match-the-schools-subject-list)
When a new placement date is created the user is prompted to check all subjects that apply for the given date. A school can have many subjects and checking them all is time consuming/an annoyance.
Instead, we want to pre-check all the subjects and let the user uncheck those that don't apply.
- Pre-check all subjects for new placement dates
To check this you can manage placement dates and add a new date with specific subjects; ensure all the subjects are checked. Go back and edit the placement date and then make sure the old selections are retained.
Also adds a missing error message translation and additional hint text for the field.
> Pre-check all subjects for new placement dates

- app/controllers/candidates/schools_controller.rb
- app/models/bookings/school_search.rb
- app/models/candidates/school_search.rb
- app/views/candidates/schools/_england_only_service.html.erb
- app/views/candidates/schools/index.html.erb
- lib/geocoding_response_country.rb
- spec/lib/geocoding_response_country_spec.rb
- spec/models/bookings/school_search_spec.rb
- spec/views/candidates/schools/index.html.erb_spec.rb
We can retrieve country from the Geocoding response. However, it tends to return 'United Kingdom', whereas we are interested in the actual country (England, Scotland, Northern Ireland, Wales). Therefore, we need to actively search the result for countries. The country mostly comes through on the key 'administrative_area_level_1', but this doesn't seem to be consistent.
Move the country logic into its own class, and handle unknown countries (i.e., countries that we don't actively search for)
> Handle unknown countries in candidate school search

- app/views/pages/cookies_policy.html.erb
The GA code has been removed so this cookie won't drop; the method also no longer exists and is causing an exception.
> Remove redundant cookie

- app/controllers/schools/placement_requests/acceptance/preview_confirmation_email_controller.rb
N/A
Currently if the school changes from virtual flex to fixed dates, the set_is_virtual_experience will return true for in-school fixed dates.
Check if a placement_date exists which ensures the request is for a fixed date
> Set the is_virtual_experince correctly

- app/controllers/candidates/booking_feedbacks_controller.rb
- app/controllers/schools/confirm_attendance_controller.rb
- app/models/bookings/booking.rb
- app/models/candidates/booking_feedback.rb
- app/models/schools/attendance.rb
- app/notify/notify_email/candidate_booking_feedback.189569bd-3115-43e0-8396-be14480a5f2d.md
- app/notify/notify_email/candidate_booking_feedback_request.rb
- app/views/candidates/booking_feedbacks/_form.html.erb
- app/views/candidates/booking_feedbacks/booking_not_attended.html.erb
- app/views/candidates/booking_feedbacks/feedback_already_provided.html.erb
- app/views/candidates/booking_feedbacks/new.html.erb
- app/views/candidates/booking_feedbacks/show.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20220202103752_create_candidates_booking_feedbacks.rb
- db/schema.rb
- features/candidates/booking_feedback.feature
- features/schools/confirm_attendance.feature
- features/step_definitions/candidates/bookings/feedback_steps.rb
- features/step_definitions/schools/confirm_attendance_steps.rb
- features/support/database_cleaner.rb
- spec/controllers/candidates/booking_feedbacks_controller_spec.rb
- spec/controllers/schools/confirm_attendance_controller_spec.rb
- spec/factories/candidates/booking_feedbacks.rb
- spec/models/bookings/booking_spec.rb
- spec/models/candidates/booking_feedback_spec.rb
- spec/models/schools/attendance_spec.rb
- spec/notify/notify_email/candidate_booking_feedback_spec.rb
[Trello-264](https://trello.com/c/35VTFD2c/264-dev-create-a-post-experience-survey-experience-for-those-who-are-confirmed-attendees-of-school-experience)
When a candidate has attended a school experience booking we want to obtain feedback so that we can improve the service.
- Add model to capture candidate booking feedback
When a candidate has attended a placement we want to ask them for feedback about their experience.
Add `Candidates::BookingFeedback` model to capture feedback from users.
- Accept feedback for attended bookings
Allow candidates to submit feedback for bookings they have attended.
We use the secure token on the `PlacementRequest` to allow a candidate to submit feedback.
Candidates can only submit feedback on bookings that they have attended. Feedback can only be submitted …
> Candidate booking feedback

- db/seeds.rb
When we seed the education phases they all default to `supports_subjects: true` - this means we can never add a placement date for a primary education phase (the control is never displayed to the user).
We seem to have manually fixed this in the production/staging database, however when reseeding locally its an issue.
Fix by ensuring `supports_subjects` is `false` for the primary education phase.
| Before      | After |
| ----------- | ----------- |
| <img width="825" alt="Screenshot 2022-02-10 at 10 04 33" src="https://user-images.githubusercontent.com/29867726/153384337-50bc46da-ae9c-485f-a632-5a02cb122abd.png">      | <img width="773" alt="Screenshot 2022-02-10 at 10 04 45" src="https://user-images.githubusercontent.com/29867726/153384364-d64e2d10-a9ee-43c0-8f43-f6a55074b825.png"> …
> Fix education phase seed data

- app/views/schools/placement_dates/edit.html.erb
- app/views/schools/placement_dates/new.html.erb
- config/locales/en.yml
https://trello.com/c/FD9u9tIl
1. Move suffix text into translations file
2. Update the way we ask how long a placement will last: The duration input should match the publication inputs.
3. Tidy up placement dates inputs: Allow normal spacing on the between the label and hint of the duration input, and add missing full stops.
| Before      | After |
| ----------- | ----------- |
| <img width="812" alt="image" src="https://user-images.githubusercontent.com/47089130/153849346-e7367026-a4d6-4915-880b-ca492fd6a3d2.png">      | <img width="806" alt="image" src="https://user-images.githubusercontent.com/47089130/153849215-a4ca06a4-7620-4a31-bf31-d87bc0e6462d.png">       |
Adding a new placement date looks the same.
> How long will it last?

- app/controllers/schools/placement_requests/acceptance/make_changes_controller.rb
- app/controllers/schools/placement_requests/acceptance/preview_confirmation_email_controller.rb
- app/models/bookings/booking.rb
- app/models/bookings/placement_date.rb
- app/models/bookings/placement_request.rb
- app/views/schools/placement_requests/acceptance/make_changes/new.html.erb
- app/views/schools/placement_requests/acceptance/preview_confirmation_email/edit.html.erb
- config/locales/en.yml
- db/migrate/20220203124105_add_experience_type_to_requests_and_bookings_tables.rb
- db/schema.rb
- features/schools/placement_requests/acceptance/confirming_a_request_with_a_future_date.feature
- features/schools/placement_requests/acceptance/confirming_flex_requests_with_unclear_experience_type.feature
- features/schools/placement_requests/acceptance/sending_details_to_candidate.feature
- features/step_definitions/schools/placement_requests/accept_steps.rb
- features/step_definitions/schools/placement_requests/preview_confirmation_email_steps.rb
- spec/controllers/schools/placement_requests/acceptance/make_changes_controller_spec.rb
- spec/controllers/schools/placement_requests/acceptance/preview_confirmation_email_controller_spec.rb
- spec/factories/bookings/bookings_factory.rb
- spec/factories/bookings/placement_request_factory.rb
- spec/factories/bookings/placement_requests_factory.rb
- spec/factories/bookings/school_factory.rb
- spec/models/bookings/booking_spec.rb
- spec/models/bookings/placement_date_spec.rb
- spec/models/bookings/placement_request_spec.rb
https://trello.com/c/NzhZrsbg
We need to reliably know whether a candidate is requesting and having an In school or Virtual experience when schools offer flexible dates.
We currently store the school experience type, but can be unclear, meaning either the school offers both types or the school experience type is shifted while there are pending requests and bookings.
- Add the experience type column in the PlacementRequest model
This allows to always know what experience type the candidate requested, but also to determine if the school experience type has shifted since a placement request was created.
- Add the experience type column in the Bookings model 
This allows to know what experience type the candidate is actually going to have, so to display content relevant to In school or …
> Experience type for flex dates

- app/controllers/schools/placement_requests/acceptance/make_changes_controller.rb
- app/controllers/schools/placement_requests/acceptance/preview_confirmation_email_controller.rb
- app/models/bookings/booking.rb
- app/models/bookings/placement_date.rb
- app/models/bookings/placement_request.rb
- app/views/schools/placement_requests/acceptance/make_changes/new.html.erb
- app/views/schools/placement_requests/acceptance/preview_confirmation_email/edit.html.erb
- config/locales/en.yml
- db/migrate/20220203124105_add_experience_type_to_requests_and_bookings_tables.rb
- db/migrate/20220216101402_update_experience_type_for_current_records.rb
- db/schema.rb
- features/schools/placement_requests/acceptance/confirming_a_request_with_a_future_date.feature
- features/schools/placement_requests/acceptance/confirming_flex_requests_with_unclear_experience_type.feature
- features/schools/placement_requests/acceptance/sending_details_to_candidate.feature
- features/step_definitions/schools/placement_requests/accept_steps.rb
- features/step_definitions/schools/placement_requests/preview_confirmation_email_steps.rb
- spec/controllers/schools/placement_requests/acceptance/make_changes_controller_spec.rb
- spec/controllers/schools/placement_requests/acceptance/preview_confirmation_email_controller_spec.rb
- spec/factories/bookings/bookings_factory.rb
- spec/factories/bookings/placement_request_factory.rb
- spec/factories/bookings/placement_requests_factory.rb
- spec/factories/bookings/school_factory.rb
- spec/models/bookings/booking_spec.rb
- spec/models/bookings/placement_date_spec.rb
- spec/models/bookings/placement_request_spec.rb
#2289 was released yesterday but the migrations failed on prod so we had to reverted the release (#2291).
This is another attempt to release the changes, but this time I've split the db structure and data changes to two separate migrations.
> Store the experience type for flex dates

- terraform/paas/production.env.tfvars
Increase Production Memory allocation from 1GB to 2GB
This will not impact the application, but will give it more memory in production to carry out migrations if necessary
> Increase Production memory allocation

- app/controllers/candidates/schools_controller.rb
- app/models/bookings/school_search.rb
- app/views/candidates/school_searches/new.html.erb
- app/views/candidates/schools/index.html.erb
- app/webpacker/controllers/autocomplete_controller.js
- app/webpacker/stylesheets/school-search.scss
- config/locales/en.yml
- spec/controllers/candidates/schools_controller_spec.rb
- spec/javascript/controllers/autocomplete_controller_spec.js
- spec/models/candidates/school_search_spec.rb
https://trello.com/c/Tc6IYa96
The search page is not displaying any validation errors, instead it submit the data to the search results page and then it gets redirected back to the search page.
1. Reduce time before search input loads: Sometimes, there is a very brief flash of blankness while the autocomplete loads. Swap the order of loading, so that the input is shown before the Google script is loaded.
2. Apply GOV.UK styling to accessible autocomplete in CSS: I was previously applying the styling in JavaScript, but the accessible autocomplete was reloading when its state changed, so was losing the class.Sass comes with an @extend rule, so use that instead.
3. Make sure validation errors are shown when user doesn't enter a value: Currently, when a user doesn't enter a search value, they …
> Error messages search

- README.md
- features/support/env.rb
https://trello.com/c/wvVsEM0g
For easier troubleshooting, we want to be able to run Capybara tests in headed mode.
Add an environment variable `SELENIUM_CHROME_DRIVER` which will configure Capybara to use the default `selenium_chrome` config. 
Because `.env.local` doesn't override the `test` environment, `SELENIUM_CHROME_DRIVER` will need to be set in `.env.test.local`.
This also removes the deprecated `options` parameter for driver initialisation.
> Add option to run Capybara tests in headed mode

- app/views/candidates/placement_requests/cancellations/_new_placement_request.html.erb
- app/views/candidates/placement_requests/cancellations/_show_placement_request_cancelled_by_school.html.erb
- app/views/candidates/registrations/subject_and_date_informations/_form.html.erb
- app/views/candidates/registrations/teaching_preferences/_form.html.erb
- app/views/pages/schools_privacy_policy.html.erb
- app/views/schools/archived_placement_requests/index.html.erb
- app/views/schools/availability_info/edit.html.erb
- app/views/schools/availability_preferences/edit.html.erb
- app/views/schools/dashboards/show.html.erb
- app/views/schools/errors/auth_failed/show.html.erb
- app/views/schools/errors/inaccessible_school/show.html.erb
- app/views/schools/errors/insufficient_privileges/show.html.erb
- app/views/schools/on_boarding/access_needs_details/_form.html.erb
- app/views/schools/on_boarding/key_stage_lists/_form.html.erb
- app/views/schools/on_boarding/previews/show.html.erb
- app/views/schools/placement_requests/index.html.erb
- features/schools/availability_information/edit.feature
- features/schools/placement_requests/index.feature
[Trello-519](https://trello.com/c/p4aJJgZX/519-update-page-titles-so-they-match-their-page-headings)
Update a number of page titles to match new versions as per a spreadsheet provided in the Trello card.
Update some form labels/legends that should be `<h1>` tags.
- Various title/headings updates
> Various title/heading updates

- Gemfile
- Gemfile.lock
- bin/delayed_job
- config/initializers/yabeda.rb
- config/puma.rb
- config/routes.rb
[Trello-86](https://trello.com/c/y0JoDoIC/86-investigate-add-metrics-endpoint-to-se-for-gathering-any-information-by-prometheus)
We want to to expose application metrics to Prometheus via a /metrics endpoint.
The Yabeda library and associated gems make this straight forward, giving us metrics for:
- DelayedJob
- Rails internals
- Puma
- Garbage collection
- HTTP requests
- Expose various metrics to Prometheus
[Metrics endpoint](https://review-school-experience-2303.london.cloudapps.digital/metrics)
We still need to setup a Prometheus instance to scrape it and then a dashboard in Grafana.
> Expose various metrics to Prometheus

- app/controllers/schools/confirmed_bookings/date_controller.rb
- app/notify/notify_email/candidate_virtual_experience_booking_date_changed.rb
- app/notify/notify_email/datechange_virtualexperience_updated_jan22.50a32920-fa3a-4294-b013-a6472e230cf8.md
- spec/controllers/schools/confirmed_bookings/date_controller_spec.rb
- spec/notify/notify_email/candidate_virtual_experience_booking_date_changed_spec.rb
https://trello.com/c/nzVAo0EK
Currently we send the same email for in school and virtual experiences when the booking date is changed, however the content of the email is tailored for in school experiences.
We want to send more suitable content for virtual experiences.
- Add the notify class for the virtual experiences booking date change email
- Update the ConfirmedBookings::DateController to send the correct email based on the booking's experience type
- Change the booking date of an in school experience and check you received the email with the in school content
- Change the booking date of a virtual experience and check you received the email with the virtual content
> Add booking date change email for virtual experiences

- app/notify/notify_email/candidate_booking_reminder_virtual_experience_updated_jan22.be4eb8b2-3abd-4882-8719-e6812975110a.md
- app/notify/notify_email/candidate_virtual_experience_booking_reminder.rb
- app/services/bookings/reminder.rb
- spec/notify/notify_email/candidate_virtual_experience_booking_reminder_spec.rb
- spec/services/bookings/reminder_spec.rb
https://trello.com/c/nzVAo0EK
The current content of the booking email reminder is not very suitable for virtual experiences. 
We want to keep sending the current reminder for in school experiences only, and create a new email reminder for virtual experiences.
- Add the notify class for the virtual experiences email reminder
- Update the `Bookings::Reminder#despatch_reminder_email` to send the proper reminder based on the booking's experience type
1. Accept/Create a 'virtual' and 'in school' booking that will take place tomorrow
2. Trigger the reminder job
3. Confirm the correct email was sent for both bookings
> Add booking reminder email for virtual experiences

- terraform/paas/application.tf
- terraform/paas/dev.env.tfvars
- terraform/paas/network.tf
- terraform/paas/production.env.tfvars
- terraform/paas/review.env.tfvars
- terraform/paas/route.tf
- terraform/paas/space.tf
- terraform/paas/staging.env.tfvars
- terraform/paas/variables.tf
School experience did not have any metrics, now that a metrics endpoint has been created at port 3000 this needs to be consumed by Prometheus using an internal network route.
1. Create an internal network route for the Application and the Delayed_Jobs Application
2. Adding networking policies to allow Prometheus to access the metrics,
for example:
|source |                            destination |                               protocol|   ports  | destination space  | destination org| 
|-------|----------------------------|---------------------------|--------|-------------------|-----------------|
|prometheus-dev-get-into-teaching |  school-experience-app-dev      |            tcp     |   3000   | get-into-teaching |   dfe|
|prometheus-dev-get-into-teaching | …
> Add network policies to allow monitoring

- app/controllers/candidates/schools_controller.rb
- app/controllers/schools/base_controller.rb
- app/controllers/schools/on_boarding/on_boardings_controller.rb
- app/models/bookings/school.rb
- app/presenters/schools/on_boarding/preview_presenter.rb
- app/presenters/schools/on_boarding/school_profile_presenter.rb
- app/views/candidates/schools/_phase1.html.erb
- app/views/candidates/schools/show.html.erb
- app/views/schools/dashboards/_help_and_support.html.erb
- app/views/schools/dashboards/show.html.erb
- app/views/schools/on_boarding/previews/show.html.erb
- app/views/schools/on_boarding/profiles/show.html.erb
- spec/models/bookings/school_spec.rb
[Trello-357](https://trello.com/c/oWgZGJYD/357-dev-spike-the-usage-of-identifying-schools-via-if-schoolprivatebeta-and-whether-we-can-remove-it)
We are currently using the term `private_beta?` to indicate if a school has completed their onboarding journey and setup a profile. We don't use this terminology any more and it's not very clear; renaming it to `onboarded?` makes more sense.
- Rename private_beta? to onboarded?
I chose `onboarded?` as we seem to use that terminology internally and elsewhere in the application; another option I thought about was `profile_complete?` but we already have a `complete?` method on `profile` and it felt a bit close. `profile_present?` also didn't feel quite right as the profile is only created once its been fully filled in.
> Rename private_beta? to onboarded?

- app/notify/notify_email/candidate_booking_date_changed.rb
- spec/notify/notify_email/candidate_booking_date_changed_spec.rb
https://trello.com/c/T2Ua6myz
Schools can choose to provide experience details in their profile, but it's optional. However the date change email is using this field and it fails when the experience details is not provided (`nil` value).
The email should not fail when schools don't provide the experience details.
- Convert the placement_details argument to string when instantiating the email
1. Edit the experience details in the school profile, set it to none and save the profile.
2. Change the date of a flex date booking and ensure no exceptions are raised
3. Check you've received the change date email
> Fix the placement details placeholder for the date change email

- Gemfile
- config/environments/production.rb
When we setup Prometheus we call the app internally (bypassing the load-balancer), however we can only do this over HTTP and not HTTPS. To allow `/metrics` to be called over HTTP we can exclude it from the forced SSL checks.
I haven't made this change to development as we seem to force SSL via Puma so it won't work locally.
> Allow http connections to /metrics endpoint

- script/docker-entrypoint.sh
The rake task `rake jobs:work` doesn't hit the `delayed_job` bin file, which starts the Prometheus metrics server on the worker using webrick.
Change from the rake task to call `./bin/delayed_job`. We start it on port 3000 so that we can use the already-exposed port in Docker; we're not running Rails so there shouldn't be a conflict.
> Use ./bin/delayed_jobs instead of rake task

- app/models/bookings/school.rb
- app/models/bookings/school_search.rb
- features/step_definitions/candidates/schools/pagination_steps.rb
- features/step_definitions/candidates/schools/results_steps.rb
- features/step_definitions/candidates/schools/sorting_steps.rb
- features/support/feature_helper.rb
- spec/helpers/candidates/results_helper_spec.rb
- spec/models/bookings/school_search_spec.rb
- spec/models/bookings/school_spec.rb
https://trello.com/c/n6kwbkSI
Non-onboarded schools are included in the search results, which are not useful to the candidates. 
We want to display only onboarded schools with availability.
- Add the `onboarded` scope in the schools model
- Scope the search results to return only onboarded schools
> Search results

- bin/metrics
- script/docker-entrypoint.sh
If we start `delayed_job` with `start` instead of `run` it will demonize the process and continue execution. We can then start the metrics instance, which spins up a new thread so we need to hold the session by joining the thread thats spawned.
I've tested the jobs still run in the dev environment (by pausing the dev worker and spinning up a new one with this change).
> Run metrics from separate bin file

- config/routes.rb
We are leaking PII into our metrics instance as the payload of delayed jobs are being logged as labels.
> Temporarily disable Yabeda

- app/models/schools/change_school.rb
- spec/models/schools/change_school_spec.rb
[Trello-540](https://trello.com/c/JZNdk7DU/540-can-we-order-the-change-school-page-by-number-of-notifications-then-those-with-zero-alphabetically)
We want to show the schools with the most outstanding tasks at the top of the list, then the remaining schools in alphabetical order.
- Order change schools by outstanding tasks, then alphabetically
| Before      | After |
| ----------- | ----------- |
|   <img width="398" alt="Screenshot 2022-02-28 at 09 11 00" src="https://user-images.githubusercontent.com/29867726/155955731-a7f4acbe-ed42-4f2e-9b90-f73ade407b80.png">    | <img width="403" alt="Screenshot 2022-02-28 at 09 10 25" src="https://user-images.githubusercontent.com/29867726/155955645-fea0264c-ee5d-4cb7-9116-27d32c5135f6.png">       |
> Order change schools by outsanding tasks, then alphabetically

- bin/delayed_job
- bin/metrics
- script/docker-entrypoint.sh
Running the metrics in a separate process causes it not to return any metrics because it can't access the same memory; we have to spawn the metrics server from the delayed job process. The only way I can get this working is to run delayed jobs in a background process, then boot the webrick instance and join the thread to keep the session open.
> Run yabeda metrics server in delayed job process

- app/models/bookings/subject.rb
- db/migrate/20220304152958_remove_gitis_uuid_from_bookings_subject.rb
- db/schema.rb
> ⚠️ 🕙  Wait until 04/03/22 to merge
https://trello.com/c/qYsZJIbR
We ignored gitis_uuid to catch any left over references, but it can now be safely removed.
> Remove gitis_uuid

- app/webpacker/controllers/autocomplete_controller.js
- spec/javascript/controllers/autocomplete_controller_spec.js
Currently, we are dynamically adding the Google Places script to ensure that the order of loading is correct.
I forgot about the Google API loader library, which can be used for this instead and simplifies things a bit.
> Use Google API loader library for Places Autocomplete

- feature-flags.json
N/A
Enabling this in staging so the PM can have a full review.
> Enable candidate dashboard in staging

- config/application.rb
- terraform/paas/variables.tf
[Trello-86](https://trello.com/c/y0JoDoIC/86-investigate-add-metrics-endpoint-to-se-for-gathering-any-information-by-prometheus)
The Prometheus metrics work fine in the main application, but not all of the DelayedJob metrics are working. 
Whilst we run the metrics server and `DelayedJob` command in the same process, under the hood `daemonize` ends up forking a new process which means the default Prometheus store is not going to work.
Currently the only alternative is to use a `DirectFileStore` which works across forked processes. Sidekiq doesn't have this issue because you can run the metrics server on each Sidekiq server, but I can't find a way of doing the equivalent with DelayedJob (it doesn't have a hook for configuring a server in the pool).
Increases the disk quota as we'll be …
> Switch to DirectFileStore for Prometheus metrics

- config/initializers/delayed_job.rb
The `sleep_delay` is currently 15 seconds, which means it can take up to 30 seconds for a queued job to be picked up and processed; this is fairly noticeable with the registration confirmation emails.
Reducing this time will make the jobs execute more promptly and isn't going to have an impact on resource consumption (each time a worker checks it'll query the database, but GSE sits fairly idle most of the time anyway so we have plenty of capacity).
> Reduce DelayedJob sleep_delay

- Gemfile
- Gemfile.lock
- app/controllers/pages_controller.rb
- app/models/healthcheck.rb
- app/services/candidates/registrations/registration_store.rb
- config/initializers/rack_attack.rb
- config/initializers/redis.rb
- spec/controllers/healthchecks_controller_spec.rb
- spec/controllers/pages_controller_spec.rb
- spec/models/healthcheck_spec.rb
- spec/rails_helper.rb
- spec/services/candidates/registrations/registration_store_spec.rb
https://trello.com/c/w6kbXWGZ
We have some deprecation warnings that need fixing
- Replace deprecated RackAttack method
- Fix deprecation warning for rendering templates with a dot
- Fix deprecation warning from using Redis.current: Using a single connection to Redis is now discouraged because it can lead to blocking. The recommended fix is to enable connection pooling. Wrap the existing connection using the connection_pool gem.
> Deprecations

- app/helpers/schools/placement_dates_helper.rb
- app/views/schools/placement_dates/index.html.erb
- spec/factories/bookings/placement_dates.rb
- spec/helpers/schools/placement_dates_helper_spec.rb
https://trello.com/c/BORWNkYX
Currently, dates are displayed as "Closed" when they are scheduled to be published. 
Add a new scheduled status to help to alleviate any confusion when they are in this state.
- Add a scheduled status for placement dates
Do the colours look okay?
> Add a scheduled status for placement dates

- app/helpers/schools/placement_dates_helper.rb
- spec/helpers/schools/placement_dates_helper_spec.rb
There's an over-use of yellow tags on some pages, such as managing dates. This aims to rectify it.
> Update scheduled tag to grey

- app/helpers/schools/placement_requests_helper.rb
- app/presenters/candidates/placement_presenter.rb
More conversions to grey for all cases of 'expired' (this PR works across a couple of placement/request pages), toning down the colour usage.
> Change all expired to grey

- app/views/errors/unprocessable_entity.html.erb
- features/errors/unprocessable_entity.feature
- features/step_definitions/errors/error_page_steps.rb
https://trello.com/c/6ZukkTBr
We display a hint in the unprocessable entity error page for what may have gone wrong, which can be misleading for the users.
We want to keep the error more generic and have the user contact the support if it issue persists.
- Update the heading
- Remove the hint
|Before|After|
|-|-|
|![before](https://user-images.githubusercontent.com/951947/158431558-c93957db-5734-472e-bd27-5a224a0555d5.png)|![after](https://user-images.githubusercontent.com/951947/158431585-b18e4085-cbce-4b98-b41a-ddd44ee59db3.png)|
> Update the content in Unprocessable entity page

- app/webpacker/stylesheets/facet-tags.scss
https://trello.com/c/ldqbOeig
The font of the 'x' on our facet tags is set to Arial, which also affects its vertical alignment. 
- Update the font of the facet tag to "GDS Transport"
> Update the facet tag font to GDS Transport

- app/views/candidates/schools/index.html.erb
https://trello.com/c/NAuPfTD3
The font size in the sorting info is a bit bigger comparing the sibling elements in the search results section.
We want to be the same.
- Put the sorting info inside a div element
It will inherit the font size from the search-results and match the font size of its sibling elements
> Use div element for the sorting info

- app/views/candidates/registrations/application_previews/show.html.erb
https://trello.com/c/ED8dD7tC
A review by Candidate's Interaction Designer suggested that this summary page should be a 2/3 layout.
Use two thirds layout for summary page:  The two thirds layout is generally preferred, so that lines don't get so long that they are difficult to read on desktop.
This looks like its squashing the text too much?
|Before|After|
|-|-|
|![image](https://user-images.githubusercontent.com/47089130/158837095-9f099c27-3e4d-49d8-95e7-2eebf7df5b12.png)|![image](https://user-images.githubusercontent.com/47089130/158836945-91d5639f-f518-41f3-9fc4-61e0c2cb04af.png)|
> Use two thirds layout for summary page

- app/helpers/schools/placement_dates_helper.rb
- spec/helpers/schools/placement_dates_helper_spec.rb
https://trello.com/c/CZUFR55q
When the date is not inside the availability window, but it is active, it will have the scheduled tag. When the availability end date has passed, we want these to be closed instead.
- Only show the scheduled tag when the availability end date is in the future.
The 23rd March closes 6 days before (today), if I update it to 7 days, its still closed.
> Fix scheduled status bug

- app/models/bookings/school_search.rb
- app/models/candidates/school_search.rb
- app/views/candidates/schools/index.html.erb
- features/schools/placement_dates/edit.feature
- features/step_definitions/schools/placement_dates/placement_date_steps.rb
- spec/models/bookings/school_search_spec.rb
- spec/models/candidates/school_search_spec.rb
- spec/views/candidates/schools/index.html.erb_spec.rb
[Trello-559](https://trello.com/c/AB5YiS3G/559-dev-can-we-add-counts-to-our-facet-tag-filters)
We want to be able to indicate to the user if there are going to be any results for a given search filter.
- Add total counts to school search filters
Add counts to each filter; if they are in the same group they are OR'ed together, whereas different groups of filters are AND'ed together.
Remove the brackets from the phase labels to avoid doubling up, e.g. "Primary (11 - 14) (2)".
- Fix broken Cucumber tests
Unrelated to my changes, but I noticed we had warnings from Cucumber that a few steps weren't defined; this defines them and/or fixes the underlying tests.
> Add counts to search filters

- app/jobs/cron/reminders/add_availability_job.rb
- app/models/bookings/school.rb
- app/notify/notify_email/school_add_availability_reminder.eee3d861-3365-40ff-a178-80516f771024.md
- app/notify/notify_email/school_add_availability_reminder.rb
- spec/jobs/cron/reminders/add_availability_job_spec.rb
- spec/models/bookings/school_spec.rb
- spec/notify/notify_email/school_add_availability_reminder_spec.rb
- spec/support/notify_email_shared_examples.rb
https://trello.com/c/orbxaF6t
Schools that haven't yet added dates to their profile don't appear in the search. We want to send a reminder email which will help them take the next step and add some dates.
- Update shared notify email spec to handle no personalisation.
- Send email reminding schools to complete the dates section
> Profile complete email

- app/controllers/schools/rejected_requests_controller.rb
https://trello.com/c/QWioFdT0
We have seen a few errors via Sentry of `ActionView::Template::Error: undefined method first_name for nil:NilClass`, all originating from the RejectedRequestsController.
This controller doesn't use the contact fetcher; it must have been missed when the contact fetcher was originally created.
Update the controller to use the contact fetcher, this should handle missing contact errors where they weren't handled previously.
- Fix nil candidate error
> Fix nil candidate error

- terraform/paas/application.tf
[Trello-588](https://trello.com/c/IquM2i7n/588-check-cloud-foundry-health-check-configuration)
We changed the health check to `process` when we were struggling to get the DelayedJobs metrics working a few weeks ago. This has resulted in a few seconds of downtime during deployments to production as the process goes 'live' before the web service has fully booted; StatusCake then hits the app and it gets an error. I don't think the `process` check type was necessary in the end for the metrics to work so reverting back to `port`.
- Change CF healthcheck to use port
> Change CF healthcheck to use port

- terraform/paas/dev.env.tfvars
We're already running v13 in dev; this makes terraform consistent.
> Update terraform with correct Postgres version

- app/models/service_update.rb
- app/views/schools/dashboards/_service_update_notice.html.erb
- app/views/service_updates/_service_update.html.erb
- app/views/service_updates/index.html.erb
- data/service_updates/20211025.yml
- data/service_updates/20220127.yml
- data/service_updates/20220322.yml
- spec/models/service_update_spec.rb
- Add March 2022 service update
- Fix service update titles: We have hardcoded the date in the title for the past few service updates (e.g., "25 October 2021 - 'Under consideration' status tag and new features"). However, the list of previous service updates interpret the date from the file name and add this to the title, which means the dates are doubled up (e.g., "25 October 2021 - 25 October 2021 - 'Under consideration' status tag and new features"). To fix, add the generated date to the service update notice and latest service update, and remove any hardcoded dates from previous service updates.
**New service update**
**Fixed Titles**
|Before|After|
|-|-|
|<img width="744" alt="image" src="https://user-images.githubusercontent.com/47089130/159898752-d7314a08-d869-40d5-ad82-e29bfb67a805 …
> March Service update

- Gemfile
- Gemfile.lock
This doesn't appear to be compatible with Ruby 3.1 yet and we see an error on the metrics endpoint in production.
Removing it for now and we can look to bring it back in at a later date.
> Remove yabeda-gc gem

- Dockerfile
The multiple consecutive RUN statements was resulting in a warning during linting.
> Fix warning with Dockerfile

- terraform/paas/staging.env.tfvars
We have updated to v13 via Cloud Foundry now, so this makes terraform consistent.
> Update staging terraform with correct postgres version

- Dockerfile
Previous version of chromium is no longer available, docker image fails to build as a result.
- Update chromium to version 99.0.4844.84-r0
- Explicitly updated zlib-dev to latest version to resolve a snyk vulnerability report
Confirm that tests still run as expected.
> Bumped chromium to version 99.0.4844.84-r0

- app/controllers/candidates/placement_requests/cancellations_controller.rb
- app/controllers/schools/placement_requests/cancellations/notification_deliveries_controller.rb
- app/services/bookings/gitis/school_experience.rb
- spec/controllers/candidates/placement_requests/cancellations_controller_spec.rb
- spec/controllers/schools/placement_requests/cancellations/notification_deliveries_controller_spec.rb
https://trello.com/c/MrgxyV50
I accidentally used the withdrawn status for candidates who did not attend their placement when migrating the app to use the CandidateSchoolExperience entity. Withdrawing is a separate action, when a candidate cancels their placement request before it has been accepted by the school.
To fix this, we have updated the withdrawn status name to did not attend (which will fix the existing requests), and added a new status for withdrawn (so that this can be used in the correct place).
Also, distinguish `rejected` requests from `cancelled by school` requests. These were replaced like-for-like when the initial migration was done.
- Update school experience statuses
> Update school experience statuses

- app/views/candidates/schools/_profile_compact.erb
This was flagged by Sentry:
https://sentry.io/organizations/dfe-teacher-services/issues/3172895416/?project=5856726&referrer=slack
Ideally it should have a test covering it; I'll add one on Monday though so this can go out before the weekend.
> Fix typo on school teacher_training_website attribute

- app/controllers/schools/on_boarding/fees_controller.rb
- app/forms/schools/on_boarding/current_step.rb
- app/forms/schools/on_boarding/fees.rb
- app/models/schools/school_profile.rb
- app/presenters/schools/on_boarding/school_profile_presenter.rb
- app/views/schools/on_boarding/fees/_form.html.erb
- config/locales/en.yml
- features/schools/onboarding/dbs_required_toggling_fees.feature
- features/schools/onboarding/fees.feature
- features/schools/onboarding/school_profile.feature
- features/step_definitions/form_steps.rb
- features/step_definitions/schools/onboarding_steps.rb
- spec/controllers/schools/on_boarding/fees_controller_spec.rb
- spec/factories/schools/on_boarding/fees_factory.rb
- spec/factories/schools/school_profile_factory.rb
- spec/forms/schools/on_boarding/current_step_spec.rb
- spec/forms/schools/on_boarding/fees_spec.rb
- spec/models/schools/school_profile_spec.rb
https://trello.com/c/Yjx2EUw9
As part of the onboarding redesign, we want to use checkboxes instead of yes no radios for the initial fees question.
- Simplify the initial fees question.
- Add an option for "none" to the fees question: GOV guidance says that we should have an option for "none", when that is a valid answer. The built in GOV "none" checkbox requires the fields to have matching names, so introduce a new "selected_fees" attribute, which we can map the user's selection to. We also need to make sure "none" works with JavaScript disabled, so add some addition validation. Additionally, persist the "none" selection, for when the user revisits this page.
Before:
After:
> Simplify the initial fees question

- Dockerfile
Base image has snyk warning for vulnerability https://snyk.io/vuln/SNYK-ALPINE315-BUSYBOX-2440607
This can be addressed by by upgrading base image to ruby:3.1.1-alpine3.15 but that also requires upgrading app dependencies.  This is an interim workaround until base image is updated.
Bump busybox to latest version in Dockerfile
> Bump busybox to latest version in Dockerfile

- .github/workflows/build.yml
Dependabot by default has readonly permissions, some steps in the workflow require write permissions.
This change sets workflow permissions for Actions and Dependabot.
Check that workflow is running as expected
> Add permissions to build and deploy workflow

- .github/workflows/build.yml
The `zaproxy/action-full-scan` action creates or updates a GitHub issue so requires the `issues: write` permission.
Add the `issues: write` permission to the build workflow.
The  `zaproxy/action-full-scan` action is only ran after a merge to `master` so this change cannot be tested.
> Add issues write permission to build workflows

- .github/workflows/build-no-cache.yml
Docker build layers are cached to optimise build performance but sometimes the base image is updated so we need to rebuild it.
Add a build-no-cache work that is scheduled once a week on Sunday and can be run manually as required.
Check the new workflow runs as expected., example [here](https://github.com/DFE-Digital/schools-experience/actions/runs/2226069942) which published image [here](https://github.com/DFE-Digital/schools-experience/pkgs/container/schools-experience/20658314?tag=master)
> Workflow to rebuild master docker image

- .github/workflows/build.yml
- .github/workflows/manual.yml
The ACTIONS-API-ACCESS-TOKEN token requires manually configuration and renewal.
The GitHub Actions secret and workflow permissions can be used to manage API access.
Check that modified workflows continue to work as expected.
> Remove references to ACTIONS-API-ACCESS-TOKEN

- config/initializers/content_security_policy.rb
[Trello-592](https://trello.com/c/RPHAijwM/592-allow-googleapiscom-on-the-script-csp)
An update from Google informed us that Google Maps will require `googleapis.com` to be whitelisted in the CSP as of v3.5 (v3.49 comes out in May).
> Add googleapis.com to the CSP script/connect directives

- config/environments/development.rb
- config/environments/production.rb
We are doing a major upgrade of the Postgres database which will mean the website has some downtime; putting it into maintenance mode so that users are locked out while we do this.
I'm enabling it for dev as well so that I can test the maintenance page is working as expected as its not been used in a while.
> Enable maintenance mode in dev/prod

- .env.test
- Gemfile
- Gemfile.lock
- app/controllers/candidates/school_searches_controller.rb
- app/controllers/candidates/schools_controller.rb
- app/models/candidates/school_search.rb
- app/models/concerns/encrypted_attributes.rb
- app/views/candidates/school_searches/new.html.erb
- app/views/candidates/schools/index.html.erb
- config/routes.rb
- features/step_definitions/candidates/schools/results_steps.rb
- features/step_definitions/candidates/schools/search_steps.rb
- features/step_definitions/candidates/schools/sorting_steps.rb
- lib/encryptor.rb
- spec/controllers/candidates/schools_controller_spec.rb
- spec/lib/encryptor_spec.rb
- spec/models/candidates/school_search_spec.rb
- spec/models/concerns/encrypted_attributes_spec.rb
[Trello-608](https://trello.com/c/lfyfQ4dT/608-obscure-postcode-in-location-searches)
A UK postcode is considered Personally Identifiable Information (PII) and therefore should not be sent to external services such as Google Analytics or output in URL/made available in the browser history.
We want to avoid this happening by encrypting postcodes before they are rendered in the URL of a GET request.
- Add simple Encryptor lib
Add a simple `Encryptor` library that can encrypt/decrypt string values. We are using [Hashids](https://hashids.org/) which is intended for obfuscating your database ids when used in URLs and results in a short hash when given a postcode (mapped to character integer values).
This isn't going to be as secure as something like `ActiveSupport::MessageEncryptor` but I …
> Ensure postcodes are not sent to Google Analytics

- lib/placement_request_transfer.rb
- lib/tasks/data/placement_requests.rake
- spec/factories/bookings/placement_request_factory.rb
- spec/lib/placement_request_transfer_spec.rb
[Trello-614](https://trello.com/c/YKeOes5L/614-move-requests-and-delete-school-profile-the-hollins?filter=member:rossoliver15,member:josephkempster)
When a school becomes an academy they end up with a new School Experience account and often get locked out of their old account/no longer sign in to it. They may have pending placement requests that they have not yet actioned and want to see them under the new school account that they use.
- Add rake task to transfer a placement request to another school
Add a rake task to transfer a placement request from one school to another (unlinking it from the original school and linking it to the new school). Currently the functionality is limited/restricted and it will only transfer new placement requests (providing matching subjects and placement …
> Add rake task to transfer a placement request to another school

- app/controllers/schools/on_boarding/candidate_requirements_selections_controller.rb
- app/forms/schools/on_boarding/candidate_requirements_selection.rb
- app/models/schools/school_profile.rb
- app/presenters/schools/on_boarding/candidate_requirements_selection_presenter.rb
- app/views/schools/on_boarding/candidate_requirements_selections/_form.html.erb
- config/locales/en.yml
- spec/controllers/schools/on_boarding/candidate_requirements_selections_controller_spec.rb
- spec/factories/schools/on_boarding/candidate_requirements_selection_factory.rb
- spec/forms/schools/on_boarding/candidate_requirements_selection_spec.rb
[Trello-590](https://trello.com/c/4K2U9iP5/590-make-sure-checkboxes-have-a-none-option)
We want to have a 'None' option on the candidate requirements checkbox for if none of the other options apply. The form builder requires the checkboxes to have the same attribute name in order to add a `None` option.
Refactor `CandidateRequirementsSelection` to have a single `selected_requirements` attribute that contains the selected options.
- Add none option to candidate requirements step
> Add none option to candidate requirements step

- config/environments/production.rb
We are seeing a reasonable number of invalid CSRF token errors; as far as I can tell the only way a user would legitimately get these is if the CSRF token expires. As they are stored in the `session_store` (Redis in our case) the TTL will be 1 hour.
The errors we see primarily come from steps that ask a free-text question; I expect people are routinely taking > 1 hour to complete these steps and subsequently find their session expiring (which will be an irritating user experience as they will have to re-enter it).
Increase to 3 hours so that we can see the impact on these errors; if they're not suitably reduced we can look to increase further, but its a trade-off with security (and a max of 24 hours as we can't store PII longer than that).
> Increase TTL on session store

- package.json
- script/get_next_mapping.sh
- yarn.lock
A while ago we added another 10 routes to DfE Sign In but neglected to update this script, which meant only 10 were being pulled instead of the full 20 and the pool was getting exhausted due to open dependabot PRs.
Increase to use all available DSi routes.
Also pins Shackapacker gem/node module so the version matches (otherwise we get an error on boot).
> Increase to use all 20 available DSi routes

- terraform/paas/production.env.tfvars
We upgraded Postgres in production a while ago and I forgot to update the plan (as we did the upgrade manually) so its causing the prod deployments to fail as its out of sync.
> Update database plan to match production

- app/jobs/cron/identify_closed_schools_job.rb
- app/notify/notify_email/closed_onboarded_schools_summary.a9547f2d-adb2-4cff-b9df-f2afc1ccbc66.md
- app/notify/notify_email/closed_onboarded_schools_summary.rb
- spec/jobs/cron/identify_closed_schools_job_spec.rb
- spec/notify/notify_email/closed_onboarded_schools_summary_spec.rb
[Trello-625](https://trello.com/c/AybmKNMB/625-post-closed-on-boarded-schools-to-slack)
We want to keep track of schools that have been onboarded to the service but subsequently marked as closed according to the latest GIAS data. We will aim to get in touch with these schools and transition them to a new account on the system (for their replacement school if one exists).
- Periodically email list of onboarded, closed schools
Run periodic cron job (Mondays at 9am) to email the service inbox with a list of closed, on-boarded school details.
Originally I wanted to include this as a markdown formatted table but the GOV.UK Notify service is very restricted on what it will accept and it blocks this kind of content. Instead I've opted to format it as a sentence that can be read out (I wasn't …
> Periodically email list of onboarded, closed schools

- app/views/candidates/registrations/application_previews/show.html.erb
- app/views/candidates/registrations/contact_informations/_form.html.erb
- features/candidates/registrations/contact_information.feature
[Trello607-](https://trello.com/c/3bGRyQDV/607-fix-accessibility-issues-from-april-22-accessibility-report?filter=member:rossoliver15,member:josephkempster)
We want to address all the AA issues that DAC raised in their accessibility audit.
- Remove home from autocomplete value
According to DAC we should omit this and just use the `address-x` values. On reading up online I can't find much of a reference to the use of `home` apart from this spec, which suggests the attributes it can be used with (and they don't include address):
https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#attr-fe-autocomplete-home
- Make acceptance label accessible
Screen readers read out "By checking this box you're confirming that:" which doesn't make sense; instead, we can put the bullet list …
> Medium Priority WCAG Level AA Accessibility Updates #2545

- app/helpers/candidates/school_helper.rb
- app/views/candidates/home/index.html.erb
- app/views/candidates/schools/index.html.erb
- app/views/kaminari/_page.html.erb
- app/views/schools/dashboards/_service_update_notice.html.erb
- app/views/schools/on_boarding/access_needs_details/_form.html.erb
- app/views/schools/on_boarding/candidate_requirements_selections/_form.html.erb
- app/views/service_updates/_service_update.html.erb
- app/views/shared/application/_cookie_banner.html.erb
- app/webpacker/controllers/search_controller.js
- config/locales/en.yml
- spec/helpers/candidates/school_helper_spec.rb
- spec/javascript/controllers/search_controller_spec.js
[Trello-607](https://trello.com/c/3bGRyQDV/607-fix-accessibility-issues-from-april-22-accessibility-report?filter=member:rossoliver15,member:josephkempster)
DAC flagged a number of WCAG Level A accessibility issues on the website; we want to fix these to give our users a better experience.
- Ensure unique index in search result summary rows
The search result summary rows default to have an `id` of the key for the row; if there are multiple results this causes duplicate `id` values.
Prefix the summary row key with the index of the result to ensure it will always be unique.
- Make pagination component accessible
When a user focuses on a page indicator its not clear what the navigation is for (it just reads out a number). Instead, we want to provide the 'page' context, so "Page: 1", "Current …
> High Priority WCAG Level A Accessibility Updates

- Dockerfile
- app/jobs/cron/heart_beat_job.rb
- config/initializers/yabeda.rb
- spec/jobs/cron/heart_beat_job_spec.rb
- spec/rails_helper.rb
[Trello-632](https://trello.com/c/ABJDfPlN/632-investigate-issues-with-alerting-in-gse-failed-jobs-and-queue)
Our delayed job worker occasionally hangs/crashes in production, resulting in candidate emails not going out. We have monitoring to catch this at the moment however its not firing reliably (we use pending job count however GSE sometimes bulk-enqueues a batch meaning we have a high-threshold). 
The purpose of this job is to simply provide a 'heart beat' counter metric that fires from a delayed job on a consistent schedule; that way we can infer that the worker has crashed if the metric does not increment over a short period of
time (a couple of minutes). We should then get a near-instant notification when our worker fails.
- Add a heart beat scheduled job
> Add a heart beat scheduled job

- Makefile
https://trello.com/c/FvvgC3LY
Bug fix
The default branch is master so the default image is master, not main
> Fix default docker image

- app/helpers/candidates/school_helper.rb
- app/helpers/schools/dashboards_helper.rb
- app/models/bookings/school.rb
- app/views/schools/dashboards/_profile_status.html.erb
- app/views/schools/dashboards/_status.html.erb
- config/locales/en.yml
- db/migrate/20220810101108_add_default_to_bookings_school_availability.rb
- db/migrate/20220810142124_make_availability_info_and_experience_type_not_nullable.rb
- db/schema.rb
- features/candidates/registrations/availability_preference.feature
- features/candidates/schools/show/full_school_details.feature
- features/schools/dashboard.feature
- features/step_definitions/candidates/registrations/request_school_experience_placement_steps.rb
- features/step_definitions/candidates/schools/show_steps.rb
- spec/factories/bookings/school_factory.rb
- spec/helpers/schools/dashboards_helper_spec.rb
- spec/models/bookings/school_spec.rb
[Trello-629](https://trello.com/c/xBEYXmhr/629-make-flexible-dates-the-default-for-all-future-schools-with-placeholder-text)
We want new schools to have preset availability info text and accept in-school bookings by default. We also want existing schools that have not specified availability info text/experience type to be backfilled with the defaults.
- Default school availability and backfill existing data
Add migration to default the `availability_info` text and set `experience_type` to in-school.
Backfill existing data to set defaults when the `availability_info` has not yet been specified by the user. Supports rolling back the `availability_info`, however we will not be able to determine the previous `experience_type` in all cases so this will remain as in-school. Using `update_all` …
> Default school availability and backfill existing data

- terraform/paas/application.tf
- terraform/paas/route.tf
https://trello.com/c/KqqWtveD
Delete review app failures:
- https://github.com/DFE-Digital/schools-experience/runs/7802362758?check_suite_focus=true
- https://github.com/DFE-Digital/schools-experience/runs/7802807874?check_suite_focus=true
Delete the redundant delayed_jobs route
Run terraform plan
> [660] Remove extra delayed_jobs route

- app/views/schools/on_boarding/key_stage_lists/_form.html.erb
- app/views/schools/on_boarding/phases_lists/_form.html.erb
- app/webpacker/stylesheets/school-profile.scss
[Trello-589](https://trello.com/c/hq890weE/589-fix-spacing-between-checkboxes)
The checkboxes are styled as individual fieldsets as they map to different underlying attributes. With the formbuilder this results in larger spacing between checkboxes than elsewhere on the website. Instead, we can group the checkboxes in a single fieldset (using a generic key) and it will result in the correct spacing to match other areas of the site.
- Rework checkboxes to improve spacing
I only found the spacing issues on the key stage and phases steps of onboarding, so I've sorted them there.
> Rework checkboxes to improve spacing

- terraform/paas/production.env.tfvars
- terraform/paas/staging.env.tfvars
Remove the existing alerts so we can create them again using the new resource compatible with the updated StatusCake Terraform provider. These will be re-added in a subsequent https://github.com/DFE-Digital/schools-experience/pull/2616
Removal of production and staging StatusCake alerts
> Remove existing StatusCake alerts

- config/environments/production.rb
Reverts DFE-Digital/schools-experience#2629
We are seeing jobs backing up in production; possibly related to this but I'm not sure why. I would expect to see _more_ jobs as the events are sent asynchronously but I'm not sure why that would cause other jobs to fail. It could be that we need to punt the analytics jobs to a separate queue with lower priority.
> Revert "Enable dfe-analytics in production"

- docs/documents/DevOps/tools/powerbi.md
The Service Principal used by ADO here was updated in GitHub Actions, but not in ADO. This update ensures the link between the ADO and GitHub Actions using the same Service Principal secret is documented.
> Add documentation regarding PowerBI job

- app/services/schools/dfe_sign_in_api/role_checked_organisations.rb
- app/views/pages/_request_organisation_access.html.erb
- spec/controllers/schools/change_schools_controller_spec.rb
- spec/services/schools/dfe_sign_in_api/role_checked_organisations_spec.rb
[Trello-636](https://trello.com/c/hJhmEc45/636-create-a-feature-flag-for-the-role-checker-code)
We have an existing feature flag `rolecheck` that appears to disable the role checking for the initial sign in process.
Once signed in we appear to use the `Schools::DFESignInAPI::RoleCheckedOrganisations` module to scope down the available schools so that the user can only access the schools that they have the GSE role enabled for in DFE sign in.
Going forward we want to disable role checking, so that a user will have access to the GSE application if they have access to that school within DFE sign in (removing the need to get a second stage of approval for using the GSE app).
- Disable role checking via `rolecheck` feature flag
Re-purpose `rolecheck` feature flag; when disabled (which it is on …
> Disable role checking via rolecheck feature flag

- app/forms/schools/on_boarding/wizard.rb
- spec/forms/schools/on_boarding/wizard_spec.rb
In some scenarios the user will arrive to the on-boarding journey without the initial step being defined (for example if they left half way through on-boarding and returned manually later). In this scenario we want to take them to the first step that is required but they have not completed (to be inline with the existing on-boarding journey).
> Show first required step when no previous step given

- terraform/paas/network.tf
This is so Prometheus can scrape the Sidekiq instances.
> Add network for Sidekiq monitoring

- Gemfile
- Gemfile.lock
- config/initializers/sidekiq.rb
- config/routes.rb
- config/schedule.yml
[Trello-641](https://trello.com/c/W6usHTny/641-switch-our-job-processor-to-sidekiq)
We run a number of jobs using `delayed_cron_job`; as we are moving to Sidekiq we need to replicate this functionality and can do so with `sidekiq-cron`.
- Add sidekiq-cron for scheduled jobs
Add `sidekiq-cron` gem and configure the jobs/cron expressions to match `delayed_cron_job`.
- Remove basic auth check in dev for sidekiq web
Remove the basic auth check for local development so we can easily access the sidekiq web UI.
- Add sentry-sidekiq gem
Inserts middleware for Sentry into the Sidekiq jobs.
The Sidekiq queue adapter is only running in staging at the moment.
> Run scheduled jobs with sidekiq-cron

- app/controllers/schools/placement_requests/cancellations/notification_deliveries_controller.rb
- app/controllers/schools/placement_requests/cancellations_controller.rb
- app/helpers/schools/placement_requests_helper.rb
- app/models/bookings/placement_request/cancellation.rb
- app/notify/notify_email/candidate_request_rejection.rb
- app/views/schools/placement_requests/cancellations/_form.html.erb
- app/views/schools/rejected_requests/show.html.erb
- config/analytics.yml
- config/locales/en.yml
- db/migrate/20220907093024_add_rejection_categories_to_bookings_placement_request_cancellations.rb
- db/schema.rb
- features/schools/placement_requests/cancelling.feature
- features/step_definitions/form_steps.rb
- features/step_definitions/schools/rejected_requests_steps.rb
- spec/controllers/schools/placement_requests/cancellations/notification_deliveries_controller_spec.rb
- spec/controllers/schools/placement_requests/cancellations_controller_spec.rb
- spec/factories/bookings/placement_request/cancellations_factory.rb
- spec/factories/bookings/placement_request_factory.rb
- spec/helpers/schools/placement_requests_helper_spec.rb
- spec/models/bookings/placement_request/cancellation_spec.rb
- spec/notify/notify_email/candidate_request_rejection_spec.rb
[Trello-606](https://trello.com/c/NdePhNq2/606-enable-multiple-reasons-for-rejection-on-manage)
We currently only allow a single rejection reason for a placement request, however we want to allow candidates to specify multiple reasons.
- Allow multiple reasons for a placement rejection
Add attributes/columns for each available rejection category. Populate new attributes from the existing, single attribute as part of the migration.
Retain the original `rejection_category` attribute and ensure it stays up to date (so when the categories change we pick the latest to populate this attribute) -- assuming we don't need to revert it can later be removed.
Update analytics whitelist to include the new attributes.
To test this you need to sign up for a placement at a school then sign in as the …
> Allow multiple reasons for a placement rejection

- .github/dependabot.yml
We're finding the weekly interval too frequent and the number of PRs dependabot raises is a pain to keep on top of - monthly should work out better for us.
> Change dependabot to monthly interval

- app/controllers/application_controller.rb
- config/initializers/sentry.rb
- config/initializers/yabeda.rb
- spec/requests/session_expired_spec.rb
[Trello-659](https://trello.com/c/M9u3sqbf/659-switch-csrf-token-errors-to-use-metrics-and-threshold-alerting)
The CSRF error is unavoidable and we will see them happen on occasion (for example when a candidate's session times out or if they cleared their cookies before submitting a form). We only really care about these if they happen on a scale that is unexpected (several per minute or hour).
To avoid spamming Slack with errors we can't resolve we will instead have Sentry ignore them (which it does by default) and increment a Prometheus counter that we can then alert on at a given threshold.
- Record CSRF token errors as a metric
[Corresponding PR to add an alert rule](https://github.com/DFE-Digital/get-into-teaching-api/compare/master...add-csrf-token-alert?quick_pull=1)
> Record CSRF token errors as a metric

- Gemfile.lock
- package.json
- yarn.lock
- Bump nokogiri from 1.13.8 to 1.13.9
- Bump core-js from 3.25.0 to 3.25.5
- Bump css-minimizer-webpack-plugin from 4.1.0 to 4.2.1
- Bump jest from 29.1.1 to 29.1.2
- Bump selenium-webdriver from 4.4.0 to 4.5.0
- Bump spring from 4.0.0 to 4.1.0
- Bump net-smtp from 0.3.1 to 0.3.2
- Bump shakapacker from 6.5.1 to 6.5.2
- Bump yabeda-sidekiq from 0.8.1 to 0.9.0
Closes #2708, #2699, #2698, #2692, #2691, #2690, #2687, #2686, #2684
> Various dependency updates

- Gemfile
- Gemfile.lock
- app/controllers/concerns/dfe_authentication.rb
- app/controllers/schools/insecure_sessions_controller.rb
- app/controllers/schools/sessions_controller.rb
- app/decorators/user_info_decorator.rb
- app/helpers/application_helper.rb
- app/models/user.rb
- config/analytics.yml
- config/analytics_blocklist.yml
- config/analytics_pii.yml
- config/initializers/dfe_analytics.rb
- db/migrate/20221031134558_create_users.rb
- db/schema.rb
- lib/servertest/sessions_controller.rb
- spec/controllers/concerns/dfe_authentication_spec.rb
- spec/controllers/schools/sessions_controller_spec.rb
- spec/factories/users.rb
- spec/helpers/application_helper_spec.rb
- spec/models/user_spec.rb
[Trello-662](https://trello.com/c/g44WHRsw/662-add-user-model-for-managing-roles-within-gse)
We are shifting the responsibility for managing roles/permissions to schools from DfE sign in to the application. Currently if a user wants access to a school they need to setup an account for the school/organisation in DfE sign in and _then_ request access to the School Experience service. This is unintuitive for users and causes many to drop out/not get access to the service.
Instead, we will use ID-only access via DfE sign in so that the user only needs to be part of the correct organisation and then we will manage permissions to sign in to the school on School Experience from within the app.
The first step along this route is to setup a `User` model so that we can manage roles/permissions …
> Add a user model

- app/decorators/user_info_decorator.rb
- app/helpers/application_helper.rb
I removed this class in a previous PR, however some sessions have objects of this class stored in them still; until all sessions have expired/are using the new `User` model its not safe to remove.
The interface of `User` and `UserInfoDecorator` are the same so the rest of the code shouldn't need updating.
> Reinstate UserInfoDecorator

- Gemfile
- Gemfile.lock
- app/models/bookings/school.rb
- app/models/role.rb
- app/models/user.rb
- config/analytics.yml
- config/analytics_pii.yml
- config/initializers/rolify.rb
- db/migrate/20221104080002_rolify_create_roles.rb
- db/schema.rb
- spec/models/bookings/school_spec.rb
- spec/models/role_spec.rb
- spec/models/user_spec.rb
[Trello-664](https://trello.com/c/NUHQxJWP/664-add-role-library-for-controlling-access-to-schools)
We want to manage permissions within the app going forward (instead of via DfE sign in). To do this we need a way of tracking who has access to which resource/school.
- Add rolify gem to manage roles
Add `rolify` gem; this is a simple and well maintained gem that will enable us to manage user roles on a per-resource/school basis.
> Add rolify gem to manage school permissions

- .github/workflows/check_sp.yml
https://trello.com/c/SPbIS1pl
Reducing GitHub secrets reduces management overhead and makes this workflow easier to generalise.
- Get KeyVault name for sp_check from matrix data instead of a GitHub secret.  
- Pinned major version of rtCamp/action-slack-notify
Checks logs on [test run](https://github.com/DFE-Digital/schools-experience/actions/runs/3573076076).
> Get KeyVault name for sp_check from matrix data instead of a GitHub secret

- app/views/layouts/application.html.erb
- features/candidates/landing_page.feature
- features/schools/landing_page.feature
- features/schools/service_updates.feature
- features/step_definitions/common_steps.rb
[Trello-653](https://trello.com/c/xYJXz7M2/653-add-get-help-section-to-the-footer-of-candidate-facing-pages-of-gse-but-not-manage)
We want to display a 'Get help' section in the footer for all candidate-facing pages (and not the school/manage pages) so that candidates know where to go to get support or give feedback with their School Experience.
- Add 'Get help' section to candidate footer
> Add 'Get help' section to candidate footer

- lib/placement_request_transfer.rb
- spec/lib/placement_request_transfer_spec.rb
Comparing the supported experience type of the school is a bit too restrictive; we can transfer the placement request if the school we're transferring it to supports the experience type of the placement.
> Compare placement request experience type

- Gemfile.lock
[Trello-4014](https://trello.com/c/W50wYBTV/4014-fix-gse-timeout-when-calling-api-crm)
This will reduce the API client timeout to 10 seconds, which is less than the 30s app timeout. Hopefully this will result in a retry and fix timeout errors we occasionally get (mainly from the health check endpoint).
- Update API client gem
> Update API client gem

- app/views/schools/on_boarding/_school_fees_shared_form.html.erb
- app/views/schools/on_boarding/access_needs_details/_form.html.erb
- app/views/schools/on_boarding/access_needs_policies/_form.html.erb
- app/views/schools/on_boarding/access_needs_supports/_form.html.erb
- app/views/schools/on_boarding/admin_contacts/_form.html.erb
- app/views/schools/on_boarding/candidate_dress_codes/_form.html.erb
- app/views/schools/on_boarding/candidate_experience_schedules/_form.html.erb
- app/views/schools/on_boarding/candidate_parking_informations/_form.html.erb
- app/views/schools/on_boarding/candidate_requirements_selections/_form.html.erb
- app/views/schools/on_boarding/dbs_requirements/_form.html.erb
- app/views/schools/on_boarding/descriptions/_form.html.erb
- app/views/schools/on_boarding/disability_confidents/_form.html.erb
- app/views/schools/on_boarding/experience_outlines/_form.html.erb
- app/views/schools/on_boarding/fees/_form.html.erb
- app/views/schools/on_boarding/key_stage_lists/_form.html.erb
- app/views/schools/on_boarding/phases_lists/_form.html.erb
- app/views/schools/on_boarding/subjects/_form.html.erb
- app/views/schools/on_boarding/teacher_trainings/_form.html.erb
[Trello-3911](https://trello.com/c/MEZlmkIu/3911-update-about-git-events-page-for-end-of-autumn-programme)
We want to add the school name as the top-level `h1` heading on all on-boarding steps so that users on-boarding multiple schools can easily see which school they are filling out the current step for. Bump previous top-level headings down to `h2` and subsequent step fields should be `h3`.
- Update on-boarding heading structure
> Update on-boarding heading structure

- app/models/application_record.rb
- spec/requests/big_query_analytics_spec.rb
[Trello-4028](https://trello.com/c/oDECMFWN/4028-fix-deprecation-warnings-in-git-website-tta-service)
We no longer need to include `DfE::Analytics::Entities` explicitly; as of v1.4 it is included automatically.
- Fix dfe-analytics deprecation warning
> Fix dfe-analytics deprecation warning

- app/controllers/candidates/registrations/confirmation_emails_controller.rb
- app/views/candidates/registrations/application_previews/show.html.erb
- config/initializers/rack_attack.rb
- feature-flags.json
- spec/controllers/candidates/registrations/confirmation_emails_controller_spec.rb
- spec/requests/rate_limiting_spec.rb
[Trello-599](https://trello.com/c/dwv1HiJ0/599-implement-now-spike-is-complete-alternative-ways-to-prevent-spam-record-creation)
Currently if a new candidate signs up for a placement they are required to confirm their email address before the request is processed. We've had support tickets for candidates struggling to sign up and we believe that they are not actioning the sent email. Going forward we want to remove this requirement and introduce other, non-intrusive checks to prevent spam record creation.
- Remove confirmation requirement for new candidates
Currently we require new candidates to confirm their email before issuing the placement request. We believe that this prevents a number of candidates from successfully finishing their request (the email doesn't arrive and/or they don't …
> Remove confirmation step

- config/analytics.yml
- config/analytics_blocklist.yml
[Trello-4424](https://trello.com/c/o7ECY3uk/4424-whitelist-gitisuuid-in-gse-dfe-analytics)
Alex Christensen has requested this field to be sent to BigQuery so that he can match up records to those in the GiTiS CRM.
> Whitelist gitis_uuid for dfe-analytics

- db/data/school_types.yml
[Trello-683](https://trello.com/c/S8ucFDaE/683-investigate-mass-importer-errors)
This was recently added to the school data we import on a nightly basis. I've manually added it to the dev/staging/production environments; this updates the seed data to be consistent.
- Add Online Provider school type
Manually added with:
```
Bookings::SchoolType.create!(name: "Online provider", edubase_id: 49)
```
> Add Online Provider school type

- app/views/candidates/schools/index.html.erb
https://trello.com/c/jD8JzBiE/685-implement-link-to-university-of-york-realistic-job-preview
We are experimenting with Realistic Job Previews. This link is added to the results page and has UTM parameters attached.
Add new module to search results page (NB copy has been tweaked slightly since this screengrab):
Do we want any tests?
> Add Realistic Job Preview link to search results page

- .github/workflows/check_sp.yml
The test service principal secret is expiring, but the alert is not appearing in the channel.
The error appears to suggest the service principal in use doesn't have access to the s105t01-kv key vault.
It appears that as the check is using the 'test' environment context which does not exist, it does not pickup the updated AZURE_CREDENTIAL value and therefore does not have the proper access to the test subscription key vault to retrieve the Slack webhook.
Change the environment in the check to 'Staging'
Removed the token auth as we login to Azure the step before
Confirmed the workflow runs using the Staging environment for the test subscription.
> Update env context to use staging.

- Makefile
https://trello.com/c/cWqGr01f/604-redeploy-dev-staging-and-prod-environments-due-to-tagging
RG_TAGS changed from {"Product" : "Get Schools Experience"} to
{"Product" : "Get School Experience"}
service name was changed from get-schools-experience to get-school-experience
> Changed the tag and service name to singular school

- .gitignore
- Makefile
- global_config/domains.sh
- global_config/production.sh
- terraform/domains/environment_domains/.terraform.lock.hcl
- terraform/domains/environment_domains/config/development.tfvars.json
- terraform/domains/environment_domains/config/development_Terrafile
- terraform/domains/environment_domains/config/production.tfvars.json
- terraform/domains/environment_domains/config/production_Terrafile
- terraform/domains/environment_domains/config/staging.tfvars.json
- terraform/domains/environment_domains/config/staging_Terrafile
- terraform/domains/environment_domains/main.tf
- terraform/domains/environment_domains/terraform.tf
- terraform/domains/environment_domains/variables.tf
- terraform/domains/infrastructure/.terraform.lock.hcl
- terraform/domains/infrastructure/config/zones.tfvars.json
- terraform/domains/infrastructure/config/zones_Terrafile
- terraform/domains/infrastructure/main.tf
- terraform/domains/infrastructure/terraform.tf
- terraform/domains/infrastructure/variables.tf
Adds Terraform code, config and Makefile commands to support managing DNS using Terraform
https://trello.com/c/iEt2nhFs
Allow management of the services DNS using Terraform
[Deployed resource group](https://portal.azure.com/#@platform.education.gov.uk/resource/subscriptions/3c033a0c-7a1c-4653-93cb-0f2a9f57a391/resourceGroups/s189p01-gsedomains-rg/overview)
> [576] Add Terraform code to manage DNS

- .github/workflows/paas_to_aks_db_backup_and_restore_manual.yml
- .gitignore
- Makefile
- terraform/aks/config/development.tfvars.json
- terraform/aks/config/production.tfvars.json
- terraform/aks/config/review.tfvars.json
- terraform/aks/config/staging.tfvars.json
- terraform/aks/variables.tf
WHY: The DB migration is required for the migration of PAAS to AKS on the workflows
HOW: Put functionality in workflow to log in to paas dump db and restore to AKS
https://trello.com/c/6bFaCVR8/681-enable-daily-database-refresh-from-paas-to-aks
to migrate GSE dbs from PAAS to AKS on workflow
code added in workflow to be run manually 
select the pipeline, select the desired environment and run
> Added paas to aks db restore

- .github/workflows/build.yml
WHY: paas deployment for dev will not be necessary after deployment
HOW: Remove development from matrix
https://trello.com/c/gkhvqc5A/691-remove-dev-env-from-workflow
to remove dev env from workflow run
development removed from the list
> To remove paas dev from workflow after merge

- .github/workflows/database-copy.yml
- .github/workflows/paas_to_aks_db_backup_and_restore_manual.yml
WHY: It is important to refresh the DB whilst waiting for migration
HOW: A scheduled workflow is created to call the migration script
https://trello.com/c/6bFaCVR8/681-enable-daily-database-refresh-from-paas-to-aks
enabled scheduled refresh for staging and production
db migration is scheduled
schedule:
- cron: '0 2 * * *' # 02:00 UTC
> Added scheduled DB refresh

- .github/workflows/build.yml
- .github/workflows/database-copy.yml
WHY: Staging build and deploy for PAAS not necessary after Migration
HOW: by removing from the list of build environments
remove staging from build and db refresh
remove staging from build and db refresh
> Removed staging PAAS from build and deploy to be merged after Migration

- Dockerfile
- Gemfile.lock
[5278](https://trello.com/c/4L1ukRUv/5278-gse-rails-app-load-error-after-nokogiri-fix)
The Docker build fails because it does not contain the platform specific installation of the nokogiri gem. Changes through bundler were failing to work, so explicitly adding.
Explicitly add the required platform specific version of nokogiri to the image.
> Dependabot sidekiq 6.5.12 update with nokogiri fix

- .github/workflows/destroy_aks.yml
https://trello.com/c/hI9AAMsQ/800-fix-destroy-review-aks-bug
the destroy aks  review pr fails due to not getting context 
az aks get-credentials -g s189t01-tsc-ts-rg -n s189t01-tsc-test-aks
PR is destroyed
> added az get credentials

- .github/labeler.yml
https://trello.com/c/rMgSHSgy/863-labeler-fix
WHY: The syntax has been changed in the target, leading to build failure
HOW: By changing the syntax to match the latest syntax
labeler syntax changed to current
> Changed labeler to use the current syntax

- features/step_definitions/candidates/registrations/request_school_experience_placement_steps.rb
- yarn.lock
This pull request upgrades the govuk-frontend library from version ^4.0.1 to 4.7.0. 
https://trello.com/c/D7upaa5C
Ahead of the breaking changes introduced by the release of 5.0, this upgrade brings new features and improvements to the govuk-frontend library, enhancing the user experience and keeping our application up-to-date with the latest design patterns. 
This update is part of our ongoing effort to keep our dependencies current. Notably, 4.7.0 is the last upgrade before a major 5.0 release. While this PR doesn't include major breaking changes, it prepares us for the upcoming transition and allows us to identify and address any potential issues early on.
- Tested locally to ensure the application functions as expected.
-  Ensured all existing features are unaffected by the upgrade.
- …
> Update govuk-frontend from `4.0.1` to `4.7.0`

- .github/workflows/actions/database-backup/action.yml
- Makefile
https://trello.com/c/RnXWAXvO/943-bug-school-experience-db-backup-is-failing
DB backup failing for AUTO_APPROVE not set.
changed the following call
make ${{ inputs.environment }} get-cluster-credentials
to 
make ci ${{ inputs.environment }} get-cluster-credentials
From command line execute make ci ${{ inputs.environment }} get-cluster-credentials , it should not ask approvals.
> Fixed db backup pipeline failures

- package.json
- yarn.lock
Due to ci-failures, temporarily downgrading this to the previous working version in an attempt to get the pipeline working fine again.
> Downgrade sass-loader version

- app/views/candidates/schools/index.html.erb
https://trello.com/c/UEseqfYg/
The Realistic job previews (Klassen) pilot has ended
This fix removes the link from Get school experience
The link highlighted in the screenshot should no longer be on the page.
> Remove realistic job previews link from Get school experience

- app/views/schools/change_schools/show.html.erb
- app/views/schools/dashboards/_profile_and_dates.html.erb
- app/views/schools/show.html.erb
- spec/views/schools/change_schools/show.html.erb_spec.rb
[#5535 ](https://trello.com/c/KSbGXeZ5)
As part of the integration with the Identity only version of DfE Sign-in on Get School Experience
We are making changes to the copy on same pages.
- Update copy on school show page to use bullet points for service description
- Remove request school radio button and add contact information for DfE Sign-in support
- Update school access message for users with no schools
- navigate to the pages to see the difference.
Before:
After:
Before:
After:
> Copy Changes on Manage GSE

- config/locales/en.yml
https://trello.com/c/wUYLWrEk/389-content-dac-audit-error-handling-for-dbs-response
If a candidate doesn't click an option for this question, the error message is generic, which doesn't help with accessibility. This improves the error message.
Select an option -> Select whether you have a DBS certificate
- Does this render correctly on the candidate sign up flow?
> Improve error message for DBS certificate question on candidate flow

- app/controllers/schools/users_controller.rb
- app/notify/notify_email/school_user_invite.8ac4d9f9-f51d-4c3b-9cc7-fd59751ece3d.md
- app/notify/notify_email/school_user_invite.rb
- app/services/schools/dfe_sign_in_api/organisation_users.rb
- app/services/schools/dfe_sign_in_api/user_invite.rb
- app/views/schools/users/_form.html.erb
- app/views/schools/users/index.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/servertest.rb
- config/environments/staging.rb
- config/environments/test.rb
- spec/notify/notify_email/school_user_invite_spec.rb
Address Feedback from this review:
https://github.com/DFE-Digital/schools-experience/pull/3080#issuecomment-1994113504
- Update the form fields  `Firstname` & `Lastname`  to First name & Last name
- On /schools/users page - DfE Sign-in link should redirect users to /approvals/users on the respective environments
- Ensures new users are displayed On /schools/users page when a new user is invited 
- Ensure invited users receive any email notification confirming that they have been granted access to manage a school
> Address review feedback on schools user invite

- app/views/candidates/home/index.html.erb
N/A
This got removed during prior accessibility fixes. Needs changing.
- Guide for candidate -> guide for candidates.
-
> Amend typo in 'guide for candidates' link

- app/views/pages/dfe_signin_help.html.erb
- app/views/schools/show.html.erb
Updates the copy on parts of the Get school Experience app.
> MSE Copy Updates

- app/views/candidates/registrations/personal_informations/_form.html.erb
https://trello.com/c/xGsAiAp3
- As part of improving the foundations of the Get school experience service, we think it's a good idea to align how we surface information on the privacy notice at the start of the user request flow. This language is broadly similar to the Get Into Teaching website's approach.
Add information on, and link to, privacy notice on the first page of the school experience sign up flow.
- Does this look right?
- Do the links work?
- Does it avoid repetition of info throughout the flow?
> Add links to privacy notice on matchback page

- app/views/candidates/home/guide_for_candidates.html.erb
https://trello.com/c/ODlo5o8c
- Found this whilst checking some changes in another PR. Wanted to get views on removing this now we're into 2024.
- Remove COVID paragraph in guidance for candidates page.
- Does this look right?
- Do you agree with removal?
> Remove copy on COVID procedures

- .github/workflows/build.yml
https://trello.com/c/3zfsmtLr/
Following the OWASP Docker Org Depreciation, the current docker image will no longer be updated with the ZAP releases in the OWASP Docker Hub organisation.
Link: https://www.zaproxy.org/blog/2024-03-04-zap-updates-february-2024/#owasp-docker-org-depreciation
Updating to use ghcr.io/zaproxy/zaproxy
> ZAP Scan docker image upgrade

- app/views/schools/confirmed_bookings/cancellations/_letter.html.erb
N/A
- Spotted this in another review, we shouldn't have full stops in anchor links.
- This is when a school is cancelling a confirmed booking
Move full stop out of anchor link.
Is the full stop now out of the anchor link?
> Fix full stop in anchor link

- app/views/candidates/registrations/background_checks/_form.html.erb
https://trello.com/c/zo7QPFde
- We've identified some issues with this page, such as a link needing context, and unnecessary quote marks.
- This PR corrects these.
_**Before**_
_**After**_
- Go through a candidate request and check the page
- Do you think we need to remove the remaining bold text? I'm not sure it's necessary as such.
> Improve DBS page (candidate flow) accessibility

- app/models/bookings/subject.rb
- app/models/candidates/placement_date_option.rb
https://trello.com/c/NOHbwt7v
We're seeing issues with a few schools not able to receive requests.
This could be due to our removal of subjects: `physics with maths` and `vocational health`.
* Refactor `secondary_subjects` scope in `Bookings::Subject` model to include only non-hidden secondary subjects
* Remove safe navigation from `bookings_subject` in `placement_date_option.rb`
> Filter hidden subjects in Schools `secondary_subjects`

- app/views/candidates/home/index.html.erb
- app/views/candidates/registrations/application_previews/show.html.erb
- app/views/candidates/registrations/sign_ins/show.html.erb
https://trello.com/c/Shy150vw
- We don't use this term anymore, so changing all instances of it.
**Start page**
**Matchback question**
**Check your answers page**
- Do a school experience request, all 3 views are on those pages.
> Find + replace GITIS -> Get Into Teaching service

- app/views/schools/confirm_attendance/show.html.erb
- app/views/schools/dashboards/_no_placement_dates_warning.html.erb
- app/views/schools/on_boarding/profiles/editing.html.erb
- app/views/schools/on_boarding/profiles/onboarding.html.erb
- app/views/schools/placement_dates/index.html.erb
- app/views/schools/toggle_enabled/edit.html.erb
- features/schools/placement_dates/index.feature
https://trello.com/c/QHKZbml7
- We have some issues relating to how our buttons are grouped, we too often rely on putting them on separate lines, which does not align with the Design System.
- Improve button grouping on the confirm attendance page
- Add a back link on the 'toggle profile on/off' page and group this with existing buttons
- Improve button grouping on our onboarding flow
- Improve button grouping on our edit profile flow
- Improve button grouping on our 'add dates' page
Attendance page (you will need to login as a school with attendances to confirm (Holland Park) and one without (Outwood Academy Acklam)):
- https://get-school-experience-review-pr-4.test.teacherservices.cloud/schools/confirm_attendance
Toggle page on/off:
- …
> Improve button groupings (first tranche)

- app/views/schools/dashboards/_update_your_school_profile.html.erb
- app/views/schools/on_boarding/profiles/onboarding.html.erb
https://trello.com/c/XYoC2LnC
_**Before**_ 
_**After**_ (NB checkbox alignment issue is already known and ticketed up to fix)
> Improve location of our school privacy notice

- app/webpacker/stylesheets/application.scss
- app/webpacker/stylesheets/school-search.scss
https://trello.com/c/nDfEHJnU
- We introduced some CSS in our Gov Frontend 5.2 upgrade due to a bug we identified in the candidate search function.
- However, this had knock on impacts on other areas of the system, mainly on the school side.
- This fix removes the code we introduced as part of that Frontend upgrade, but also removes some stray CSS which seems to be causing the issue with checkboxes.
> CSS changes for checkbox

- terraform/aks/config/staging.tfvars.json
https://trello.com/c/ThDx6UzV
Alerts are too noisy in staging because of dependencies (DSI, GIT CRM...).
Use the /check endpoint to check the app only.
Check URL
> [1797] Do not check dependencies in staging statuscake

- app/views/feedbacks/_form.html.erb
- app/views/schools/availability_preferences/edit.html.erb
- app/views/schools/confirmed_bookings/cancellations/notification_deliveries/show.html.erb
- app/views/schools/contact_us/show.html.erb
- app/views/schools/organisation_access_requests/show.html.erb
- app/views/schools/placement_dates/close_confirmation.html.erb
- app/views/schools/placement_requests/cancellations/notification_deliveries/show.html.erb
- app/views/schools/toggle_enabled/edit.html.erb
- features/schools/toggle_enabling_and_disabling.feature
https://trello.com/c/gapHzCUD
- Some pages lack breadcrumbs
- Some pages lack backlinks
- Add breadcrumbs to the toggle profile page
- Add breadcrumbs to choose how dates are displayed page
- Add backlinks to contact us/request access to another organisation/close placement dates page
- Do breadcrumbs render on the profile on/off page?
- Do breadcrumbs render on the 'choose how dates are displayed' page?
- Do the breadcrumbs link to where you expect?
- Are backlinks appropriate in the other locations?
- Should we use breadcrumbs in the close placement date page?
> Add breadcrumbs to pages without them

- .github/workflows/build-no-cache.yml
- .github/workflows/trello.yml
https://trello.com/c/C1iKu3uI/1827-gse-fix-workflow-secrets
Replace keyvault-yaml-secret with azcli in failing workflows
- build-no-cache.yml
- trello.yml
Update github workflows
Confirm workflows run successfully
see https://github.com/DFE-Digital/schools-experience/actions/runs/9159213206 and https://github.com/DFE-Digital/schools-experience/actions/runs/9158198801
> replace keyvault-yaml-secret with azcli

- app/models/bookings/school_search.rb
- app/views/candidates/school_searches/new.html.erb
- app/views/pages/accessibility_statement.html.erb
- app/views/schools/dashboards/_requests_and_bookings.html.erb
- bin/shakapacker
- bin/shakapacker-dev-server
- bin/yarn
- config/locales/en.yml
- features/candidates/schools/search/results/filtering.feature
- features/candidates/schools/search/results/sorting.feature
- features/schools/dashboard.feature
- features/step_definitions/candidates/schools/sorting_steps.rb
- spec/models/bookings/placement_request/cancellation_spec.rb
- spec/models/bookings/school_search_spec.rb
validate for a location or query
small rubocop fixes on other files
[Surface a validation error](https://trello.com/c/NLPhh1Wh/5840-ensure-that-we-surface-a-validation-error-if-a-user-tries-to-search-for-a-school-experience-placement-with-no-postcode-on-gse)
The Schools Experience does not show an error if the location field is left blank when searching for a schools experience
This is a re-implementation of work originally done in PR https://github.com/DFE-Digital/schools-experience/pull/3159 - now using Rails validators and GOVUK frontend libraries
Validate for location
> Surface location validation

- app/views/schools/on_boarding/disability_confidents/_form.html.erb
- https://trello.com/c/HP4qUga0
- This scheme (two ticks) was replaced in 2013. We think enough time has passed to remove reference to it.
- Remove reference to the two ticks scheme.
**After**
> Remove two ticks scheme copy

- config/initializers/timeout.rb
N/A
Since shipping the log files to logit, there is a lot of noise being generated by rack-timeout.
Disable log messages from tack-timeout
> Disable rack-timeout logging

- terraform/aks/application.tf
- terraform/aks/config/development.tfvars.json
- terraform/aks/config/production.tfvars.json
- terraform/aks/config/staging.tfvars.json
- terraform/aks/variables.tf
https://trello.com/c/Zlih3dRZ/1889-scrape-custom-metrics
Scrape custom metrics that are exported for gse,
which can then be used in dashboards and alerting
Add enable_prometheus_monitoring to application deployments and set for each env
remove from review apps before merge
make development terraform-plan IMAGE_TAG=x
Review app metrics are visible in prometheus test (yabeda-rails, sidekiq, http_requests, puma)
> Scrape custom metrics

- terraform/aks/application.tf
https://trello.com/c/Zlih3dRZ/1889-scrape-custom-metrics
Scrape the worker process custom metrics
merge when ttps://github.com/DFE-Digital/terraform-modules/pull/110/commits/aacddbd753ba10580a0551dc9b0ca29bec940a4d is in STABLE
Add enable_prometheus_monitoring to worker
Deployed using branch [1889-scrape-custom-metrics](https://github.com/DFE-Digital/terraform-modules/tree/1889-scrape-custom-metrics)
Remove from review tfvars before merge
make env terraform-plan
Check metrics are being collected for the review app (most starting with sidekiq)
> Scrape worker custom metrics

- app/views/pages/cookies_policy.html.erb
https://trello.com/c/hzAfNgD6
Remove references to UA from cookie policy
> Remove reference to universal analytics from cookie policy 

- app/controllers/candidates/registrations/educations_controller.rb
- app/services/candidates/registrations/behaviours/education.rb
- app/services/candidates/registrations/education.rb
- app/views/candidates/registrations/educations/_form.html.erb
- app/webpacker/controllers/education_form_controller.js
- app/webpacker/stylesheets/application.scss
- app/webpacker/stylesheets/candidate.scss
- config/locales/en.yml
- features/candidates/registrations/education.feature
- features/step_definitions/candidates/registrations/application_preview_steps.rb
- features/step_definitions/candidates/registrations/education_steps.rb
- features/step_definitions/candidates/registrations/subject_preferences_steps.rb
- features/step_definitions/candidates/registrations/wizard_steps.rb
- spec/features/candidates/api_registrations_spec.rb
[No-javascript free text box for degree subject](https://trello.com/c/UejNSJb6/6333-implement-no-javascript-free-text-box-fallback-for-degree-subject-autocomplete-get-school-experience)
If a browser has javascript disabled, display a textbox to capture the degree subject, rather than a very long select list
Test with JS enabled and disabled
> No js degree inputbox

- spec/requests/cookie_banner_spec.rb
https://trello.com/c/Ww7AoZHF
The `seen_cookie_message` was removed in #3241, this removes it's surrounding code from the cookies spec
Removes mention of `seen_cookie_message` in the specs
> Remove unused seen_cookie_message spec

- Gemfile
- Gemfile.lock
- app/views/layouts/application.html.erb
- package.json
- yarn.lock
https://trello.com/c/V2PCc0U6/6340-upgrade-shakapacker-from-7-to-8-on-get-school-experience?filter=member:spencerldixon
Shakapacker needs to be upgraded to v8 inline with the Get Into Teaching website
- Update shakapacker to v8.0.1
- Configure packageManager as per new requirements
> Upgrade Shakapacker

- .github/workflows/db_backup.yml
- .github/workflows/postgres-ptr.yml
- .github/workflows/postgres-restore.yml
https://trello.com/c/E83HBQc9/2189-gse-plan-for-dr-test
Implement postgres backup/restore workflows required for DR testing
- update backup workflow using TS backup github action
- add postgres point-in-time restore workflow
- add postgres restore from backup workflow
staging backup: https://github.com/DFE-Digital/schools-experience/actions/runs/12394436024
dev backup: https://github.com/DFE-Digital/schools-experience/actions/runs/12394151304
restore workflows will be tested after merge
> Add new postgres backup and restore workflows

- package.json
- yarn.lock
https://trello.com/c/G8v3P73S/7264-bump-frontend-to-580-for-get-school-experience
GDS has recently released a new version of Frontend - 5.8.0, and we need to bump to the latest version.
Bump of GOV.UK frontend. Ran tests and did a careful check of visuals; all looks ok.
> Bump GOVUK frontend to 5.8.0

- features/candidates/feedback.feature
- features/candidates/registrations/availability_preference.feature
- features/candidates/registrations/education.feature
- features/candidates/registrations/experience_preference.feature
- features/candidates/schools/search/results/filtering.feature
- features/candidates/schools/search/results/sorting.feature
- features/schools/feedback.feature
- features/schools/placement_dates/primary_and_secondary_school_configuration.feature
- features/schools/placement_dates/primary_school_configuration.feature
- features/schools/placement_dates/secondary_school_configuration.feature
- features/schools/placement_requests/cancelling.feature
[Related to Ruby 3.4 upgrade](https://trello.com/c/5gIskHMH/7384-upgrade-the-ruby-version-on-get-school-experience-app-from-v31-to-v34)
As part of the upgrade to Ruby 3.4, we need to disable Selenium/javascript based cucumber tests as the underlying Chromedriver does not work on Alpine 3.21
> Disable JS-selenium based tests

- .github/workflows/build-no-cache.yml
- .github/workflows/build.yml
- .github/workflows/trello.yml
https://trello.com/c/CAZOMOph/2294-remove-kv-secrets-from-build-and-test-workflow
Move workflow only secrets from azure keyvault to github secrets.
This removes the github environment from non deploy steps, and makes more sense for a workflow secret.
Updates to workflows
Check workflows all run correctly for this PR
manual build-no-cache: https://github.com/DFE-Digital/schools-experience/actions/runs/13942489603
> Move workflow secrets to github

- terraform/domains/environment_domains/config/production.tfvars.json
- terraform/domains/environment_domains/config/staging.tfvars.json
- terraform/domains/environment_domains/main.tf
- terraform/domains/environment_domains/variables.tf
https://trello.com/c/rmljcE5W/2345-add-rate-limiting-for-services
Configure rate limiting for production and staging
Add global rate limit per IP for 5 minute intervals
Value for global rate set from checking ingress logs for the last 4 weeks and is higher than any 10 minute period in that time.
make production domains-plan
make staging domains-plan
> Add ingress rate limit

- package.json
- yarn.lock
Updated the govuk-frontend dependency from 5.8.0 to 5.9.0 in package.json and yarn.lock to incorporate the latest features and fixes.
[Upgrade govuk-frontend to version 5.9.0](https://trello.com/c/R0n4bcik/7946-bump-frontend-to-590-for-get-school-experience)
Regular update to govuk-frontend
> Upgrade govuk-frontend to version 5.9.0

- .github/workflows/build.yml
After updating the build workflow, realised I dropped the master image from the docker build cache list
Adding it back in
see the build runs correctly using master as a cache option
https://github.com/DFE-Digital/schools-experience/actions/runs/16777424058
> Add the master image to the build cache list
