DFE-Digital/schools-experience

Dockerfile
The image correctly with regard to signals and exposes the app on port 3000 by default.
Assets and WebPacks are compiled at build time. A health check is configured, currently just checking the webserver has booted and responds successfully.
The image can be built with
`docker build -t my-built-image .`
from the project root.
Additional all the entry point allows running things like rails or rake tasks
`docker run -it --rm my-built-image rails c`
or
`docker run -it --rm my-built-image rake db:migrate`
=> Allow building a Docker Image containing the application

package.json, yarn.lock
Version 2.5.0 of the govuk-frontend package contains plenty of fixes and improvements over 2.3.0.
N/A
N/A
=> Bump govuk-frontend from version 2.3.0 to 2.5.0

.dockerignore
This shouldn't be needed but something in the PostGIS adapter is trying to
explicitly load this file whether needed or not.
=> Include the database.yml file in the Docker image

azure-pipelines.yml
Within the Azure Pipeline, we run Postgres from a Docker Image
The official image does include support the PostGIS extension within the Docker
image, so `create extension postgis` will always fail.
Switching to mdillon's fork which includes the PostGIS extension. This has 10M
downloads at this point and seems to be regularly updated. The running container
is not accessible outside of the internal Docker network within the CI
environment so this seems safe to depend upon from a security perspective
despite being a non official image.
=> Switched to using PostGIS enabled version of Postgres

db/migrate/20190116152522_enable_postgis_extension.rb
Ensure PostGIS is enabled
Note that [`enable_extension`](https://api.rubyonrails.org/classes/ActiveRecord/ConnectionAdapters/PostgreSQLAdapter.html#method-i-enable_extension) only enables if it's not already enabled.
=> Add a migration that ensures PostGIS is enabled

app/controllers/candidate/registrations/account_infos_controller.rb, app/controllers/candidate/registrations/personal_details_controller.rb, app/controllers/candidate/registrations/placements_controller.rb, app/controllers/candidate/registrations_controller.rb, app/services/candidate/registrations/personal_detail.rb, app/views/candidate/registrations/account_infos/new.html.erb, app/views/candidate/registrations/personal_details/new.html.erb, config/routes.rb, spec/controllers/candidate/registrations/personal_details_controller_spec.rb, spec/features/candidate/registrations_spec.rb, spec/services/candidate/registrations/personal_detail_spec.rb
Adds initial personal details form for candidate registrations.
UI is unstyled. To be added in ticket #SE-172.
Successful form submission persists the candidate's personal details
information to the session.
Registration related controllers now inherit from RegistraionsController
so we have a single place to managed the current registration session
and avoid overwriting it at each end point.
Only basic presence validations have been added for the personal details fields
until more information on validation requirements have been gathered
(#SE-170)
Again only the skeleton so far. Have tickets open for fleshing out the UI and the validation errors. Just want to get the basic flow through the 'wizard' sorted before moving on to the styling during the week.
=> SE-142 #comment Add registrations personal details form

app/controllers/candidate/registrations/account_infos_controller.rb, app/controllers/candidate/registrations/background_and_security_checks_controller.rb, app/services/candidate/registrations/account_info.rb, app/views/candidate/registrations/account_infos/new.html.erb, app/views/candidate/registrations/background_and_security_checks/new.html.erb, config/candidate_form_options.yml, config/routes.rb, spec/controllers/candidate/registrations/account_infos_controller_spec.rb, spec/controllers/candidate/registrations/personal_details_controller_spec.rb, spec/features/candidate/registrations_spec.rb, spec/services/candidate/registrations/account_info_spec.rb
Adds initial account info form for candidate registrations.
UI is unstyled. To be added in ticket #SE-172/
Sucessful form submission persistes the candidate's account information
to the session.
=> SE-143 #comment Add registrations account info form

azure-pipelines.yml
We need to push images to a container registry so they be consumed by different environments 
The pipeline now has an additional step which pushes to an Azure private registry. This step is skipped unless the the build is off of the master branch. 
This has been tested with a condition testing for this branch, then changed to test for the master branch. The two builds in Azure DevOps resulted in the docker push step running for the former (and succeeding) and being skipped for the latter (since the pipeline was being run on a branch other than master).
=> Pushing built docker image to registry

azure-pipelines.yml
Builds in CI are currently quite slow because a full Docker image gets built on every run
1. The login to the Docker Registry is moved earlier in the process
2. The image when built is tagged as :latest as well as a specific version if on master
3. Both images are pushed if on master
4. The build process will attempt to pull the :latest image
5. The build process will use the :latest image as a cache to build the new image from
This was constrained to its own branch but I dropped that commit and its now back on the `master` branch
Builds 370 - 373 show the evolution of the successful builds in this branch
=> Use existing docker image for build cache

app/assets/stylesheets/application-preview.scss, app/assets/stylesheets/application.scss, app/controllers/candidates/registrations/application_previews_controller.rb, app/controllers/candidates/registrations/background_checks_controller.rb, app/controllers/candidates/registrations/placement_requests_controller.rb, app/services/candidates/registrations/application_preview.rb, app/views/candidates/registrations/application_previews/_list_row.html.erb, app/views/candidates/registrations/application_previews/show.html.erb, config/routes.rb, spec/controllers/candidates/registrations/background_checks_controller_spec.rb, spec/features/candidates/registrations_spec.rb, spec/services/candidates/registrations/application_preview_spec.rb
Adds the candidate application preview screen.
Adds the candidate application preview screen between background check and your application has been placed screen.
If manually testing expect the wizard step after background check to be preview application.
=> Adds candidate application preview screen

config/database.yml, features/support/env.rb
We were unable to make Cucumber run against a specified host/database via the use of environment variables and the Cucumber section of `database.yml` appeared to be ignored.
Allow settings in the test environment to be overridden giving us a little more flexibility when running Cucumber tests in Azure. Also allow `autorun_database_cleaner` to be disabled.
Make sure it looks sane
=> Allow finer control of Cucumber via env vars

app/assets/stylesheets/global-styles.scss, app/assets/stylesheets/school-search.scss, app/controllers/candidates/schools_controller.rb, app/helpers/candidates/school_helper.rb, app/javascript/controllers/back_link_controller.js, app/models/bookings/school.rb, app/models/candidates/school.rb, app/views/candidates/schools/_form.html.erb, app/views/candidates/schools/_results.html.erb, app/views/candidates/schools/show.html.erb, demo-school.yml, spec/controllers/candidates/schools_controller_spec.rb, spec/helpers/candidates/school_helper_spec.rb, spec/models/bookings/school_spec.rb, spec/views/candidates/schools/index.html.erb_spec.rb, spec/views/candidates/schools/show.html.erb_spec.rb
As a user viewing a result I expect to see further information relating to the school
Adds a schools information page
Currently this is implemented against a stub file, rather than the correct information from the DB. Since there needs to be further fields added to the DB schema
=> Show school screen

Gemfile, Gemfile.lock
Hiredis gem prevents us from connecting to SSL encrypted Redis servers. It offers most benefit in large batched requests which is not our use case so is of limited benefit and obvious cost.
Remove `hiredis` gem
=> Removed Hiredis gem since no ssl suppot

app/controllers/candidates/registrations/application_previews_controller.rb, app/controllers/candidates/registrations_controller.rb, app/services/candidates/registrations/application_preview.rb, app/services/candidates/registrations/registration_session.rb, spec/services/candidates/registrations/application_preview_spec.rb, spec/services/candidates/registrations/registration_session_spec.rb
Was having an issue with stubbing the session in some specs. Added this wrapper class to keep the knowledge of to read / write models to / from the session in one place. Also has the benefit of cleaning up some of the specs.
Introduce session wrapper.
Refactors how application preview presenter is initialized.
=> Refactor registration session

Gemfile, Gemfile.lock, README.md, config/environments/production.rb, config/environments/test.rb, config/initializers/delayed_job.rb, db/migrate/20190205164245_create_delayed_jobs.rb, db/schema.rb
In production we'll need a way to run potentially slow tasks in the background.
Adds DJ, sets up some useful defaults. Configures it as the default queue adapter in production, sets 
`:test_adapter` as the queue adapter in the test environment.
Leaves `:async` as the default adapter in development since DJ is an implementation detail and we're writing jobs against the ActiveJob API.
**Note**
I've not added the `bin/delayed_job` file - this isn't useful anyway with a dependence on `daemons` gem and I don't think there's a good reason for a rails process to be worrying about daemonisation when Docker can do it with more control, monitoring, auto restart, etc - Likewise outside of Docker, the modern expectation is that SystemD handles the daemonisation rather than the process itself.
=> Added Delayed::Job

Gemfile, Gemfile.lock, README.md, config/initializers/exception_notification.rb
Need to be able to report exceptions from Production environments
Uses Slack notifier, which is available to us now.
There are other more comprehensive solutions (eg Sentry) but this gets us exception reporting for now. Doesn't fire unless env vars are set but works in both production and development if they are.
Webhook is available at the beginning of the chat in the private channel `school-exp-errors`. Vars can be set in `.env` file
**Note:** This doesn't include integration with ActiveJob failures - I'll get this merged than look at that next week
=> Added optional Slack notification of Exceptions

Gemfile, features/support/env.rb
To be able to run the cucumber tests as functional tests in the continuous deployment development environment we need to manually set the chrome driver. We also need to be able to specify the application's remote URL.
Introduces an environment variable `APP_URL` through which the applicaton URL is set.
The Azure DevOps agent publicises the location of the Chrome driver URL via an environment variable `ChromeWebDriver`. This pull request leverages this to set the driver path appropriately,
This has been tested by using this branch in the release pipeline.
=> enable cucumber test in CD

Gemfile, Gemfile.lock, app/assets/stylesheets/form-extensions.scss, app/controllers/candidates/schools_controller.rb, app/helpers/candidates/school_helper.rb, app/javascript/controllers/instant_filter_controller.js, app/models/bookings/school.rb, app/models/candidates/school.rb, app/models/candidates/school_search.rb, app/models/candidates/school_stub.rb, app/services/bookings/school_search.rb, app/views/candidates/schools/_results.html.erb, app/views/candidates/schools/show.html.erb, config/environments/development.rb, config/environments/test.rb, config/locales/en.yml, demo-school.yml, features/step_definitions/candidates/landing_page_steps.rb, features/step_definitions/common_steps.rb, features/support/path_helper.rb, spec/controllers/candidates/schools_controller_spec.rb, spec/helpers/candidates/school_helper_spec.rb, spec/models/bookings/school_spec.rb, spec/models/candidates/school_spec.rb, spec/rails_helper.rb, spec/views/candidates/schools/show.html.erb_spec.rb
Assorted tidy ups to the Candidates School Search screens
1. Add Bullet
2. Fix N+1 issues
3. Make auto submit for forms recognise `<select>` changes
4. Optimise lookups of Subjects and Phases
5. Hooked up Sorting the results
6. Show some correct school fields on View School screen, fallback to stub data when fields not available
7. Prevent unintended Geocoder calls from Specs
8. Prevent unneeded Geocoder calls when no location supplied
9. Fixes for handling of URLs in Cucumber
There's a mixture of changes/fixes/clean-ups so maybe easier to look at commits in isolation
=> Search tidy ups

app/jobs/application_job.rb, config/environments/development.rb, config/initializers/delayed_job.rb, lib/delayed_notification_plugin.rb
Background jobs when misconfigured can result in silent failures which are very problematic.
1. Add a hook in Delayed::Job to notify the Slack channel when jobs fail. 
2. Changed the parent ActiveJob class to retry 3 times with a back off. Failed jobs are explicitly not handled so that they will fall through to the notification hook in Delayed::Job and be retained in the DJ table.
Does the setup look sane.
=> Added Exception Notification handling to Active Jobs

app/views/layouts/application.html.erb
The interface doesn't resize correctly when on mobile devices
The meta tags we inherited from the boilerplate are generating incorrect tags, this fixes them
Test using an emulated mobile device (as opposed to just resizing the browser window)
=> Fixed meta tags for responsive UI behaviour

app/assets/stylesheets/application.scss, app/assets/stylesheets/school-search.scss, app/models/candidates/school_search.rb, app/views/candidates/schools/_form.html.erb, config/locales/en.yml, features/step_definitions/candidates/schools/search_steps.rb, spec/models/candidates/school_search_spec.rb
The school search form doesn't behave correctly on mobile devices
1. Extend grid system to support the functionality we require
2. Utilise grid system extensions on the School Search form
Form should resize correctly when moving between mobile, tablet and desktop form factors
=> Mobile friendly school search form

app/views/layouts/application.html.erb
The Open Graph tags are actually RDF tags, and RDF tags use <meta property=""
instead of <meta name=""
Revert to using the property attribute on the `og:image` meta tag
=> It turns out the og:image meta tag was correct.

app/notify/notify.rb, spec/notify/notify_spec.rb, spec/support/notify_email_shared_examples.rb
This error should be detectable by the calling classes and make it easy
to identify which failures should be retried. All other errors will
bubble through as before but Notifications::Client::ServerError will be
transformed into a Notify::RetryableError
=> Add RetryableError type to Notify class

script/check_timings.py
The first step involves the spinning up of chrome and initiating communication via the driver. This results in a misleading slow first step duration.
Ignore the first step duration.
Only minor script changes.
=> refining timing script

Dockerfile, app/controllers/application_controller.rb, app/controllers/pages_controller.rb, bin/check_health.sh, config/initializers/password_protection.rb, config/routes.rb
1. Health checks within Docker fail if HTTP Basic Auth is configured, because they do not include the username/password. 
2. The Auth check from Azure raises a 404 because its an undefined endpoint.
1. Use the username and password as part of the Docker internal health check
2. Add an endpoint for the Azure health check, which bypasses the username/password checks
=> Make health check password aware

app/controllers/candidates/registrations/confirmation_emails_controller.rb, app/controllers/candidates/registrations/resend_confirmation_emails_controller.rb, app/services/candidates/registrations/registration_session.rb, app/services/candidates/registrations/registration_store.rb, app/views/candidates/registrations/application_previews/show.html.erb, app/views/candidates/registrations/confirmation_emails/show.html.erb, app/views/candidates/registrations/resend_confirmation_emails/session_expired.html.erb, config/routes.rb, spec/controllers/candidates/registrations/confirmation_emails_controller_spec.rb, spec/controllers/candidates/registrations/resend_confirmation_emails_controller_spec.rb, spec/features/candidates/registrations_spec.rb, spec/services/candidates/registrations/registration_store_spec.rb, spec/support/stubbed_candidates_school_context.rb
Adds controllers for sending & resending candidate email confirmation
emails.
This pr adds the confirm your email step. `ConfirmationEmailsController#create` stores the `current_registration` in Redis and triggers the background job for sending the confirm your email notification.
Manual testing if so inclined.
Complete the wizard, expect to see `[ActiveJob] Enqueued Candidates::Registrations::SendEmailConfirmationJob ... with arguments: "m654W2ScKEpKK_Hltsm40g"` in the logs and the arguments to match the registration key in Redis.
=> Adds email confirmation step

script/cleanse
Simply enforce universal newline encoding as part of the data cleansing utility script
=> Enforce data cleansing script to use universal newlines

config/routes.rb
RobotsXXXX.txt was incorrectly identified as a healthcheck endpoint. The health check endpoint is still useful though since it bypasses the http basic auth.
Change the route to just be '/healthcheck.txt'
=> Renamed healthcheck endpoint

app/controllers/pages_controller.rb, config/routes.rb
May help with testing Peter Yates work on error pages as well
To be removed in future
Currently we have no way of verifying 500 errors are handled correctly in production
This adds an endpoint which always triggers an exception
This is intended as a temporary feature, to be removed in the future. There is a ticket filed in Jira to ensure this gets removed
=> Test page for verifying exception handling in production

app/controllers/candidates/registrations/confirmation_emails_controller.rb, app/jobs/candidates/registrations/send_email_confirmation_job.rb, config/environments/development.rb, config/environments/test.rb, spec/controllers/candidates/registrations/confirmation_emails_controller_spec.rb, spec/jobs/candidates/registrations/send_email_confirmation_job_spec.rb
Removes hardcoding the default host in initializers. We now pass it in as a parameter to the job that needs it.
Remove setting default host in initializer, pass the request's host into the job that needs it.
Everything should work as before, urls in notification emails should still be correct
=> Pass host from request rather than set in config for each env

Gemfile, Gemfile.lock
This got missed by the round up pull request of gem updates because it was set to a specific version in the Gemfile
Rather than use the dependabot PR, which changes the locked version - instead I've slackened the requirements to be anything in the 4.0 series.
=> Upgraded shoulda-matchers to official release

features/candidates/schools/search/results/pagination.feature, features/step_definitions/candidates/schools/pagination_steps.rb
In the CD environment where Cucumber runs on a different machine to the
application the overrides don't have any effect and tests fail. Just use
defaults for the moment at the expense of adding a few more test records
Revert to use default page numbers by increasing the number of records used in the features
=> Remove Kaminari overrides from Cucumber features

app/javascript/packs/application.js, package.json, yarn.lock
Currently the Stimulus controllers wont run on IE11
Add polyfills package to enable running on Stimulus
Download modern.ie image (or grab a machine with IE11), the filters and sort order toggles on the school search results page should trigger page reloads when they are changed. if they do then this is working.
=> Added polyfills packages for IE11 compat in javascript

app/controllers/candidates/registrations/placement_preferences_controller.rb, app/notify/notify_email/candidate_request_confirmation.8bd7e9b3-8c3f-4702-b642-1ccff32a264f.md, app/notify/notify_email/candidate_request_confirmation.rb, app/notify/notify_email/school_request_confirmation.dd4490f8-1d7b-455b-8502-47f57a65179a.md, app/notify/notify_email/school_request_confirmation.rb, app/services/candidates/registrations/application_preview.rb, app/services/candidates/registrations/behaviours/placement_preference.rb, app/services/candidates/registrations/placement_preference.rb, app/views/candidates/registrations/application_previews/show.html.erb, app/views/candidates/registrations/placement_preferences/_form.html.erb, config/locales/en.yml, db/migrate/20190225092622_remove_access_needs_and_access_needs_details_from_candidates_registrations_placmenet_requests.rb, db/schema.rb, features/candidates/registrations/request_school_experience_placement.feature, features/step_definitions/candidates/registrations/request_school_experience_placement_steps.rb, spec/controllers/candidates/registrations/placement_preferences_controller_spec.rb, spec/factories/candidates/registrations/registration_session_factory.rb, spec/features/candidates/registrations_spec.rb, spec/models/candidates/registrations/placement_request_spec.rb, spec/notify/notify_email/candidate_request_confirmation_spec.rb, spec/notify/notify_email/school_request_confirmation_spec.rb, spec/services/candidates/registrations/application_preview_spec.rb, spec/services/candidates/registrations/registration_as_placement_request_spec.rb, spec/support/notify_email_shared_examples.rb, spec/support/placement_preference_shared_examples.rb
Removes access needs fields across the candidate journey now they've
been taken out of the prototype.
Updates app to reflect changes in the prototype
Removes access_needs and access_needs_details
Everything should work as before but now without access needs fields
=> Remove access needs fields

app/controllers/pages_controller.rb, config/routes.rb
Reverts DFE-Digital/schools-experience#87
This will remove the temporary page for triggering exception handling on the servers
=> Revert "Test page for verifying exception handling in production"

app/javascript/controllers/grab_location_controller.js
When using the 'use my location' feature, then performing a search, followed by
navigating back to the original page, the widget ends up in an inconsistent
state.
The text fields are repopulated, the hidden fields are not.
Make the widget reinitialise itself properly on load and detect the inconsistent
state between text and hidden fields and just reset to back to unset.
Use the 'use my location' feature to select current location, perform a search. Hit 'Back' - check the field is set back to blank, rather than 'use my location'.
=> Reinitialise state in GrabLocationController js

config/environments/test.rb, spec/services/bookings/school_search_spec.rb
Setting the default cache to `:memory_store` could have some unforeseen consequences later on
Change the default to `:null_store` which will require it to be explicitly set wherever we interact with the cache in tests.
=> Set Rails' default test cache to null_store

Gemfile.lock, app/views/candidates/registrations/subject_preferences/_form.html.erb, config/locales/en.yml
Prototype now has .govuk-heading-m on the tell us your your degree subject label.
Adds .govuk-heading label, bumps form builder version so collection_selects support label_options, also adds a hint for this field.
candidates/schools/<urn>/registrations/subject_preference/new
The 'If you have or are studying for a degree, tell us your your degree subject' label should be embiggend
=> Use .govuk-heading-m for degree subject label

app/controllers/candidates/registrations_controller.rb, app/services/candidates/registrations/registration_session.rb, app/services/candidates/registrations/school_session.rb, spec/factories/candidates/registrations/registration_session_factory.rb, spec/models/candidates/registrations/placement_request_spec.rb, spec/services/candidates/registrations/registration_session_spec.rb, spec/services/candidates/registrations/school_session_spec.rb
Previously if a user performed two simulations registrations for
different schools in separate windows the first registration session
would be overwritten by the second. This commit fixes that issue by
scoping the session by school urn.
School session is not needed for registration store as the store
generates a uuid for each registration session.
We want to support a candidate registering for two (or more) schools without the details for the first school being overwritten by the later.
Scopes the registration session by school urn
Manual testing steps if desired:
Open two browser windows and complete the registration for two different schools. Once on the application preview screen reload the page in both windows, the details should remain correct (on master the details in the first …
=> Scope registration sessions by school urn

app/controllers/candidates/registrations/confirmation_emails_controller.rb, app/controllers/candidates/registrations/resend_confirmation_emails_controller.rb, app/services/candidates/registrations/registration_session.rb, app/services/candidates/registrations/registration_store.rb, spec/controllers/candidates/registrations/confirmation_emails_controller_spec.rb, spec/controllers/candidates/registrations/resend_confirmation_emails_controller_spec.rb, spec/services/candidates/registrations/registration_session_spec.rb, spec/services/candidates/registrations/registration_store_spec.rb
There was an issue with redirecting to confirmation_emails#show with the
uuid in the url such that the user could skip straight to
placement_requests/new?uuid=<uuid> without having to click the link in
the email. This PR fixes the issue by storing the uuid in the session
when redirecting to confirmation_emails#show.
The instances of RegistrationSession are now responsible for generating
a uuid rather than the RegistrationStore. The store now asks the session
for it's uuid.
We want to ensure candidates controller the email address confirmation emails are sent to.
Stores 'magiclink' uuid in the session rather than in the params.
Moves responsibility for generating the uuid to the registration session
Manual review steps if desired:
Completed candidate registration up to confirm email step. …
=> Moves magic link uuid from params to session.

app/assets/stylesheets/application-preview.scss, app/controllers/candidates/registrations/application_previews_controller.rb, app/controllers/candidates/registrations/confirmation_emails_controller.rb, app/helpers/candidates/registrations_helper.rb, app/services/candidates/registrations/privacy_policy.rb, app/views/candidates/registrations/application_previews/show.html.erb, config/locales/en.yml, spec/controllers/candidates/registrations/confirmation_emails_controller_spec.rb, spec/features/candidates/registrations_spec.rb, spec/services/candidates/registrations/privacy_policy_spec.rb
The prototype has added a checkbox for the user to confirm that they accept
the privacy policy.
Adds the accept privacy policy checkbox.
Manual testing steps: complete the candidate registration wizard, expect to need to check that you accept the privacy policy to continue.
=> Adds privacy policy acceptance checkbox

app/controllers/candidates/registrations_controller.rb, app/services/candidates/registrations/registration_session.rb, app/services/candidates/registrations/registration_session/step_not_found.rb, spec/controllers/candidates/registrations/application_previews_controller_spec.rb, spec/services/candidates/registrations/registration_session/step_not_found_spec.rb
RegistrationSession now reraises a custom exception when a step's key is
not found. We rescue this error and redirect to the appropriate step's
new action.
If the user directly navigates to the application preview screen url (or a later stage) without completing some of the previous steps the app will throw an error when trying to fetch the missing attributes.
Throw a custom exception, rescue that in the controller and redirect the user to the appropriate missing step.
Skip ahead to application preview screen, expect to be redirected to any steps you have missed.
=> Handles candidate skipping a step.

app/controllers/candidates/registrations/placement_requests_controller.rb, app/services/candidates/registrations/registration_session.rb, spec/controllers/candidates/registrations/placement_requests_controller_spec.rb, spec/services/candidates/registrations/registration_session_spec.rb
This commit prevents additional visits to the email confirmation url
form queuing placement request jobs.
If users revisited the confirm email address link in their email we would send a second placement request email to the school, which we want to avoid.
Marks the registration_session as completed on the first visit, only enqueues non completed jobs 
Manual review steps:
Complete candidate registration wizard, revisit the confirm email address url, expect additional placement request jobs not to be queued.
=> Only queue placement_request_job if not already queued

app/assets/stylesheets/placement-preference.scss
The form builder adds .govuk-input--error rather than
.govuk-textarea--error to textareas with error. However the javascript
that provides the maxwords behaviour removes .govuk-textarea--error from
textareas on page load (it adds this class when the word count is too
high and removes it once the word count is low enough). The textarea's
normal border overrules .govuk-input--error border (stylesheet is
arranged alphabetically) so we need to add this styling with heigher
specificity.
Manual testing steps: Start candidate wizard, don't enter anything in one or both of the textareas, submit the form, textareas should have a red error border.
=> Fix missing error border on textarea with errors

Gemfile, Gemfile.lock, app/services/candidates/registrations/contact_information.rb, app/views/candidates/registrations/application_previews/show.html.erb, app/views/candidates/registrations/contact_informations/_form.html.erb, config/initializers/phonelib.rb, config/locales/en.yml, spec/features/candidates/registrations_spec.rb, spec/services/candidates/registrations/contact_information_spec.rb, spec/support/placement_preference_shared_examples.rb
Some minor fixes that needed doing. 
Fixes up some validation messages, adds autocomplete attribute to address fields, adds a phone number validator.
Manual testing steps, if required:
Error messages should seem reasonable, invalid phone numbers should not be accepted on candidate contact information form, valid UK phone numbers should be accepted.
=> Se 488/se 297 candidate registration validation messages

Gemfile.lock, app/javascript/controllers/subject_preference_form_controller.js, app/services/candidates/registrations/behaviours/subject_preference.rb, app/views/candidates/registrations/subject_preferences/_form.html.erb, features/candidates/registrations/subject_preferences.feature, features/step_definitions/candidates/registrations/subject_preferences_steps.rb, spec/support/subject_preference_shared_examples.rb
If the candidate selects they don't have a degree and aren't studying for one, then we want to select 'Not applicable' for the degree subject and hide the select box (there are existing validations in case the candidate has javascript disabled)
Hide the degree subject select if no degree is selected as the degree stage.
Complete the candidate wizard up to the subject preference screen. Select no degree as degree stage  and submit the form without selecting anything else, expect there to be no validation error on degree subject. When the form rerenders expect the degree subject select to still be hidden. Chose a different degree stage, expect the degree subject select to re appear.
=> Hide degree subject if no degree selected

features/step_definitions/candidates/schools/sorting_steps.rb
The previous attempt (#151) was not successful, it failed at the same point. Upon directly-navigating to the results page by building the search string and jumping right to it, the select box for filtering isn't present on the page.
Now, instead of jumping we're filling in and submitting the search page.
Ensure it's sensible. Please chip in if you have any other suggestions for making this work in CD 😕
=> Replace direct jump to results with actual search

app/assets/stylesheets/school-search.scss, app/assets/stylesheets/stimulus/grab-location.scss, app/views/candidates/schools/_form.html.erb, features/step_definitions/candidates/schools/search_steps.rb
It has been decided to remove the 'Find What' field from the search schools page
Removed the Find What field, and changed the layout of the remaining fields to split into 3 equal columns
View the page in both mobile and desktop, and check the search still works
=> Removed 'find what' option

features/candidates/schools/search/results/sorting.feature, features/step_definitions/candidates/schools/sorting_steps.rb
Failure caused in CD by removed field still being referred to by the Cucumber tests,
Remove the reference
=> Remove reference to 'Find what?' which was removed

app/controllers/candidates/registrations/background_checks_controller.rb, app/controllers/candidates/registrations/contact_informations_controller.rb, app/controllers/candidates/registrations/placement_preferences_controller.rb, app/controllers/candidates/registrations/subject_preferences_controller.rb, app/services/candidates/registrations/registration_session.rb, features/candidates/registrations/wizard.feature, features/step_definitions/candidates/registrations/wizard_steps.rb, spec/controllers/candidates/registrations/background_checks_controller_spec.rb, spec/controllers/candidates/registrations/contact_informations_controller_spec.rb, spec/controllers/candidates/registrations/placement_preferences_controller_spec.rb, spec/controllers/candidates/registrations/subject_preferences_controller_spec.rb
We want to support candidates leaving the wizard part way through and picking up where they left off.
Populate the new forms with the information from the session. 
Manual testing steps:
Complete some steps on the candidate wizard for a school. Navigate away. Navigate back to the school's show view and restart the wizard. Expect the forms to be populated with the details you've entered so far. Complete the wizard up to the check your answers screen. Edit some answers, expect submitting the edit form to still redirect you back to the check your answers screen
=> Populate new form with session attributes

config/webpacker.yml, features/support/assets.rb, spec/rails_helper.rb
The @javascript tagged Cucumber scenarios were delayed by a couple of seconds by Webpacker compiling prior to running each one. Now the assets will be compiled once at the beginning instead.
Now we are disabling the automatic compilation in the test environment and manually performing the compile before we start both the Cucumber and RSpec suites.
The [AfterConfiguration hook](https://docs.cucumber.io/cucumber/api/#hooks) runs after support has been loaded but before any features are run. It runs only once.
=> Only compile assets at beginning of test runs

script/check_timings.py
This is intended to be a temporary change so we can view the output without having the CD build fail every time
=> Make the check timings script never fail

config/initializers/geocoder.rb
We should be using Bing Maps to geocode locations
Configure Geocoder to use bing maps when the BING_MAPS_KEY environment variable is set, otherwise fallback to using OpenStreetmap
=> Use Bing maps for geocoding look ups

azure-pipelines.yml, features/support/env.rb
Currently we have tests which are passing in CI but failing when run against a real server in CD
To improve the quality of the testing in CI we now run the Cucumber tests against Chrome in CI as well
1. Changed Smoke test to run server in servertest rails environment
2. Run Selenium tests against the smoketest webserver
3. Run Cucumber Javascript tests against remote driver when one is configured
Does CI still pass - looking for review from both Peter Yates and Peter Fry
=> Add selenium running against Chrome to the CI pipeline

config/environments/test.rb
Bullet was previously failing while running tests due to a n+1 error.
It appears that this problem was independently-resolved in e128e5e09d95
Re-enable bullet in the `test` env.
Ensure bullet is re-enabled, tests pass and n+1 issue in `Bookings::SchoolSearch` is resolved.
=> Re-enable Bullet in the test environment

Dockerfile
Gemfile is currently locked to a specific Ruby version. Either we slacken that
requirement or increase strictness of Dockerfile.
Since 2.5.4 has been released with known problems with Puma, and since 2.5.5
which fixes the issue, is not yet available in the Docker registry - I'm locking
to a specific version and taking the view that changing versions is something
which should be a code change by the developers.
=> Lock to Ruby to 2.5.3

app/javascript/controllers/grab_location_controller.js
@rjlynch pointed out that GeoLocation lookups were failing on his mobile phone. After some investigation, this only affects non-https sites and is an in built restriction in Safari.
This in turn highlighted that the code was assuming a failure to retrieve Geolocation was because the user denied the permission, hence understood what happened. This is not always the case (see non-HTTPS) so instead an alert is shown to the user in the event of failed geolocation lookup
notify the user of a failed Geolocation lookup
Test again on mobile, compare with the running copy at https://schoolexperience.education.gov.uk - that should pass because its on HTTPS
=> Flag up to the user when we cannot retrieve their location

app/models/bookings/school.rb
Current school address is stubbed to an invalid value
Allow replacing this with an Environment Variable as a temporary solution
=> Allow overriding school notifications address

app/notify/notify.rb
This allows for overriding the key used where necessary
Different environments, or local development environments may require different API keys
This allows the API key to be set from an Environment variable as per 12 Factor guidance
=> Allow setting the GovUK Notify API Key from an Env Var

app/models/candidates/school_search.rb, app/services/bookings/school_search.rb, features/candidates/schools/search/results/sorting.feature, features/step_definitions/candidates/schools/sorting_steps.rb, spec/services/bookings/school_search_spec.rb
Relevance sort is no longer needed. Fee sorting is currently awaiting refinement of Fee information
1. Remove Fee and Relevance sorting options from both RSpec and Cucumber tests
=> Drop relevance and fee sort

app/helpers/candidates/school_helper.rb, app/models/bookings/school.rb, app/models/candidates/school_stub.rb, app/views/candidates/schools/_phase1.html.erb, app/views/candidates/schools/_phase2.html.erb, demo-school.yml
Need to display the school availability on the school profile, if we have it.
Use the new method name that's backed by a db column. Otherwise fallback to 'Not specified'.
Visit a school's show page, expect to see availability information, if the school has any
=> Se 596 surface school availability on school profile

config/locales/en.yml
Currently the DBS question validation just says **Select an option**
Changed to be **Select Yes or No** which matches the options available
=> Updated error message from blank DBS question

config/initializers/filter_parameter_logging.rb
Add params from candidate contact_information controller to filter
parameters list
We don't want to store candidates personally identifiably information in the logs
Add pii attributes to the params filter
Tail the logs, submit the candidate's contact information step, expect the params to be replaced with [FILTERED] in the logs
=> Scrub pii from params

app/notify/notify_email/school_request_confirmation.3da1cb35-efd2-4aa6-8416-27efc5611d06.md, app/notify/notify_email/school_request_confirmation.rb, app/services/candidates/registrations/application_preview.rb, spec/notify/notify_email/school_request_confirmation_spec.rb, spec/support/notify_email_shared_examples.rb
Also avoid duplicate comma's in address lines
There are a couple of minor issues with the School Request Confirmation email
1. There's a duplicate 'Placement details' line
2. The information is bulleted on the Candidates email which is much clearer
3. There are duplicate comma's for blank address lines
1. Removed duplicate line
2. Added Bullets to information
3. Remove blank lines from formatted address
=> Update School-Request-Confirmation email to clarify formatting

app/views/candidates/registrations/placement_requests/show.html.erb
Footer text on the final screen, after the Candidate has confirmed their email, includes references to Sign Out, etc.
Remove these
=> Removed incorrrect footer text from final screen of Application process

app/services/candidates/registrations/placement_request_action.rb, spec/services/candidates/registrations/placement_request_action_spec.rb
We want to clear the pii from redis once we no longer need it rather than rely on redis' key expirey 
Delete the registration session from redis once we've persisted the registration information in postgres.
Monitor redis, complete the wizard, get to the placement request step, expect redis to have received del with the correct uuid. Refresh the placement request sent screen, expect to see session expired as we've removed it from redis.
=> Remove session info from redis after persisting in postgres

app/controllers/pages_controller.rb, app/helpers/back_to_top_helper.rb, app/views/layouts/application.html.erb, app/views/pages/cookies_policy.html.erb, app/views/pages/privacy_policy.html.erb
We need to display our cookie and privacy policy
Adds links to the cookie and privacy policy to the footer, adds cookie and privacy pages from the prototype.
Text should match the prototype's cookie and privacy policy pages. Layout should look ok, links to the policies in the footer should work.
=> Adds privacy policy and cookie policy pages

app/helpers/candidates/school_helper.rb, spec/helpers/candidates/school_helper_spec.rb
Not all schools have given us subject information. We currently show nothing on school index and school show pages if the school has no subjects.
So 'Not specified' if we don't have any subject information.
Visit school index page, perform a search. If a school has subjects expect to see the list of subjects, if the school has no subjects expect to see 'Not specified'. Click on 'View school details', if the schools has subjects expect to see them listed, if it doesn't expect to see 'Not specified'
=> Show "Not specified" if no school subject info available

config/environments/production.rb
We are getting unexplained `InvalidAuthenticityToken` errors on both Staging and Research sites. Working hypthesis is this is caused by flakiness in the Redis connection, which is used to hold Session data, and in turn holds the AuthenticityToken.
This scenario should result in errors being recorded in the Logs. It does not.
Further investigation of the default error handler in ActiveSupport::RedisCacheStore leads me to think there is a coding error in the default handler, where errors are only logged when there is access to the logger, but that is never set.
This explains the silent failure, and makes sense if the flaky Redis hypothesis is correct.
In order to gain further information, and aid in to solving the issue I've added a custom error for Redis connection issues, which logs …
=> Added custom error handler for Redis connection issues

azure-pipelines.yml, config/environments/production.rb, config/environments/servertest.rb
Currently URLs in Emails are http:// instead of https:// - this is because the application is actually served over http, and the TLS terminates at the proxy.
Set the force_ssl option, this will make cookies https only, and force URLs to all be HTTPS. Resulting in correct URLs in the emails.
=> Enable force_ssl

app/views/candidates/schools/_form.html.erb
We don't offer search by school type or subject
Sub heading on school search was inaccurate
Fix the sub heading text
Visit school search, expect sub heading to be correct
=> Fixes search sub heading

app/services/candidates/registrations/registration_store.rb, config/environments/production.rb, config/initializers/redis.rb
We've been encountering some dropped connections between the App and Redis.
Set a single reconnect attempt to see if this resolves the issue, this can be
incremented later if it continues to be an issue.
=> Set reconnection for RedisCacheStore and Redis.current

config/environments/production.rb, config/initializers/redis.rb
We are getting dropped connections to Redis so use Keep Alive to reduce frequency of dropped connections
Configuration is based off Redis source and the following document.
Redis gem when given an integer calculates its own keep alive socket settings,
see
https://github.com/redis/redis-rb/blob/master/lib/redis/client.rb#L477
Value of 60 seconds is chosen based off understanding of the Keep Alive values
documented at the link below
http://man7.org/linux/man-pages/man7/tcp.7.html
see
* TCP_KEEPCNT
* TCP_KEEPIDLE
* TCP_KEEPINTVL
=> Added Keep Alive settings for Redis

app/assets/stylesheets/global-styles.scss, app/views/candidates/registrations/confirmation_emails/show.html.erb
Note chose grey-1 instead of grey-2 to avoid contrast issues for users with
accessibility needs.
Easy change later if designers disagree.
=> De-emphasized resend link

features/support/env.rb
The IE functional tests currently run very slowly and different steps experience timeouts.
This might be to do with slow typing by the driver but to be honest the causes seem unclear etc.
https://stackoverflow.com/questions/27985300/selenium-webdriver-typing-very-slow-in-text-field-on-ie-browser/27985398
Implement 'require window focus' and 'ignore protected mode settings' as IE driver options.
The previous IE tests were timing out and resulted in the maximum step duration being reached (15 mins). The pass rate was as follows
```
2019-03-24T14:28:43.1174777Z 55 scenarios (18 failed, 37 passed)
2019-03-24T14:28:43.1175631Z 201 steps (17 failed, 26 skipped, 158 passed)
```
with the changes the tests complete in c. 10 mins and have close to 100% pass rate (3 failing steps)
``` …
```
=> adding IE Selenium driver options

app/controllers/pages_controller.rb, app/views/layouts/application.html.erb, config/locales/en.yml, config/routes.rb
Privacy policy link was not working on application preview page
Fixes the link
Complete the wizard up to application preview page, click the privacy policy link, expect link to take you to the privacy policy
=> fix privacy policy link on registration preview

app/services/candidates/registrations/contact_information.rb, spec/services/candidates/registrations/contact_information_spec.rb
If the candidate enters a blank phone number we were showing both the invalid and blank error messages
Only show the blank error message if the phone number is blank
Complete the candidate wizard up to entering a contact phone number, don't enter a number, submit the form, expect to only see a single validation error for phone number.
=> Only show single error if phone number is blank

app/views/candidates/registrations/subject_preferences/_form.html.erb
The subject select boxes on the candidate wizard were different widths
Fix the select boxes to be the same width
Complete the wizard up to subject preferences, the select boxes for teaching subjects should be the same width.
=> make select width consistent

app/models/bookings/school_search.rb, spec/models/bookings/school_search_spec.rb
As we're no longer using it in the front end it makes no sense for it to be represented in the service object and associated tests.
Remove the query param from `Bookings::SchoolSearch`.
The scope powering it, `.search_by_name` and `.search` remain in the FullTextSearch concern and are available to the model should they be needed again.
Ensure everything looks sensible.
=> Remove query from Bookings::School and specs

app/helpers/application_helper.rb, app/views/layouts/application.html.erb
Apostrophes in school names are being escaped in the
page title. This commit calls html_safe on the page
title, which isnt ideal, but Ive tested by adding script
tags into school names and the script isnt executed
when rendered from the title.
Open to any better suggestions on this
See above
Call html_safe in page title
Visit schools show for a school with an apostrophe in it's name, eg urn 144046, expect the page title to be displayed correctly. Update the school name to have some script tags in, expect them not to be executed.
=> Call html_safe on titles

Gemfile.lock, app/views/candidates/registrations/application_previews/show.html.erb
In order to make the edit application links more useful they should jump to the field in question rather than just the page.
Links directly to the fields
Complete the wizard up to the application preview. Click edit next to the fields, expect to be taken straight to the fields. Submit a form with errors expect the links in the summary to still take you directly to the fields.
=> Se 626 anchor links placement summary screen

app/controllers/candidates/registrations/placement_requests_controller.rb, app/jobs/candidates/registrations/send_email_confirmation_job.rb, config/routes.rb, spec/controllers/candidates/registrations/placement_requests_controller_spec.rb, spec/factories/candidates/registrations/registration_session_factory.rb, spec/features/candidates/registrations_spec.rb, spec/jobs/candidates/registrations/send_email_confirmation_job_spec.rb, spec/support/stubbed_candidates_school_context.rb
We want a shorter confirmation url
Shortens confirmation url.
Removes stubbing of redis in placement_request controller specs
Complete wizard, you should get a shorter email confirmation url, confirmation url should work as before.
=> Se 621 confirmation url

app/helpers/candidates/school_helper.rb, app/models/bookings/school_search.rb, app/models/candidates/school_search.rb, lib/servertest/geocoder.rb, spec/helpers/candidates/school_helper_spec.rb, spec/models/bookings/school_search_spec.rb
Currently we tell the user the results are for the location they typed in. In reality they are for the location Geocoder found matching the location they typed in. 
1. For clarity show the Geocoder matched location instead
=> Show matched location in Search title if available

Gemfile.lock, app/assets/stylesheets/stimulus/map.scss
Bing have made a change to their maps which breaks IE
Always show the Image map as a fall back for when the map is not showing in IE
=> Handle Javascript failure of loading map in IE

config/initializers/canonical_redirect.rb
Mistake made in development meant we were always redirecting to HTTP
Redirect to the protocol the request was made over, which should always be https in production
=> Use correct protocol when redirecting to canonical domain

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, config/environments/production.rb, config/initializers/sentry.rb
Reverts DFE-Digital/schools-experience#228
Currently Sentry is swallowing our exceptions and the developers don't all have access to Sentry.
Reverting this until we understand the interaction between this and ExceptionNotifier better.
=> Revert "Add Sentry"

config/environments/production.rb
We want urls we send in notifications to use https
Use https in urls sent in notifications
Start the app in production env, expect urls sent in notification to use https
=> Set protocol to https for urls in production

jmeter/schoolexperience.jmx
A load test was developed which ran within the JMeter GUI. Though this is useful, it does mean that the tool needs to be installed, interested parties need to understand how to run tests etc.
A build job has been developed which executes the tests using this script from the command line. 
Adding the load test script.
View the build job.
=> adding load test jmeter file

app/models/bookings/school.rb, db/migrate/20190326112400_make_bookings_schools_contact_email_not_null.rb, db/schema.rb, spec/factories/bookings/school_factory.rb, spec/models/bookings/school_spec.rb
There was no email validation, now there is
Add email format validation to the `Bookings::School` model. Format check uses the regexp provided by `URI::MailTo::EMAIL_REGEXP`.
Ensure it looks sensible and tests make sense. We could simplify this by _just_ checking for a single `@` etc but the supplied regexp looks suitable to me.
=> Add validation for contact_email field

app/services/candidates/registrations/contact_information.rb, config/locales/en.yml, spec/services/candidates/registrations/contact_information_spec.rb
Over looked validating format of candidate emails 🤦‍♂️, as the input field's type is email and the form wont submit if it's incorrect but we want this for completion.
Add validation of candidate email
Should look correct
=> Validate format of candidate email

app/controllers/candidates/registrations/resend_confirmation_emails_controller.rb, spec/controllers/candidates/registrations/resend_confirmation_emails_controller_spec.rb
Fixes a bug where a user could click resend confirmation email after
they had completed the wizard and been purged from redis, causing the
background job to error when attempting to retrieve the session from
redis.
This issue was caused due to the user's session not refelecting the
state in redis.
Fix: We need to fetch the the registration session from redis in the
controller and handle any errors there, rendering the session expired
template.
Test: Complete the wizard, keeping the resend confirmation email page
open. After having confirmed your email click resend confirmation email,
expect to show session expired page.
=> Don't attempt to resend emails if reg completed

app/services/candidates/registrations/behaviours/subject_preference.rb, spec/controllers/candidates/registrations/subject_preferences_controller_spec.rb, spec/features/candidates/registrations_spec.rb, spec/support/stubbed_candidates_school_context.rb, spec/support/subject_preference_shared_examples.rb
Populate subject choice with schools subjects if it has any
If the school has provided us with a list of subjects during enrichment
we'll show that list, if the school has not we'll default to showing all
available subjects.
Testing:
Find a school which has it's own subjects, eg urn 142541,
complete the wizard up to the "We need some more details" screen
expect the list of subjects in the what subject do you want to teach selects to
match the schools' subject.
Find a school which has no subjects, eg urn 138304,
complete the wizard up to the "We need some more details" screen
expect the list of subjects in the what subject do you want to teach selects to
show all subjects.
=> Se 760 subject choice limiting

azure-pipelines.yml
We need to be able to distinguish docker images built from different branches. This can be accomplished by including the branch in the tag.
Use an image tag which follows the pattern:
v123 - on master
v123-phase2 - on the phase2 branch.
Another merge request will be raised to get this onto master.
Can you double check the use of 'refs/heads/phase2' - that is correct?
=> include branch in tag

app/models/concerns/geographic_search.rb, spec/models/concerns/geographic_search_spec.rb
When distance param is supplied in the URL but has no value (eg
`&longitude=&distance`) Rails was passing nil into the scope
explicitely, causing it not to revert to the default value set in the
database.
Now there is a `DEFAULT_RADIUS` constant defined in the module to ensure a
value is present
=> Fix crash caused by missing distance param

azure-pipelines.yml
After merge realised that the Docker build on the phase 2 branch without the cache wasn't taking place
Condition broadened to be an or statement on the branch name (master or phase2) for the build without cache.
Should be clear from the minor diff.
=> need to build on phase2 branch as well!

app/views/layouts/application.html.erb
Page title should only have the first letter of Get school experience capitalised
Changed capitalisation
=> Fixed case of page titles

jmeter/schoolexperience.jmx
It seems there are command length or parsing issues with the Azure DevOps BASH tool.
Reduce the character lengths of the jmeter variable names.
The branch has been used on the 'Functional Tests' build pipeline (see the checks passing which includes a reference to this job).
=> shortening variable names

app/views/candidates/school_searches/new.html.erb
There is a blank 'distance' option in the drop down of available distances.
This doesn't make sense from a UI stand point and is problematic from a
technical standpoint.
Remove the 'distance' option from the drop down
Does it still work
=> Remove the blank 'distance' value from search form

app/javascript/controllers/grab_location_controller.js
Whilst Internet Explorer implements the navigator.geolocation feature. It
doesn't implement it fully, missing the 'failed to get location' callback.
This means if the user disables the prompt, then we never receive a message to
say the browser has stopped searching for the location.
Since the feature is an optional enhancement, IE only partially implements this
feature, and the use case for supporting it under IE is very niche, I am
instead just disabling the feature under Internet Explorer.
1. Don't show 'find my location' on IE
Test both IE and Edge in VMs
1. both are in the Win10 + Edge VM on modern.ie
2. puma on your own computer probably needs starting with --binding=0.0.0.0
3. local computer can be accessed from within the VM at http://10.0.2.2:3000/
=> Disabled the find-my-location field on Internet Explorer

lib/data/school_enhancer.rb
Re-running the enrichment/enhancement task is problematic if schools re-define their subjects
Now new subjects are only added if they aren't already present.
Ensure it looks sane.
=> Only try to add subjects if they don't exist

Gemfile, Gemfile.lock, app/services/candidates/registrations/contact_information.rb, config/locales/en.yml, spec/services/candidates/registrations/contact_information_spec.rb
Adds postcode validation to candidates contact information
Complete the wizard up to the candidate contact information step. Expect only to be able to supply valid postcodes
REGEX taken from top answer here: https://stackoverflow.com/questions/164979/uk-postcode-regex-comprehensive
=> Adds postcode validation to candidate wizard

features/support/env.rb
Currently we don't register the Safari browser.
Registering the Safari browser.
Have confirmed that this allows testing to occur but full validation can only occur after this merge.
=> register safari browser

config/environments/production.rb
In order to test DFE Sign-in in our research environment (and eventually deploy it) we need to provide the secret via an environment variable
If `config.x.phase_two` is `enabled` allow the OIDC settings to be applied. In `development` and `test` envs these are hard-coded (and the secret is loaded from the credentials file) but we want a bit more flexibility in `production`
The four environment variables are called:
* `DFE_SIGNIN_BASE_URL`
* `DFE_SIGNIN_CLIENT_ID`
* `DFE_SIGNIN_HOST`
* `DFE_SIGNIN_SECRET`
Defaults are provided for all **except** `DFE_SIGNIN_SECRET`, if this is absent the application will fail to boot.
Ensure everything looks sensible
=> Add DFE Sign-in config for production

app/controllers/schools/on_boarding/on_boardings_controller.rb, app/controllers/schools/on_boarding/profiles_controller.rb, app/models/schools/school_profile.rb, app/presenters/schools/on_boarding/school_profile_presenter.rb, app/views/schools/on_boarding/profiles/show.html.erb, features/schools/admin_contact.feature, features/schools/school_profile.feature, features/step_definitions/schools/shared_steps.rb, spec/factories/schools/on_boarding/candidate_experience_detail_factory.rb, spec/factories/schools/school_profile_factory.rb, spec/models/schools/school_profile_spec.rb, spec/presenters/schools/on_boarding/school_profile_presenter_spec.rb
Adds the school profile show page, still need to polish the show page to handle capitalising the sentences etc but that will be added when implementing fred's changes to the prototype
Should seem sensible, should be able to complete the wizard and see the profile overview at the end
=> Adds school profile show screen from prototype

app/views/schools/on_boarding/experience_outlines/_form.html.erb
Users might be confused by the url field requiring the protocol
=> adds placeholder url

azure-pipelines.yml
CI is broken for Phase2
1. Bring master and Phase2 inline
2. Avoid dynamic variable assignment
3. Tag Docker Images accordingly to BuildNumber instead of BuildId
Note: This PR is to sort conflicts when merging the `bugfix/ci-build-number` branch into `phase2
=> Fix CI for Phase2

azure-pipelines.yml
CI is broken for Phase2
1. Bring master and Phase2 inline
2. Avoid dynamic variable assignment
3. Tag Docker Images accordingly to BuildNumber instead of BuildId
=> Fix CI Builds

azure-pipelines.yml
We're going to be changing the CI build pipeline but it turns out using BuildID wont actually cause 
problems since thats consistent across the whole project.
This will reduce changes needed to the CD pipeline
1. Swap back from BuildNumber to BuildId
=> Swapped back to BuildId

app/forms/schools/on_boarding/candidate_experience_detail.rb
Want to make sure parking_provided is false and not nil before
validating nearby_parking_details. nearby_parking_details is hidden
behind a conditional reveal so the error isn't shown to the user unless
they have selected an option from the parking_provided radio buttons
=> Don't validate nearby_parking_details unless parking option selected

Gemfile.lock, app/views/schools/on_boarding/profiles/show.html.erb
We're using `f.check_box_input` outside of `check_box_fieldset` as we
don't want a legened for this check box. This caused us not to generate
the correct id for the containing form group div that the error message
links to.
To fix this we need to call `form_group_id` to set the id for the
containing form_group.
This PR bumps the form builder version which makes `form_group_id`
a public method.
=> Fixes error message anchor on schools profile show

azure-pipelines.yml
we are getting the `-phase2` appended twice to docker images
Removed duplicate tag assignment for phase2 branch
=> Removed duplicate tag assignment for phase2 branch

app/forms/schools/on_boarding/candidate_experience_detail.rb, config/locales/en.yml, spec/forms/schools/on_boarding/candidate_experience_detail_spec.rb
This isn't really an ideal solution, but it's straightforward and
flexible. It is possible for invalid times to be entered, like 25:00
It's lower impact than going down the `type='time'` route for the time
being, thanks to some browsers requiring polyfills.
Fixes [SE-870](https://dfedigital.atlassian.net/browse/SE-870)
=> Validate school start and end times

azure-pipelines.yml, features/step_definitions/candidates/landing_page_steps.rb, features/step_definitions/candidates/schools/results_steps.rb, features/step_definitions/candidates/schools/sorting_steps.rb, features/support/env.rb, features/support/feature_helper.rb
Currently we have sleep statements within the Cucumber Tests. This enable the tests to pass on IE and FF in CD but take CI runs from approx 10 minutes to approx 30 minutes.
This can be optimised by only using the delay in the CD. This change allows manually overriding the page delay time (including to a delay of 0), and only delays if CUC_DRIVER is set to something.
Are the tests still running correctly. Have the sped up
=> Speed up cucumber

features/support/feature_helper.rb
Currently tests fail in CD. This is caused by incorrect code for reading the default CUC_PAGE_DELAY value.
1. Fix reading CUC_PAGE_DELAY with a default
=> Fix page delay when CUC_DRIVER set but CUC_PAGE_DELAY not set

app/views/schools/on_boarding/profiles/show.html.erb
Removes links to edit the school's name, email, and address from
schools/on_boarding/profile#show as we don't have the corresponding pages in
the prototype.
=> Removes link to edit school from school profile show

app/forms/schools/on_boarding/candidate_requirement.rb, app/models/schools/school_profile.rb, app/services/candidates/registrations/behaviours/placement_preference.rb, app/validators/number_of_words_validator.rb, app/views/schools/on_boarding/candidate_requirements/_form.html.erb, config/locales/en.yml, spec/forms/schools/on_boarding/candidate_requirement_spec.rb, spec/validators/number_of_words_validator_spec.rb
Need to validate number of words on schools/on_boarding/candidate_requirement#dbs_policy is less than 50
Extracts number_of_words validation from candidate/registrations/placement_preference to validator.
Uses validator for dbs_policy.
Adds text_area_with_maxwords to dbs_policy field.
Also removes bookings_school dependent: :destroy from school_profile as we probably don't want to delete the school if the profile is deleted.
=> Se 847/schools/on boarding/word limit validation

app/controllers/schools/on_boarding/confirmations_controller.rb, app/models/bookings/profile.rb, app/models/bookings/profile_attributes_convertor.rb, app/models/bookings/profile_publisher.rb, app/models/bookings/school.rb, db/migrate/20190424145543_create_bookings_profiles.rb, db/schema.rb, spec/controllers/schools/on_boarding/confirmations_controller_spec.rb, spec/factories/bookings/profile_factory.rb, spec/models/bookings/profile_attributes_convertor_spec.rb, spec/models/bookings/profile_publisher_spec.rb, spec/models/bookings/profile_spec.rb, spec/models/bookings/school_spec.rb
Currently we have a Profile in the Schools namespace. This can be edited by the School Administrator though, and my represent a 'work in progress' whilst the Profile shown to Candidates should be the last complete version
1. Add a second Profile model which is the one shown to the Candidates as part of the search.
2. Create or update the new Bookings::Profile as part when the user confirms the updates to their Profile held within the Schools namespace
1. There is currently no output of the Profile but it can be viewed within the rails console
=> Create a Bookings::Profile when completing a Schools::SchoolProfile

app/models/bookings/profile.rb, db/migrate/20190502084101_make_bookings_profile_school_id_unique.rb, db/schema.rb, spec/models/bookings/profile_spec.rb
We shouldn't allow more than 1 profile per school
1. Add a uniqueness index on the `bookings_profiles.school_id` column
2. Add a uniqueness validate on the column in the ActiveRecord model
=> Add unique index on profile school

app/views/schools/dashboards/show.html.erb, config/environments/development.rb, config/environments/production.rb, config/environments/servertest.rb, config/environments/test.rb, config/routes.rb
We need to feature flag certain features so that the can be merged without being exposed to the public until we are ready to release a given phase
Change from `config.x.phase_two.enabled` as a boolean, to be `config.x.phase` as an integer.
This means we can also target functionality to a specific phase, or a given phase and below.
This initially targets the `phase2` branch so has been set to default to phase 2
releases onwards.
This uses the PHASE environment variable, ie PHASE=3, to choose the phase.
It is also compatible with the old PHASE_TWO=true environment variable.
Does it work, does it make sense
=> Added feature flagging for multiple phases

app/forms/schools/on_boarding/school_fee.rb, config/locales/en.yml, spec/support/schools/on_boarding/school_fee_shared_examples.rb
Bug: SE-848 
Currently the School Administrator can enter a fee of 0 for the DBS/Admin/Other Fee - in this scenario they should instead be marking that a Fee is not required rather than entering a zero fee.
Require the Fee to be greater than 0, instead of greater than or equal to 0
=> Require an amount greater than zero for the School Fees

app/controllers/candidates/schools_controller.rb, app/models/bookings/school_search.rb, app/models/candidates/school_search.rb, app/views/candidates/school_searches/new.html.erb, config/locales/en.yml, features/candidates/schools/search/search.feature, features/step_definitions/candidates/schools/search_steps.rb, features/step_definitions/common_steps.rb, features/step_definitions/form_steps.rb, spec/models/bookings/school_search_spec.rb, spec/models/candidates/school_search_spec.rb
Geocoder searches previously weren't limited by region and returned
worldwide results. This is now limited to the `region: 'gb'`.
When Bing returned results we only use the first one, now the query is
limited so that Bing will only return one - this is more efficient from
both a network and cache point of view.
Finally, ensure location search strings are at least 3 characters long.
This is verified at the browser level via `minlength` and in Rails'
validation.
=> Limit Geocoder to GB, validate search location

db/migrate/20190503120209_rename_phases.rb
In CD the migrations are run from scratch against an empty database and
this migration uses `.find_by!` meaning it will fail when the records
it's looking for are absent.
Normally, in environments that have been seeded (ie in prod) this would
be the correct behaviour but it fails in CD, so we'll make it less fussy
and manually check that it's been successful afterwards...
Change `.find_by!` to `.find_by` and add safe navigation to the following `.update`.
Make sure it'll work in CD
=> Make find_by not blow up when record absent

app/models/bookings/profile_attributes_convertor.rb, app/models/bookings/profile_publisher.rb, spec/factories/bookings/phase_factory.rb, spec/factories/bookings/school_factory.rb, spec/models/bookings/profile_attributes_convertor_spec.rb, spec/models/bookings/profile_publisher_spec.rb, spec/support/with_phases.rb
Currently we don't set the subjects or phases on the Bookings::School model when publishing a profile
1. Copy the Subject Ids from Schools::SchoolProfile to Bookings::School
2. Map the Phases from the columns on Schools::SchoolProfile to Bookings::School#phase_ids
I've left the mostly redundant phases columns on the Bookings::Profile table
This is because they are currently used as part of the validation on that model. The mapping needs removing and the difference between schools and candidates refactoring at a future point anyway.
=> SE-929 Copy subjects keystages and phases between profiles

azure-pipelines.yml
Currently we are spending 20 to 30 mins on cucumber runs against Chrome and
Firefox. The application runs without JS in almost all cases, so running against
a real web browser is not needed for every branch build and this will
significantly speed up a majority of CI runs.
Only run cucumber against Firefox and Chrome on `master` and `phase2` branches
Is this a good idea?
=> Only run Cucumber against Chrome and Firefox on master

script/check_timings.py
Currently we don't print out detailed timings information for Cucumber scripts which will help in analysing why they take so long.
Print detailed timing information (note the usage format is not detailed enough).
Note that the mount using the `-v` flag must be fully qualified and changed to something that is correct on your machine (it currently references my home directory)
docker-compose -f docker-compose-selenium.yml up
docker-compose run --rm -e RAILS_ENV=test -e SELENIUM_HUB_HOSTNAME=selenium-chrome -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true -e APP_URL='http://school-experience:3000' -v /Users/peterfry/projects/schools-experience/reports:/app/reports school-experience cucumber  --format json --out reports/cucumber-chrome.json
python script/check_timings.py …
=> improve timings script

app/models/bookings/school_search.rb, spec/models/bookings/school_search_spec.rb
This was more of an exploratory look into improving searches and isn't yet tied to a ticket.
Limiting searches to GB (#387) doesn't appear to have been _entirely_ successful.
The Bing API [makes it appear that setting the region to `UK` or `GB` should limit the searches to those areas respectively](https://docs.microsoft.com/en-us/bingmaps/rest-services/locations/find-a-location-by-address), and Geocoder [should pass the param through to the search API](https://github.com/alexreisner/geocoder/blob/master/lib/geocoder/lookups/bing.rb#L23). However, we still appear to get results from further afield back.
Rather than try specifying country codes that aren't really suitable for our (England-only) service, we can _ensure_ results are limited to England by adding ", England" onto the search …
=> Limit searches to England rather than GB

app/views/schools/errors/not_registered/show.html.erb, features/schools/errors/not_registered.feature, features/step_definitions/common_steps.rb, features/support/path_helper.rb
Users reach a dead end if they pick a school not registered with our service
Add a 'Change school' link to the error page
Ensure it looks sensible. It's the exact same path used by the corresponding link used on the dashlette and works in exactly the same manner.
=> Add instructions and change school link to 'not registered' error

app/services/candidates/registrations/placement_request_action.rb, spec/services/candidates/registrations/placement_request_action_spec.rb
Schools are asked to supply a contact address as part of their onboarding process. This should be used to send the Placement Request email to.
Use this address if it has been supplied
=> Use the email address from a Schools profile if they have one

app/controllers/schools/base_controller.rb, app/helpers/application_helper.rb, app/views/layouts/application.html.erb, features/candidates/landing_page.feature, features/candidates/splash_page.feature, features/schools/dashboard.feature, features/step_definitions/common_steps.rb
The schools' half of the application is known as 'Manage school experience' but the heading on the site currently is always 'Get school experience'.
Make the header default to 'Get school experience' but override it in `Schools::BaseController` so it'll be 'Manage School Experience'.
Ensure it works and the change is made in a sensible manner. I was thinking about using `content_for` like we do elsewhere but that doesn't look accessible from controllers 🤷🏽‍♂️
=> Allow override of main site header

config/routes.rb
Phase 3 work should be inaccessible to users, not just unlinked
Moved the routes behind a feature flag
Note: Used an `if` on the end of the block to avoid future merge issues as a result of
indentation.
=> Hide placement request functionality behind a feature flag

db/migrate/20190510173936_allow_null_for_bookings_profiles_experience_details.rb, db/schema.rb
We’ve removed the validation on ExperienceOutline#candidate_experience
(to allow admins to complete this at a later date) but we still have a
not null constraint on Bookings::Profile#experience_details which this
field is mapped to by Bookings::ProfileAttributesConvertor.
=> Removes not null constraint on experience_details

app/views/candidates/registrations/placement_preferences/_form.html.erb, config/locales/en.yml, features/candidates/registrations/request_school_experience_placement/schools_with_specified_placement_dates.feature, features/step_definitions/form_steps.rb
Some placeholder text containing a `FIXME` was left in 🤦🏽‍♂️
Replace it with a useful hint
Ensure text change looks sensible
=> Replace FIXME placeholder with useful hint

app/controllers/schools/errors/auth_failed_controller.rb, app/controllers/schools/sessions_controller.rb, app/views/schools/errors/auth_failed/show.html.erb, config/routes.rb, spec/controllers/schools/sessions_controller_spec.rb
Login attempts that didn't go to plan (ie if a user reset their password mid-way through) resulted in them seeing an error page and hitting a dead end.
Add `AuthFailedError` and `StateMissmatchError` classes and the `AuthFailedController`, which shows a more human-friendly error message. It contains details of who to contact if the problem persists.
Ensure changes look sensible
=> Add a more-generic login error page

app/services/candidates/registrations/application_preview.rb, app/views/candidates/registrations/application_previews/show.html.erb
Reference the type of placement date used for the registration rather
than the school'c current placement date type to avoid state mismatch
issue.
=> Fix bug where school updates dates as candidate views reg

app/models/bookings/placement_date.rb, spec/factories/bookings/placement_dates.rb, spec/models/bookings/placement_date_spec.rb
There was no validation (other than presence) on `Bookings::PlacementDate#date`.
On new records, ensure `date` is in the future. Still allow older records to be modified, they shouldn't just become invalid when they expire
Ensure changes make sense
=> Add validation on placement date dates

azure-pipelines.yml
Currently we use the phase2 image as a build cache - the biggest speedup is the caching of Gems and the cache will stop being effective the first point we do a gem update on master.
Use `master` (:latest tag in Docker) as the cache base instead
=> Use :latest instead of :phase2 image for build cache

spec/controllers/candidates/registrations/application_previews_controller_spec.rb, spec/controllers/candidates/registrations/background_checks_controller_spec.rb, spec/controllers/candidates/registrations/confirmation_emails_controller_spec.rb, spec/controllers/candidates/registrations/contact_informations_controller_spec.rb, spec/controllers/candidates/registrations/placement_preferences_controller_spec.rb, spec/controllers/candidates/registrations/resend_confirmation_emails_controller_spec.rb, spec/controllers/candidates/registrations/subject_preferences_controller_spec.rb, spec/factories/candidates/registrations/background_check_factory.rb, spec/factories/candidates/registrations/placement_preference_factory.rb, spec/factories/candidates/registrations/registration_session_factory.rb, spec/factories/candidates/registrations/subject_preference_factory.rb, spec/services/candidates/registrations/registration_store_spec.rb, spec/support/eq_model_matcher.rb, spec/support/stubbed_current_registration.rb
Refactors candidate registrations specs to remove doubles and stubbing
to better test integration.
As part of refactoring the candidate registration wizard to remove the duplicated school fetching I needed to refactor some tests. I thought I might as well fix up all the controller tests to remove the doubles and stubbing and follow the same test pattern as the schools on boarding controller specs.
Removes doubles and stubbing. Follow same controller pattern as in schools on boarding.
Not app code changes, only specs
This is a low priority PR so probably best reviewing something more pressing!
=> refactors candidate registration specs

Dockerfile, Gemfile, Gemfile.lock
The timeout is currently set really quite long but its only to handle
exceptional delays for now, we can bring it down to something more reasonable
later on.
1. Add Rack Timeout to cancel requests which overrun the timeout. Defaults to 120 seconds when run from within Docker Container. Controllable via Env Var - RACK_TIMEOUT_SERVICE_TIMEOUT
=> Added Rack Timeout

app/services/candidates/registrations/application_preview.rb, app/services/candidates/registrations/registration_session.rb, app/services/candidates/registrations/school_session.rb, spec/factories/candidates/registrations/registration_session_factory.rb, spec/services/candidates/registrations/application_preview_spec.rb, spec/services/candidates/registrations/school_session_spec.rb
RegistrationSession shouldn't be delegating `school` to it's
subject_ preference. Instead pass a urn into the registration session
when it's initialized, use this to find the correct school.
Now we have two steps in the candidate registration wizard that require a school (subject_preference and placement_preference) the knowledge of how to get the school is duplicated. This is the first step in moving that out of the steps and up into the registration session.
Add a school and urn method to the registrations session.
Refactor some specs to use factories.
Should look sensible.
Code is backwards compatible with existing `registration_sessions` as we merge the urn into the registration_session when we fetch it.
=> Add school to registration_session

features/support/database_cleaner.rb
Currently we do not have an understanding of the overhead of using the database cleaner. It would be useful to understand when it is interacting with the database and how long certain operations are taking.
Adding an environment variable to toggle on and off the use of a STDOUT logger as the logger for Active Record.
ActiveRecord::Base.logger = Logger.new(STDOUT)
Checkout this branch and do a docker build
docker build -f Dockerfile -t school-experience:latest .
Then to check current behaviour is unchanged 
docker-compose run --rm -e RAILS_ENV=test -e SELENIUM_HUB_HOSTNAME=selenium-chrome -e DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL=true -e APP_URL='http://school-experience:3000' school-experience cucumber
Then to enable logging
docker-compose run --rm -e RAILS_ENV=test -e …
=> adding debug option for database cleaner

Gemfile, Gemfile.lock, lib/apimock/gitis_crm.rb, lib/tasks/external_specs.rake, spec_external/gitis_crm_spec.rb
Gitis CRM has a complex schema and permissions model. We need some means of verifying we have appropriate access to their API, and the Schema still matches our expectations.
1. Add a separate test suite for external apis
1. Adds `rails spec:external` to run all api tests
2. Adds `rails spec:external:read` to run api tests which don't modify external services
3. Adds `rails spec:external:write` to run api tests which **do** modify external services
2. Adds some helpers to mock out CRM api requests - this is intended for use as part of future CRM work but was developed tested against the new test suite in (1).
At this point its really just code checking - I can share credentials for running the read only parts if required.
=> GiTiS CRM test suite

config/initializers/application_insights.rb
Rename the instrumentation key variable to match documentation
=> Rename App Insights Instrumentation Key variable

azure-pipelines.yml
The technology guidance has been updated to recommend the use of Docker Hub.
As part of the migration the initial step is to add a push to the new Docker Hub repository.
Once this is merged then the CD Dev stage will be updated use the Docker Hub repository. Once this step is complete then the CI pipeline variables will be updated to refer to the Docker Hub repository and the additional push will be deleted.
The phase2 two elements to the pipeline have been removed.
Three new variables have been added to the CI pipeline definition in the Azure DevOps GUI  (imageName, DOCKER_HUB_CONNECTION_NAME, DOCKER_HUB_REPO). 
This has been tested by temporarily changing the conditions on the docker push tasks to the branch which is being merged.
=> tagging and pushing to Docker Hub

app/forms/schools/on_boarding/candidate_experience_detail.rb, spec/forms/schools/on_boarding/candidate_experience_detail_spec.rb
Schools want to express time as 11.15am instead of 11:15am 🤷🏽‍♂️
Relax the regular expression accordingly
Make sure it looks ok
=> Allow schools to enter times with point delimiter

app/notify/notify_email/candidate_request_cancellation.12370ef4-5146-4732-87c9-76f852b4bfa9.md, app/notify/notify_email/candidate_request_cancellation.rb, app/notify/notify_email/school_request_cancellation.1d2b44bc-9d73-4839-b06b-41f35012c14d.md, app/notify/notify_email/school_request_cancellation.rb, spec/notify/notify_email/candidate_request_cancellation_spec.rb, spec/notify/notify_email/school_request_cancellation_spec.rb
Placement requests don't have the concept of a start and end date so
this has been replaced with availability in the emails. Also added
additional information to the school's notification so they can more
easily identify which request has been cancelled.
No code is currently using these emails at the minute
=> Update placement request cancellation emails

Gemfile, Gemfile.lock, bin/rspec
Repeated runs of tests boot the entire application each time. I'm used to this being fairly quick in minitest, rspec is noticeably slower. I'm currently doing lots of fiddly test runs as part of the CRM work.
1. Enable spring for rspec
Spring is only used when running `bin/rspec` but not `rspec` outside of the binstub, allowing those who dislike spring it to bypass it.
=> Added Spring RSpec integration to speed up repeated test runs

app/javascript/controllers/map_controller.js
Scrolling on the school profile page occasionally causes accidental map zooming
This option prevents the map from zooming in and out inadvertently when
scrolling up and down the page. Plus and minus buttons are still visible
to facilitate zooming
https://docs.microsoft.com/en-us/bingmaps/v8-web-control/map-control-api/mapoptions-object
Ensure changes fix the problem
=> Add disableScrollWheelZoom option for maps

config/initializers/phonelib.rb, spec/forms/schools/on_boarding/admin_contact_spec.rb
During research we observed users entering their phone number and
“ext 451” into the same field; this is their extension within the
school.
Add 'ext' and 'extension' to the list of supported extension symbols.
';' and '#' are the default extension separators.
=> Support additional extension options

app/views/schools/on_boarding/admin_contacts/_form.html.erb, config/locales/en.yml
The error message summary at the top of the page wasn't descriptive of
which fields had validation errors
New error messages should seem sensible
=> Improve school onboarding validation messages

app/controllers/candidates/registrations/placement_requests_controller.rb, app/controllers/candidates/school_searches_controller.rb, app/controllers/candidates/schools_controller.rb, app/controllers/concerns/analytics_tracking.rb, app/jobs/candidates/registrations/placement_request_job.rb, app/models/bookings/placement_request.rb, app/models/candidates/school_search.rb, app/services/candidates/registrations/placement_request_action.rb, db/migrate/20190524103626_add_tracking_uuid_to_bookings_school_searches.rb, db/schema.rb, spec/controllers/candidates/registrations/placement_requests_controller_spec.rb, spec/controllers/candidates/schools_controller_spec.rb, spec/jobs/candidates/registrations/placement_request_job_spec.rb, spec/models/bookings/placement_request_spec.rb, spec/services/candidates/registrations/placement_request_action_spec.rb
Currently we are unable to link searches to requests in our analytics as there is no common data shared between the two aspects of the app. This makes producing certain kinds of reports much more diffcult for @onah-noelyn 
Introduce a concern, `AnalyticsTracking` included by the `Candidates::SchoolSearchesController` and `Candidates::SchoolsController` that, if one isn't already set, adds an `analytics_tracking_uuid` to the session. It is stored with every search.
If that value is still present in the session when the actual placement request is made, it is stored in the `Bookings::PlacementRequest`.
These two `uuid` values can then be matched either in the analytics layer or prior to that (as part of the [analytics preparation](https://github.com/DFE-Digital/analytics-preparation) …
=> Link searches and placement requests for analytics SE-1012

app/helpers/candidates/results_helper.rb, app/models/bookings/school_search.rb, app/models/candidates/school_search.rb, app/models/concerns/geographic_search.rb, spec/helpers/candidates/results_helper_spec.rb, spec/models/bookings/school_search_spec.rb, spec/models/candidates/school_search_spec.rb
Previously if we couldn't find a point to search around (either via
Geocoder or 'Use my current location') the `.close_to` scope would call
`.call` and all schools that matched the other criteria would be
returned.
Now, if we have no point to search around, we call `.none` instead and
return zero results.
Ensure everything works as expected
=> Make geo search unchainable when point absent

app/views/schools/on_boarding/_school_fees_shared_form.html.erb, app/views/schools/on_boarding/admin_contacts/_form.html.erb, app/views/schools/on_boarding/availability_descriptions/_form.html.erb, app/views/schools/on_boarding/candidate_experience_details/_form.html.erb, app/views/schools/on_boarding/candidate_requirements/_form.html.erb, app/views/schools/on_boarding/dbs_fees/new.html.erb, app/views/schools/on_boarding/descriptions/_form.html.erb, app/views/schools/on_boarding/experience_outlines/_form.html.erb, app/views/schools/on_boarding/fees/_form.html.erb, app/views/schools/on_boarding/key_stage_lists/_form.html.erb, app/views/schools/on_boarding/phases_lists/_form.html.erb, app/views/schools/on_boarding/profiles/show.html.erb, app/views/schools/on_boarding/subjects/_form.html.erb, features/schools/onboarding/admin_contact.feature, features/schools/onboarding/administration_fee.feature, features/schools/onboarding/availability_description.feature, features/schools/onboarding/candidate_experience_detail.feature, features/schools/onboarding/candidate_requirements.feature, features/schools/onboarding/dbs_fee.feature, features/schools/onboarding/descriptions.feature, features/schools/onboarding/experience_outline.feature, features/schools/onboarding/fees.feature, features/schools/onboarding/other_fee.feature, features/schools/onboarding/phases.feature, features/schools/onboarding/school_profile.feature, features/schools/onboarding/secondary_subjects.feature
The school onboarding pages were difficult to identify in Analytics because they didn't have a page title.
Set the page titles for all onboarding pages, for the time being set it to the same value as appears in the breadcrumbs
Make sure everything looks ok.
=> Add titles to the school onboarding pages

app/assets/stylesheets/application.scss, app/assets/stylesheets/school-profile.scss, app/views/candidates/schools/_phase1.html.erb, app/views/candidates/schools/_phase2.html.erb, spec/views/candidates/schools/show.html.erb_spec.rb
The start button should always be at the bottom of the school profile page
Ensure the start request is always at the bottom using media queries. There are actually two buttons but one will always be hidden
Ensure it works! It looks like it does
=> Ensure start button is at bottom of school profile

config/initializers/canonical_redirect.rb, spec/requests/canonical_url_redirection_spec.rb
SEP are redirecting to our service from multiple domains.
Instead of allowing a single one (in `OLD_SEP_DOMAIN`) this change allows multiple separated by commas. The environment variable has been renamed to `OLD_SEP_DOMAINS` to reflect this, but it will still work with just one
This'll need some changes to our live config, best to be checked by @petenorth
=> Allow for multiple OLD_SEP_DOMAIN redirects

app/controllers/schools/placement_dates_controller.rb, app/views/schools/placement_dates/_form.html.erb, app/views/schools/placement_dates/edit.html.erb, app/views/schools/placement_dates/new.html.erb, features/schools/placement_dates/edit.feature, features/step_definitions/form_steps.rb, features/step_definitions/schools/placement_dates/edit_steps.rb, features/step_definitions/schools/placement_dates/new_steps.rb
Date validation for placement dates (that they're in the future) only occurs on create. When editing, school admins could set them in the past which would mean they'd expire and disappear
Remove the ability to edit placement dates. This will make the process simpler and schools have the opportunity to prevent unwanted dates from appearing by disabling them
Ensure it looks fine and works
=> Remove date changing from placement date edit

config/initializers/application_insights.rb
It would be nice to have the Javascript tracking enabled via Application Insights as we will be able to get more context information.
Toggle the Javascript tracking Application Insights initialiser via an environment variable.
Toggle on and off via APPINSIGHTS_JAVASCRIPT_ENABLED environment variable
=> adding configurable support for Application Insights Javascript tracking

Gemfile, Gemfile.lock
The current published version is 0.5.6 but we need 0.5.7, which is as of
yet, unreleased. As a temporary fix we're now pointing at a particular
Git revision, but I've raised a bug[0] with the project requesting an
actual date, when we should revert to using the official published gem
[0] https://github.com/microsoft/ApplicationInsights-Ruby/issues/71
=> Bump ApplicationInsights for JavaScript middleware

app/controllers/candidates/registrations/contact_informations_controller.rb, app/services/candidates/registrations/contact_information.rb, app/views/candidates/registrations/contact_informations/_form.html.erb, config/locales/en.yml, features/candidates/registrations/contact_information.feature, features/candidates/registrations/wizard.feature, features/step_definitions/candidates/registrations/application_preview_steps.rb, features/step_definitions/candidates/registrations/wizard_steps.rb, spec/factories/candidates/registrations/contact_information_factory.rb, spec/factories/candidates/registrations/registration_session_factory.rb, spec/features/candidates/registrations_spec.rb, spec/services/candidates/registrations/contact_information_spec.rb
In order to integrate with the CRM we need to provide a first name and
last name. This commit updates the candidate registration wizard to
capture first name and last name rather than full name.
Should look sensible and backwards compatible. 
There is one edge case: if a candidate has completed the contact details screen and we push the update before they submit their application, they will get stuck on the application preview screen. There is a [ticket](https://dfedigital.atlassian.net/browse/SE-1006) to address this, it's currently blocked waiting for [this PR ](https://github.com/DFE-Digital/schools-experience/pull/429) to be merged
=> Split full_name into first_name and last_name

app/services/bookings/gitis/crm.rb, spec/services/bookings/gitis/crm_spec.rb
Implementation of the Candidate sign in screens don't need the gitis integration completing, just a consistent API to operate around.
Add a new method `Bookings::Gitis::CRM#find_contact_for_signin` which can be used within the auth flow. This can then be back filled with an actual implementation as part of the Gitis API work
Does it seem reasonable
=> Added stub method which the Candidate auth screens can build around

app/models/bookings/candidate.rb, db/migrate/20190606081440_create_bookings_candidates.rb, db/schema.rb, spec/factories/bookings/candidates_factory.rb, spec/models/bookings/candidate_spec.rb
We need a reference point for candidates - those are currently a UUID referencing a Contact entity in GitisCRM but that may not be the case in the future.
1. Add a simple Candidate model which other models can associate with
=> Add candidate model

app/models/bookings/placement_request/cancellation.rb, app/presenters/schools/on_boarding/school_profile_presenter.rb
User research has indicated school admins are confused by the school
email shown on the school profile show page being the original email
we got from get information about schools rather than the email they
entered in the school on boarding wizard.
Display the school notification email rather than the contact email.
Bookings::School#notification_email defaults to the original email if
the school hasn't completed the onboarding wizard
=> Display notifications_email not contact_email

app/models/bookings/school.rb
Default school admin contact to the school email if the school hasn't completed the onboarding wizard and we don't know the admins name
=> Set default contact name if the school hasnt onboarded

app/notify/notify.rb, features/candidates/placement_requests/cancelling_a_placement_request.feature
Our stub notify client, set in the initializer, was being lost when a
new thread was spun off between requests in cd.
Replace storing notification_class in Thread.current with a class variable.
Should pass when run against the docker-compose-selenium cucumber tests
=> Replace Thread.current with class vars

features/step_definitions/schools/placement_requests/confirm_booking_steps.rb
Capybara returns nil if the value isn't present but Selenium returns
empty strings. The latter causes this step to fail. This change fixes it.
=> Deal with empty strings in addition to nils

app/controllers/schools/sessions_controller.rb
Continue to show the user the 'please try again' page as before.
Previously authentication failures would have been more visible since it would result in an exception. Now we swallow the exception and show the user a nice page, this has reduced our visibility of problems and requires us to go back through the logs to find any issues users have encountered.
1. Manually raise the exceptions in Sentry and Slack.
=> Raise authentication failures in Slack and Sentry

app/controllers/schools/placement_requests/acceptance/add_more_details_controller.rb, app/forms/schools/placement_requests/add_more_details.rb, features/schools/placement_requests/acceptance/add_more_details.feature, features/step_definitions/form_steps.rb, features/step_definitions/schools/placement_requests/add_more_details_steps.rb, spec/factories/bookings/bookings_factory.rb, spec/forms/schools/placement_requests/add_more_details_spec.rb
If schools are repeatedly having to type in contact info when accepting placement requests it could be frustrating
When schools have prior accepted bookings we default the form to use the values from the previous booking. This should speed up the process for most schools, making it easier and avoiding potential typos
Ensure the approach is logical
=> If prior bookings exist pre-populate the form

app/models/bookings/school.rb, spec/models/bookings/school_spec.rb
Some schools that exist in the database were imported with data that
doesn't meet the validation critera that is currently in place,
specifically the availability_info field (existing values include things
like 'Term time' and 'TBC')
To accomodate, reduce the minimum number of characters from 10 to 3
https://sentry.io/organizations/dfe-se/issues/1064898105/events/ad7c22d2576143f68118861ac13fea60/
=> Fix an error where old imported data is invalid

app/views/candidates/home/index.html.erb
The school experience service doesn’t just cover this academic year,
and so the reference to this on the start page is misleading.
=> Remove current academic year from start page

app/models/bookings/candidate.rb, app/models/candidates/session.rb, app/models/candidates/session_token.rb, db/migrate/20190617135043_candidates_session_tokens.rb, db/schema.rb, spec/factories/bookings/candidates_factory.rb, spec/factories/candidates/session_token_factory.rb, spec/models/bookings/candidate_spec.rb, spec/models/candidates/session_token_spec.rb
We will need to invalidate a candidates sign in if they update their email address in the future
1. Record when a token is confirmed
2. Record when a candidate is confirmed via a token
3. Allow de-confirming a candidate
4. Auto expire other tokens when confirming a token
Does it look sane
=> SE-1176 Record token confirmation

app/controllers/candidates/registrations/placement_requests_controller.rb, app/models/bookings/placement_request.rb, app/services/candidates/registrations/behaviours/placement_preference.rb, app/services/candidates/registrations/registration_session.rb, spec/controllers/candidates/registrations/placement_requests_controller_spec.rb, spec/services/candidates/registrations/registration_session_spec.rb
If a school changes it's availability preference while there are
candidates on the email confirmation step of the placement_request
wizard this will invalidate their placement_request and throw an error
when we create! the placement_request in the database. To handle this we
won't revalidate the availability before persisting the record.
If the availability was valid at the time candidate selected it then it
should still be applicable when they come back from validating their
email address. Schools still have to set a solid date when they create a
booking from the placement requests as the placement request's
availability is just a suggestion.
Open to suggestions for a neater way to do this.
=> Don't revalidate placement request on email confirm

app/models/feature.rb, spec/models/feature_spec.rb
Currently we're repeating `Rails.application.config.x.phase >= X` all over the place, this isn't very DRY and is needlessly verbose.
1. Adds a helper model to do the check with `Feature.only(phase)`,`Feature.until(phase)` and `Feature.from(phase)`
2. Each helper can optionally take a block which will get run and the result returned, if not block is given then `true` is returned
eg
```erb
<% if Feature.from_phase(3) %>
<p>My Big New Feature</p>
<% end %>
```
or 
```erb
<% Feature.from(3) do %>
<p>My Big New Feature</p>
<% end %>
```
or
```ruby
resource :dashboard if Feature.until(5)
```
Sanity checking - note, converting the code base to use this will be a separate PR
=> Added Feature checking model

app/views/pages/privacy_policy.html.erb
Privacy policy needed a back link to prevent users becoming trapped
Adds a back link to privacy policy
Privacy policy should have a back link
=> Adds back link to privacy page

app/services/bookings/gitis/fake_auth.rb, app/services/bookings/gitis/fake_crm.rb, config/environments/test.rb, spec/services/bookings/gitis/auth_spec.rb, spec/services/bookings/gitis/crm_spec.rb, spec/support/bypass_fake_gitis.rb, spec/support/stubbed_gitis.rb
Master is currently broken because previously we used the FakeCRM in tests, and have subsequently switched to using stubbed.
1. Swap back to using FakeCRM in tests by default
2. Allow enabling/disabling FakeCRM at runtime for those tests which require stubbing API requests instead.
=> Use FakeCrm in tests by default

app/views/schools/on_boarding/dbs_fees/new.html.erb, config/locales/en.yml, features/schools/onboarding/dbs_fee.feature
Update text on the DBS screen to match prototype. Also, to further match the prototype, make the text boxes a bit wider.
Prototype on left, app on right:
=> Update DBS Check costs page to match prototype

app/controllers/schools/placement_requests/acceptance/preview_confirmation_email_controller.rb, app/notify/notify_email/candidate_booking_confirmation.29ed44bd-dc79-4fb3-bf8e-6e0ff18365b3.md, app/notify/notify_email/candidate_booking_confirmation.rb, spec/notify/notify_email/candidate_booking_confirmation_spec.rb
Adds a link to allow candidates to cancel a booking from the booking confirmation email confirmation
Review after [SE-1108](https://github.com/DFE-Digital/schools-experience/pull/548
) has been merged
=> Se 1162/candidate/bookings/add cancellation link to booking confirmation email

app/assets/stylesheets/school-dashboard.scss, app/views/schools/dashboards/_full_dashboard.html.erb
Update the dashboard to match the prototype.
Dashboard should look the same as the prototype.
Some of the links are wip as they're done in other tickets.
I've copied over the change availability type, which is missing in the prototype, as that's currently the only way for schools to switch fixed/flex dates.
=> Updates the school dashboard to match prototype

app/views/schools/confirmed_bookings/cancellations/_form.html.erb, app/views/schools/confirmed_bookings/cancellations/_letter.html.erb, app/views/schools/confirmed_bookings/cancellations/notification_deliveries/show.html.erb, app/views/schools/confirmed_bookings/cancellations/show.html.erb, features/schools/confirmed_bookings/cancelling.feature, features/step_definitions/form_steps.rb, features/step_definitions/schools/bookings/cancellation_steps.rb
Booking cancellation screens used the wrong wording, 'rejection' instead of 'cancellation'
Replace incorrect words, plus add a couple of extra tests
Ensure everything looks sensible
=> Update copy, replace 'reject' with 'cancel'

app/views/schools/confirmed_bookings/index.html.erb, features/schools/confirmed_bookings/index.feature, features/step_definitions/schools/bookings_steps.rb
Showing the table when there are no bookings looks odd
Hide the table when the school has no bookings
Table should be hidden when there are no bookings.
=> Hide the bookings table if no bookings for school

app/notify/notify.rb, config/environments/servertest.rb, config/environments/test.rb, spec/notify/notify_spec.rb
Configuring the fake notify client has been triggering some odd behaviour in tests launched via Spring, easiest solution seems to be to use `Rails.application.config` and move the configuration aspect
entirely outside the class.
Use `Rails.application.config.x.notify_client` to control the class used for sending messages via Notify
Does it seem like a good idea? Does it cause issues for anyone else. Seems to be more reliable for me.
=> Removed use of class vars for controlling Notify client

app/notify/notify_email/candidate_booking_confirmation.29ed44bd-dc79-4fb3-bf8e-6e0ff18365b3.md, app/notify/notify_email/candidate_booking_confirmation.rb, spec/notify/notify_email/candidate_booking_confirmation_spec.rb
Some _extra_ and unnecessary fields remained in the confirm booking template that are no longer needed, namely `placement_fee` and `placement_finish_date`.
Remove the unnecessary fields and sync the remaining content with the master copy on Notify
Ensure the email makes sense
=> Finalise booking confirmation email text

spec/controllers/schools/confirmed_bookings/cancellations/notification_deliveries_controller_spec.rb, spec/controllers/schools/confirmed_bookings/cancellations_controller_spec.rb
Some specs failed when subsets were run, ie. running
`rspec spec/controllers` but didn't when the entire suite was run.
=> Add stubbing Gitis to confirmed booking controllers

app/notify/notify.rb
Notify client access is broken in `development` and `production` (unreleased so far)
Didn't allow for Rails.config.x returning a hash when unset instead of a Nil
=> Fixed bug in notify refactor

app/services/bookings/gitis/contact.rb
The epic branch is currently broken because `DEFAULT_CHANNEL_CREATION` is not getting set to anything.
1. Set it to an arbitrary default value of 0
=> Assign default value for channel creation

app/views/candidates/registrations/personal_informations/_form.html.erb, app/views/candidates/sessions/new.html.erb, config/locales/en.yml, features/candidates/registrations/personal_information.feature, features/step_definitions/candidates/registrations/personal_information_steps.rb, spec/features/candidates/registrations_spec.rb
Some of the content on the Personal Information screen needs to make clear how the information will be used
1. Updated the content on the Personal Information step
2. Updated the content on the Sign In screen
=> Updated Personal Information and Sign In screen content

app/controllers/candidates/registrations/confirmation_emails_controller.rb, app/controllers/candidates/registrations/contact_informations_controller.rb, app/controllers/candidates/registrations/personal_informations_controller.rb, app/controllers/candidates/registrations/placement_requests_controller.rb, app/controllers/candidates/registrations_controller.rb, config/routes.rb, spec/features/candidates/registrations_spec.rb, spec/rails_helper.rb
We need to continue to be able to run the Candidate Journey in Phase 3 mode
1. Avoid interacting with Gitis if in Phase 2 mode
2. Dont associate placement requests with candidates if running in Phase 2 mode
1. Code review
2. Real test - set .env
```
PHASE=2
FAKE_CRM=false
```
=> SE-1257 Feature flag phase3 work

app/helpers/form_for_helper.rb
Currently when submitting a form which requires an email field to be
completed, a small non obvious error message is shown as a tooltip.
The user never sees the big obvious GDS error until they’ve successfully
passed the in browser validation. This places the accessibility/usability
of errors under the browsers control rather than ours, and users the
particular browsers own design instead of our GDS compliant design.
Couldn't find a configuration option in rails to set this globally for forms - if there's a better way to do this let me know!
=> Disable HTML5 validations site wide

app/views/candidates/registrations/placement_preferences/_form.html.erb, app/views/schools/on_boarding/candidate_requirements/_form.html.erb, app/views/schools/placement_dates/edit.html.erb
Fix textarea_with_maxwords
govuk-frontend/all.js CharacterCount.prototype.createCountMessage
appends a reference to the word count span to the textarea's
aria-describedby attribute. If this attribute is not set on the textarea
the govukjs sets it to `'null' + ' ' + <id-of-word-count-span>` causing an
error to be shown in waves.
Visit 
/candidates/schools/:urn/registrations/placement_preference/new
/schools/onboarding/candidate_requirement/new
/schools/placement_dates/:id/edit
Expect not to see any errors in waves
I looked into baking this into form builder, but it would require substantial work as generating ids for the label tags is tricky. Something to consider for formbuilder 2
=> Se 1031/acessibility/form builder fixes

app/views/schools/placement_requests/_placement_requests_table.html.erb, features/schools/placement_requests/index.feature
Schools are getting confused that ‘date requested’ means the date that the request was made rather than the date the candidate is requesting.
Update the table heading
=> Updates table header text

app/helpers/schools/placement_requests_helper.rb, app/models/bookings/placement_request.rb, app/views/schools/placement_requests/_placement_request.html.erb, features/schools/placement_requests/index.feature, features/step_definitions/form_steps.rb, features/step_definitions/schools/placement_request_steps.rb
Cancelled labels were being hidden once placement requests are viewed
Move the status logic to a helper
Ensure it looks sensible and works
=> Stop cancelled flag disappearing

features/step_definitions/schools/placement_request_steps.rb
Master is broken, this is caused by features in cucumber failing to match the text of gov-uk tags because the CSS upcases them
make the specs match case insensitively
broader fix is probably to change the tag names but this is the lower risk fix for now
=> Made failing features match govuk tags case-insensitively

app/controllers/schools/placement_requests_controller.rb, spec/controllers/schools/placement_requests_controller_spec.rb
Booked placement requests were appearing in the placement requests index, they should 'move' to the Bookings list instead.
Prevent booked placement requests from appearing in the placement requests index.
Also, order the placement requests by their creation date, newest first.
=> Withold booked placement requests from listing

app/views/schools/placement_requests/show.html.erb
The ordering of sections on placement request show doesn't match
the prototype, looks like this got mixed up when fixing a conflicting
merge
=> Reorder sections on placementrequest show

app/views/schools/placement_requests/index.html.erb
Updates the copy on placement request show to inform the school they
won't be shown placement requests made before phase3 release date.
This copy has already been added on bookings show
=> Update copy on placement request show

app/models/bookings/candidate.rb, db/migrate/20190628133753_add_created_in_gitis_to_bookings_candidates.rb, db/schema.rb, spec/models/bookings/candidate_spec.rb
Currently we need to query Gitis to find whether Candidate already existed or was created by us. This prevents us using it as part of our Analytics
1. When we create a Candidate in our database, include whether it already existed in Gitis when we created it.
=> SE-1261 Record gitis record creation

app/views/candidates/sessions/new.html.erb, config/locales/en.yml, spec/models/bookings/registration_contact_mapper_spec.rb
Minor fixes to issues with the Date of Birth field on the Personal Information page
1. Improved the error message when the Date of Birth is not set
2. Added specs to ensure the Date of Birth gets prepopulated when it should
=> DOB field fixes

app/views/candidates/registrations/personal_informations/_form.html.erb
Changes from Fred to clarify how we use the candidates personal information
1. Added additional explanation text to personal information screen - only shown conditionally for Phase 3 since it only applies from Phase 3 onwards
=> Updated Personal Information screen text

config/environments/production.rb
We should be running with a Real CRM instance in production
1. Default to using the Real CRM in production environments
2. Allow configuring the Fake CRM for use in production environments
=> Default to Real CRM in production

azure-pipelines.yml, features/step_definitions/candidates/landing_page_steps.rb
I've broken master with an Invalid CSS selector - passes on Rack::Test but not with Chrome
1. Fix CSS Selector
2. Switch to run against Chrome in addition to Rack::Test when on branches - this should catch issues before they get merged to master
=> Breakage on `master` on landing page

spec_external/gitis_crm_spec.rb
Updates to the Gitis Test Suite for correctness
1. Use telephone2
2. Use emailaddress2
3. Dont hard code the channel creation field
=> Use correct fields and dont hardcode channel field

app/controllers/candidates/registrations/personal_informations_controller.rb, app/controllers/candidates/registrations/sign_ins_controller.rb, app/helpers/application_helper.rb, app/services/candidates/registrations/application_preview.rb, app/services/candidates/registrations/personal_information.rb, app/views/candidates/registrations/application_previews/show.html.erb, app/views/candidates/registrations/personal_informations/_form.html.erb, app/views/shared/_list_row.html.erb, spec/controllers/candidates/registrations/personal_informations_controller_spec.rb, spec/controllers/candidates/registrations/sign_ins_controller_spec.rb, spec/features/candidates/registrations_spec.rb, spec/services/candidates/registrations/personal_information_spec.rb
1. Once the user has validated their email address we shouldn't let them update it.
1. Added a read_only_email attribute which defaults to false
2. Only allow assigning the email address if read_only_email isn't assigned
3. Mark the address as Read Only at sign in
1. Code review and Sanity Checking
2. Check that after sign in, returning to the Personal Info page shows the email address marked readonly
=> Marked PersonalInformation#email as read only

app/controllers/schools/placement_requests/acceptance/confirm_booking_controller.rb, app/models/bookings/booking.rb, spec/controllers/schools/placement_requests/acceptance/confirm_booking_controller_spec.rb, spec/models/bookings/booking_spec.rb
For fixed date placement requests the `duration` wasn't being carried over to the newly-created booking
Update the #find_or_create_booking method so that if there's a placement request present with a placement date it uses the booking, and ignores it if there isn't (allowing the booking to revert to its default of `1`)
An additional change was to improve the formatting of the date formatting so it includes the word 'for'.
Ensure changes look sensible
=> Ensure the duration is set properly when the placement request has an associated date

app/notify/notify_email/candidate_booking_confirmation.rb, spec/notify/notify_email/candidate_booking_confirmation_spec.rb
The booking confirmation email had a badly-formatted address like: "Street, , , Postcode"
Remove any 'blank' address parts before joining
Ensure the fix looks sensible
=> Remove empty address parts before combining

app/views/candidates/registrations/sign_ins/update.html.erb
Button should be a secondary button
1. Made it a secondary button
=> De-emphasise resend link button

app/controllers/schools/sessions_controller.rb
This is an attempt to work out why the state mismatch errors are
frequently happening. Rich speculated that it might be the retrieval of
the state from Redis that's causing the issue rather than comparing the
retrieved value to the one provided in params.
Fetch will blow up if it can't find `:state`, potentially highlighting the
issue
=> Use fetch to retrieve state from session

public/robots.txt
Google currently can't index the schools landing page, only the candidate one
Add `/schools$` to the whitelist
It's a pretty minimal change! `$` denotes the end of a URL
=> Add /schools$ to the whitelist

azure-pipelines.yml
We assume an up to date latest tag in our Azure Container Registry based repos (for the various release jobs that execute rake tasks that disable, enable, enrich etc. via Docker).
Therefore prior to switching off ACR we need to have a latest tagged image in Docker Hub.
Create a latest tag and push that to the docker hub repo
This will only be verified once pushed to master due to the conditions on the tasks.
=> push a latest tag to docker hub repo

app/services/bookings/gitis/contact.rb, app/services/bookings/gitis/crm.rb, spec/services/bookings/gitis/contact_spec.rb
Following on from conversations with the CRM team - its been requested we update telephone1 and emailaddress1 when its our own records in the CRM
1. Added method to detect when they are 'our own records'
2. Use that to determine which fields to update when assigning email and phone on the Contact entity
3. Tests to check for the above
1. Code review
2. CRM interactions are now written to the log, prefixed with [CRM] - this includes the fields written but not values
=> SE-1331 Write to tel1 and email1

app/notify/notify_to_logger.rb, config/environments/development.rb
Its useful to see the information being sent in an email actually needing to send the email via notify.
1. Allow the notify client to be controlled by an environment variable in `development.rb`
2. Added Notify client which just writes to the Logger
1. Would like to add a more fully fleshed option which leverages letter_opener, but we're not there yet and this suffices.
2. This is quite subjective, and is just some code I've had knocking around on my machine so feel free to knock back if it doesn't seem like a good idea
=> Added Notify client which just writes to the Logger

azure-pipelines.yml
Currently within the CI pipeline, any steps with conditions will be running irrespective of whether the prior step succeeded. This is because we override the default condition which is to depend upon the earlier step
1. Make any steps with conditions first check the earlier step succeeded
1. Sanity checking
=> Make later pipeline steps dependent upon earlier pipeline steps

app/views/candidates/registrations/personal_informations/_form.html.erb, spec/features/candidates/registrations_spec.rb
Heading on the Personal Information needs to be corrected for runnning in Phase 2, ie no CRM
1. Change the title
2. Update the phase2 feature spec
=> Changed heading on Personal Information screen for Phase 2

app/notify/notify.rb, spec/notify/notify_spec.rb, spec/support/notify_erroring_client.rb
We weren't receiving slack notifications for Notify errors.
This commit notifies slack if a notification fails to send before the
jobs has expired it's retires.
=> Notifies slack and sentry on Notify error

app/controllers/schools/dashboards_controller.rb, app/models/bookings/booking.rb, app/models/bookings/placement_request.rb, spec/models/bookings/booking_spec.rb, spec/models/bookings/placement_request_spec.rb
'open' conflicts with a built in Ruby method
=> Rename 'open' scope to 'uprocessed'

app/views/schools/placement_requests/acceptance/confirm_booking/new.html.erb, app/views/schools/placement_requests/acceptance/email_preview_sections/_school_experience_details.html.erb, features/schools/placement_requests/acceptance/confirm_booking.feature, features/schools/placement_requests/acceptance/preview_confirmation_email.feature, features/schools/placement_requests/acceptance/review_and_send_email.feature, features/step_definitions/schools/placement_requests/confirm_booking_steps.rb, features/step_definitions/schools/placement_requests/review_and_send_email_steps.rb
Add duration to placement request acceptance wizard, it was missing from the accept placement request and both screens with email previews
Add the booking date to the relevant parts
Ensure it looks ok. Note that the date/duration summary will be improved by #667
=> Add duration to acceptance screens SE-1330

config/environments/production.rb
We are triggering warnings from Pen Test tools because we don't set the `X-Content-Type-Options` header to `nosniff`
1. Explicitly set the header for static assets served by Puma
Run the app in production, verify the header is present on the CSS/JS files and matches the header setting on the main html file.
Note this requires
1. Assets to be precompiled
2. `RAILS_SERVE_STATIC_FILES=true` set in `.env`
3. `config.force_ssl`  set to false in `production.rb`
=> Added nosniff header for static assets

app/controllers/candidates/placement_requests/cancellations_controller.rb, app/models/bookings/placement_request.rb, spec/controllers/candidates/placement_requests/cancellations_controller_spec.rb, spec/controllers/schools/placement_requests_controller_spec.rb, spec/models/bookings/placement_request_spec.rb
Whilst investigate a couple of flaky test failures, I also found the format of the cancellation email sent to schools when Candidates cancel a booking is in an incorrect format, including the time of placement request.
1. Change the Cancellation email to show the date without the time.
2. A fix a flaky test in the test suite which was assuming records were created by FactoryBot were created in a specific order.
1. Sanity checking
=> Fix for incorrectly formatted date in Cancellation email

app/controllers/concerns/gitis_authentication.rb, app/services/candidates/registrations/school_session.rb, spec/controllers/candidates/registrations/sign_ins_controller_spec.rb, spec/features/candidates/registrations_spec.rb, spec/services/candidates/registrations/school_session_spec.rb
If the signed in candidate switches, then we should not allow the new candidate to access the prior candidates information.
1. Remove all existing registration sessions, if the signed in candidates changes - Note: this doesn't affect candidates signing in when no one was already signed in
1. You can replicate the process by using Fake CRM, completing the journey to after the verification process
2. Then opening a separate browser window and going to `/candidates/dashboard`, signing in their with different details
3. Swap back to the original window and continue the process
4. At the point you'd expect to see the application preview, you should be bounced back to the Personal Information step since those details have now been removed from the session.
5. The form should be prefilled with …
=> SE-1256 Cancel registrations if current contact switches

azure-pipelines.yml
We are no longer using Azure Container Registries and so we no longer should push to those container registries
No longer login to the ACR, only tag with the Docker Hub repo name (latest and the `v$(Build.BuildId)` ), only push to the Docker Hub Repo
Some changes will only be validated when merged onto master
=> removing references to Azure Container Registries

config/locales/en.yml
Schools on boarding wizard fee radio buttons were missing validations messages when no fee was selected
Adds validation errors when no fees are selected.
=> Adds validation message for unselected fees

app/views/pages/cookies_policy.html.erb
Before we turn on App Insights client-side reporting we need to inform users that they'll receive some additional cookies 
Add a new section to the cookies policy covering `ai_session` and `ai_user` cookies
Ensure it makes sense. Copy reviewed already by @fredbrenton
=> Added App Insights cookies to the policy

config/initializers/filter_active_job_logging.rb, spec/jobs/notify_job_spec.rb
When enqueuing a notify job the personalisation and email address were
being stored in the logs, this commit removes this information from
activejob logging.
Original method is here:
https://github.com/rails/rails/blob/661cf57906743a0965edc31443a28181cee348d6/activejob/lib/active_job/logging.rb#L97
=> Remove PII from active job logs

app/services/candidates/registrations/personal_information.rb, spec/services/candidates/registrations/personal_information_spec.rb
If the user enters negative values into the date of birth fields rails
throws an argument error when attempting to cast it to a date causing
us to show a 500 page to the user.
=> Handle negative dob

app/controllers/concerns/analytics_tracking.rb, spec/controllers/candidates/schools_controller_spec.rb
The analytics tracking cookie was not marked as _httponly_. This [increases the risk of cookies being revealed to third parties](https://www.owasp.org/index.php/HttpOnly#What_is_HttpOnly.3F).
Make the `analytics_tracking_uuid` cookie _httponly_.
The change is very minimal, covered by specs and tested locally:
=> Make analytics cookie httponly SE-1310

app/services/bookings/gitis/crm.rb, app/services/bookings/gitis/entity.rb, lib/apimock/gitis_crm.rb, spec/services/bookings/gitis/contact_spec.rb, spec/services/bookings/gitis/entity_spec.rb
Certain fields in the CRM seem to slow down queries, plus it balloons up the data we needlessly retrieve.
1. Explicitly request the columns we require
1. Sanity checking
=> SE-1177 Restrict crm fields queried

app/models/bookings/booking.rb, spec/models/bookings/booking_spec.rb
Durations were being shown for flexible dates which will always have 1 day duration (the default)
Hide the duration for bookings made from PRs with flexible dates - always show it for those with fixed.
=> Display duration only if request has fixed dates

app/controllers/schools/toggle_enabled_controller.rb, app/models/bookings/school.rb, app/models/event.rb, db/migrate/20190716094514_create_events.rb, db/migrate/20190717131205_change_event_gitis_uuid_to_bookings_candidate_id.rb, db/migrate/20190717135225_add_index_to_events_candidate_id.rb, db/schema.rb, lib/data/school_manager.rb, spec/factories/events_factory.rb, spec/models/bookings/school_spec.rb, spec/models/event_spec.rb
It's currently impossible to tell the frequency at which schools are enabling and disabling themselves.
Add a generic `Event` class that's linked to
* `Bookings::School`
* `Bookings::Candidate`
* An optional polymorphic third object. This would make sense if we record that a candidate has made a request on a `Bookings::PlacementDate` - we could then link a single event to the school, candidate and date.
The first two logged events are `school_disabled` and `school_enabled`. Events are logged when the `Bookings::School#enable!` and `Bookings::Schools#disable!` methods are used. The current school enabling and disabling functionality is exposed in two places, in the `ToggleEnabledController` and in the `SchoolManager` object, which is used by the enabling and disabling rake tasks.
There is …
=> Event log SE-1343

azure-pipelines.yml, docker-compose-chrome.yml, docker-compose-firefox.yml, docker-compose-selenium.yml, docker-compose.yml, script/generate_matrix.sh
The functional tests take a long time to execute in CI . These functional tests can be run in parallel as long as each process accesses a dedicated application instance.
Utilise the Docker Compose file to spin up the dedicated application instance.
Note the use of Docker Compose has been limited to the functional tests.
Since the dedicated application instance is running in a separate agent it needs a Docker image that has not yet been pushed. For this reason the docker image is rebuilt in each agent. The image that is pushed will still be functionally tested in CD .
The duration of a feature branch build is reduced by roughly 10 mins i.e. 26 mins down to 16 mins. I imagine the reduction in the master branch builds will be c. 20 mins i.e. 50 mins down to 30 mins.
=> running functional tests in parallel

app/controllers/candidates/schools_controller.rb, config/initializers/content_security_policy.rb
The lack of content security policy was raised as a concern in the internal Pen Test performed by @petenorth 
1. Added a generic CSP granting access for google analytics and app insights
2. Added a specialised CSP for the show school profile page, which also allows bing maps to run
1. Check various pages, including the search for schools -> show school page, with the javascript console open looking for any errors
2. Ensure Google Analytics, Bing Maps and App Insights are all enabled
=> SE-1312 add Content Security Policy

app/controllers/candidates/registrations/personal_informations_controller.rb, app/views/candidates/registrations/personal_informations/_form.html.erb, spec/controllers/candidates/registrations/personal_informations_controller_spec.rb, spec/features/candidates/registrations_spec.rb, spec/views/candidates/registrations/personal_informations/_form.html.erb_spec.rb
The Candidate is not allowed to amend their email address when they are signed in via that email
1. Disable the field in the page, so the user is aware they can't change it
Run in development with
```
PHASE=3
FAKE_CRM=true
```
Complete the Candidate Journey, signing in along the way. Checking the email field is editable and not disabled.
Continue to the the 'Check your answers' screen, choose to change the Name
Verify the field is disabled and read only.
=> Disable the email field on the Candidate journey

spec/features/candidates/registrations_spec.rb
This spec was referencing the subject_preference screen which had been
removed as part of SE-1167
=> Fixes spec broken by merging SE-1167 work

azure-pipelines.yml
at intervals of 5 secs for a maximum of 60 secs.
Previously it simply slept for 15 secs and assumed that the database will have bee seeded for db-tasks container by that time. There was some evidence that this wasn't enough time (the truncation of the tables by the cucumber tests failed as they didn't exist).
Rather than sleep it now check the status of the db-tasks container and wait until it has successfully exited. This container generally restarts as it initially exits with a non zero error code as the database has fully started, the next instance generally is able to connect and run successfully.
To confirm locally
```
docker-compose -f docker-compose.yml -f docker-compose-chrome.yml up -d
WAIT_COUNT=0
until docker-compose ps | grep -m 1 "db-tasks" | grep -m 1 "Exit 0" || [ …
```
=> poll 'docker-compose ps' output for strings 'db-tasks' and 'exit 0'

app/controllers/schools/sessions_controller.rb, spec/controllers/schools/sessions_controller_spec.rb
The state mismatch error was being raised but the informative message was only going to the logs and not to Sentry
Increase visibility of what's going on by pushing the error message to Sentry as well as the logs
Also spelling of 'Mismatch'
Ensure it looks sensible. Testing difficult because the `rescue_from StateMismatchError` in the `Schools::SessionsController`.
=> Raise the state missmatch error in addition to log

app/views/schools/dashboards/_manage_dates.html.erb, features/schools/dashboard.feature
These weren't carried over from the dashlette/dashboard merge (#731)
Because they were from the dashlette side they weren't covered by Cucumber, so scenarios have been added to ensure their presence
=> Re-add no dates/availability warnings to dashboard

app/controllers/schools/on_boarding/admin_contacts_controller.rb, app/forms/schools/on_boarding/admin_contact.rb, app/models/bookings/placement_request.rb, app/models/bookings/placement_request/cancellation.rb, app/models/bookings/profile.rb, app/models/bookings/profile_attributes_convertor.rb, app/models/bookings/school.rb, app/models/schools/school_profile.rb, app/notify/notify_email/candidate_booking_confirmation.rb, app/notify/notify_email/candidate_booking_confirmation_withoutadmincontactname.b9882e65-b644-4c52-871e-0e5922f27d7e.md, app/presenters/schools/on_boarding/school_profile_presenter.rb, app/views/schools/on_boarding/admin_contacts/_form.html.erb, app/views/schools/on_boarding/profiles/show.html.erb, app/views/schools/placement_requests/acceptance/email_preview_sections/_help_and_support.html.erb, features/schools/onboarding/admin_contact.feature, features/schools/onboarding/school_profile.feature, features/schools/placement_requests/acceptance/preview_confirmation_email.feature, features/schools/placement_requests/acceptance/review_and_send_email.feature, features/step_definitions/schools/onboarding_steps.rb, features/step_definitions/schools/placement_requests/review_and_send_email_steps.rb, spec/factories/schools/on_boarding/admin_contact_factory.rb, spec/forms/schools/on_boarding/admin_contact_spec.rb, spec/models/bookings/profile_attributes_convertor_spec.rb, spec/models/bookings/profile_spec.rb, spec/models/schools/school_profile_spec.rb, spec/notify/notify_email/candidate_booking_confirmation_spec.rb, spec/presenters/schools/on_boarding/school_profile_presenter_spec.rb
Removing this field to avoid capturing unnecessary pii.
Removes the school admin name from the app, leaves the column name in the db.
should be no instances of school admin name.
I've added a new notify template for candidate booking confirmation, will want to remove the old template once this code is deployed to staging.
=> Remove capturing school admin (name from UI)

app/views/schools/placement_requests/acceptance/confirm_booking/new.html.erb, app/views/schools/placement_requests/index.html.erb
Content didn't line up, an superfluous class suffix `-width` was used
Remove the incorrect suffix
=> Fix incorrect class, content now aligns properly

azure-pipelines.yml
Currently we just use `:latest` for the build cache but this is often newer than a feature branch requires.
1. Tag a build cache according to the versions of dependencies
2. Use this tag for the `--cache-from` param
3. Upload the build cache using this tag
1. Does it work, is it sane.
=> SE-1506 Cache docker builds by dependency

Gemfile.lock, app/views/candidates/registrations/contact_informations/_form.html.erb, app/views/candidates/registrations/personal_informations/_form.html.erb, app/views/candidates/sessions/new.html.erb, app/views/schools/placement_dates/new.html.erb, features/candidates/registrations/contact_information.feature, features/candidates/registrations/personal_information.feature, features/step_definitions/candidates/registrations/personal_information_steps.rb, features/step_definitions/form_steps.rb
Enhance autocompletion for various steps of the candidate journey, namely their personal details and their date of birth fields
By being [more-specific than `on`](https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill) we can help the browser provide autocompletion values
Ensure everything works and looks ok
=> Candidate autocompletion SE-1273

app/views/schools/confirmed_bookings/date/edit.html.erb
PR #768 introduced some changes to the form builder that weren't
reflected in the changes made in #756. This fix makes the necessary
amendment to the problematic form
=> Fix failing spec caused by update to form builder

config/environments/production.rb, yarn.lock
We are currently locked to v2.7 of the GOV.UK Frontend - newer versions are failing to compile within the asset pipeline.
After some investigation, this appears to be caused by Sprockets double compiling the SCSS input - once to preprocess it all, and a second run to compress it. 
The GOV.UK Frontend includes code which is 'quoted' to pass through the SCSS processor, 
1. the first run passes through and remove's the quoting, 
2. the second run now tries to run the CSS function because its no longer quoted
The second run is a legacy of supporting a non-sass `application.css` using sprockets to include the other files. This is not an requirement in our instance.
1. Disable the second SCSS pass
2. Enable compression on the initial SCSS pass
1. Does it work ok, does it look correct
=> Update design system to version 1.13

app/controllers/schools/on_boarding/descriptions_controller.rb, app/views/schools/on_boarding/descriptions/_form.html.erb, spec/controllers/schools/on_boarding/descriptions_controller_spec.rb
Needed to add a skip button to the description step of the school on boarding wizard so it's clear that this step isn't required. 
I've added this as a submit button, I think this is probably better than a link as we don't need to hard code the navigation. Do you think we should blank any details they've entered if they submit the form using the skip button?
=> Adds skip button to description step

app/views/pages/privacy_policy.html.erb
If we're using :back as the url and the user has clicked the 'back to
top' link at the bottom of the page they can get stuck in a loop.
Instead attempt to send the user back to where they came from or failing
that send them to the candidate start page.
=> Fix back links

app/forms/schools/on_boarding/experience_outline.rb, spec/forms/schools/on_boarding/experience_outline_spec.rb
URI::regexp matches when there is text before the scheme, this allows
xss attacks.
Add an additional validation that the url must start with http:// or
https://
fixing a bug from the security audit
Adds a validation that the url starts with http:// or https://
=> Don't allow xss in teacher training urls

CUCUMBER_TESTING.md
The documentation on how to run Cucumber tests via docker-compose.yml is currently in Confluence.
This pull requests proposes moving this to our GitHub repo.
Adding a Cucumber testing markdown document.
No functional changes, this is just documentation.
Only concern is duplication (if we move it I will link from confluence to this document).
=> adding cucumber testing doc

config/database.yml
The keepalives directive[0] controls whether or not client-side TCP
keepalives are used. The default is `1` (on). The keepalives_interval
directive[1] controls the number of seconds after which a keepalive
message should be sent.
After making these changes it's not really clear that anything has
changed, nothing special about the connection is visible in
`pg_stat_activity`, making thee changes tricky to test.
However, the changes can be seen by interrogating ActiveRecord's
connection info:
```ruby
ActiveRecord::Base.connection.raw_connection.conninfo
```
```
{:keyword=>"keepalives", :val=>"1", :label=>"TCP-Keepalives", ...}
{:keyword=>"keepalives_interval", :val=>"60", :label=>"TCP-Keepalives-Interval", ...}
```
Without the new settings, the keepalives and keepalives_interval
settings are …
=> Add keepalives and keepalives_interval db settings

config/environments/test.rb
The second pass through SASS to compress the CSS trips up the escaping in the
GOV.UK Frontend since v2.8
This isn't necessary for the tests so disabling it.
Does it solve running tests without precompiled assets
=> Don't compress CSS assets in test environments

config/initializers/application_insights.rb
Enable ApplicationInsights::UnhandledException notifier. It will give us more data on errors than we're currently getting from the middleware.
=> Add the App Insights unhandled exception handler SE-1391

features/support/env.rb
This appears to have changed in a Selenium update, the 'capabilities'
approach is no longer mentioned. It has been replaced by creating an
options object and calling the `#headless!` method on it.
The other option that was originally set, disable-gpu, doesn't appear to
have a corresponding method. I suggest we allow this to remain as
default and revisit if it causes problems
https://www.rubydoc.info/gems/selenium-webdriver/Selenium/WebDriver/Chrome/Options#headless!-instance_method
=> Update the way of setting Chrome to be headless

lib/tasks/external_specs.rake, spec_external/gitis_crm_spec.rb
Integration with GiTiS CRM requires a greater number of permissions over the Dynamics Entities
1. Extended the Read specs to check the various new entities
2. Extended the write specs to assign the various relationships
1. Run the `rails spec:external:read` and `rails spec:external:write` to check - ask me for any missing env vars
=> SE-1520 Updated crm testsuite

app/models/candidates/session_token.rb, app/notify/notify_email/candidate_signin_link.5b451894-3640-47df-a119-6461ecb890d9.md, app/notify/notify_email/candidate_verify_email_link.0e4b2eaa-ae1f-472a-9293-c2a24f3f8187.md, config/environments/development.rb, config/environments/production.rb, config/environments/test.rb
Current sessions require 24 hours of inactivity to timeout. This has been determined to be too long as part of our pen test.
1. Reduce session timeout to be 1 hour
2. Reduce session sign in tokens to a lifetime of 1 hour - this avoids users expecting to sign in and continue with their session when in fact it has expired.
=> SE-1502 Reduce session timeout

app/controllers/candidates/schools_controller.rb, config/initializers/content_security_policy.rb
Pen test pointed out out the wildcard we'd added on the microsoft domain was actually their CDN, so could potential host other hostile scripts
1. Locked the App Insights JS to a specific subdomain in the CDN
2. Removed the ability to load <object>s
=> SE-1515 Remove csp wildcard

app/services/bookings/gitis/api.rb, app/services/bookings/gitis/auth.rb, app/services/bookings/gitis/contact.rb, app/services/bookings/gitis/crm.rb, app/services/bookings/gitis/fake_auth.rb, app/services/bookings/gitis/fake_crm.rb, config/environments/development.rb, config/environments/production.rb, config/environments/servertest.rb, config/environments/test.rb, features/support/env.rb, spec/services/bookings/gitis/contact_spec.rb, spec/support/bypass_fake_gitis.rb
Currently we are accessing environment variables directly then occassionally applying logic specific to different environments
Instead access the config from `Rails.application.config.x.gitis`, and load the environment variables into there.
1. Does it look sane
2. Does Gitis access still work, if you've got the gitis config settings
=> SE-1553 Moved CRM config into environment config files

app/services/candidates/registrations/registration_session.rb
Originally when Personal Information was split from Contact Information some
temporary migration code was added, to handle reading the fields from Contact
Information if necessary.
This is no longer needed and has been removed.
=> Removed migration code for PersonalInformation attributes

config/initializers/geocoder.rb
Having had a slight problem with results for the query 'Leeds' where
Bing was returning "Leeds, Kent" rather than "Leeds, Yorkshire", we were
advised by our Bing Maps support agent that:
> ... if you are querying in England it would really help if you set the
culture to "en-gb" that will be adding "c=en-gb" to your REST Query.
We were previously using the default, which is "en-us", which was a
contributing factor to the odd search results.
Bing Maps have fixed the data issue so in that instance (for Leeds) the
correct result is returned. To reduce the risk of this problem affecting
other searches we'll also follow their advice and set the culture
=> Add 'en-gb' culture to default Bing params

app/assets/stylesheets/school-dashboard.scss, app/helpers/schools/dashboards_helper.rb, app/views/schools/dashboards/_new_requests_and_bookings.html.erb, features/step_definitions/schools/dashboard_steps.rb, spec/helpers/schools/dashboards_helper_spec.rb
The SVG notification counters weren't particularly accessible
Replace the SVGs with `div` tags with rounded corners, and add `aria-label` attributes with appropriate values.
One difference is that now, when numbers overflow the circle, rather than the circle increasing in size (like with the SVG), the `div` tag stretches. This will _probably_ never happen but it's worth mentioning
Ensure everything makes sense, is accessible and looks ok.
=> Replace SVG with div with border radius

app/controllers/candidates/registrations/contact_informations_controller.rb, app/controllers/candidates/registrations/personal_informations_controller.rb, app/controllers/candidates/registrations_controller.rb, app/services/candidates/registrations/gitis_registration_session.rb, app/services/candidates/registrations/registration_session.rb, app/services/candidates/registrations/school_session.rb, spec/controllers/candidates/registrations/background_checks_controller_spec.rb, spec/controllers/candidates/registrations/contact_informations_controller_spec.rb, spec/controllers/candidates/registrations/personal_informations_controller_spec.rb, spec/factories/candidates/registrations/gitis_registration_session_factory.rb, spec/features/candidates/registrations_spec.rb, spec/services/candidates/registrations/gitis_registration_session_spec.rb, spec/services/candidates/registrations/school_session_spec.rb
Currently the GiTiS contact data is merged in as part of the controller. This leads to some complexity around trying to sync between GiTiS and Registration Session - in some scenarios (Address, Phone number) the Registration data takes priority. In others (Email address) the GiTiS data takes priority.
Currently this logic logic is spread piecemeal across the registration controllers.
This PR adds a `GitisRegistrationSession`, which will either return data from GiTiS or the Registration Steps as appropriate, and can be unit tested.
1. Do the various behaviours in the Candidate journey still work
2. Do the tests still pass
=> SE-1525 Add gitis registration session

app/views/schools/confirmed_bookings/_booking_table.html.erb, app/views/schools/placement_dates/index.html.erb, app/views/schools/placement_requests/_placement_request.html.erb
Repeated links with the same text make navigating with screen readers
difficult. Add aria labels to repeated links to give more context for
screen readers.
=> Add aria labels to repeated links

app/helpers/application_helper.rb
Previously change links didn't provide enough context for screen readers
Update summary row to include aria-label for screen readers
Change links on summary rows should provide better context for screen readers
=> DAC fixes - Add aria labeled by to change links

app/assets/stylesheets/application.scss, app/assets/stylesheets/cookie-banner.scss, app/helpers/cookies_helper.rb, app/views/layouts/application.html.erb, app/views/shared/application/_cookie_banner.html.erb, features/step_definitions/candidates/landing_page_steps.rb, spec/requests/cookie_banner_spec.rb
We currently don't actively warn users that we use cookies
Add a banner that's displayed when users first visit the School Experience web app. When it's displayed a cookie called `seen_cookie_message` is set and whenever this is present the banner is not displayed. It defaults, as per our existing cookie policy message, to expire after two weeks
Ensure things work as expected, everything looks ok and is accessible.
The ratio of the text on the light blue is AAA and the link is AA.
=> Cookies banner SE-1405

app/views/candidates/schools/_phase1.html.erb, app/views/candidates/schools/_phase2.html.erb, app/views/candidates/schools/index.html.erb
View school details and some of the links on candidates/schools/show were lacking context for screen readers
Added aria-labels to provide better context for links when using a screen reader
Links should now have a better context when read by a screen reader
=> Se 1437/school search dac fixes

app/controllers/candidates/registrations/personal_informations_controller.rb, app/controllers/candidates/registrations/sign_ins_controller.rb, app/services/bookings/gitis/contact.rb, app/services/candidates/registrations/application_preview.rb, app/services/candidates/registrations/gitis_registration_session.rb, app/services/candidates/registrations/personal_information.rb, app/views/candidates/registrations/application_previews/show.html.erb, app/views/candidates/registrations/personal_informations/_form.html.erb, spec/controllers/candidates/registrations/personal_informations_controller_spec.rb, spec/controllers/candidates/registrations/sign_ins_controller_spec.rb, spec/features/candidates/registrations_spec.rb, spec/services/bookings/gitis/contact_spec.rb, spec/services/bookings/gitis/crm_spec.rb, spec/services/candidates/registrations/gitis_registration_session_spec.rb, spec/services/candidates/registrations/personal_information_spec.rb, spec/views/candidates/registrations/personal_informations/_form.html.erb_spec.rb
This builds off PR802 which is now merged.
Users should be prevented from updating their firstname, lastname, email or date_of_birth in Gitis
1. This marks those fields as read only in the UI
2. Gives precendence to the Gitis versions in `GitisRegistrationSession`
3. Marks the fields to be excluded from updates in the Gitis Contact Entity
=> SE-1525 Mark personal info read only

app/controllers/candidates/registrations/background_checks_controller.rb, app/models/bookings/registration_contact_mapper.rb, app/services/bookings/gitis/contact.rb, app/services/bookings/gitis/entity.rb, app/services/bookings/gitis/fake_crm.rb, app/services/candidates/registrations/gitis_registration_session.rb, config/environments/development.rb, config/environments/production.rb, config/environments/servertest.rb, config/environments/test.rb, lib/apimock/gitis_crm.rb, spec/controllers/candidates/registrations/background_checks_controller_spec.rb, spec/factories/bookings/gitis/contact_factory.rb, spec/models/bookings/registration_contact_mapper_spec.rb, spec/services/bookings/gitis/contact_spec.rb, spec/services/bookings/gitis/crm_spec.rb, spec/services/bookings/gitis/entity_spec.rb, spec/services/candidates/registrations/gitis_registration_session_spec.rb, spec_external/gitis_crm_spec.rb
**Note:** This PR is currently based against the SE-1525 branch since it builds off that and this simplifies the diff for review
We've have a revised plan for the integration with Gitis Contacts. This PR implements most of that plan.
1. Assign Ownerid
2. Assign the country
3. Revised how telephone number and email address get updated
4. Assign the dbs certificate information
5. Removed references to `statecode`
6. Added support for attributes which are not written at either `create` or `update`
Note: Assignment of ownerid and country is a bit simplistic at the moment but is sufficient until I implement some relationship logic.
1. Check that creating a contact in Gitis still works
=> SE-1275 Updated attributes mapping

app/services/bookings/gitis/contact.rb, app/services/bookings/gitis/fake_crm.rb, spec/services/bookings/gitis/contact_spec.rb
`master` currently relies on Contact attributes which we don't yet have access to.
1. Remove the minor bits of code which depend on them
=> Temporarily removed support for Contact attributes we lack access to

config/environments/production.rb
We currently depend on some env vars which are not needed is most environments, and not yet configured in others.
Stub out until they are setup
This will get reverted once they are set in the production environments
=> Dont require env vars which are not yet used in production

spec_external/gitis_crm_spec.rb
Gitis test suite is broken because of the syntax error.
Add a missing comma
=> Fixed typo which got introduced into the Gitis testsuite

app/controllers/schools/dashboards_controller.rb, app/views/schools/dashboards/_new_requests_and_bookings.html.erb, features/schools/dashboard.feature, features/step_definitions/schools/dashboard_steps.rb
The confirm attendance counter was added before the confirm attendance feature, the two weren't integrated.
Plumb the counter in so it shows an accurate number of attendances to confirm
Ensure the count looks right. It's all bookings that have no attendance marked that are in the past.
=> Integrate the dashboard confirm attendance counter SE-1590

app/models/bookings/profile_publisher.rb
The confirmations controller uses the timestamp to check the latest profile
has been published, if a change occurs on the SchoolProfile, which is not
reflected on the Bookings::Profile then the user ends up in a loop.
For now we solve this by always setting the updated at timestamp
1. Code review
2. Do the testsuites still pass
=> Always set the updated at when publishing a profile

app/views/pages/privacy_policy.html.erb
There were a couple of small typos in our privacy policy
1. Removal of an errant 'at' at the end of a sentence.
2. Corrected a capitalisation of Get School Experience
1. Code review
=> Corrected typos in the original privacy policy content

app/models/bookings/booking.rb, features/step_definitions/schools/dashboard_steps.rb, spec/models/bookings/booking_spec.rb
We don't want to show incomplete bookings in the upcoming counter on the
dashboard
Phantom bookings were being showing in the upcoming bookings counter.
Exercise phantom bookings by limiting the upcoming scope to only available bookings
Create a booking within the upcoming window (2 weeks) but don't complete the last step. Expect it not to show in the manage bookings counter on school dashboard
=> Add accepted to the upcoming scope

app/views/candidates/registrations/placement_preferences/_form.html.erb, config/locales/en.yml, features/candidates/registrations/request_school_experience_placement/page_contents.feature, features/candidates/registrations/request_school_experience_placement/schools_with_flexible_availability.feature, features/step_definitions/candidates/registrations/application_preview_steps.rb, features/step_definitions/candidates/registrations/request_school_experience_placement_steps.rb, features/step_definitions/candidates/registrations/wizard_steps.rb, spec/features/candidates/registrations_spec.rb
This screen had some repeated text and was generally too long. The text
has been replaced with more succinct copy and now matches the prototype
=> Update wording on request school experience screen

app/controllers/candidates/registrations/sign_ins_controller.rb, app/views/candidates/registrations/sign_ins/update.html.erb, spec/controllers/candidates/registrations/sign_ins_controller_spec.rb, spec/services/candidates/registrations/gitis_registration_session_spec.rb, spec/views/candidates/registrations/sign_ins/update.html.erb_spec.rb
A Candidate may start the Registration process on one device (eg their laptop),
they will then expect to continue the process on the device they received their
sign in link on, potentially their phone.
We actually hold enough information to facilitate this - everything from the
first step, Personal Information, is overridden by the GiTiS Contact
information, and the school URN is included in the URN.
1. This PR removes some unnecessary processing of the PersonalInformation now we
instead override it with GitisRegistrationSession
2. Removes off the step check for just the token sign in since thats not
necessary in this context and it then allows the sign in to occur.
1. Code review
2. Testing process
1. Complete a full registration in a private browser session to ensure your in Gitis
2. …
=> SE-1640 Support switching devices as part of registration process

app/views/schools/show.html.erb
The old one was too wordy and not all information was completely
relevant.
Here it is alongside the prototype. The only difference is the sidebar link to 'DfE Sign-in Help' which doesn't exist yet in the Rails app
=> Update and simplify the school start page copy SE-1459

app/controllers/candidates/registrations_controller.rb, app/views/candidates/registrations/application_previews/show.html.erb, spec/features/candidates/registrations_spec.rb
If the candidate still needs to complete the email verification step
they should be shown a 'Continue' button check answers rather than
'Accept and Send'
Change the submit button text on application preview if the user still has to verify their email.
Application preview's submit button should show 'Accept and send' if gitis integration is enabled and the candidate is signed in otherwise it should show 'Continue'
=> Change button text if registration isn't complete

app/views/schools/on_boarding/confirmations/show.html.erb
User's were missing the link to return to their dashboard.
Reduce the content so the return to dashboard link is above the page fold.
Style the link as a button so it's more noticeable.
=> Se 1453/schools/onboarding/return to dashboard link

script/compose-school-experience.sh
The `deploy.sh` script deletes the created `compose-school-experience.yml` after the deployment so the appending behaviour is not immediately apparent. Only is seen when you kill the deploy script during the `az group deployment` .
overwrite rather than append.
Is used in the CD pipeline so requires merging etc. to test.
=> overwrite compose file rather than append

app/controllers/schools/contact_us_controller.rb, app/views/schools/contact_us/show.html.erb, app/views/schools/dashboards/show.html.erb, config/routes.rb, features/schools/contact_us.feature, features/schools/dashboard.feature, features/support/path_helper.rb
In case schools need to contact the DfE regarding School Experience there should be a single place with relevant contact details
Add a 'Contact us' page for schools. Currently it only has an email address, phone number to follow once set up
Make sure it looks ok and works correctly
=> Add DfE contact us page for schools SE-1415

app/services/bookings/gitis/contact.rb, spec/services/bookings/gitis/contact_spec.rb, spec/services/bookings/gitis/crm_spec.rb
Currently we write newlines into the GiTiS notes field using LF line separators, in order to show correctly in dynamics these probably need to be CRLF.
1. Change line endings to CRLF
1. Code review should be enough
=> Use CRLF (DOS) line endings when writing notes in Gitis

app/services/bookings/gitis/event_logger.rb, spec/services/bookings/gitis/event_logger_spec.rb
1. Currently the header row for the gitis logs is not aligned correctly
1. Correct alignment of header row
2. Appropriately pad URN width
1. Code review
=> Alignment fixes to the gitis logging

app/helpers/schools/availability_preference_helper.rb, app/views/schools/availability_preferences/edit.html.erb, features/schools/availability_preferences/edit.feature
There's a new design for the availability preference screen that now has some extra text
beneath the radio buttons with example data
The new design includes features that aren't supported by the form
builder, namely hints on radio buttons and additional (example)
information that's related to the radio button.
As a result, the default Rails form builder is used and the inputs are
manually surrounded by the appropriate HTML.
Ensure it looks ok. This is a good candidate for replacement with the new form builder when it's deemed to be the right time 👍🏽
=> Update the date preferences screen

app/models/bookings/registration_contact_mapper.rb, spec/models/bookings/registration_contact_mapper_spec.rb
If there is whitespace in an email address, gitis still matches it returns data to us but we then treat that data as invalid, preventing the user from signing in.
1. Strip the whitespace from the returned email address in the mapper.
1. Code review
=> Fix for whitespace in email addresses held in gitis

app/services/candidates/registrations/gitis_registration_session.rb, spec/services/candidates/registrations/gitis_registration_session_spec.rb
Currently we break if the date of birth in a matched Gitis Contact is blank because this then fails our own validation.
1. Fall through to the users supplied value in the absence of the absence of a value in Gitis
1. Code review
=> Handle blank fields supplied from Gitis which we require values for

app/helpers/application_helper.rb, app/views/schools/errors/not_registered/show.html.erb, spec/helpers/application_helper_spec.rb
The `current_user_full_name` is ordinarily only used after we've checked
that the user is present (in the Phase Banner partial).
The one other place it's used is on the not registered error page. That call has been
wrapped to prevent the paragraph from being shown if the user is absent
and the method will now return 'Unknown' if the current user isn't a
valid `UserInfo` object
=> Add safeguards around current_user_full_name method

app/jobs/candidates/registrations/placement_request_job.rb, app/notify/notify_email/school_request_confirmation_link_only.2a5a54b8-17cb-4da8-94ce-1647d6bf1da3.md, app/notify/notify_email/school_request_confirmation_link_only.rb, spec/jobs/candidates/registrations/placement_request_job_spec.rb, spec/notify/notify_email/school_request_confirmation_link_only_spec.rb
We want School Administratrors to use our Dashboard to view Placement Requests and interact with the service.
1. Removed information from the Email so they are required to engage with the service.
1. Code review
2. Test url in email works
=> Switch to simplified notification email for schools

app/notify/notify_email/candidate_request_confirmation.3860fb06-9af2-49c8-ac0b-007b9f360033.md, app/views/candidates/registrations/placement_requests/show.html.erb
Revert summer holiday delay warnings. The email change has already been made on Notify and is reflected by the change to the candidate request notification template.
=> Revert summer holiday warnings SE-1548

app/controllers/candidates/registrations/placement_requests_controller.rb, app/jobs/bookings/log_to_gitis_job.rb, app/jobs/candidates/registrations/accept_privacy_policy_job.rb, app/jobs/gitis_job.rb, app/services/bookings/gitis/accept_privacy_policy.rb, app/services/bookings/gitis/candidate_privacy_policy.rb, app/services/bookings/gitis/privacy_policy.rb, config/environments/development.rb, config/environments/production.rb, config/environments/servertest.rb, config/environments/test.rb, spec/controllers/candidates/registrations/placement_requests_controller_spec.rb, spec/jobs/candidates/registrations/accept_privacy_policy_job_spec.rb, spec/services/bookings/gitis/accept_privacy_policy_spec.rb, spec/services/bookings/gitis/candidate_privacy_policy_spec.rb, spec/services/bookings/gitis/privacy_policy_spec.rb, spec_external/gitis_crm_spec.rb
When a Candidate completes the application process, they accept the current privacy.
1. Record acceptance of this within Gitis by creating an appropriate dfe_CandidatePrivacyPolicy entity for any new Contacts we create
1. Code review
This currently only applies to new Contacts - there will be a follow on PR for existing contacts.
=> SE-1582 Accept privacy policy

app/controllers/schools/availability_preferences_controller.rb, app/helpers/schools/dashboards_helper.rb, app/views/schools/dashboards/_manage_dates.html.erb, app/views/schools/dashboards/_no_placement_dates_warning.html.erb, features/schools/availability_preferences/edit.feature, features/schools/dashboard.feature, features/schools/placement_dates/index.feature
The **Manage dates** section of the dashboard still wasn't clear
Now there is only one link in the **Manage dates** section:
Users will first need to pick fixed or flexible, then, depending on their choice they'll be directed to the date manager or availability description page.
Ensure the changes make sense and everything works as expected. Wording agreed with @fredbrenton
=> Send users through choose date type screen SE-1541

app/services/bookings/gitis/candidate_privacy_policy.rb, app/services/bookings/gitis/contact.rb, app/services/bookings/gitis/country.rb, app/services/bookings/gitis/entity.rb, app/services/bookings/gitis/privacy_policy.rb, app/services/bookings/gitis/teaching_subject.rb, spec/services/bookings/gitis/entity_spec.rb, spec/support/test_entity.rb
Currently we require manual assignment of entity attributes on initialize - this is a product of prior assumptions on how we'd handle mapping attributes and is no longer necessary.
1. Automatically assign recognised entity attributes as part of the default initialize method.
2. Added an inheritable method to define custom assignments.
1. Code review
=> Populate entity attributes on initialize

app/helpers/application_helper.rb, app/views/candidates/schools/index.html.erb
The summary_row method was always rendering the action element even when
it's not required. Now the summary_row helper takes an additional
show_action argument that overrides its display, in the search results
it is set to false
=> Don't show the action list when it's not required SE-1593

app/views/candidates/home/index.html.erb
Remove an unnecessary bit of text from the candidate home page
=> Remove unnecessary text from candidate start page SE-1676

app/services/candidates/registrations/application_preview.rb, app/services/candidates/registrations/personal_information.rb, spec/controllers/candidates/registrations/sign_ins_controller_spec.rb, spec/services/candidates/registrations/application_preview_spec.rb, spec/services/candidates/registrations/personal_information_spec.rb
Currently we validate the personal information fields we get back from Gitis, but this data may not comply with our validation rules. 
We should also not be letting the user change these it in Gitis. 
This leaves the user unable to progress with their registration.
1. Don't validate these fields if we will not allow the user to change them.
1. Code review
2. Testing
- Change Fake CRM to return a nil date_of_birth
- Start a registration using a private browser
- Simulate device switch by closing down all private browser sessions
- Start a new private browser session, use the verification URL
- You should be able to successfully complete the registration
=> SE-1664 Dont revalidate gitis data

app/services/bookings/gitis/fake_crm.rb, features/schools/confirmed_bookings/show.feature, features/schools/placement_requests/show.feature, spec/features/candidates/registrations_spec.rb
Fake CRM currently returns an invalid postcode. This results in the registration specs for a known candidate passing 'accidentally'
Its also annoying when doing manual testing with fake crm.
1. Changed FakeCRM to return a valid postcode
1. Code review
=> Changed FakeCRM to return a valid postcode

app/assets/stylesheets/school-search.scss, app/views/candidates/schools/index.html.erb
Users who navigate with the keyboard have to tab through a large number of filters before getting to the search results.
Adds a hidden skip to results link that's only focusable via the keyboard.
On the search results page start tabbing, expect to see a "skip to results" link appear. Hitting enter on this link should jump you straight to the results and allow you to tab through them.
=> Se 1564/dac fixes/focus order

db/migrate/20190911085544_add_secondary_subject_flag_to_subjects.rb
In the dev environment this migration failed because the schema hadn't
been reloaded between the column being added and the following line
attepting to write to it.
Calling #reset_column_information between those two events should
fix it
Ensure it looks sensible. Appropriate Rails docs [here](https://api.rubyonrails.org/classes/ActiveRecord/ModelSchema/ClassMethods.html#method-i-reset_column_information).
=> Force column info reload before appyling update SE-1454

app/views/candidates/schools/index.html.erb, features/candidates/schools/search/results/filtering.feature
DAC feed back indicated the page reload when the filter is applied was
disorienting to blind users.
Remove the filter and instead provide a submit button.
Filters on the school search results page shouldn't auto reload when clicked, there should now be a search button at the bottom of the page.
=> Removes instant-filter from search filters

app/views/schools/placement_dates/edit.html.erb, app/views/schools/placement_dates/new.html.erb
Fix from QA
Hide "You'll be able to add subject-specific dates soon." if subject specific dates are enabled
=> Don't show inset if subject_specific_dates enabled.

config/initializers/password_protection.rb
Currently we set multiple http auth checks on the `/deployment.txt` endpoint when a global auth pair is defined. This can never pass
1. Skip the global auth for the `/deployment.txt` end point
1. Code review
=> Avoid incompatible layers of HTTP Auth definitions

db/migrate/20190911085544_add_secondary_subject_flag_to_subjects.rb
This migration was causing problems in environments where the record
isn't found
Following on from #929
Make the migration not raise when the subject `Primary` isn't found
=> Make update not raise exception if row not found

azure-pipelines.yml
There have been intermittent database truncation errors in the CI functional tests.
Use `--no-deps` with  `docker-compose run` so that there is no attempt to start dependent services (even though it should only start dependent services if they are not already started without the flag). This simplifies the logs and will help work out what is going on with the truncation errors.
This is only a minor change and the test is whether the CI functional tests succeed.
=> use --no-deps in CI functional tests

app/views/schools/on_boarding/profiles/show.html.erb, features/step_definitions/schools/onboarding_steps.rb
Schools were worried they were losing formatting when pasting content
from their websites in to the school description.  Wrap description on
check answers in simple_format so it keeps formatting. The
candidates/schools#show view already wraps descriptions in
simple_format.
=> Keep formatting on pasted text

app/controllers/schools/sessions_controller.rb, spec/controllers/schools/sessions_controller_spec.rb
State mismatch errors where the state is missing (none returned from DfE Sign-in) weren't
being reported because they were failing earlier, because of the use of `#fetch`. This was done
intentionally to highlight the problem but has been reverted to give users a better experience by
showing them a more-relevant error message
Revert the change in accessing params by fetch instead of square bracket notation.
Also, this PR includes a change that checks for errors returned by DfE Sign-in. These have been
observed in production but fail with a KeyError which just shows a generic error page, these
are now swept up by AuthFailedError (and logged)
Ensure everything looks sensible and works. The error handling can be tested by logging out of the app then navigating to …
=> Handle session expiry errors more gracefully SE-1681

app/jobs/candidates/registrations/placement_request_job.rb, app/notify/notify_email/candidate_request_confirmation_no_pii.8ee470a1-0b94-48ee-9fe7-98b7beb8921c.md, app/notify/notify_email/candidate_request_confirmation_no_pii.rb, spec/jobs/candidates/registrations/placement_request_job_spec.rb, spec/notify/notify_email/candidate_request_confirmation_no_pii_spec.rb
Removes PII section from candidate request confirmation email.
Should look sensible.
=> Remove PII from candidate request confirmation.

features/candidates/dashboard.feature
It passes *everywhere* except for in CD with Firefox (via Selenium).
More investigation needed
=> Mark failing scenario as WIP

app/views/schools/on_boarding/fees/_form.html.erb
Screen readers browsing out of context were having trouble identifying
what the radio inputs related to.
=> Add aria-labels for radio buttons

app/views/schools/on_boarding/descriptions/_form.html.erb
When browsing out of context with a screen reader it's not clear what
"View description example" refers to.
=> Add aria-label to sample description

app/views/schools/confirmed_bookings/show.html.erb
Currently the page titles are included in logging to AppInsights and potentially Google Analytics. The page title when viewing a confirmed booking includes the candidates name. This looks to be the result of a merge conflict since the page title is set twice.
1. Remove the candidate name from the page title
=> Removed candidate name from page title

jmeter/schoolexperience.jmx
Load tests are failing again.
Made the check for Buile Hill to be less sensitive to the full name i.e. just the text Buile Hill
Will only be verified in CD (Staging)
=> just check for Buile Hill rather than a full name

app/views/schools/dashboards/_your_school_is_disabled.html.erb, app/views/schools/dashboards/show.html.erb, features/schools/dashboard.feature, features/step_definitions/schools/dashboard_steps.rb
Schools sometimes don't realise that their profiles are disabled and won't appear in results
Add a warning that is displayed at the top of their dashboard when onboarded schools are disabled
=> Add disabled warning to top of dashboard - SE-1741

config/initializers/content_security_policy.rb
Content security policy was blocking some of google analytics requests.
Allow google-analytics in the connect-src directive.
Ensure GA isn't being blocked any more, should see it in the connect-src portion of the content security policy header.
=> Add google-analytics to connect-src

app/views/candidates/schools/_access_needs_statement.html.erb
The start request button was too close to the access needs badge.
=> Increase spacing after access needs badge

app/controllers/candidates/placement_requests/cancellations_controller.rb, app/notify/notify_email/candidate_booking_cancellation.rb, app/notify/notify_email/candidate_booking_cancellation_no_pii.af2311b2-7b7e-4342-b1da-bba957273b3e.md, app/notify/notify_email/candidate_request_cancellation.rb, app/notify/notify_email/candidate_request_cancellation_no_pii.86b06712-cb58-4cc7-82a1-3748cc9ad671.md, spec/controllers/candidates/placement_requests/cancellations_controller_spec.rb, spec/notify/notify_email/candidate_booking_cancellation_spec.rb, spec/notify/notify_email/candidate_request_cancellation_spec.rb
Emails sent to the candidate to confirm their cancellation of a booking or placement request included the candidate's name, this is unnecessary pii.
Removes candidate's name from booking and placement request withdrawal emails.
Should look sensible and emails should still work!
=> Se 1720/remove candidate name from withdrawal email

app/assets/stylesheets/global-styles.scss, app/controllers/schools/confirmed_bookings_controller.rb, app/controllers/schools/dashboards_controller.rb, app/controllers/schools/placement_requests_controller.rb, app/helpers/schools/placement_requests_helper.rb, app/models/bookings/booking.rb, app/models/bookings/placement_request.rb, app/models/bookings/placement_request/cancellation.rb, app/models/concerns/view_trackable.rb, app/views/schools/confirmed_bookings/_booking_table.html.erb, app/views/schools/confirmed_bookings/index.html.erb, app/views/schools/confirmed_bookings/show.html.erb, app/views/schools/dashboards/_new_requests_and_bookings.html.erb, db/migrate/20190919111332_add_viewed_at_to_bookings_placement_request_cancellations.rb, db/schema.rb, features/schools/confirmed_bookings/index.feature, features/schools/confirmed_bookings/show.feature, features/schools/dashboard.feature, features/schools/placement_requests/index.feature, features/step_definitions/schools/bookings_steps.rb, features/step_definitions/schools/dashboard_steps.rb, features/step_definitions/schools/placement_request_steps.rb, spec/controllers/schools/placement_requests_controller_spec.rb, spec/factories/bookings/bookings_factory.rb, spec/factories/bookings/placement_request/cancellations.rb, spec/factories/bookings/placement_request_factory.rb, spec/models/bookings/booking_spec.rb, spec/models/bookings/placement_request_spec.rb
The counters on the dashboard were confusing users.
This kept getting larger as I spotted more stuff, didn't think it warranted a pr chain though!
Updates the placement request counter to show new (no booking, no cancellation) placement requests and placement requests with an unviewed candidate cancellation.
Updates the bookings counter to only show those with an unviewed candidate cancellation.
Updates the bookings index page to only show upcoming bookings. Past bookings will appear the confirm attendance section for the school to action.
Adds candidate cancellation details to the booking show template as we were missing that.
Adds a status column to bookings index page and full list of statuses to bookings and placement requests (wording agreed with Fred)
Ensure only placement requests …
=> Se 1718/schools/dashboard counters

app/services/candidates/registrations/behaviours/placement_preference.rb, spec/services/candidates/registrations/placement_preference_spec.rb
When the placement request is created on a school that has flexible
dates and the school subsequently changes to fixed, the saving context
around the presence of a bookings placement date changes rendering the
existing placement requests invalid.
This problem hasn't yet reared its head but now we are updating the
`viewed_at` timestamp it's possible to trigger it as the placement
request object is invalid.
Ensuring that either the availability description or placement date
being present should be sufficient and both directions are accounted for
Ensure it looks sensible and won't break anything!
=> Only check that placement requests have either availability or a placement date SE-1776

app/controllers/pages_controller.rb, app/views/pages/maintenance.html.erb, config/environments/development.rb, config/environments/production.rb, config/environments/servertest.rb, config/environments/test.rb, config/routes.rb, spec/controllers/pages_controller_spec.rb
We will need to take the site offline when we move the hosting
1. Add an environment variable controlled maintenance mode which shows the maintenance page for all requests apart from healthchecks
1. set `MAINTENANCE_MODE=1` and check different paths, they should all return 503s with the maintenance page
=> Added maintenance mode to take the site offline

app/models/concerns/view_trackable.rb
This is a reaction to a bug seen in prod where validation failed due to the context of the placement request changing. In this case it was subjects being absent. 
Validation is now bypassed when updating the viewed_at `timestamp`
=> Change update! to update_column to avoid validation

db/schema.rb
This wasn't doing any harm but showing up in subsequent migrations. Probably caused by a merge.
=> Remove duplicate line from schema file

app/services/candidates/registrations/contact_information.rb, app/services/candidates/registrations/personal_information.rb, config/locales/en.yml, spec/services/candidates/registrations/contact_information_spec.rb, spec/services/candidates/registrations/personal_information_spec.rb
The GITIS API rejects some records that are too long
Add length validation for various contact and personal information fields that are sent to the GITIS API.
Ensure the validations all make sense and match those referenced in the ticket.
```
emailaddress1 = 100
emailaddress2 = 100
address1_line1 = 250
address1_line2 = 250
address1_line3 = 250
address1_city = 80
address1_stateorprovince = 50
address1_postalcode = 20
telephone1 = 50
telephone2 = 50
```
=> Add length validations matching the gitis CRM API SE-1503

features/schools/confirmed_bookings/editing_a_date.feature, features/schools/confirmed_bookings/show.feature, features/step_definitions/schools/bookings_steps.rb, features/step_definitions/schools/placement_requests/confirm_booking_steps.rb
We had a couple of hard coded 'future' dates that are now in the past. Remove them and replace with something that won't break 🤦🏽‍♂️
=> Remove hard-coded dates from features

app/assets/stylesheets/cookie-banner.scss, app/assets/stylesheets/school-placement-requests.scss
The update to govuk frontend has lightened govuk light-blue, when we
lighten it 50% it becomes white. Lightening it 35% fixes the issue.
=> Fix email-preview colour

app/helpers/candidates/school_helper.rb, spec/helpers/candidates/school_helper_spec.rb
Since the initial implementation of search the way the search is
described has improved to the point where the original location isn't as
important as it was (now we show the result from Geocoder rather than
the search term in most cases).
To improve the experience when searching for postcodes, the initial
query is no longer capitalised when a match isn't found. This should be
less confusing for the person searching as it will match exactly what
they typed in.
Additionally, now we no longer support search near my location, that
functionality has been removed from the description method and
associated specs
Ensure it makes sense and works
The following has changed:
Searching for a partial postcode will display the search term as it was typed, so 'DY3' will be displayed as 'DY3', 'dy3' as …
=> Stop describe_current_search capitalising searches SE-1114

app/controllers/schools/sessions_controller.rb, spec/controllers/schools/sessions_controller_spec.rb
Sentry was receiving a lot of NoIDTokenError errors which created a lot of noise 
When a user is logging out, the fact they have no `id_token` isn't really important enough to warrant an error, so instead of failing just log the error, clear the session and redirect them
Ensure it looks sensible and the logout flow works as normal
=> Stop reporting no id token errors SE-730

.rubocop.yml, azure-pipelines.yml, spec_external/gitis_crm_spec.rb
Run `govuk-ruby-lint` against `./spec_external` too.
Rubocop wasn't detecting the `spec_external` file as being specs and failing with on `Metrics/Blocklength`, so that cop is disabled for both `spec` and `spec_external` via `.rubocop.yml`.
=> Lint external specs

app/controllers/schools/confirm_attendance_controller.rb, features/schools/confirm_attendance.feature, features/step_definitions/schools/confirm_attendance_steps.rb
Schools were marking cancelled bookings as not-attended due to them not being excluded from the 'confirm attendance' screen
Jordan Russell masterminded the fix by using the `.not_cancelled` scope to prevent cancelled bookings from being retrieved
Sanity check
=> Exclude cancelled bookings from attendance confirmation SE-1802

Gemfile.lock, spec/services/schools/dfe_sign_in_api/organisations_spec.rb
Various gems have become stale with new versions available
1. Upgrade to use those versions
2. Amend error classes in tests for the shift from Faraday 0.15 to 0.16
1. Do tests continue to pass
=> Gem updates 04 oct 2019

app/helpers/application_helper.rb, app/views/pages/accessibility_statement.html.erb, app/views/pages/cookies_policy.html.erb, app/views/pages/help_and_support_access_needs.html.erb, app/views/pages/migration.html.erb, app/views/pages/privacy_policy.html.erb, app/views/pages/service_update.html.erb, spec/helpers/application_helper_spec.rb
Some of the simple content pages are missing page titls
1. Added a helper to assign both page title and write out the page heading
2. Changed various pages to use it
1. Code review
2. Test the pages in the Pages controller have an appropriate title in the browser
=> Add missing titles on accessibility pages

app/views/schools/on_boarding/_school_fees_shared_form.html.erb, config/locales/en.yml, features/schools/onboarding/administration_fee.feature, features/schools/onboarding/other_fee.feature, features/step_definitions/schools/onboarding_steps.rb
The Admin/DBS/Other Fees pages in the Schools onboarding section are out of sync with the prototype app
1. Use heading style for 'Enter the number of pounds'
2. Use heading style for 'Explain how the fee is paid'
3. Added a hint to 'Explain how the fee is paid'
1. Compare to pages in prototype.
2. Check test suite still passes
=> Updated content of fees pages

app/models/bookings/booking.rb, features/step_definitions/schools/bookings_steps.rb, spec/models/bookings/booking_spec.rb, spec/models/bookings/profile_publisher_spec.rb
Currently we only show the next 2 weeks worth of upcoming bookings, this prevents the user from seeing accepted bookings further in the future.
1. Removed the confusing 'upcoming' scope
2. Added a 'future' scope
3. Use the future scope for the needing attention scope which in turn is used to generate the list for the Confirmed bookings screen
4. Changed the Booking factory to create bookings for increasingly far future dates
5. Stop enforcing the date for the confirmed bookings feature, this means it falls back to the 'increasingly far future' date, which in turn means it will test for the presence of a booking beyond the 2 week horizon.
1. Code review
2. Testing
=> SE-1784 Show all upcoming bookings

app/views/candidates/registrations/contact_informations/_form.html.erb
When a candidate is recognised in the CRM, they are actually asked to confirm their Contact Details instead of Enter them.
1. Update the page title to clarify whether the user is Entering or Confirming their contact details
1. Check page title for unrecognised candidate
2. Check page title for recognised candidate
=> Updated Contact Details title when the user is known to Gitis

app/services/bookings/gitis/api.rb, spec/services/bookings/gitis/api_spec.rb
The errors from Gitis are currently not exposing the URL we are failing to access
1. Include the url in the exception
2. Ensure the error message is not blank, just use the whole body if it is
1. Code review
=> Improved error messages in unexpected Gitis responses

app/services/bookings/gitis/auth.rb, spec/services/bookings/gitis/auth_spec.rb
Currently we are getting occasional expiries from Gitis tokens. I think this
maybe caused by page queries with multiple gitis requests in them. The first
occurs within the expiry time of the token, the token then expires during this
time window. The second request to gitis then fails because the token has by now
expired.
1. Expire Gitis tokens at 55 minutes instead of 1 hour
2. Also verify that the retrieved token isn't blank - conceivably possible if Redis is glitchy
1. Code review
2. Does gitis still work
=> Expire Gitis tokens at 55 minutes instead of 1 hour

app/views/candidates/registrations/confirmation_emails/show.html.erb, spec/features/candidates/registrations_spec.rb
The confirmation screen at the end of the Candidate journey needs to make it clearer that the Candidate needs to click the link in the email acccount
1. Updated the content according to the requested changes.
1. Verify content is correct
=> SE-1613 Updated content on Placement Request confirmation screen

app/controllers/schools/dashboards_controller.rb, features/schools/dashboard.feature, features/step_definitions/schools/dashboard_steps.rb
The dashboard counter number was greater than those shown in the confirm attendances list
Apply the same scopes so cancelled bookings don't affect the counter
Ensure it works and looks sensible
=> Add missing scopes to confirm attendances counter SE-1836

app/views/pages/cookies_policy.html.erb, app/views/pages/help_and_support_access_needs.html.erb, app/views/pages/schools_privacy_policy.html.erb
The javascript back controller is not compatible with the 'scroll to top' of page behaviour - since that pushes a navigation target onto the stack. Which the back link then pops back off.
1. Removed the back link js controller from pages with scroll to top.
2. Also added missing back link on cookies page.
1. Code review
2. Behaviour test
=> SE-1738 Back link problems on access needs page

Gemfile, Gemfile.lock
We don't yet have a manifest file which sprockets 4.0 requires.
1. Lock sprockets to the pre-4.0 release
=> Lock sprockets to pre-4.0

app/controllers/schools/confirmed_bookings/date_controller.rb, app/models/bookings/booking.rb, app/views/schools/confirmed_bookings/_booking.html.erb, app/views/schools/confirmed_bookings/date/uneditable.html.erb, spec/controllers/schools/confirmed_bookings/date_controller_spec.rb, spec/models/bookings/booking_spec.rb
Currently school administrators can edit the date of bookings even when they are in the past or have been cancelled.
1. Don't provide the change link when its not relevant
2. If the user does end up at the end point (race condition/multiple pages open) - show an error screen instead.
1. Code review
2. Manually visit the end point for a cancelled booking
=> Prevent users from editing the date of bookings

app/services/candidates/registrations/application_preview.rb, app/services/candidates/registrations/registration_state.rb, app/services/candidates/registrations/registration_step.rb, spec/services/candidates/registrations/registration_state_spec.rb
Want to keep the knowledge about which wizard journey(quest) we're on in one place, this was currently being inferred based on if the school had fixed dates.
Refactors registration state to make it easier to add in new steps.
RegistrationState now generates a <step>_in_journey? method for each step to determine whether it should be shown or not based on the registration_session.
Updates application preview to reference registration_state for whether it needs to show subject_and_date_information
Everything should still pass.
=> Feature/subject specific dates/refactor registration state

app/controllers/candidates/registrations/subject_and_date_informations_controller.rb, app/views/candidates/registrations/subject_and_date_informations/_form.html.erb, features/candidates/registrations/subject_and_date_information.feature, features/step_definitions/candidates/registrations/subject_and_date_information_steps.rb
Durations weren't being displayed on the subject/date selection screen
Add missing durations to dates on the subject/date selection screen.
Additionally, subjects are now sorted alphabetically, the screenshot is slightly out-of-date
Make sure it looks ok, here's a preview
=> (Subject-specific dates) Add durations to the subject and date options

app/services/candidates/registrations/placement_preference.rb, app/services/candidates/registrations/registration_session.rb, spec/factories/candidates/registrations/legacy_registration_session.rb, spec/services/candidates/registrations/application_preview_spec.rb, spec/services/candidates/registrations/registration_session_spec.rb
In flight registrations for fixed date schools need to handle the new
subject specific code.
If the candidate has completed the placement_preference step for a fixed
date school the placement_preference attributes will contain a
bookings_placement_id, we can use this to identify legacy sessions.
We can treat a legacy session for fixed date school as the candidate
having applied for a non subject_specific date and build a valid
subject_and_date_information_step. This will allow the candidate to
continue and also allow any background jobs to work.
bookings_placement_date_id has been readded to placement_preference to
preserve backwards compatability. It has been added as an attr_accessor
so it doesn't show up in the models attributes and overwrite the
bookings_placement_date_id from …
=> Handle in flight legacy sessions.

app/forms/schools/placement_dates/configuration_form.rb, spec/forms/schools/placement_dates/configuration_form_spec.rb
Dates that don't support subjects were not being shown in the
placement_dates index as they weren't published.
=> (Subject-specific dates) Publish dates that don't support subjects

app/presenters/candidates/school_presenter.rb, spec/presenters/candidates/school_presenter_spec.rb
Subjects on the subject-specific dates page were being shown in the order they were added
Ensure subjects are sorted alphabetically. This isn't done using a scope as we need to make sure 'All subjects' is included
Ensure it looks sensible and works
=> (Subject-specific dates) Sort subjects on the profile page alphabetically

app/controllers/candidates/registrations/subject_and_date_informations_controller.rb, app/presenters/candidates/school_presenter.rb, spec/presenters/candidates/school_presenter_spec.rb
Date order isn't enforced when displaying subject-specific dates
Enforce the order using the `.in_date_order` scope
=> (Subject-specific dates) Ensuring dates are ordered properly

app/assets/stylesheets/subject-and-date-information.scss, app/controllers/candidates/registrations/subject_and_date_informations_controller.rb, app/helpers/candidates/registrations/subject_and_date_information_helper.rb, app/views/candidates/registrations/subject_and_date_informations/_form.html.erb, config/locales/en.yml, features/candidates/registrations/subject_and_date_information.feature, features/step_definitions/candidates/registrations/subject_and_date_information_steps.rb, features/step_definitions/common_steps.rb
The form was lacking in some areas, namely in error handling, not having a sensible title and lacking a 'back' button 
Add better error handling, title and back button to the dates and subjects page
Ensure it looks sensible, here's the form with errors:
=> (Subject-specific dates) Subject and date form improvements

app/notify/notify_email/candidate_request_confirmation_no_pii.8ee470a1-0b94-48ee-9fe7-98b7beb8921c.md, app/notify/notify_email/school_request_confirmation_link_only.2a5a54b8-17cb-4da8-94ce-1647d6bf1da3.md, app/views/candidates/registrations/placement_requests/show.html.erb, spec/features/candidates/registrations_spec.rb
The confirmation screen at the end of the Candidate creating a Placement Request is out of date with the prototype content.
1. Bring the page up to date with the content in the prototype for the placement request confirmation page
2. Synced with email content in Notify
=> SE-1686 Update school will contact you language

app/services/candidates/registrations/personal_information.rb, spec/services/candidates/registrations/personal_information_spec.rb
A user was able to get through the Personal Information email validation with an unqualified domain name - whilst technically valid, this isn't an address type we wish to support. The more normal scenario is its a typo from the user and they've missed part of their address.
1. Ensure the hostname has multiple component parts
I've tried to avoid 'over validating' - particularly since domain names can now be UTF-8, and different systems support different rules for the username component.
1. I've added a couple of additional addresses to be checked in the tests
2. I've reworked the tests to use the shoulda helpers to improve clarity
3. I've added an additional regex on top of the existing regex which is quite loose but does ensure there are multiple parts to the domain name
4. I now strip …
=> SE-1876 Ensure user has entered a fully qualified email address

config/locales/en.yml
Add missing full stop to `end_time` label 🤦🏽‍♂️
=> Add missing full stop to end time label

app/controllers/candidates/registrations/subject_and_date_informations_controller.rb, app/services/candidates/registrations/subject_and_date_information.rb, app/views/candidates/registrations/subject_and_date_informations/_form.html.erb, features/step_definitions/candidates/registrations/subject_and_date_information_steps.rb, spec/services/candidates/registrations/subject_and_date_information_spec.rb
The `SubjectAndDateInformationsController` was a bit heavy
Move the list-building functionality out to the `Candidates::Registrations::SubjectAndDateInformation` and enforce sorting
Ensure it looks sensible and works
=> Separate subject and date info logic into registration step SE-1804

app/views/pages/accessibility_statement.html.erb
Aria attributes are currently showing up on a link on the accessibility page.
1. Correct the mailto syntax to avoid the aria attributes being shown to the user
1. Check the page
2. Code check
=> Corrected email link on accessibility statement

app/views/schools/availability_preferences/edit.html.erb
When examples were listed normally on the page some users thought the
example data was real.
Move the examples inside details tags and hide by default
Ensure it looks ok:
=> Move date option examples inside details tags

config/locales/en.yml, features/candidates/registrations/education.feature
This fix hasn't been been applied to other occurrences of 'explaination'
in attribute names because with the values being stored in Redis and not
controllable by migrations we run the risk of breaking in-flight
registrations.
=> Fix typo in the word explanation in locales file SE-1886

config/candidate_form_options.yml
The **What stage are you at with your degree?** list isn't in the most logical order
Move _I don't have a degree and am not studying for one_ down to the bottom of the known options (second last, above 'Other')
🤷🏽‍♂️
=> Move "I don't have a degree" down in degree list

app/controllers/candidates/placement_requests/cancellations_controller.rb, app/models/bookings/placement_request/cancellation.rb, app/views/candidates/placement_requests/cancellations/_show_booking_cancelled_by_candidate.html.erb, app/views/candidates/placement_requests/cancellations/_show_booking_cancelled_by_school.html.erb, app/views/candidates/placement_requests/cancellations/_show_placement_request_cancelled_by_candidate.html.erb, app/views/candidates/placement_requests/cancellations/_show_placement_request_cancelled_by_school.html.erb, app/views/candidates/placement_requests/cancellations/show.html.erb, spec/controllers/candidates/placement_requests/cancellations_controller_spec.rb
Previously if a candidate followed the cancel placement request link in
the confirmation email to a placement request that the school had
already rejected then they would get an error as we were fetching the
candidate_cancellation which would be nil.
Add templates to handle candidate viewing school
cancellations/rejections
Manual testing if required:
Create a placement request and reject it as the school, visit the cancellation url `/candidates/cancel/<booking.token>`. You should be directed to the appropriate template
Create a booking and cancel it as the school, visit the cancellation url `/candidates/cancel/<placement_request.token>`. You should be directed to the appropriate template.
=> Handle showing requests cancelled by school

Gemfile.lock, app/views/candidates/registrations/educations/_form.html.erb
Prototype has additional text before the select box.
Add the new text from the prototype.
Bump form builder version to support passing markup to collection_select.
The degree subject selector should have the additional text to match the text on [this](https://school-experience-rolling.herokuapp.com/register/account-info) page.
=> Adds instructions  text to education subject

app/forms/schools/on_boarding/dbs_requirement.rb, app/presenters/schools/on_boarding/school_profile_presenter.rb, app/views/schools/on_boarding/dbs_requirements/_form.html.erb, spec/forms/schools/on_boarding/dbs_requirement_spec.rb
Removes presence validation on no_dbs_policy_details making the additional details field optional if a school admin selects that they don't require dbs checks.
Adds guidance to the dbs requirements screen (start of the wizard) that is present in the prototype.
Manual testing if desired: On board a new school, select no for dbs requirements, expect not to have to provide additional details.
=> Se 1839/schools/on boarding/dbs requirement fixes

app/views/schools/on_boarding/dbs_fees/new.html.erb, config/locales/en.yml
Some hint text is no longer accurate
Replace the hint text and standardise on using the locales file so spacing is consistent on the form
Does it look ok?
=> Remove no-longer-accurate text from hints

app/controllers/schools/confirmed_bookings/date_controller.rb, app/views/schools/confirmed_bookings/date/edit.html.erb, config/locales/validates_timeliness.en.yml, features/schools/confirmed_bookings/editing_a_date.feature, features/schools/placement_dates/new.feature, features/step_definitions/schools/bookings/editing_a_date_steps.rb, spec/controllers/schools/placement_requests/acceptance/confirm_booking_controller_spec.rb
The change_booking_date method always returned true, even when the
booking wasn't saved.
This process has been simplified by moving the
logic up to the if statement and removing the wrapping transaction.
Also, add a missing error summary to the page and specs covering the
behaviour.
Ensure it looks sensible and new features cover the behaviour
=> Stop invalid bookings from being treated as saved SE-1894

app/forms/schools/placement_dates/configuration_form.rb, app/views/schools/placement_dates/configurations/new.html.erb, config/environments/development.rb, config/environments/servertest.rb, config/environments/test.rb
The do you have limited availability section of the placement_date form
was added as it was in the prototype at the time of implementing subject
specific dates, however it's a seperate piece of work.  This has been
feature flagged off, until the canidate side of the work has been done.
All placement dates will have no limit to the maximum number of
bookings, until the feature is enabled.
Manual testing:
Disable the feature 'capped_bookings' in development, set up a new subject specific date, it should work as expected,
=> Feature flag has_limited_availability

app/views/schools/placement_requests/show.html.erb, features/schools/placement_dates/show.feature, features/schools/placement_requests/show.feature, features/step_definitions/schools/placement_request_steps.rb
SE-1898
When subject-specific bookings are made the school _should_ be able to see the selected subject on the placement request screen. It's currently omitted
Add requested subject to the placement request show screen. It should only be displayed for subject-specific requests.
Ensure it looks ok
=> Show subject specific date on placement request show SE-1898

app/presenters/candidates/school_presenter.rb, spec/presenters/candidates/school_presenter_spec.rb
SE-1804
Durations had been unintentionally omitted from the date/subject list
They have now been added, the layout matches the following page
Ensure it looks ok and the code makes sense
=> (Subject-specific dates) Add the duration to dates on the school profile

app/services/candidates/registrations/behaviours/subject_and_date_information.rb, app/services/candidates/registrations/subject_and_date_information.rb, db/migrate/20191029134926_remove_bookings_placement_dates_subjects_from_bookings_placement_requests.rb, db/schema.rb, features/step_definitions/schools/placement_request_steps.rb
SE-1804
This column is no longer used by bookings_placement_requests as we store
the date and the subject separately on the placement_request
Removes the bookings_placement_dates_subject_id from bookings_placement_request.
Moves the validation for this field out of the validations that are shared with placement_request to the SubjectAndDateInformation model.
Not sure on the revert migration, it's probably best to remove the migration that added this column from the subject_specific_date work before it's merged to master.
=> Remove placement_date_subject_and_id from BPRs

app/services/candidates/registrations/behaviours/subject_and_date_information.rb, app/services/candidates/registrations/subject_and_date_information.rb
SE-1804
We we're getting a duplicate presence validation error on
bookings_placement_date_id when no date is selected on the subject and
date information screen.
Removes the duplicate presence validation.
Simplifies the validation conditionals.
Apply for school experience as a candidate at a school with subject specific dates, dont select a date, expect to only see one validation error.
=> Update validations on SubjectAndDateInformation

app/controllers/schools/on_boarding/candidate_experience_details_controller.rb, app/forms/schools/on_boarding/candidate_experience_detail.rb, app/forms/schools/on_boarding/current_step.rb, app/models/bookings/profile.rb, app/models/bookings/profile_attributes_convertor.rb, app/models/schools/school_profile.rb, app/presenters/schools/on_boarding/school_profile_presenter.rb, app/views/candidates/schools/_phase2.html.erb, app/views/schools/on_boarding/candidate_experience_details/_form.html.erb, app/views/schools/on_boarding/profiles/show.html.erb, config/environments/development.rb, config/environments/production.rb, config/environments/servertest.rb, config/environments/test.rb, config/routes.rb, spec/factories/schools/on_boarding/candidate_experience_detail_factory.rb, spec/factories/schools/school_profile_factory.rb, spec/forms/schools/on_boarding/candidate_experience_detail_spec.rb, spec/models/bookings/profile_attributes_convertor_spec.rb, spec/models/schools/school_profile_spec.rb, spec/presenters/schools/on_boarding/school_profile_presenter_spec.rb
Removes the branching on access_needs_journey. Removes the old
disabled_facilities and disabled_facilities_details that were on the
candidate experience details question screen.
SE-1843
The new access_needs_journey has been in place for a while now so the feature flags are just generating noise.
Remove the access_needs_journey and the old code that supported the access needs questions on the candidate experience screen.
Nothing should be broken. Manual testing, on board a new school, should work as expected.
=> Removes access_needs_journey feature flag

db/migrate/20191031105854_remove_column_default_from_bookings_placement_dates_subject_specific.rb, db/schema.rb
This caused the supports subjects radio button to be pre selected. We
want to leave this up to the school to decide.
SE-1804
Review of subject specific dates pr flagged that supports subjects radio button was being preselected.
Remove the column default (and the null constraint) for supports_subjects on placement_dates
Shouldn't have broken anything, shouldn't effect existing placement dates which will be treated as non subject specific.
=> Remove column default on supports_subjects

app/controllers/candidates/registrations/subject_and_date_informations_controller.rb, app/models/bookings/placement_date_subject.rb, app/services/candidates/registrations/subject_and_date_information.rb, spec/models/bookings/placement_date_subject_spec.rb, spec/services/candidates/registrations/subject_and_date_information_spec.rb
SE-1804
There was some repetition and messiness around the struct used for building the combined list of subjects and dates
Simplify the subject and date ids serialising and deserialising and move most of the logic surrounding it to the `SubjectAndDateInformation` object
Ensure everything makes sense and is actually tidier than before!
=> (Subject-specfic dates) rework combined ids SE-1804

app/controllers/schools/placement_dates/configurations_controller.rb
SE-1804
The line initialising the `ConfigurationForm` was a bit long
Shorten it by splitting out the assignment to a separate line
🤷🏽‍♂️
=> Simplify form setup by not merging params

app/presenters/candidates/school_presenter.rb, spec/factories/bookings/placement_dates.rb, spec/presenters/candidates/school_presenter_spec.rb
SE-1804
The primary and secondary date queries sent from the `SchoolPresenter` weren't limited as much as they should be
Use the `.available` scope rather than `.in_date_order`, not only does it sort them correctly but it prevents unpublished, past or inactive ones from being included in the record set. This was applied to both primary and secondary dates
Ensure code looks correct and tests encompass behaviour
=> Ensure primary and secondary dates are .available

app/controllers/candidates/registrations/subject_and_date_informations_controller.rb, app/services/candidates/registrations/subject_and_date_information.rb, spec/services/candidates/registrations/subject_and_date_information_spec.rb
Updates the subject and date information to match the other
registrations controllers.  We can have `subject_and_date_ids=` do all
the lifting of splitting the param and finding the right date and
subject (if applicable) then we can just pass the params straight in
like a normal rails controller.
SE-1804
=> Standardise subject and date info controller

app/models/bookings/placement_date.rb, app/models/candidates/placement_date_option.rb, app/presenters/candidates/school_presenter.rb, app/services/candidates/registrations/subject_and_date_information.rb, app/views/candidates/schools/_placement_dates.html.erb, spec/presenters/candidates/school_presenter_spec.rb
SE-1804
Fixing one of Jeremy's comments about duplication
Presenting subject specific dates for a school was duplicated between
candidates/schools#show and the subject_and_date_information forms.
Add a class method to placement_date_option that handles building
placement_date_options for a given date to avoid this duplication.
Should all still work the same as before
=> Se 1804 dedup presenting dates

app/services/candidates/registrations/behaviours/education.rb, app/services/candidates/registrations/personal_information.rb, app/validators/email_format_validator.rb, lib/shoulda_matcher_duplicate_messages.rb, spec/rails_helper.rb, spec/services/candidates/registrations/personal_information_spec.rb, spec/validators/email_format_validator_spec.rb, spec/validators/website_validator_spec.rb
SE-1876
If the user uses an email address with a dot in the hostname, but not fully qualified then they see 2 validation errors on the field instead of a single one, eg `testuser@btinternet.`
1. Added a monkey patch to the shoulda-matchers to avoid matching a validation error message if it occurs multiple times.
2. Added a test to the PersonalInformation spec to test addresses like `testuser@btinternet.`
3. Combined the regexes for checking emails into an EmailFormatValidator to ensure the message is only once
4. Used the validator for PersonalInformation model
5. Fixed a bug in the Education behaviour which was validating the degree subject against both the full list and the ['Not applicable'] list in some scenarios.
1. Code review
2. Testing
3. Particular consideration should be given …
=> SE-1876 Handle host name ending in dot

db/migrate/20190930142055_add_supports_subjects_flag_to_bookings_placement_dates.rb, db/migrate/20191008135000_add_subjects_supported_default_value.rb
Add defaults when creating this column, remove migration that adds
column defaults. The second migration errors when trying to add not null
constraint as exiting rows have null columns.
=> Fix migration

app/controllers/schools/availability_info_controller.rb, app/models/bookings/school.rb, app/views/schools/availability_info/edit.html.erb, config/locales/en.yml, features/schools/availability_information/edit.feature, spec/models/bookings/school_spec.rb
Schools can currently submit an empty availability description
The availability info field is covered by new validation that is contextual and will only be applied on the edit availability information page. The minimum character limit is currently
set to 3 characters. The submit button text has been updated from 'Continue' as this is the final step in the journey.
Ensure changes make sense.
=> Prevent blank flexible date submissions SE-1754

app/controllers/candidates/feedbacks_controller.rb, app/controllers/schools/feedbacks_controller.rb, app/views/feedbacks/_form.html.erb, db/migrate/20191104112809_add_referrer_to_feedbacks.rb, db/schema.rb, features/candidates/feedback.feature, features/schools/feedback.feature, features/step_definitions/feedback_steps.rb
SE-1774
We currently don't know what stage of the process people are at when they leave feedback
This change adds a `referrer` field to the feedback record that is set based on the page they were last on before clicking 'Give feedback'. This isn't guaranteed to give an accurate view on the state of the user; they _may_ have already completed their transaction and have returned to the home page. It should give an indication, though, and is likely to provide some useful information on what people are doing when they feel the need to offer an opinion of the service.
Ensure the changes look sensible
=> Record feedback referrers SE-1774

app/controllers/schools/placement_requests/acceptance/confirm_booking_controller.rb, app/forms/schools/on_boarding/subject_list.rb, app/models/bookings/subject.rb, app/models/schools/school_profile.rb, spec/models/bookings/subject_spec.rb, spec/models/bookings/subject_sync_spec.rb, spec/support/stubbed_candidates_school_context.rb
This is set in a sync job to remove certain subjects returned by gitis.
Rather than having to remember to call the available scope everywhere we
can make this the default scope as we never want to show these to the
end user.
We we're duplicating the call to the available scope in multiple places through out the app (and missed calling it some places).
Make the available scope the default scope.
Change should be sensible. Use of default scope was discussed offline
=> Make non hidden subjects the default scope

app/controllers/candidates/registrations/subject_and_date_informations_controller.rb, app/models/bookings/placement_date_subject.rb, app/models/candidates/placement_date_option.rb, app/services/candidates/registrations/subject_and_date_information.rb, app/views/candidates/registrations/subject_and_date_informations/_form.html.erb, config/locales/en.yml, spec/controllers/candidates/registrations/subject_and_date_informations_controller_spec.rb, spec/models/bookings/placement_date_subject_spec.rb, spec/services/candidates/registrations/subject_and_date_information_spec.rb
The combined_id currently represents placement date id and placement date subject id. This is partly redundant information, and will also unnecessarily fail if a school accidentally removes a placement date subject, then subsequently adds it back in - whilst the user is applying.
In general the placement_date_subject_ids are just join ids and treated as very ephemeral, and so shouldn't be being exposed to the users.
1. Use placement date id and bookings subject id for the combined id
2. Whilst I'd originally used the reference combined_id - date_and_subject_id better represents what this holds.
3. Rename references to subject_and_date_ids to date_and_subject_ids which better reference what they hold
4. Validate SubjectAndDateInformation to ensure there is a PlacementDateSubject …
=> SE-1804 Use subject id instead of placement date subject

app/controllers/schools/sessions_controller.rb, spec/controllers/schools/sessions_controller_spec.rb
SE-1857
Sometimes, for reasons unknown, users reach our OIDC callback path
`/auth/callback` with the param `?error=sessionexpired`. We previously
treated this as an AuthFailedError but that was causing too much noise
in our error reporting.
Having asked on the DfE Sign-in Slack channel and getting no response I
had a search on GitHub and other teams are manually handling this
error[0][1].
This PR implements that approach, users who are redirected back with the
sessionexpired error, instead of raising AuthFailedError will raise
SessionExpiredError. This is handled by session_expired_failure which
redirects instead of reporting the error to Sentry via Raven.
Users will be redirected to `/schools/dashboard` which will, in turn,
send them back to DfE Sign-in where they will log in again. …
=> Stop raising errors for session expiry

config/locales/en.yml
Simple typo fix by adding missing letter
=> Add the missing 'r' to understand

app/services/bookings/gitis/entity.rb, spec/services/bookings/gitis/entity_spec.rb
Modifying a variable which has been assigned will potentially be missed by the change tracking. This will result in changes the user makes not getting written. 
1. Freeze all attributes on assignment, forcing the developer to overwrite attributes instead of modifying them in place. There by ensuring change tracking notices the changes.
1. Code review
=> Freeze Entity attribute assignment

app/services/bookings/gitis/crm.rb, spec/services/bookings/gitis/crm_spec.rb
When we write an Entity to Dynamics, we currently leave the written attributes as marked dirty. Correct behaviour would be to reset the changes information in case the Entity is written a second time.
1. Clear changes information after a successful write to dynamics.
1. Code review
=> Reset change tracking after successful write

app/views/schools/dashboards/_no_availability_info_warning.html.erb
SE-1833
The link on the warning went straight to the availability description edit page
Since the warning was added we've opted to send flexible users via the preferences screen in the hope they'll notice that fixed dates are an option and switch. The warning now follows the same behaviour
=> Change the warning link to point to availability preferences SE-1833

app/controllers/schools/on_boarding/candidate_requirements_selections_controller.rb, app/forms/schools/on_boarding/candidate_requirements_selection.rb, app/models/schools/school_profile.rb, app/presenters/schools/on_boarding/candidate_requirements_selection_presenter.rb, app/views/schools/on_boarding/candidate_requirements_selections/_form.html.erb, config/locales/en.yml, db/migrate/20191108132921_add_photo_id_requirements_to_schools_school_profiles.rb, db/schema.rb, spec/factories/schools/on_boarding/candidate_requirements_selection_factory.rb, spec/forms/schools/on_boarding/candidate_requirements_selection_spec.rb, spec/models/bookings/profile_attributes_convertor_spec.rb, spec/presenters/schools/on_boarding/school_profile_presenter_spec.rb
SE-1885
Prototype has been updated to include another candidate requirement option.
Adds provide_photo_identification and photo_identification_details to
schools profile.
Manual testing if required: On board a new school or edit an existing school. On the candidate requirements step chose the photo id requirement, enter some details, complete the rest of the wizard. Visit the school profile as a candidate, expect the photo requirement details you entered to be present.
=> Add photo id candidate requirement

app/services/candidates/registrations/subject_and_date_information.rb, app/views/candidates/registrations/subject_and_date_informations/_form.html.erb, app/views/candidates/schools/_placement_dates.html.erb, app/views/schools/placement_dates/configurations/new.html.erb, app/views/schools/placement_dates/index.html.erb, app/views/schools/placement_dates/new.html.erb, app/views/schools/placement_dates/subject_selections/new.html.erb, config/locales/en.yml, features/schools/placement_dates/index.feature, features/schools/placement_dates/new.feature, features/schools/placement_dates/primary_and_secondary_school_configuration.feature, features/schools/placement_dates/secondary_school_configuration.feature, features/schools/placement_dates/subject_selection.feature, features/step_definitions/candidates/registrations/subject_and_date_information_steps.rb, features/step_definitions/schools/placement_dates/new_steps.rb, features/step_definitions/schools/placement_dates/placement_date_steps.rb, spec/services/candidates/registrations/subject_and_date_information_spec.rb
SE-1915
The copy in the prototype had progressed and this should bring the Rails app up to date
Make various text changes and, for the conditional help sentence on the subject/date selection screen add some helper methods to reduce the logic in the view.
Ensure everything makes sense. Only real discrepancy between this and the prototype is that as the form builder doesn't support radio button hints the text is inline with the label - this looks clear to me
=> Updating subject specific date copy SE-1915

app/controllers/schools/confirmed_bookings_controller.rb, app/controllers/schools/placement_requests_controller.rb, app/controllers/schools/previous_bookings_controller.rb, app/controllers/schools/withdrawn_requests_controller.rb, app/helpers/application_helper.rb, app/models/bookings/school_search.rb, app/views/schools/confirmed_bookings/index.html.erb, app/views/schools/placement_requests/index.html.erb, app/views/schools/previous_bookings/index.html.erb, app/views/schools/withdrawn_requests/index.html.erb, config/initializers/kaminari_config.rb, config/locales/en.yml
Placement Requests currently shows all requests on a single page.
No ticket number but uncapped database queries are a bad idea - and Gitis cannot return more than 130 items in a single request.
Added pagination to Placement Requests listing in Schools dashboard
1. Standardised pagination handling into helpers
2. Changed default pagination to be 50, rather than override it everywhere
3. Changed SchoolSearch to set its own pagination limit
4. Added pagination and 'no requests' message to placement requests listing
1. Code review
2. Testing - Within the schools dashboard - Placement requests, Confirmed Bookings, Withdrawn Requests, Cancelled Requests and Previous Bookings should all still work fine. There should now be pagination on the Placement Requests screen
=> Added pagination to Placement Requests listing in Schools dashboard

app/views/candidates/schools/_placement_dates.html.erb, features/candidates/schools/show/upcoming_placement_dates.feature, features/step_definitions/candidates/schools/show_steps.rb
SE-1804
There were a few cucumber scenarios around displaying the school profile page to candidates with fixed (subject-specific) dates that had no step definitions
Add them and make sure they work
Does it look sensible?
=> Add step defs for subject specific date scenarios SE-1804

app/services/bookings/gitis/api.rb, app/services/bookings/gitis/auth.rb, spec/services/bookings/gitis/api_spec.rb, spec/services/bookings/gitis/auth_spec.rb
We do not want to allow indefinite length page requests, so we use Rack::Timeout. Occasionally Gitis will take a long time to respond to a request - this means we are hitting the Rack Timeout.
1. Add a shorter timeout to API requests - 25 seconds so there is time for a couple of attempts before hitting the page time out.
2. Add the Faraday Retry middleware to make a second request to Gitis if the first one times out.
1. Testing
2. Code review
=> SE-1673 Retry GETs to gitis

app/services/bookings/gitis/event_logger.rb
SE-1942
We're hitting a length limit occasionally on the log field in Gitis. This is normally caused by overlong school names.
1. Shorten the school name to 25 chars since we also include the URN.
1. Code review
=> Truncate the length of school names

app/controllers/schools/placement_requests/cancellations/notification_deliveries_controller.rb, app/notify/notify_email/candidate_request_rejection.rb, app/notify/notify_email/candidate_request_rejection_nopiii.74f84226-539a-43b0-b887-d8ffc9348965.md, spec/controllers/schools/placement_requests/cancellations/notification_deliveries_controller_spec.rb, spec/notify/notify_email/candidate_request_rejection_spec.rb
Avoid sending unnecessary pii
SE-1752
We we're sending over the candidate name in the email for the sake of the greeting.
Replace the candidate name in the email with just 'Hello'
Rejection email sent to the candidate should not include their name.
=> Remove candidate name from Rejection emails

app/controllers/schools/confirm_attendance_controller.rb, app/models/bookings/booking.rb, spec/controllers/schools/confirmed_bookings/cancellations_controller_spec.rb, spec/models/bookings/booking_spec.rb, spec/models/schools/attendance_spec.rb
SE-1841
To prevent bookings getting in an inconsistent state validate the booking is not cancelled when updating acceptance.
Add validation to ensure Booking#attended is nil if booking is cancelled.
Should look sensible, is there a better way to validate a field is nil?
=> Validate booking not cancelled on setting attended

app/controllers/schools/placement_requests_controller.rb, app/controllers/schools/switch_controller.rb, app/views/schools/switch/show.html.erb, config/routes.rb, spec/controllers/schools/placement_requests_controller_spec.rb, spec/views/schools/switch/show.html.erb_spec.rb
SE-1878
When users are navigating directly to placement requests (potentially other things too, but at the moment only placement requests are linked to from emails) and are already logged into the web application as another school they'll receive a 404. This is confusing for them as it's not clear why they can't see the record
When the DfE Sign-in API is turned on we'll be able to work out the other schools a user has access to, we can then prompt them to change school:
This is a stop gap until true multi-school behaviour lands but it should improve the UX in the short term.
Ensure everything looks sensible. Some considerations:
* Should we move exception types up to `app/errors`?
* Are there any ways I've overlooked where a user can navigate directly to a resource that belongs to another …
=> Offer school change when navigating to placement request SE-1878

azure-pipelines.yml
SE-1934
To enable use of the deletion strategy in Database Cleaner we need to be able to debug the pipeline. Currently debug builds have gotten broken at some point.
1. Tag the debug image
2. Upload the debug image to dockerhub for use within CD
3. Disambiguate names of some other steps
1. Do pipeline changes make sense
=> Fix building debug branch

features/step_definitions/feedback_steps.rb
SE-1951
Currently the tests feedback in cucumber are doing a full string match on the URL - but the url requested includes credentials, but the url compared with has them removed.
1. Strip the credentials out from the referrer prior to comparison
1. Code check
2. Does it pass CD (going to set `debug`) to match this branch so look for a release with matching SHA
=> SE-1951 Handle credentials in url
