DFE-Digital/schools-experience

- .dockerignore
Added missing .dockerignore file
> Added missing .dockerignore

- Gemfile
- Gemfile.lock
- app/controllers/candidate/home_controller.rb
- app/controllers/pages_controller.rb
- azure-pipelines.yml
- config/routes.rb
- spec/controllers/candidate/home_controller_spec.rb
This pull request configures all branches to be tested using Azure pipelines
* A Docker image is built
* Test, Specs and Cucumber features are run within the Docker Image
* Linting and Rubocop checks are run
* A Brakeman security scan is run
* The `rails server` is booted, and checked it starts up correctly and responds to the health check
_**Note:** The downgrading of sass is not ideal but brakeman currently requires an older version so there's not much we can do about this_
> Set up CI with Azure pipeline

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/form-extensions.scss
- app/assets/stylesheets/global-styles.scss
- app/javascript/packs/application.js
- app/views/layouts/application.html.erb
- config/initializers/govuk-form-builder.rb
- package.json
- yarn.lock
Include the 
1. GovUK Elements Form Builder (via git for now)
2. Set some default styles in the CSS
3. Include the Stimulus JS framework
> Add common components

- README.md
As a developer I should understand what is required to get the app running
Minor updates for PostGIS and using HTTP Basic Auth
> Added info to Readme

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/form-extensions.scss
- app/assets/stylesheets/global-styles.scss
- app/javascript/packs/application.js
- app/services/candidate/registrations/account_info.rb
- app/services/candidate/registrations/placement.rb
- app/views/candidate/registrations/account_infos/new.html.erb
- app/views/candidate/registrations/dbs_checks/new.html.erb
- app/views/candidate/registrations/personal_details/new.html.erb
- app/views/candidate/registrations/placements/new.html.erb
- app/views/layouts/application.html.erb
- azure-pipelines.yml
- config/initializers/govuk-form-builder.rb
- config/locales/en.yml
- db/migrate/20190116152522_enable_postgis_extension.rb
- package.json
- spec/features/candidate/registrations_spec.rb
- spec/services/candidate/registrations/account_info_spec.rb
- spec/services/candidate/registrations/personal_detail_spec.rb
- spec/services/candidate/registrations/placement_spec.rb
- yarn.lock
Integrates form builder with the current candidate registration screens.
visit /candidate/registrations/placements/new, complete the steps. Expect form styling to match govuk styling guide (roughly, opted not to spend hours on sorting all of the spacing to exactly match the prototype as I expect this will be rapidly changed)
> Se 168 candidate registration screens styling

- app/controllers/candidate/registrations/placement_requests_controller.rb
- app/views/candidate/registrations/placement_requests/show.html.erb
Stubs the your request has been sent screen. This gives the candidate
registration flow an end point.
> SE-145 #comment Add stub your request has been sent screenn

- app/controllers/candidate/registrations/account_checks_controller.rb
- app/controllers/candidate/registrations/placements_controller.rb
- app/services/candidate/registrations/account_check.rb
- app/views/candidate/registrations/account_checks/new.html.erb
- app/views/candidate/registrations/account_infos/new.html.erb
- config/locales/en.yml
- config/routes.rb
- spec/controllers/candidate/registrations/account_checks_controller_spec.rb
- spec/controllers/candidate/registrations/placements_controller_spec.rb
- spec/features/candidate/registrations_spec.rb
- spec/services/candidate/registrations/account_check_spec.rb
This uses the 'check if we have your details' screen design from the
prototype, until we get some new copy for this screen.
> SE-229 #comment Adds candidate email/name capture

- app/assets/stylesheets/school-search.scss
- app/controllers/candidates/schools_controller.rb
- app/models/candidates/school_search.rb
- app/views/candidates/schools/_form.html.erb
- app/views/candidates/schools/_results.html.erb
- spec/models/candidates/school_search_spec.rb
- spec/views/candidates/schools/index.html.erb_spec.rb
Currently the search just returns stub data - this hooks it up to the search logic
Hooking up the Candidate::SchoolSearch model to the Bookings::SchoolSearch backend service
> Connect search to data

- features/support/env.rb
Adding the drivers for IE and Firefox and the associated driver paths.
Adding the drivers for IE and Firefox and the associated driver paths (based on the Azure DevOps driver path environment variables).
> Adding IE and Firefox driver paths

- features/candidates/schools/search/results.feature
- features/step_definitions/candidates/registrations/request_school_experience_placement_steps.rb
- features/step_definitions/candidates/schools/results_steps.rb
- features/step_definitions/form_steps.rb
- features/support/env.rb
- features/support/javascript_helper.rb
Enabling running database tests as part of the CD pipeline
Use database truncation strategy for Cucumber tests plus 2 fixes to tests failing against Chrome
Amended how JS tests are run to get cucumber passing against Chrome as well
> Cucumber DB truncation

- config/cucumber.yml
- features/candidates/schools/search/results.feature
Simple clean up removing redundant 'onlylocal' annotations.
> remove onlylocal annotation

- app/services/candidates/registrations/registration_store.rb
- spec/rails_helper.rb
- spec/services/candidates/registrations/registration_store_spec.rb
Seems sensible to namespace redis keys per environment
> Namespace redis keys per environment

- app/views/candidates/registrations/background_checks/_form.html.erb
- config/locales/en.yml
- features/candidates/registrations/background_check.feature
- features/step_definitions/candidates/registrations/background_checks_steps.rb
Brings the DBS check screen in sync with changes to the prototype
Content changes, no functionality
Everything should work as before.
> Updates DBS screen with latest prototype changes

- app/views/candidates/registrations/application_previews/show.html.erb
The prototype has had a a sub title added to the check your answers screen
Adds the missing sub title.
> Adds sub title to check your answers

- app/services/candidates/registrations/behaviours/subject_preference.rb
Avoid hitting the AR cache
Memoizes SubjectPreference#available_subject_choices
Everything should work as before
> Memoizes available_subject_choices

- Gemfile.lock
Bumps form builder version to include fix for placing errors below hints
> bump form builder version

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/school-search.scss
- app/assets/stylesheets/stimulus/map.scss
- app/helpers/candidates/maps_helper.rb
- app/helpers/candidates/school_helper.rb
- app/javascript/controllers/map_controller.js
- app/javascript/packs/application.js
- app/views/candidates/schools/show.html.erb
- app/views/layouts/application.html.erb
- spec/helpers/candidates/maps_helper_spec.rb
- spec/helpers/candidates/school_helper_spec.rb
Candidates want to be able to clearly see the location of a School on the Schools Profile page
Integrated Maps 
- the maps show in a box which maintains a 2/3 aspect ratio
- an Ajax map is show with a popup marking the schools location
- an Image based fallback is shown when no js is run
Test maps show correctly on different form factors, both with and without javascript enabled.
> Add map school profile

- app/views/candidates/registrations/subject_preferences/_form.html.erb
- config/candidate_form_options.yml
- spec/controllers/candidates/registrations/subject_preferences_controller_spec.rb
- spec/factories/candidates/registrations/registration_session_factory.rb
- spec/features/candidates/registrations_spec.rb
- spec/services/candidates/registrations/registration_as_placement_request_spec.rb
Teaching stages in the prototype have been updated.
Updates the the teaching stages and fixes tests broken by this.
Everything should still work but now with 50% more teaching stage options!
> Updates the teaching stages options to match prototype

- app/services/bookings/school_search.rb
Add a line of debug to try to see what's up with CD
> Add debug statement that prints out cached result

- config/candidate_form_options.yml
- features/step_definitions/candidates/registrations/wizard_steps.rb
Fixes feature spec failing on CI due to option having been removed
> Se 568 fix cucumber spec

- Gemfile.lock
- app/views/candidates/registrations/placement_preferences/_form.html.erb
- config/locales/en.yml
- features/candidates/registrations/request_school_experience_placement.feature
- features/step_definitions/candidates/registrations/request_school_experience_placement_steps.rb
- features/step_definitions/candidates/registrations/wizard_steps.rb
- spec/features/candidates/registrations_spec.rb
Updates the placement preference form to bring it in line with the
changes to the prototype.
Prototype content has changes.
Bumps form builder version. Updates the placement preference form. fixes specs.
Everything should work as before.
> Update placement preference form content

- app/views/candidates/registrations/placement_preferences/_form.html.erb
- app/views/candidates/registrations/subject_preferences/_form.html.erb
- config/locales/en.yml
- spec/features/candidates/registrations_spec.rb
see SE-672
1. Added Placeholder text to availability field
2. Default second subject to be "no preference"
3. Added help text above subject preferences options
> Minor Text changes

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/subject-preference.scss
- app/services/candidates/registrations/behaviours/subject_preference.rb
- app/views/candidates/home/index.html.erb
- app/views/candidates/home/splash.html.erb
- app/views/candidates/registrations/application_previews/show.html.erb
- app/views/candidates/registrations/background_checks/_form.html.erb
- app/views/candidates/registrations/confirmation_emails/show.html.erb
- app/views/candidates/registrations/contact_informations/_form.html.erb
- app/views/candidates/registrations/placement_preferences/_form.html.erb
- app/views/candidates/registrations/placement_requests/show.html.erb
- app/views/candidates/registrations/subject_preferences/_form.html.erb
- app/views/candidates/schools/_form.html.erb
- app/views/candidates/schools/_results.html.erb
- app/views/candidates/schools/show.html.erb
- config/locales/en.yml
- features/candidates/landing_page.feature
- features/candidates/registrations/request_school_experience_placement.feature
- features/candidates/schools/search/search.feature
- features/candidates/schools/show/full_school_details.feature
- features/step_definitions/candidates/landing_page_steps.rb
- features/step_definitions/candidates/registrations/background_checks_steps.rb
- features/step_definitions/candidates/registrations/contact_information_steps.rb
- features/step_definitions/candidates/registrations/request_school_experience_placement_steps.rb
- features/step_definitions/candidates/registrations/wizard_steps.rb
- features/step_definitions/candidates/schools/show_steps.rb
- spec/controllers/candidates/schools_controller_spec.rb
- spec/features/candidates/registrations_spec.rb
- spec/support/stubbed_candidates_school_context.rb
- spec/views/candidates/schools/index.html.erb_spec.rb
Need to update the rails app to match the copy in the prototype
Updates the copy to match prototype (Except for the landing page, need to discus this on Monday)
Copy should match prototype
> Se 630 sync text changes

- app/views/candidates/home/index.html.erb
We don't want to use the term placement
Replace the term placement with school experience
Should word good
> Replace placement with school experience

- app/notify/notify_email/candidate_magic_link.a06fe38a-5f7f-4c68-8612-6aae9495a8ab.md
- app/notify/notify_email/candidate_request_confirmation.3860fb06-9af2-49c8-ac0b-007b9f360033.md
- app/notify/notify_email/school_request_confirmation.3da1cb35-efd2-4aa6-8416-27efc5611d06.md
Fred has updated the Email templates on the Notify service
This change updates our copy in Git
> Updated Phase 1 email templates to match Notify service

- app/views/candidates/home/index.html.erb
- app/views/candidates/registrations/placement_requests/show.html.erb
Becky requested some last minute content changes
1. One paragraph added at the start of the candidate journey
2. One paragraph added on the final confirmation page of the candidate journey
> Added new paragraphs explaining service limits

- app/assets/stylesheets/school-search.scss
- app/assets/stylesheets/stimulus/map.scss
- app/helpers/candidates/maps_helper.rb
- app/helpers/candidates/school_helper.rb
- app/views/candidates/schools/_phase1.html.erb
- app/views/candidates/schools/_phase2.html.erb
- app/views/candidates/schools/show.html.erb
- spec/helpers/candidates/maps_helper_spec.rb
- spec/helpers/candidates/school_helper_spec.rb
Minor tweaks coming out of user research
1. Reduced width of map on mobile to handle scrolling
2. Moved links to the foot of the page
3. Added handler bad links supplied by schools better
4. Added link below map to 'Get directions'
> Profile page tweaks

- app/models/candidates/school_search.rb
Jordan requested a larger default search radius
Change default radius to 10 miles
> Changed default search radius

- app/notify/notify_email/candidate_magic_link.a06fe38a-5f7f-4c68-8612-6aae9495a8ab.md
- app/notify/notify_email/candidate_request_confirmation.3860fb06-9af2-49c8-ac0b-007b9f360033.md
- app/notify/notify_email/school_request_confirmation.3da1cb35-efd2-4aa6-8416-27efc5611d06.md
Email templates have been tweaked, this PR syncs the updates
> Update local email templates

- app/views/candidates/home/index.html.erb
Page title is incorrect
Corrects page title
> Fixes landing page title

- app/views/candidates/home/index.html.erb
Text used was from the wrong version of the prototype 🙄
Minor text changes from prototype
Make sure it's correct!
> Remove the word 'placements' to match prototype:

- jmeter/schoolexperience.jmx
Missed hostname references
Fix hostnames and text for assertion test.
Minor fixes
> hostname fix and text check

- app/services/bookings/gitis/contact.rb
- app/services/bookings/gitis/crm.rb
- app/services/candidates/registrations/registration_session.rb
- spec/factories/bookings/gitis/contact_factory.rb
- spec/services/bookings/gitis/contact_spec.rb
- spec/services/bookings/gitis/crm_spec.rb
As a Developer I will want to write code against the Gitis CRM. Currently that is not available but
we know enough to mock out the internal API we will work against.
Adds CRM and Contact models which mock out
1. look ups by Contact Id and Email Address
2. Writing updates back to the CRM
Sanity checking at this stage. Its worth noting I'm only including functionality I'm absolutely sure we need at this stage, hence the Email address lookup being against a single address.
The batch functionality is for the Schools Dashboard, but we'll have Ids in that scenario.
> Gitis stub object

- config/environments/production.rb
Reduce log level in production
> Set log level to info in production

- app/notify/notify_email/candidate_request_confirmation.3860fb06-9af2-49c8-ac0b-007b9f360033.md
Synchronising the change from Notify
> Add Easter amendment to Candidate Request Conf

- app/services/candidates/registrations/registration_session.rb
I'm getting lint errors whilst committing, not sure why this is affecting my machine but not others but the code is incorrect and the fix is minor
Pass params through for #to_json
Does CI pass
> Fix lint error on master

- azure-pipelines.yml
- features/support/env.rb
Run CI against Firefox as well as Chrome. Logic is it runs so much faster in CI than CD, why not. 
1. Add Firefox CI steps
> Use ff in ci

- app/assets/stylesheets/global-styles.scss
Paul wants the blue bar removing on mobile
Use break points to hide blue bar css on mobile
> Remove blue line

- app/notify/notify_email/school_request_confirmation.3da1cb35-efd2-4aa6-8416-27efc5611d06.md
Update templates to reflect Notify
> Sync changes from Notify

- app/controllers/schools/on_boarding/availability_preferences_controller.rb
- app/forms/schools/on_boarding/availability_preference.rb
- app/forms/schools/on_boarding/current_step.rb
- app/models/schools/school_profile.rb
- app/presenters/schools/on_boarding/school_profile_presenter.rb
- app/views/schools/on_boarding/availability_preferences/new.html.erb
- app/views/schools/on_boarding/profiles/show.html.erb
- config/locales/en.yml
- config/routes.rb
- db/migrate/20190418151613_add_availability_preference_fixed_to_schools_school_profile.rb
- db/schema.rb
- features/schools/admin_contact.feature
- features/schools/availability_preference.feature
- features/schools/candidate_experience_detail.feature
- features/schools/experience_outline.feature
- features/schools/school_profile.feature
- features/step_definitions/schools/shared_steps.rb
- features/support/path_helper.rb
- spec/controllers/schools/on_boarding/admin_contacts_controller_spec.rb
- spec/controllers/schools/on_boarding/availability_descriptions_controller_spec.rb
- spec/controllers/schools/on_boarding/availability_preferences_controller_spec.rb
- spec/controllers/schools/on_boarding/candidate_experience_details_controller_spec.rb
- spec/controllers/schools/on_boarding/experience_outlines_controller_spec.rb
- spec/factories/schools/on_boarding/availability_preference.rb
- spec/factories/schools/school_profile_factory.rb
- spec/forms/schools/on_boarding/availability_preference_spec.rb
- spec/forms/schools/on_boarding/current_step_spec.rb
- spec/models/schools/school_profile_spec.rb
Adds the ability for schools to specify if the offer fixed or flexable dates
> Adds ability for schools to specify their availability type

- app/controllers/schools/on_boarding/availability_preferences_controller.rb
- app/views/schools/on_boarding/availability_preferences/_form.html.erb
- app/views/schools/on_boarding/availability_preferences/edit.html.erb
- app/views/schools/on_boarding/profiles/show.html.erb
- config/routes.rb
- spec/controllers/schools/on_boarding/availability_preferences_controller_spec.rb
Adds action and view to allow editing availability type
> Adds ability to edit availability_preference

- app/views/schools/on_boarding/admin_contacts/_form.html.erb
Updates the copy on the admin contact screen to match Fred's changes to the prototype
> update copy to match prototype

- app/services/bookings/gitis/contact.rb
- app/services/bookings/gitis/crm.rb
- spec/factories/bookings/gitis/contact_factory.rb
- spec/services/bookings/gitis/contact_spec.rb
- spec/services/bookings/gitis/crm_spec.rb
The Mock CRM object didn't quite align with how the CRM works in reality.
Changed how IDs are handled to better reflect the UUIDs used in reality
> Mock crm updates

- app/controllers/schools/on_boarding/on_boardings_controller.rb
- app/controllers/schools/on_boarding/profiles_controller.rb
- app/forms/schools/on_boarding/confirmation.rb
- app/models/schools/school_profile.rb
- app/presenters/schools/on_boarding/school_profile_presenter.rb
- spec/controllers/schools/on_boarding/profiles_controller_spec.rb
Moves querrying for next step into school_profile.
Adds redirection if user skips to profile#show with incomplete profile.
> School on boarding refactoring

- app/services/candidates/registrations/application_preview.rb
Fix a failure introduced by #354
> Call #to_s on the placement date

- app/presenters/schools/on_boarding/school_profile_presenter.rb
- features/schools/school_profile.feature
- spec/presenters/schools/on_boarding/school_profile_presenter_spec.rb
Should refer to college as 16-18 years
> Use 16-18 rather than college on profile show

- app/views/schools/on_boarding/confirmations/show.html.erb
> Add dashboard link to school wiz end splash screen

- db/migrate/20190430082248_make_phase_names_index_unique.rb
- db/schema.rb
- spec/models/bookings/phase_spec.rb
Make the index on `bookings_phases.name` unique
> Make the index on bookings_phases name unique

- config/routes.rb
- features/schools/dashboard.feature
- features/step_definitions/common_steps.rb
- features/step_definitions/schools/dashboard_steps.rb
- features/support/path_helper.rb
Add root path for schools namespace
> Add root path for schools namespace

- app/presenters/schools/on_boarding/school_profile_presenter.rb
- config/locales/en.yml
- spec/presenters/schools/on_boarding/school_profile_presenter_spec.rb
Just some text updates on the DBS page of the school wizard, see [SE-899](https://dfedigital.atlassian.net/browse/SE-899)
> Update DBS requirement text in the school wizard

- app/views/schools/dashboards/_full_dashboard.html.erb
- features/step_definitions/schools/dashboard_steps.rb
This appears to have been caused by the recent change to the phase env var
Modify the dashboard's title to match the dashboard-light to satisfy the test. It'll be revised when the dashboard is completed anyway.
Ensure everything looks ok and passes
> Modify dashboard heading/feature with school name

- app/forms/schools/on_boarding/candidate_experience_detail.rb
Avoid showing the user two error messages for the same field.
> Only validate format if time present

- app/presenters/schools/on_boarding/school_profile_presenter.rb
- features/schools/school_profile.feature
- spec/presenters/schools/on_boarding/school_profile_presenter_spec.rb
Fixes some text on school profile show
> Capitalize sentences on school_profile#show

- config/locales/en.yml
> Fix validation error text for dbs check

- app/views/schools/on_boarding/availability_preferences/_form.html.erb
- app/views/schools/on_boarding/confirmations/show.html.erb
> Update copy to match changes to prototype

- app/views/candidates/home/splash.html.erb
> Updates splash to match prototype

- app/views/schools/errors/not_registered/show.html.erb
Simple text change on the 'your school is not registered' error page
> Change text content of 'not registered' error page

- app/notify/notify_email/candidate_request_confirmation.3860fb06-9af2-49c8-ac0b-007b9f360033.md
- app/notify/notify_email/school_request_confirmation.3da1cb35-efd2-4aa6-8416-27efc5611d06.md
Add a warning stating that DBS certificates haven't been checked by DfE and remove the Easter holidays warning
> Sync DBS verification text changes

- Gemfile
- Gemfile.lock
- app/controllers/candidates/schools_controller.rb
- app/models/bookings/school_search.rb
- app/models/candidates/school_search.rb
- app/views/candidates/school_searches/new.html.erb
- config/locales/en.yml
- features/candidates/schools/search/search.feature
- features/step_definitions/candidates/schools/search_steps.rb
- features/step_definitions/common_steps.rb
- features/step_definitions/form_steps.rb
- spec/models/bookings/school_search_spec.rb
- spec/models/candidates/school_search_spec.rb
Phase2 doesn't have some of the changes which on are master and we need to QA those changes
Bring latest changes from master into Phase2
> Merge master to phase2 09042019

- app/models/bookings/profile.rb
- app/models/bookings/profile_attributes_convertor.rb
- app/presenters/candidates/school_presenter.rb
- app/views/candidates/schools/_phase2.html.erb
- spec/models/bookings/profile_spec.rb
Validations on Bookings::Profile should not be tighter than than Schools::SchoolProfile or the user wont be able to publish their profile.
Brought validations inline with Schools::SchoolProfile
Also show the details from the flexible times information
> Brought the validations on the Bookings::Profile upto date

- app/views/schools/on_boarding/candidate_requirements/_form.html.erb
This information is already in the breadcrumbs
> Remove currently editing text

- app/views/schools/on_boarding/candidate_experience_details/_form.html.erb
- app/views/schools/on_boarding/dbs_fees/new.html.erb
- app/views/schools/on_boarding/experience_outlines/_form.html.erb
- app/views/schools/on_boarding/phases_lists/_form.html.erb
- config/locales/en.yml
- features/schools/onboarding/phases.feature
> Brings text inline with changes to prototype

- app/views/candidates/registrations/application_previews/show.html.erb
> Fix link from error summary to field

- app/models/bookings/profile_attributes_convertor.rb
The phases weren't being copied over to Bookings::Profile
> Fix typo in key

- app/presenters/schools/on_boarding/school_profile_presenter.rb
- features/schools/onboarding/school_profile.feature
> Add link text to prevent long links overflowing

- app/helpers/candidates/school_helper.rb
- app/presenters/schools/on_boarding/school_profile_presenter.rb
- app/views/candidates/registrations/subject_preferences/_form.html.erb
Where we're displaying subjects we want to order them alphabetically rather
than the default id ordering.
> Order subjects by name

- config/candidate_form_options.yml
Geology and earth science degree subject was displayed incorrectly.
> Fix Geology degree subject option

- config/initializers/filter_parameter_logging.rb
> Add new PII fields to params filter list

- app/views/schools/availability_info/edit.html.erb
> Fix text_area size

- app/views/schools/on_boarding/confirmations/show.html.erb
> Fixes copy on confirmation dashboard link

- app/models/bookings/booking.rb
- db/migrate/20190604105251_add_duration_to_bookings_booking.rb
- db/schema.rb
- spec/models/bookings/booking_spec.rb
> Adds duration to bookings

- Gemfile.lock
Reverts DFE-Digital/schools-experience#533
> Revert "Bump openid_connect from 1.1.6 to 1.1.7"

- features/candidates/placement_requests/cancelling_a_placement_request.feature
Temporarily marking as wip until we can resolve the issue
> This test is currently failing ci

- Gemfile.lock
Reverts DFE-Digital/schools-experience#535
> Revert "Revert "Bump openid_connect from 1.1.6 to 1.1.7""

- app/views/schools/on_boarding/descriptions/_form.html.erb
> Adds new hint text from prototype

- app/views/schools/on_boarding/profiles/show.html.erb
- features/schools/onboarding/school_profile.feature
Add the school phone number to the School details section as per the
prototype
> Add phone number to check your answers school details

- app/controllers/candidates/registrations/placement_requests_controller.rb
> Cancellation url not available before phase3

- app/views/candidates/home/index.html.erb
> Add Guidance for schools link to landing page

- features/schools/landing_page.feature
In the CD pipeline features must be named so that the JUnit formatter (used for publishing test results) can run.
Naming the school landing page feature.
Minor change.
> missing feature title for the school landing page

- app/models/bookings/candidate.rb
- app/models/bookings/placement_request.rb
- db/migrate/20190618152627_add_candidate_id_to_bookings_placement_requests.rb
- db/schema.rb
- spec/models/bookings/candidate_spec.rb
- spec/models/bookings/placement_request_spec.rb
- spec/models/candidates/session_token_spec.rb
This PR builds off 590 and that should be reviewed first.
Add an association between a Candidate and PlacementRequest - this is allowed to be blank since we're not using it yet, that work is coming in in 742.
You'll only need to look at the last commit - the rest is the same as PR 590 thanks
> Add candidate association

- app/views/schools/on_boarding/confirmations/show.html.erb
Updates the copy to match the prototype.
> Update school onboarding confirmation page copy

- app/controllers/candidates/registrations/placement_requests_controller.rb
- app/jobs/candidates/registrations/placement_request_job.rb
- app/views/schools/dashboards/show.html.erb
- app/views/schools/on_boarding/confirmations/show.html.erb
- config/routes.rb
- spec/jobs/candidates/registrations/placement_request_job_spec.rb
The Phase 3 release has been split in two, Phase 3 will include _just_
the CRM integration and Phase 4 will add the new placement
request/booking functionality and new dashboard.
In addition, where possible I've opted to use greater/less than or equal
so the actual phase number is included on the line.
Ensure that the new values make sense and the correct features are flagged.
> Update feature flags to match new phases

- app/services/bookings/gitis/crm.rb
- app/services/bookings/gitis/entity.rb
We are potentially going to have attributes which we can write to if we are creating a new entity but not update once they are set
Separate out the code paths for create attributes vs update attributes
> SE-1262 Whitelist updated attributes

- app/views/candidates/home/index.html.erb
Remove aria-labelledby
List content can be inferred from heading
Remove "in subsection"
Confusing when navigating with voice over, voice over reads the link
followed by "in subsection".
> Se 1029/acessibility/candidates home screen

- app/views/schools/on_boarding/_school_fees_shared_form.html.erb
- app/views/schools/on_boarding/dbs_fees/new.html.erb
- app/views/schools/on_boarding/fees/_form.html.erb
School onboarding wizard had some headings that weren't headings
Fixes incorrect heading markup
> Fixes incorrect heading markup

- Gemfile.lock
- app/assets/stylesheets/school-placement-dates.scss
- app/views/schools/placement_dates/edit.html.erb
- app/views/schools/placement_dates/new.html.erb
- config/locales/en.yml
- features/schools/placement_dates/edit.feature
- features/schools/placement_dates/new.feature
- features/step_definitions/form_steps.rb
- features/step_definitions/schools/placement_dates/new_steps.rb
Updates the copy and styling on placement dates new and edit to match the screen shots in the ticket.
> Se 1186/schools/dates/add content to fixed dates

- app/views/candidates/registrations/subject_preferences/_form.html.erb
- app/views/schools/on_boarding/candidate_requirements/_form.html.erb
> Adds additional copy from prototype

- app/views/schools/availability_info/edit.html.erb
- app/views/schools/availability_preferences/edit.html.erb
- app/views/schools/dashboards/_dashlette.html.erb
- app/views/schools/placement_dates/index.html.erb
- config/locales/en.yml
- features/schools/availability_information/edit.feature
- features/schools/availability_preferences/edit.feature
- features/schools/placement_dates/index.feature
- spec/controllers/schools/dashboards_controller_spec.rb
Update text as per SE/1236
Several small text changes including page titles, labels and headings
Ensure my changes match those in the ticket and it all makes sense
> Update text on dashlette and dates pages

- app/views/candidates/schools/index.html.erb
- spec/views/candidates/schools/index.html.erb_spec.rb
Add aria-labels to important landmarks
Fix h3 to be h2
> Accessibility fixes

- app/views/schools/on_boarding/_school_fees_shared_form.html.erb
- app/views/schools/on_boarding/admin_contacts/_form.html.erb
- app/views/schools/on_boarding/candidate_experience_details/_form.html.erb
- app/views/schools/on_boarding/candidate_requirements/_form.html.erb
- app/views/schools/on_boarding/dbs_fees/new.html.erb
- app/views/schools/on_boarding/descriptions/_form.html.erb
- app/views/schools/on_boarding/experience_outlines/_form.html.erb
- app/views/schools/on_boarding/fees/_form.html.erb
- app/views/schools/on_boarding/key_stage_lists/_form.html.erb
- app/views/schools/on_boarding/phases_lists/_form.html.erb
- app/views/schools/on_boarding/subjects/_form.html.erb
School on boarding wizard didn't have back links
Adds back links to the school on boarding wizard
School on boarding wizard should have back links
> Adds missing back links to school on boarding wizard

- app/assets/stylesheets/global-styles.scss
- app/views/candidates/home/index.html.erb
- features/candidates/landing_page.feature
- features/step_definitions/candidates/landing_page_steps.rb
- spec/views/candidates/home/index.html.erb_spec.rb
Fred has provided updated copy for the homepage
1. Include the updated copy
2. Update the specs and features accordingly
> Updated homepage content from Fred

- app/jobs/candidates/registrations/placement_request_job.rb
- app/notify/notify_email/school_request_confirmation_with_placement_request_url.rb
- app/notify/notify_email/school_request_confirmation_withviewplacementrequesturl.74f5df05-548a-4949-8ec2-fcc27b9034d7.md
- spec/jobs/candidates/registrations/placement_request_job_spec.rb
- spec/notify/notify_email/school_request_confirmation_with_placement_request_url_spec.rb
Change school request conf email dependent on phase
Send a different version of the school request confirmation email
depending on phase.
In releases before phase4 school's don't have access to
PlacementRequests#show, so we don't want to add that url in the
personalisation params sent to notify.
Code should be compatible with phases 2-4
> Se 1249/remove personalisation param from notify email

- app/views/schools/dashboards/_full_dashboard.html.erb
- app/views/schools/dashboards/_new_requests_and_bookings.html.erb
- app/views/schools/placement_requests/index.html.erb
The layout on the school dashboard got out of sync with all the recent
merges.
Fixes dashboard and placement_request show views.
School dashboard and placement request show should look correct
> Dashboard fixes

- app/views/candidates/placement_requests/cancellations/_show_placement_request.html.erb
This was raising an error when phase was set to 4
> Only show path helper if phase 5

- app/services/bookings/gitis/auth.rb
Just got an Auth failure - and it tells us where the problem is but not what the problem is.
1. Improved quality of Exception raised
> Expand the error from a Token failure

- app/services/bookings/gitis/contact.rb
- app/services/bookings/gitis/entity.rb
- app/services/bookings/gitis/fake_crm.rb
- spec/controllers/candidates/registrations/contact_informations_controller_spec.rb
- spec/factories/bookings/gitis/contact_factory.rb
- spec/services/bookings/gitis/contact_spec.rb
- spec/services/bookings/gitis/entity_spec.rb
Small changes to how we handle the attributes mapping around Email addresses and Telephone
1. Cleaned up handling of dirty attributes
2. Added smarter mapping of email addresses - in line with Gitis's requested changes
2. Added smarter mapping of telephone numbers addresses - in line with Gitis's requested changes
1. Does it look sane
> SE1255 - update attributes handling

- app/views/pages/cookies_policy.html.erb
The cookie policy needed updating to cover changes in #503 
Update with new content. Also standardised some of the language, replacing __the user's__ with __your__.
Ensure everything reads ok
> Update cookies policy for analytics tracking UUID

- app/views/schools/placement_requests/index.html.erb
> Adds missing back button

- features/candidates/registrations/application_preview.feature
- features/candidates/registrations/wizard.feature
- features/candidates/schools/show/full_school_details.feature
- features/step_definitions/candidates/registrations/application_preview_steps.rb
- features/step_definitions/candidates/schools/show_steps.rb
- features/step_definitions/common_school_steps.rb
- features/step_definitions/schools/placement_request_steps.rb
Various features manipulate the current school. The steps to do so are
spread over various step_definition files.
This commit moves the common school realated steps in to
common_school_steps.rb
> Refactor school steps

- app/services/candidates/registrations/contact_information.rb
Needed incase Phase 2 and 4 are both in production less than 24 hours apart.
Extended phase check to phase 4
1. Code review
> Allow migratory fields in Phase 4

- app/views/candidates/placement_requests/cancellations/_show_booking.html.erb
Noticed an error on staging, looks like bumping this phase check got missed
> Candidate dashboard route only exists in phase >=5

- app/views/schools/dashboards/_dashlette.html.erb
- app/views/schools/dashboards/_full_dashboard.html.erb
- config/routes.rb
Service update page is misleading since we're not rolling out phase 3 just yet
1. Feature flag route
2. Feature flagged links from dashboard
3. Feature flagged links from dashlette
> Feature flagged service update screen

- features/schools/placement_requests/acceptance/confirm_booking.feature
- spec/controllers/schools/placement_requests/acceptance/confirm_booking_controller_spec.rb
- yarn.lock
> merge master into run-functional-tests-in-parallel

- script/generate_matrix.sh
If statement is wrong in generate matrix
A bug fix
> fixing generate matrix script

- app/views/schools/errors/not_registered/show.html.erb
Simple text change, slight re-wording with a bit more direction
> Add more direction when requesting further info

- app/views/candidates/registrations/confirmation_emails/show.html.erb
> fix missing h1

- app/views/schools/on_boarding/descriptions/_form.html.erb
Removes copy to match changes to the prototype
> Remove copy to match prototype

- app/views/schools/show.html.erb
School show on the prototype has been updated, need to bring the rails app inline with content changes
Updates schools#show to match the prototype
> Bring schools/show inline with prototype

- config/locales/en.yml
- features/schools/onboarding/phases.feature
- features/step_definitions/schools/onboarding_steps.rb
Update the phase labels to match those shown to the candidates
> Update phase labels on school onboarding

- app/controllers/schools/insecure_sessions_controller.rb
- app/views/candidates/schools/_phase2.html.erb
- features/schools/onboarding/confirmation.feature
- features/step_definitions/candidates/registrations/application_preview_steps.rb
- features/step_definitions/candidates/schools/show_steps.rb
- features/support/path_helper.rb
We were missing a feature test for publishing the school profile
Adds a feature test to ensure the profile is published correctly
Test should look sensible
> Adds publishing profile feature specs

- Gemfile.lock
- app/views/candidates/registrations/personal_informations/_form.html.erb
- app/views/candidates/sessions/new.html.erb
- app/views/schools/confirmed_bookings/date/edit.html.erb
- app/views/schools/placement_dates/new.html.erb
The `date_field` method prototype in the form builder has changed back to its original format
1. Update the form builder version
1. Amend usage of form builder to the original method prototype
1. Do specs pass
2. Does it look sane
> Update form builder

- app/views/candidates/registrations/placement_preferences/_form.html.erb
- features/step_definitions/candidates/registrations/request_school_experience_placement_steps.rb
> Updates copy for flexible dates

- app/views/schools/on_boarding/key_stage_lists/_form.html.erb
- app/views/schools/on_boarding/phases_lists/_form.html.erb
- app/views/schools/on_boarding/subjects/_form.html.erb
- config/locales/en.yml
Screen readers we're having a hard time demeriting the purpose of each check box as they weren't grouped in a field set.
Group check box inputs into fieldsets
> DAC - feedback. Wraps checkboxes in fieldsets

- app/assets/stylesheets/form-extensions.scss
- app/views/candidates/schools/index.html.erb
- config/locales/en.yml
- features/candidates/schools/search/results/sorting.feature
- features/step_definitions/candidates/schools/results_steps.rb
- features/step_definitions/candidates/schools/sorting_steps.rb
Feedback from DAC suggested that having the page reload when a select
option is chosen was surprising behaviour.
> Change sort order select to radio buttons

- config/environments/production.rb
Reverts DFE-Digital/schools-experience#825
> Revert "Dont require env vars which are not yet used in production"

- azure-pipelines.yml
- script/image_tags_and_ipaddress.sh
The script contents appears in numerous places in the CD pipeline and extracting into the code base and then referencing it in the CD pipeline will keep things DRY.
Add a script for image tag names and the setting of a IP address environment variable.
Should just be confirmation that the script is added as an artefact to the build summary.
> image tags and ip address script

- app/views/pages/privacy_policy.html.erb
- config/locales/en.yml
- spec/features/candidates/registrations_spec.rb
We need to show the same privacy policy to our Candidates as Gitis uses
1. Updated the privacy policy file
2. Updated the Preview your Placement Request screen with updated information to be shown alongside the tickbox.
1. Does it show correctly
2. Does the content match that included with the docx file attached to the ticket in Jira (SE-1579)
> SE-1579 New privacy policy

- spec_external/gitis_crm_spec.rb
Our test suite should reflect what we need to write to the CRM
1. Stop writing ownerId on contacts
2. Populate `telephone1` and `address1_telephone1` on Contacts
3. Create CandidatePrivacyPolicy records
4. Verify the CandidatePrivacyPolicy records
2. if you've got the env vars you can run it against the Gitis DEV environment
> Updated CRM testsuite

- app/jobs/cron/sync_subjects_with_gitis_job.rb
Currently the Synchronisation of subjects with Gitis is not running
1. Run the synchronisation
1. Code review
> Enabled Gitis Subject sync

- app/controllers/schools/confirm_attendance_controller.rb
- app/controllers/schools/confirmed_bookings_controller.rb
- app/models/bookings/placement_request.rb
- features/step_definitions/schools/bookings_steps.rb
- spec/controllers/schools/placement_requests_controller_spec.rb
- spec/models/bookings/placement_request_spec.rb
> Hide cancelled bookings from index

- jmeter/schoolexperience.jmx
There has been a content change on the initial search page.
Update an assertion in the JMeter load test to reflect the content change.
The JMeter test runs in the CD pipeline, but still a developer can still confirm that the context for the change is correct.
Eventually the CD pipeline will be defined in yaml like the CI pipeline (it may even be that there is a single pipeline) so the location of the JMeter test is not so odd.
> text has changed on the search page, so the JMeter test needs updating

- app/javascript/packs/application.js
- app/views/candidates/registrations/application_previews/show.html.erb
Prevent users from accidentally double clicking the submit button
> Prevent accidental duplicate submissions of the Placement Requests

- config/environments/production.rb
We are now running with Phase 4 and this should now be the default phase
1. Changed the default phase in production
> Changed default phase to phase 4

- app/views/candidates/registrations/sign_ins/show.html.erb
- features/candidates/registrations/verify_your_email.feature
- spec/features/candidates/registrations_spec.rb
- spec/views/candidates/registrations/sign_ins/show.html.erb_spec.rb
This screen does not currently explain where we got a users details from.
1. Text change which adds an explanation.
1. Text review
> SE-1608 Updated the verify your email address screen

- config/environments/production.rb
> Enable candidate_requirement_ab_test feature in prod

- app/controllers/schools/on_boarding/candidate_requirements_selections_controller.rb
- app/forms/schools/on_boarding/candidate_requirements_selection.rb
- app/models/schools/school_profile.rb
- app/presenters/schools/on_boarding/candidate_requirements_selection_presenter.rb
- app/views/schools/on_boarding/candidate_requirements_selections/_form.html.erb
- config/locales/en.yml
- db/migrate/20190904120202_rename_candidate_requirement_selection_options.rb
- db/schema.rb
- features/schools/onboarding/confirmation.feature
- features/schools/onboarding/school_profile.feature
- features/step_definitions/schools/onboarding_steps.rb
- spec/controllers/schools/on_boarding/candidate_requirements_selections_controller_spec.rb
- spec/factories/schools/on_boarding/candidate_requirements_selection_factory.rb
- spec/forms/schools/on_boarding/candidate_requirements_selection_spec.rb
The options on the prototype have been reworded.
As this feature has not been released yet I've removed the old columns.
> Update select candidate requirement options

- app/views/candidates/registrations/placement_requests/show.html.erb
Remove the last reference to summer holidays that remained after #893
> Remove final reference to summer holidays

- app/controllers/schools/on_boarding/access_needs_details_controller.rb
- app/controllers/schools/on_boarding/access_needs_policies_controller.rb
- app/controllers/schools/on_boarding/access_needs_supports_controller.rb
- app/controllers/schools/on_boarding/disability_confidents_controller.rb
- app/views/schools/on_boarding/access_needs_details/_form.html.erb
- app/views/schools/on_boarding/access_needs_details/edit.html.erb
- app/views/schools/on_boarding/access_needs_policies/_form.html.erb
- app/views/schools/on_boarding/access_needs_policies/edit.html.erb
- app/views/schools/on_boarding/access_needs_supports/_form.html.erb
- app/views/schools/on_boarding/access_needs_supports/edit.html.erb
- app/views/schools/on_boarding/disability_confidents/_form.html.erb
- app/views/schools/on_boarding/disability_confidents/edit.html.erb
- config/routes.rb
- spec/controllers/schools/on_boarding/access_needs_details_controller_spec.rb
- spec/controllers/schools/on_boarding/access_needs_policies_controller_spec.rb
- spec/controllers/schools/on_boarding/access_needs_supports_controller_spec.rb
- spec/controllers/schools/on_boarding/disability_confidents_controller_spec.rb
The school on boarding wizard in the prototype has been changed to include new accessibility questions.
Makes the new accessibility resources editable
builds on to of [#910](https://github.com/DFE-Digital/schools-experience/pull/910) so wait for that to be merged before reviewing this
> Se 1545/schools/on boarding/split access needs page 6

- app/forms/schools/on_boarding/current_step.rb
The school on boarding wizard in the prototype has been changed to include new accessibility questions.
Refactors current step
Done as part of the work on adding the new accessibility screens so review after [#911](SE-1545/schools/on_boarding/split-access-needs-page-6) has been merged
> Se 1545/schools/on boarding/split access needs page 7

- features/schools/placement_dates/index.feature
Noticed this on Friday
Fix quoting in feature spec
> Fix quoting in feature test

- app/controllers/candidates/feedbacks_controller.rb
- app/controllers/schools/feedbacks_controller.rb
- app/models/feedback.rb
- app/models/schools/feedback.rb
- app/views/feedbacks/_form.html.erb
- config/locales/en.yml
- db/migrate/20190916105024_add_successful_visit_to_feedbacks.rb
- db/schema.rb
- features/candidates/feedback.feature
- features/schools/feedback.feature
- spec/factories/candidates/feedback.rb
- spec/factories/schools/feedback.rb
Adds a new new question to the feedback form along with an additional
option for Schools::Feedback#reason_for_using_service
A new option and a new question were requested for the feedback form
Adds a new question to both candidate and school feedback and a new option to the school reason for using service.
Should look sensible
> Adds new feedback option and question.

- app/controllers/candidates/feedbacks_controller.rb
- app/controllers/schools/feedbacks_controller.rb
We're not using it in the view
> Remove assigning instance variable

- app/views/schools/dashboards/_new_requests_and_bookings.html.erb
- features/schools/dashboard.feature
The old wording was out-of-sync with the prototype and was confusing to
users
Replace it with improved wording from the prototype
> Reword the hints on the schools dashboard - SE-1692

- app/views/candidates/registrations/application_previews/show.html.erb
> Fix markup on check answers

- config/routes.rb
These were inadvertently added by a merge some time ago, the whole block is duplicated
> Remove duplicated routes block

- config/environments/production.rb
> turn on access_needs_journey for production

- app/forms/schools/on_boarding/access_needs_policy.rb
- config/locales/en.yml
Previously url validation error said 'invalid' twice if an invalid url
was entered.
> Fix validation on url

- app/controllers/pages_controller.rb
- app/views/pages/help_and_support_access_needs.html.erb
- app/views/schools/on_boarding/access_needs_supports/_form.html.erb
- config/routes.rb
> adds missing access needs support page

- features/step_definitions/candidates/registrations/application_preview_steps.rb
- features/step_definitions/candidates/schools/sorting_steps.rb
- features/step_definitions/schools/placement_dates/placement_date_steps.rb
Minor changes to tests to prevent `govuk-lint-ruby` from complaining
> Fix some linting errors in the step definitions

- app/services/candidates/registrations/contact_information.rb
- app/services/candidates/registrations/personal_information.rb
- config/locales/en.yml
- spec/services/candidates/registrations/contact_information_spec.rb
- spec/services/candidates/registrations/personal_information_spec.rb
Reverts DFE-Digital/schools-experience#973
> Revert "Add length validations matching the gitis CRM API SE-1503"

- azure-pipelines.yml
- features/step_definitions/schools/bookings_steps.rb
- features/support/database_cleaner.rb
- features/support/env.rb
We don't currently lint the features folder in CI. This allows linting errors to creep in.
1. Run the linter on the features folder as well
1. Does it still pass CI
> Run linter on cucumber features as well

- app/services/candidates/registrations/contact_information.rb
- app/services/candidates/registrations/personal_information.rb
- config/locales/en.yml
- spec/services/candidates/registrations/contact_information_spec.rb
- spec/services/candidates/registrations/personal_information_spec.rb
Reverts DFE-Digital/schools-experience#998
> Revert "Revert "Add length validations matching the gitis CRM API SE-1503""

- .rubocop.yml
- azure-pipelines.yml
- config/environments/production.rb
- config/environments/servertest.rb
- config/initializers/application_insights.rb
- config/initializers/canonical_redirect.rb
- config/initializers/content_security_policy.rb
- config/initializers/delayed_job_web.rb
- config/initializers/exception_notification.rb
- config/initializers/filter_active_job_logging.rb
- config/initializers/filter_parameter_logging.rb
- config/initializers/kaminari_config.rb
- config/initializers/validates_timeliness.rb
- config/puma.rb
- config/routes.rb
We should lint as much of the codebase as possible
1. Also lint the config directory
1. Review code changes
2. Ensure tests still pass
> Lint config dir

- config/locales/en.yml
- features/schools/onboarding/phases.feature
- features/step_definitions/schools/onboarding_steps.rb
Improve clarity of phases wording and bring it inline with the prototype
1. Added 'years' to the Primary and Secondary phase listing
1. Code review
> Updated phases listing in Schools onboarding process

- config/locales/en.yml
- features/schools/onboarding/access_needs_support.feature
- features/step_definitions/schools/onboarding_steps.rb
We had a typo on the access needs page
Fixes the typo
Typo should be fixed
> Fix typo'd disabilities text

- config/locales/en.yml
- features/schools/onboarding/school_profile.feature
Add a line regarding GDPR compliance to the schools acceptance checkbox label
> Add GDPR terms and conditions SE-1880

- features/step_definitions/schools/withdrawn_requests_steps.rb
Linting step currently fails on the `development` branch
1. Lint fixes
> Fix for lint error on withdrawn requests cucumber steps

- app/views/schools/on_boarding/admin_contacts/_form.html.erb
- app/views/schools/on_boarding/confirmations/show.html.erb
Some text referred to schools being sent PII which is no longer the case
Amend text removing PII references
Ensure changes make sense
> Update content to reflect new pii handling SE-1860

- .github/PULL_REQUEST_TEMPLATE.md
It is useful to include a reference back from the pull request to the Jira ticket it corresponds to
1. Added a section to the template
> Added section for Jira ticket number to the Pull Request template

- app/views/schools/on_boarding/key_stage_lists/_form.html.erb
- app/views/schools/on_boarding/subjects/_form.html.erb
- config/locales/en.yml
SE-1760
Minor content changes to match prototype
Check spelling!
> Content changes to match prototype

- features/candidates/registrations/request_school_experience_placement/schools_with_specified_placement_dates.feature
- features/step_definitions/candidates/registrations/request_school_experience_placement_steps.rb
SE-1804
Some scenarios had been marked as `@wip` and hadn't been updated
Modify those scenarios to reflect the onboarding process as it now stands
Ensure the features make sense
> (Subject-specific dates) Update placement features to reflect new wizard

- app/controllers/schools/placement_dates/configurations_controller.rb
- app/forms/schools/placement_dates/configuration_form.rb
- spec/forms/schools/placement_dates/configuration_form_spec.rb
SE-1804
Move the conditional logic into a method on configuration as per Jeremy's comment
> Move conditional into method on configuration

- config/environments/development.rb
We had a N+1 on the subject specific dates work which was showing up in the logs but hadn't been picked up on.
1. Make bullet raise errors in development
1. Code review
> Make bullet raise errors in development

- app/models/bookings/profile.rb
- spec/models/bookings/profile_spec.rb
SE-1943
Fixes production bug for schools w/o dbs requirement publishing their profiles
Manual testing, on board a school, select no for dbs requirements, don't enter an explanation, expect to be able to finish on boarding without error.
> Fix publishing profile for schools w/o dbs

- app/services/bookings/gitis/contact.rb
- app/services/bookings/gitis/entity.rb
- spec/factories/bookings/gitis/contact_factory.rb
- spec/models/bookings/subject_sync_spec.rb
- spec/models/candidates/session_spec.rb
- spec/services/bookings/gitis/contact_spec.rb
- spec/services/bookings/gitis/crm_spec.rb
- spec/services/bookings/gitis/entity_spec.rb
- spec/support/test_entity.rb
ActiveModel::Attributes provides all the functionality we require to track changes for submitting data to Dynamics. We should use that instead of our custom implemention.
1. Converted to use ActiveModel::Attributes and ActiveModel::Dirty
2. Fixed bug with inherited models overwriting parents attribute lists
3. Made id a 'real' attribute
1. Does it work
2. Does it improve code clarify?
> Use ActiveModel::Attributes

- app/views/feedbacks/_form.html.erb
- app/views/pages/accessibility_statement.html.erb
- app/views/pages/help_and_support_access_needs.html.erb
- config/locales/en.yml
N/A
Mak spotted a few typos/spelling errors
Fix them and do very minor rewordings
> Make several small spelling fixes

- app/notify/notify_email/candidate_request_rejection.577100df-1dae-405e-8500-947b85edf76e.md
SE-1460
The candidate rejection email template copy was out of date
Add some resources helpful to rejected candidates to the email template
Final typo check - copied and pasted @fredbrenton's words so it _should_ be ok! 😅
> Sync template to reflect updated notify email

- config/locales/en.yml
- features/schools/onboarding/descriptions.feature
- features/step_definitions/schools/onboarding_steps.rb
SE-1757
Updating content to match prototype
Minor content changes
Check spelling!
> Updates copy to match prototype

- app/notify/notify_email/candidate_request_confirmation_no_pii.8ee470a1-0b94-48ee-9fe7-98b7beb8921c.md
- app/notify/notify_email/school_request_confirmation_link_only.2a5a54b8-17cb-4da8-94ce-1647d6bf1da3.md
SE-1571
Updated the email templates on notify to include feedback links, syncing our local copies
> Add feedback links to placement_request emails

- config/locales/en.yml
SE-1940
The provided example date was invalid
Change it for a valid one (where the candidate would be >18 years old)
Does it make sense?
> Change the example birth date from 2007 to 1997 SE-1940

- app/notify/notify_email/candidate_booking_date_changed.b02bb4c7-ae3a-466a-8d2d-5bda3c45ff6a.md
Added formatting to match booking confirmation email
SE-1771
Minor layout fix from qa
Syncs changes with notify template
> Sync template with notify

- config/environments/production.rb
Enable subject_specific_dates in production
> Enable subject specific dates

- app/views/candidates/schools/_access_needs_statement.html.erb
- app/views/candidates/schools/_phase2.html.erb
SE-1965
Reposition access needs details to match prototype
Repositions access needs details partial
> Reposition access needs details to match prototype

- app/services/bookings/gitis/contact.rb
- app/services/bookings/gitis/entity.rb
Reverts DFE-Digital/schools-experience#982
> Revert "Use defaults feature on Active Model"

- spec/controllers/candidates/dashboard_base_controller_spec.rb
- spec/controllers/candidates/registrations/personal_informations_controller_spec.rb
- spec/controllers/candidates/registrations/sign_ins_controller_spec.rb
- spec/controllers/candidates/sessions_controller_spec.rb
- spec/jobs/candidates/registrations/placement_request_job_spec.rb
- spec/jobs/candidates/registrations/send_email_confirmation_job_spec.rb
- spec/jobs/notify_job_spec.rb
- spec/notify/notify_service_spec.rb
- spec/notify/notify_spec.rb
- spec/spec_helper.rb
SE-2033
I've found a couple of bugs which have crept into the test suite which would have been caught by running the tests randomly.
1. Enable randomisation
2. Fix the ordering bugs in tests
1. Do the tests pass
2. Sanity check
> SE-2033 Randomize specs

- Gemfile
- Gemfile.lock
- azure-pipelines.yml
- docker-compose.yml
Reverts DFE-Digital/schools-experience#1199
Not sure why yet but this appears to be breaking builds
> Revert "Upload test failures into CI"

- Gemfile
- Gemfile.lock
- azure-pipelines.yml
- docker-compose.yml
Reverts DFE-Digital/schools-experience#1251
Seems to be unrelated so can be re-enabled
> Revert "Revert "Upload test failures into CI""

- app/views/pages/_0a203956-e935-ea11-a813-000d3a44a8e9.html.erb
- config/environments/development.rb
- config/environments/production.rb
SE-1976
The combined privacy policy shared by both Gitis and School Experience has been revised.
1. Add the new privacy policy to the codebase
2. Change the default privacy policy to be the new one
> SE-1976 Revised privacy policy

- app/views/candidates/registrations/personal_informations/_form.html.erb
SE-2054
This page may potentially take a while to respond if Gitis is being slow. At
which point the user may retry submitting, than we have a potential race beween
multiple requests trying to register a new user in Gitis.
1. Prevent repeat submissions to resolve this.
> SE-2054 Prevent double clicks on Personal Information form

- Gemfile
- Gemfile.lock
Other parties within DfE which to review the database structure, via an Entity Relationship Diagram.
1. Added the Rails-ERD gem to allow generating such diagrams from the ActiveRecord models
> Added Rails-ERD gem

- Dockerfile
- yarn.lock
We are currently using an unsupported version of Node JS
1. Upgraded to NodeJS 10
> Upgrade to NodeJS 10

- app/views/schools/show.html.erb
SE-2100
Experience is misspelt as exerience on the Manage school experience homepage
1. Correct spelling
> Fixed typo on the Manage schools experience page

- Gemfile.lock
Dependabots PR for the geocoder update is failing for some reason.
1. Upgrade geocoder manually
> Updated Geocoder

- azure-pipelines.yml
Disable running cucumber against real browsers since its not working for now
> Disable chrome and FF tests in CI

- azure-pipelines.yml
Reverts DFE-Digital/schools-experience#1354
> Revert "Disable chrome and FF tests in CI"

- Gemfile.lock
- package.json
- yarn.lock
SE-2086
We should use the latest version of GovUK Frontend toolkit to benefit from any fixes they include
1. Change to use govuk-frontend v3.5
> Upgraded to govuk-frontend v3.5

- app/controllers/schools/sessions_controller.rb
- spec/controllers/schools/sessions_controller_spec.rb
SE-1701
Currently the role checking code runs after the session data base been assign.
1. Instead run it prior to assignment.
> Check role prior to assigning session data

- app/assets/stylesheets/school-bookings.scss
SE-2090
Row separators are missing off table
1. Removed css hiding the row separators
> Added missing table row separators

- data/service_updates/20190326.yml
- data/service_updates/20190520.yml
SE-2128
We need to test/demo the service update feature with some sample data
1. Added sample data
> Added sample data to Service Updates for testing with

- azure-pipelines.yml
Reverts DFE-Digital/schools-experience#1351
> Revert "Disable lint check till I find why its failing"

- docker-compose-chrome.yml
- docker-compose-firefox.yml
We are getting fairly consistent failures now from CI - these have increased in likelyhood in the last couple of weeks. 
1. Upgrade the version of selenium to see if this helps
> Attempted upgrade of Selenium to 3.141.59-zinc

- app/controllers/concerns/dfe_authentication.rb
- app/models/schools/change_school.rb
- app/services/schools/dfe_sign_in_api/role_checked_organisations.rb
- app/services/schools/dfe_sign_in_api/roles.rb
- spec/controllers/concerns/dfe_authentication_spec.rb
- spec/controllers/schools/change_schools_controller_spec.rb
- spec/controllers/schools/placement_requests_controller_spec.rb
- spec/models/schools/change_school_spec.rb
- spec/services/schools/dfe_sign_in_api/role_checked_organisations_spec.rb
- spec/services/schools/dfe_sign_in_api/roles_spec.rb
SE-2121
Split this change out since whilst its a pre-requisite for SE-2121, its generally useful functionality
1. Move the checking of Roles to be before we provide the list of Schools to the user so the user doesn't see schools they are part of but lack roles over
> SE-2121 moved role check earlier in process

- docker-compose-chrome.yml
- docker-compose-firefox.yml
Reverts DFE-Digital/schools-experience#1346
New version is proving unreliable
> Revert "Attempted upgrade of Selenium to 3.141.59-zinc"

- app/controllers/schools/sessions_controller.rb
SE-2116
We've seen some 'insufficient priviledges' errors but these appear to be coming from users without organisations rather than from the users with missing roles
1. Raise a different exception for improved visibility of this
> SE-2116 Split out handling of No Organisation behaviour for better visibility

- app/controllers/schools/attendances_controller.rb
- app/helpers/application_helper.rb
- app/helpers/schools/bookings_helper.rb
- app/models/bookings/booking.rb
- app/views/schools/attendances/_table.html.erb
- app/views/schools/attendances/index.html.erb
- app/views/schools/confirm_attendance/show.html.erb
- config/routes.rb
- features/schools/attendances/index.feature
- features/step_definitions/schools/attendances_steps.rb
- features/support/path_helper.rb
- spec/controllers/schools/attendances_controller_spec.rb
- spec/models/bookings/booking_spec.rb
SE-2120
Currently schools don't have a single list showing the attendance outcome of past bookings.
1. Added screens showing historical attendance records
> SE-2120 Attendance history

- app/controllers/candidates/home_controller.rb
- app/controllers/candidates/school_searches_controller.rb
- app/controllers/candidates/schools_controller.rb
- app/views/candidates/home/index.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/servertest.rb
- config/environments/test.rb
- spec/controllers/candidates/school_searches_controller_spec.rb
- spec/controllers/candidates/schools_controller_spec.rb
- spec/views/candidates/home/index.html.erb_spec.rb
SE-2151
We need a mechanism to prevent users from searching for schools to apply for
1. Redirect all searches back to the home page
2. Remove the 'Start' button from the homepage
3. Show a formatted message explaining the deactivation
4. The feature enabled when environment variable is assigned with a message
> SE-2151 Disabling candidate applications

- app/models/bookings/data/gias_data_file.rb
- app/models/bookings/data/school_updater.rb
- app/models/bookings/school_sync.rb
- spec/models/bookings/data/gias_data_file_spec.rb
- spec/models/bookings/data/school_updater_spec.rb
SE-2055
Our sync with GIAS is currently not running
1. Check 'correctness' of file on download
2. Use CSV.foreach to avoid reading entire file into memory
3. Perform imports in batches of 1000 to allow for 'eventually consistent' syncs when it cannot be completed within the timeout for the delayed job.
> SE-2055 Fixes for sync errors

- app/assets/stylesheets/school-search.scss
- app/controllers/candidates/home_controller.rb
- app/controllers/candidates/schools_controller.rb
- app/models/bookings/school_search.rb
- app/models/candidates/school_search.rb
- app/views/candidates/home/index.html.erb
- app/views/candidates/school_searches/new.html.erb
- app/views/candidates/schools/_no_results.html.erb
- app/views/candidates/schools/index.html.erb
- spec/controllers/candidates/schools_controller_spec.rb
- spec/models/bookings/school_search_spec.rb
- spec/views/candidates/home/index.html.erb_spec.rb
- spec/views/candidates/school_searches/new.html.erb_spec.rb
- spec/views/candidates/schools/index.html.erb_spec.rb
SE-2152
Added ability to whitelist the URNs which will be returned by the search results
1. Show notification on home screen if set
2. Block access to school profiles not in URN whitelist (if whitelist not blank)
3. Return search results from URN whitelist, ordered by distance from search location
4. Show same notification on search results as on homepage
> SE-2152 Restricted urns

- app/controllers/application_controller.rb
- app/controllers/candidates/home_controller.rb
- app/controllers/candidates/schools_controller.rb
- app/controllers/schools/base_controller.rb
- app/controllers/schools/sessions_controller.rb
- app/controllers/schools_controller.rb
- app/views/candidates/home/index.html.erb
- app/views/candidates/schools/index.html.erb
- app/views/layouts/application.html.erb
- app/views/shared/candidates/_alert_notification.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/servertest.rb
- config/environments/test.rb
- spec/views/candidates/home/index.html.erb_spec.rb
- spec/views/candidates/schools/index.html.erb_spec.rb
SE-2152
We need a mechanism to show an alert explaining the current situation to all users of the Get schools experience service.
1. Moved from showing the alert on just the home page and search results page to showing on all pages.
> SE-2152 Updated notification delivery

- data/service_updates/20200324.yml
SE-2152
We need to notify schools of the changes which have occurred and the what they can do about it.
1. Added explanatory Service Update
> SE-2152 Added service update for COVID-19 response

- app/views/schools/dashboards/_no_availability_info_warning.html.erb
The link when setting up dates the first time is broken
1. Fix the link
> Fix broken link when setting up school dates

- Gemfile
- Gemfile.lock
- package-lock.json
- package.json
- yarn.lock
> Dependencies

- Gemfile.lock
- azure-pipelines.yml
- features/schools/attendances/index.feature
- features/schools/availability_information/edit.feature
- features/schools/availability_preferences/edit.feature
- features/schools/confirmed_bookings/show.feature
- features/schools/errors/not_registered.feature
- features/schools/onboarding/access_needs_policy.feature
- features/schools/onboarding/access_needs_support.feature
- features/schools/onboarding/administration_fee.feature
- features/schools/onboarding/candidate_experience_detail.feature
- features/schools/onboarding/candidate_requirements_choice.feature
- features/schools/onboarding/dbs_fee.feature
- features/schools/onboarding/dbs_required_toggling_fees.feature
- features/schools/onboarding/dbs_requirements.feature
- features/schools/onboarding/disability_confident.feature
- features/schools/onboarding/school_profile.feature
- features/schools/placement_dates/edit.feature
- features/schools/placement_dates/index.feature
- features/schools/placement_dates/primary_and_secondary_school_configuration.feature
- features/schools/placement_dates/secondary_school_configuration.feature
- features/schools/placement_requests/acceptance/confirming_a_request_with_a_past_date.feature
- features/schools/placement_requests/acceptance/sending_details_to_candidate.feature
- features/schools/placement_requests/cancelling.feature
- features/schools/previous_bookings/show.feature
- features/schools/rejected_requests/show.feature
- features/schools/withdrawn_requests/show.feature
- script/pre-commit
added @smoke_test tag to cucumber tests that post forms, so that we can run this as a subset within the browser tests.
> Smoke tests

- app/controllers/schools/base_controller.rb
- spec/controllers/schools/session_context.rb
We could do with more debug info for the users triggering the missing URN error
1. Include the user id of the user triggering the issue in the MissingURN exception
> More debug info for missing URNs

- Dockerfile
We should use the newly released Alpine 3.13 release
1. Updated dockerfile base image
1. Do the specs pass
> Upgraded the version of Alpine Linux used

- .github/PULL_REQUEST_TEMPLATE.md
Swapped to reference Trello cards
> Updated pull request template now we've swapped to trello

- app/controllers/schools/csv_exports_controller.rb
- app/models/schools/csv_export.rb
- app/models/schools/csv_export_row.rb
- app/views/schools/csv_exports/show.html.erb
- app/views/schools/dashboards/_account_admin.html.erb
- config/routes.rb
- features/schools/confirmed_bookings/show.feature
- features/schools/csv_export.feature
- features/schools/dashboard.feature
- features/schools/previous_bookings/show.feature
- features/step_definitions/common_school_steps.rb
- features/support/path_helper.rb
- lib/academic_year.rb
- spec/controllers/schools/csv_exports_controller_spec.rb
- spec/controllers/schools/session_context.rb
- spec/factories/bookings/bookings_factory.rb
- spec/lib/academic_year_spec.rb
- spec/models/schools/csv_export_row_spec.rb
- spec/models/schools/csv_export_spec.rb
https://trello.com/c/09FhFUni
We wish to provide our users with a CSV Download feature
1. Add a CSV Download option to the Account admin section of the dashboard
There's lorem ipsum text on the warning box at the moment - this will need replacing before this can be merged
> CSV download

- app/controllers/schools/errors/insufficient_privileges_controller.rb
- app/views/schools/errors/insufficient_privileges/show.html.erb
- config/environments/development.rb
- config/environments/production.rb
- config/environments/servertest.rb
- config/environments/staging.rb
- spec/controllers/schools/errors/insufficient_privileges_controller_spec.rb
- spec/views/schools/errors/insufficient_privileges/show.html.erb_spec.rb
https://trello.com/c/8W3o7HNF
We should provide users with a mechanism to 'self serve' when they lack sufficient permissions.
1. Link through to the 'Request access' page in DfE Sign-in
> Improve DSI experience when users is missing privileges

- app/controllers/schools/dashboards_controller.rb
- app/controllers/schools/organisation_access_requests_controller.rb
- app/views/schools/dashboards/_account_admin.html.erb
- app/views/schools/organisation_access_requests/show.html.erb
- config/routes.rb
- spec/controllers/schools/organisation_access_requests_controller_spec.rb
https://trello.com/c/8W3o7HNF
Users do not always know how to request access to manage school experience at other organisations.
We should explain to the users how they can do this.
1. Added page linking through to the DfE Sign in request access page
> Request privs on dashboard

- app/views/schools/errors/insufficient_privileges/show.html.erb
- app/views/schools/organisation_access_requests/show.html.erb
https://trello.com/c/8W3o7HNF
We should provide clear, correct messaging on how to request access to the school experience service.
1. Remove redundant instruction
> Improve messages for requesting access to school experience via DSI

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/candidates/registrations/resend_confirmation_emails_controller.rb
- app/controllers/schools/base_controller.rb
- app/controllers/schools/sessions_controller.rb
- app/jobs/notify_job.rb
- app/models/schools/attendance.rb
- config/environments/production.rb
- config/initializers/delayed_job.rb
- lib/delayed_notification_plugin.rb
- spec/controllers/candidates/registrations/resend_confirmation_emails_controller_spec.rb
- spec/jobs/notify_job_spec.rb
Reverts DFE-Digital/schools-experience#1652
We're getting release failures to staging - I don't think its related to this but reverting this to verify
> Revert "Drop ExceptionNotifier"

- .rubocop.yml
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- app/controllers/candidates/registrations/resend_confirmation_emails_controller.rb
- app/controllers/schools/base_controller.rb
- app/controllers/schools/sessions_controller.rb
- app/jobs/notify_job.rb
- app/models/schools/attendance.rb
- config/environments/production.rb
- config/initializers/delayed_job.rb
- lib/delayed_notification_plugin.rb
- spec/controllers/candidates/registrations/resend_confirmation_emails_controller_spec.rb
- spec/jobs/notify_job_spec.rb
Reverts DFE-Digital/schools-experience#1654
> Revert "Revert "Drop ExceptionNotifier""

- yarn.lock
https://trello.com/c/r0Z1xkv3
We should keep packages updated
Mass update of various node packages
> Mass update of all npm packages

- azure-pipelines.yml
Reverts DFE-Digital/schools-experience#1663
> Revert "Use cached builds on master as a stopgap fix"

- app/controllers/concerns/dfe_authentication.rb
- app/controllers/schools/change_schools_controller.rb
- app/controllers/schools/switch_controller.rb
- app/models/schools/change_school.rb
- app/views/schools/change_schools/show.html.erb
- config/locales/en.yml
- spec/controllers/concerns/dfe_authentication_spec.rb
- spec/controllers/schools/change_schools_controller_spec.rb
- spec/controllers/schools/switch_controller_spec.rb
- spec/models/schools/change_school_spec.rb
- spec/views/schools/change_schools/show.html.erb_spec.rb
Variable naming in new ChangeSchool model is unclear
1. Replaced naming of model variables
2. Replaced naming of function to assign current school
> Clarified variable naming for Schools::ChangeSchool model

- yarn.lock
> Upgraded npm dependencies

- .github/common_environment.yml
- .github/labeler.yml
- .github/workflows/build.yml
- Dockerfile
- Gemfile
- Gemfile.lock
- docker-compose-paas.yml
- docker-compose.yml
- sonar-project.properties
This PR will BUILD and TEST the docker image, storing it in GHCR. It will run the tests found in the current workflow, and introduces sonarcloud along with additional security checks.
The REVIEW stage fails, due to the PR number not being available in the change, the review stage is mainly commented out as it wasnt intended to work at this point.
Sonarcube has not been run on the master branch at this time, so is not analysing until this PR has been merged.
> Github Actions CI / CD

- .github/workflows/build.yml
- .github/workflows/deploy.yml
- .github/workflows/destroy.yml
- terraform/paas/.gitignore
- terraform/paas/application.tf
- terraform/paas/backend.tf
- terraform/paas/data.tf
- terraform/paas/dev.bk.vars
- terraform/paas/dev.env.tfvars
- terraform/paas/domain.tf
- terraform/paas/provider.tf
- terraform/paas/review.bk.vars
- terraform/paas/review.env.tfvars
- terraform/paas/route.tf
- terraform/paas/services.tf
- terraform/paas/space.tf
- terraform/paas/variables.tf
- tests/confidence/healthcheck.sh
Development Environment
Review  Environment ( Needs Development )
This includes databases and option to just deploy application,
which will be useful in the review deployment.
> Initial Deployment

- app/views/pages/_8da7ae80-82f2-ea11-a815-000d3a44afcc.html.erb
- app/views/pages/privacy_policy.html.erb
- config/environments/development.rb
- config/environments/production.rb
https://trello.com/c/fMj2szXM
The GSE service is using the old privacy policy and needs to be updated to the new one.
Update the privacy policy contents.
@sfawcett123  The CRM_PRIVACY_POLICY_ID env var will possibly need to be updated to `8da7ae80-82f2-ea11-a815-000d3a44afcc`.
> Update the privacy policy

- terraform/paas/application.tf
This is for delivery to PaaS only.
Remove the service binds and get the database name from the service-key
> Fix Database Connection

- Makefile
- terraform/paas/application.tf
- terraform/paas/data.tf
- terraform/paas/provider.tf
- terraform/paas/services.tf
- terraform/paas/staging.env.tfvars
- terraform/paas/statuscake.tf
- terraform/paas/variables.tf
Logging and statuscake added to the Staging Environment
> Logging and Statuscake Added

- .github/workflows/build.yml
- terraform/paas/variables.tf
Artifacts are being created but not uploaded. These all need to be kept, and then pushed into Sonarcloud
> Fix Artifacts

- .gitignore
- Gemfile
- Gemfile.lock
- spec/spec_helper.rb
Code coverage Gem added to allow for better reporting in Sonacloud
> Code Coverage Gem Added

- terraform/paas/application.tf
- terraform/paas/migrate/MIGRATE.md
- terraform/paas/staging.bk.vars
- terraform/paas/staging.env.tfvars
Using the Azure Key-Vault in the staging area
> Staging Vault

- .github/workflows/deploy.yml
Before deployment check that both application and infrastructure secrets YAML files are well formed.
This will prevent terraform leaking secrets if there is an error in the YAML
> Check All Secrets

- .github/workflows/.zap/rules.tsv
- .github/workflows/build.yml
Following the  [Guidence](https://adrianhesketh.com/2020/07/07/owasp-baseline-scan-with-basic-auth-in-docker-github-actions/)
> Fix OWASP Testing

- .github/dependabot.yml
Add Terraform to dependabot checks
> Add Terraform

- yarn.lock
https://trello.com/c/unsJlrbI
Regular maintenance
Upgrade the npm packages
> Upgrade npm packages

- doc/dfe-signin.md
This change is to force the Azure Pipeline to rerun with no software updates, but new variables in the pipeline.
> Dummy Change

- features/step_definitions/schools/dfe_signin_steps.rb
Test PR to trigger the CI build
> Debug azure ci

- package.json
- yarn.lock
https://trello.com/c/POkRKfGC
The webpack-cli package is not really needed.
Remove it from the dependencies
> Remove the webpack-cli package

- app/views/pages/schools_privacy_policy.html.erb
One more email address I missed to update in #1848
> Update another mention to the old help and support email address

- app/helpers/schools/dashboards_helper.rb
- app/models/bookings/placement_request.rb
- app/models/schools/change_school.rb
- app/views/schools/change_schools/show.html.erb
- app/webpacker/stylesheets/alert-counters.scss
- app/webpacker/stylesheets/application.scss
- app/webpacker/stylesheets/school-dashboard.scss
- features/schools/signin.feature
- features/step_definitions/schools/signin_steps.rb
- spec/factories/bookings/bookings_factory.rb
- spec/factories/bookings/placement_request_factory.rb
- spec/helpers/schools/dashboards_helper_spec.rb
- spec/models/bookings/placement_request_spec.rb
- spec/models/schools/change_school_spec.rb
SE-1884
We want to show the outstanding tasks for a given school on the School chooser screen
1. Added a scope to give a 'global' of placement requests requiring attention
2. Extended Schools::ChangeSchool to retrieve those counts for the users organisations
3. Show those counters on the Change school form
> SE-1884 Show counters on change school

- .github/workflows/build.yml
- .github/workflows/deploy.yml
Execute the terraform that will deploy the application to the production environment.
Converted the Code to use Matrix deployments, and then set the matrix up dependant on what the commit type is. 
The application should not be effected.
Code Changed to use a Matrix approach to the deployments, which permits code-reuse.
> Enable Deploy to Production

- Gemfile.lock
Regular maintenance
Upgrading gems to their latest versions
> Upgrade various gems

- terraform/paas/production.env.tfvars
Use the production Key vault now it is available.
> Set Production to use S105p01-kv

- .github/workflows/manual.yml
Manual deploy picks up wrong settings and fails.
> Manual Deploy Fails

- .github/workflows/build.yml
https://trello.com/c/X6vi18G8/195-replace-anchore-with-snyke
Anchore gives far too many false positives and is basically useless, so Snyk scanner implemented and integrated into Snyk.io
> Replace Anchore with Snyk

- app/helpers/application_helper.rb
- app/views/candidates/placement_requests/cancellations/_show_placement_request_cancelled_by_candidate.html.erb
N/A
Updated out chat online link to the talk to us section of GIT.
> Update Chat Online Path

- terraform/paas/migrate/MIGRATE.md
Do not Push, just the Documentation on steps and how to do them for migrating to PaaS
> Document Postgres Export Sequence

- terraform/paas/application.tf
Terraform was setting the variable DFE_SIGNIN_BASE_URL by doing this it causes problems, leave it to the secrets to set it.
> Terraform shouldnt set DFE_SIGNIN_BASE_URL

- app/notify/notify_email/candidate_request_rejection_nopiii.74f84226-539a-43b0-b887-d8ffc9348965.md
Updating the notify template for rejection with new copy.
> Updating a notify template

- app/views/schools/dashboards/_manage_dates.html.erb
- features/schools/dashboard.feature
Before we go to big dashboard improvements, this is a small text change to improve descriptions on one option.
For @leoapost: can you check the tests have been amended correctly?
> Add helptext to change dates and how displayed

- CUCUMBER_TESTING.md
Nothing changed, but forces new docker image, and build.
> Dummy Commit to force build

- app/views/candidates/home/index.html.erb
- app/views/schools/dashboards/_account_admin.html.erb
- app/views/schools/dashboards/_manage_dates.html.erb
- features/schools/dashboard.feature
These are further improvements on the Schools dashboard to improve clarity.
Q: Have the tests been amended correctly?
> Amend more content on dashboard

- app/views/schools/dashboards/_account_admin.html.erb
- app/views/schools/dashboards/_manage_dates.html.erb
- app/views/schools/dashboards/_new_requests_and_bookings.html.erb
- features/schools/dashboard.feature
I've chatted with Binisa on the updates I've made. I'd missed some lines and there were some further refinements.
> Updating more helptext on dashboard

- app/views/pages/_request_organisation_access.html.erb
Based on comment from @B-Bonner
> Fix content

- config/locales/en.yml
- features/schools/toggle_enabling_and_disabling.feature
Updating copy on radio buttons
> Updated radios

- app/views/schools/dashboards/_account_admin.html.erb
- app/views/schools/dashboards/_manage_dates.html.erb
- app/views/schools/dashboards/_new_requests_and_bookings.html.erb
- app/views/schools/dashboards/show.html.erb
- features/schools/csv_export.feature
- features/schools/dashboard.feature
https://trello.com/c/7LLtWwfe
These are the building blocks for an improved IA. We've decided to reorder the list based on GA data of what gets clicks as a proxy for user intent and interest.
Re-order list.
Remove CSV export link from dashboard (needs to be re-introduced elsewhere)
> Updated IA: Post UR 

- app/views/schools/confirmed_bookings/_booking_table.html.erb
- app/views/schools/placement_dates/index.html.erb
- app/views/schools/placement_requests/_placement_requests_table.html.erb
- app/views/schools/previous_bookings/_table.html.erb
- app/views/schools/rejected_requests/index.html.erb
- app/views/schools/withdrawn_requests/index.html.erb
[Trello](https://trello.com/c/xtytmvdp)
Improve accessibility of various tables.
- Make sure all table headers have text - Empty table headers have been flagged as a serious issue by accessibility checkers (axe and WAVE).
- Remove italics from table cell - Some people find italicised text difficult to read and it is not adding any real emphasis.
Example of before and after:
> Table accessibility

- app/helpers/candidates/maps_helper.rb
- app/webpacker/controllers/map_controller.js
- app/webpacker/packs/application.js
- package.json
- yarn.lock
[Trello](https://trello.com/c/nrZOmQPg)
We were sometimes seeing an error that was preventing Google Maps from zooming into the specified location.
To fix use the `js-api-loader` package to avoid the global callback.
- Load Google Maps in Stimulus controller instead of using `javascript_include_tag` to attach a callback to the global object.
- Update to use the Stimulus.js values API - Stimulus recommend passing data to controllers via the values API instead of the data API.
Currently, if you go to a school and refresh a few times you will see a console error and the map will not load properly https://schoolexperience.education.gov.uk/candidates/schools/100027
> Fix Google Maps not loading

- app/views/candidates/schools/show.html.erb
Quick update to meta descriptions.
> Quick update to meta desc

- config/environments/production.rb
https://trello.com/c/S6vpbHLK
We are currently missing useful logs that can help us with troubleshooting
Set the log level to info for production
> Increase the logs in production

- app/views/candidates/registrations/placement_preferences/_form.html.erb
- app/views/candidates/registrations/subject_and_date_informations/_form.html.erb
- app/views/candidates/registrations/teaching_preferences/_form.html.erb
- app/views/schools/contact_us/show.html.erb
- app/views/schools/feedbacks/new.html.erb
- app/views/service_updates/index.html.erb
- app/views/service_updates/show.html.erb
- config/locales/en.yml
- features/candidates/registrations/subject_and_date_information.feature
This is a PR that makes some further changes following the content audit.
> Various content changes

- app/views/candidates/schools/show.html.erb
- spec/views/candidates/schools/show.html.erb_spec.rb
Small content change to earlier PR.
> Add full stop

- app/views/candidates/registrations/placement_preferences/_form.html.erb
https://trello.com/c/fPGzH82A
Analysis of what users typed in this question suggested we could be a bit more general in terms of what they wrote when we asked what they wanted to get out of their school experience.
Update copy to version by @B-Bonner.
Previous:
> Updated copy on 'what do you want to get out of your placement'

- .github/workflows/destroy.yml
Delete terraform state file after instance has been destroyed
> Delete Terraform State File

- features/schools/onboarding/school_profile.feature
- features/step_definitions/schools/dashboard_steps.rb
Recent changes (#2130) broke some feature tests.
> Fix broken feature tests

- app/views/schools/attendances/index.html.erb
- app/views/schools/cancelled_bookings/index.html.erb
- app/views/schools/confirm_attendance/show.html.erb
- app/views/schools/confirmed_bookings/index.html.erb
- app/views/schools/confirmed_bookings/show.html.erb
- app/views/schools/placement_requests/index.html.erb
- app/views/schools/placement_requests/show.html.erb
- app/views/schools/previous_bookings/index.html.erb
- app/views/schools/rejected_requests/index.html.erb
- app/views/schools/withdrawn_requests/index.html.erb
- features/schools/confirm_attendance.feature
- features/step_definitions/schools/confirm_attendance_steps.rb
https://trello.com/c/XgmIuMkr
The structure of the school dashboard pages was changed and the return links need to be adjusted.
Update the text and the styles of the links
> Update the return links in the dashboard pages

- app/views/schools/archived_placement_requests/index.html.erb
> Update the return link in the archived requests page

- config/environments/production.rb
Enable email reminders in production.
> Enable email reminders in production

- app/views/schools/placement_requests/cancellations/_letter.html.erb
https://trello.com/c/L0aZzDbZ
Need to update the content in the cancellation form and preview page to reflect the changes in the Notify template.
Update the content in the letter partial which will update both the form and preview pages.
1. Visit a placement request
2. Click 'Reject request'. The form should have the new content
4. Fill out the form and click preview. The preview page should display the new content
> Update the cancellation email preview

- app/jobs/bookings/reminder_job.rb
- app/jobs/cron/reminders/next_week_job.rb
- app/jobs/cron/reminders/tomorrow_job.rb
- app/notify/notify_email/candidate_booking_reminder.b3e75ee5-61cf-49c5-a145-c0710c54347d.md
- app/notify/notify_sms/candidate_booking_reminder.10aa6a3b-bbe8-4e98-97b2-4409eef47496.md
- app/notify/notify_sms/candidate_booking_reminder.rb
- app/services/bookings/reminder.rb
- spec/jobs/bookings/reminder_job_spec.rb
- spec/jobs/cron/reminders/next_week_job_spec.rb
- spec/jobs/cron/reminders/tomorrow_job_spec.rb
- spec/notify/notify_sms/candidate_booking_reminder_spec.rb
- spec/services/bookings/reminder_spec.rb
[Trello](https://trello.com/c/Vt2y63Sd)
We want to remind candidates that they have School Experience coming up. We will include a cancellation link which will hopefully reduce the amount of non attendances.
To test:
1. Need to be running app locally
2. Log in as school and add a date for tomorrow.
2. Make a request for tomorrow.
3. Log in as a school and accept the request. (you will receive the non-scheduled SMS)
Then:
1. add `config.active_job.queue_adapter = :delayed_job` to `development.rb`
2. Comment out the feature flag in `tomorrow_job.rb` 
3. Add `Delayed::Worker.delay_jobs = false` to the bottom of `delayed_job.rb`.
4. Run `rails db:schedule_jobs`. Should receive SMS for tomorrow's placement. Because of step 3, you wont have to clear your delayed_jobs table.
- Add …
> Add cron sms

- app/views/schools/dashboards/show.html.erb
https://trello.com/c/XekESmCY
Changing the title of the Account home -> School dashboard to be more congruent with how we talk about it.
> Change Account Home -> School Dashboard

- app/views/schools/placement_requests/acceptance/confirm_booking/new.html.erb
- app/views/schools/placement_requests/acceptance/email_preview_sections/_cancellation_details.html.erb
- app/views/schools/placement_requests/acceptance/email_preview_sections/_date_details.html.erb
- app/views/schools/placement_requests/acceptance/email_preview_sections/_dress_code.html.erb
- app/views/schools/placement_requests/acceptance/email_preview_sections/_help_and_support.html.erb
- app/views/schools/placement_requests/acceptance/email_preview_sections/_location.html.erb
- app/views/schools/placement_requests/acceptance/email_preview_sections/_school_experience_contacts.html.erb
- app/views/schools/placement_requests/acceptance/email_preview_sections/_school_experience_details.html.erb
- app/views/schools/placement_requests/acceptance/make_changes/new.html.erb
- app/views/schools/placement_requests/acceptance/preview_confirmation_email/edit.html.erb
- app/webpacker/stylesheets/school-placement-requests.scss
- config/locales/en.yml
- features/schools/placement_requests/acceptance/sending_details_to_candidate.feature
https://trello.com/c/jUAN79Rn
Some of the content in the accept request flow is outdated.
Update the content in the acceptance pages
> Update the content in the accept request flow

- .github/workflows/check_sp.yml
Incorrect SP name was entered, wont be a problem as user does not have access to the one that was entered. but I should look if I cut and paste 👍🏻 
Can wait a little until SNOW - RITM0296704 completed
> Use correct Service Principle

- data/service_updates/20220124.yml
- data/service_updates/20220127.yml
January 2022 service update.
https://trello.com/c/v1jR6hBt
January 2022 service update.
New service update.
Check whether the opening line is being pulled into the Service update banner that should display at the top of the dashboard.
You can also view the content by clicking on the Service updates section at the bottom of the dashboard.
> Create January 2022 service update

- features/candidates/registrations/experience_preference.feature
- features/schools/dashboard.feature
N/A
Cucumber reports feature tests with undefined steps caused by typos and by using wrong step definitions.
- Fix the typos 
- Use the correct step definitions
> Fix the feature tests with undefined steps

- .github/workflows/check_sp.yml
Correct the name of the Service Principle
> Correct Name of Service Principle

- terraform/paas/dev.env.tfvars
Add delayed jobs to development deployments
> Add delayed Jobs to Development

- doc/database-migrations.md
- terraform/paas/review.env.tfvars
Run migrations when deploying to the Review Instance.
> Change Review Migration Strategy

- doc/manual-terraform.md
- terraform/paas/provider.tf
- terraform/paas/variables.tf
A quick brief on how to run terraform manually and some simple subtle changes to make it easier to do so
> Running Terraform Manually

- features/support/assets.rb
- features/support/cache.rb
https://trello.com/c/wvVsEM0g
Replace deprecated AfterConfiguration hook with BeforeAll.
> Replace deprecated AfterConfiguration hook

- Gemfile
- Gemfile.lock
- script/docker-entrypoint.sh
- terraform/paas/review.env.tfvars
It looks like the  [webrick](https://github.com/yabeda-rb/yabeda-prometheus) gem is required, which when I added seems to make it work in review,
> Run via Bundle

- app/controllers/concerns/schools/placement_dates/wizard.rb
- app/controllers/schools/placement_dates/configurations_controller.rb
- app/controllers/schools/placement_dates/subject_selections_controller.rb
- app/controllers/schools/placement_dates_controller.rb
- spec/controllers/schools/placement_dates_controller_spec.rb
https://trello.com/c/OxOJ4NK3
We are going to be adding a few more steps to the placement dates creation.
Move the next step into a wizard concern so that we can easily add new steps and handle more complicated logic.
> Move next step into wizard concern

- config/routes.rb
- spec/factories/bookings/placement_dates.rb
These appear to be behaving in staging now so switching on in prod.
> Enable metrics in production

- Dockerfile
- README.md
https://trello.com/c/daclSr5Z
Build failures: https://github.com/DFE-Digital/schools-experience/runs/5481404771?check_suite_focus=true
- Update base image
- Pin gmp version
- Security check should pass
- App should be compatible with new software versions, especially node is upgraded to 16
> [570] Fix gmp security vulnerability

- app/views/schools/placement_dates/new.html.erb
The legend of this page is used as the title as well. Make sure it's a h1.
> Make sure page has a h1

- features/step_definitions/form_steps.rb
Merged a change before the Cucumber tests had chance to run, which caused a few to break.
> Fix Cucumber tests

- app/views/candidates/registrations/placement_requests/show.html.erb
- spec/features/candidates/api_registrations_spec.rb
https://trello.com/c/gwuUsHa7
- Add button to candidate dashboard to request confirmation page
> Add button to candidate dashboard to request confirmation page

- app/views/schools/on_boarding/disability_confidents/_form.html.erb
- config/locales/en.yml
- features/schools/onboarding/disability_confident.feature
https://trello.com/c/3U3I9cr2
Content updates in the Disability Confident question
- Updated the content
- Updated the error message
|Before|After|
|-|-|
|![before](https://user-images.githubusercontent.com/951947/158426077-62c7bb5a-93e6-41b9-845e-a6874e4abe86.png)|![after](https://user-images.githubusercontent.com/951947/158426098-8a813a4d-0549-4bbb-bc05-1e76f534491f.png)|
> Update content in the Disability Confident question

- spec/views/candidates/schools/index.html.erb_spec.rb
#2383 broke some feature tests. This PR fixes them
> Fix the sorting info feature tests

- app/views/schools/on_boarding/admin_contacts/_form.html.erb
- config/locales/en.yml
- features/schools/onboarding/admin_contact.feature
https://trello.com/c/X1nvOFvQ
- Update content on the admin details page
**Before**
**After**
> Update content on the admin details page

- app/views/schools/on_boarding/access_needs_details/_form.html.erb
- config/locales/en.yml
- features/schools/onboarding/access_needs_detail.feature
https://trello.com/c/De348bY5
We want to improve the content in the Access needs question.
- Add a heading
- Update the content
- Update the feature tests
|before|after|
|-|-|
|![before](https://user-images.githubusercontent.com/951947/158420305-753b12a4-1c80-4325-97cd-283e1ad5fa1d.png)|![after](https://user-images.githubusercontent.com/951947/158420564-a611af99-3a5d-4846-8f7c-a58e924a2155.png)|
> Update the content in the Access Needs question

- app/helpers/schools/bookings_helper.rb
- app/webpacker/stylesheets/school-bookings.scss
- spec/helpers/schools/bookings_helper_spec.rb
Changing more tags.
We might be able to remove some CSS for --unavailable tags. Worth checking.
> Updating colours to less strong

- Dockerfile
See https://security.snyk.io/vuln/SNYK-ALPINE315-LIBRETLS-2428776
> Upgrade libretls to patch vulnerability

- terraform/paas/dev.env.tfvars
We are currently on v11 and want to get to v13 but need to upgrade one version at a time.
> Upgrade Postgres to v12 in dev environment

- app/models/schools/attendance.rb
- spec/controllers/schools/confirm_attendance_controller_spec.rb
- spec/models/schools/attendance_spec.rb
- Swap withdrawn for did not attend
> Swap withdrawn for did not attend

- docs/documents/env-vars.md
Review and document all application secrets
Documentation fixes
Read the doc
> [529] Small fixes to env vars documentation

- .tool-versions
- Makefile
- terraform/paas/dev.bk.vars
- terraform/paas/production.bk.vars
- terraform/paas/review.bk.vars
- terraform/paas/staging.bk.vars
Make it easier to run terraform commands locally for troubleshooting
Add Makefile targets and missing configuration
Run the terraform commands
> [648] Run terraform locally

- docs/documents/DevOps/tools/trello.md
https://trello.com/c/974QXSAh
The trello job is broken
Replaced Steve's trello user with new service account
See comment in https://trello.com/c/974QXSAh
> [602] Update Readme with Trello instructions

- app/presenters/candidates/school_presenter.rb
- app/presenters/schools/on_boarding/school_profile_presenter.rb
- config/locales/en.yml
- features/schools/onboarding/dbs_required_toggling_fees.feature
- features/schools/onboarding/dbs_requirements.feature
- features/step_definitions/schools/onboarding_steps.rb
- spec/presenters/candidates/school_presenter_spec.rb
- spec/presenters/schools/on_boarding/school_profile_presenter_spec.rb
[Trello-509](https://trello.com/c/Wj7rZ1Ph/509-redesign-dbs-question)
Update the title and radio copy to be clearer. Mirror the change in other locations where we present the same DBS requirement text.
- Update copy on the DBS requirements step
> Update copy on the DBS requirements step

- .github/workflows/check_sp.yml
The GitHub action is being updated and we need to make some changes to the workflow to support these new changes.
- Correct some naming
- Update comparison operator
- Tidy-up Slack message and links
https://github.com/DFE-Digital/schools-experience/actions/runs/2845513523
> Update workflow for check service principal action

- .github/workflows/actions/deploy/action.yml
- .github/workflows/destroy.yml
- .tool-versions
- docs/index.md
- terraform/paas/.gitignore
- terraform/paas/.terraform.lock.hcl
- terraform/paas/provider.tf
Ensure the Terraform version contains the latest fixes and supports Apple processors
> Update Terraform version to 1.2.8

- feature-flags.json
Enable the feature in production.
> Enable task progress on-boarding in production

- terraform/paas/.terraform.lock.hcl
- terraform/paas/provider.tf
https://trello.com/c/Or8Y4W6H
Ensure the azurerm provider version is pinned so that the same version is always used.
Pin and update azurerm provider version
> Pin azurerm provider version

- app/models/bookings/school_search.rb
- spec/models/bookings/school_search_spec.rb
[Trello-657](https://trello.com/c/8VxYNNts/657-investigate-pg-characternotinrepertoire-error)
Debug PG::CharacterNotInRepertoire error We are seeing this error reasonably frequently; I've no idea how its happening yet though but I expect a person/bot is searching using unexpected ASCII characters.
Add debug logging to figure out what the searches are that cause it and attempt to recover. 
- Debug PG::CharacterNotInRepertoire error
Oddly Sentry reports this as part of an `ActionView::TemplateError`, however its on the call to `save` so I think this is a red-herring and the underlying exception was an `ActiveRecord::StatementInvalid` which makes more sense and is repeatable in the tests.
> Debug PG::CharacterNotInRepertoire error

- .github/workflows/actions/deploy/action.yml
- .github/workflows/build-no-cache.yml
- .github/workflows/build.yml
- .github/workflows/check_sp.yml
- .github/workflows/destroy.yml
https://trello.com/c/3s3iC7UV
The set-output command is being deprecated soon.
Resolution is to use $GITHUB_OUTPUT as per the workflow commands docs.
Confirm updated workflows tested where possible:
> 700 update set output usage

- app/forms/schools/on_boarding/wizard.rb
- config/locales/en.yml
- spec/forms/schools/on_boarding/wizard_spec.rb
https://trello.com/c/B7NGYayf/645-move-the-safeguarding-section-to-section-3-of-the-onboarding-flow
> Change order of safeguarding and fees section

- app/jobs/cron/identify_closed_schools_job.rb
- spec/jobs/cron/identify_closed_schools_job_spec.rb
[Trello-654](https://trello.com/c/ezsFNMZg/654-add-line-breaks-into-school-closed-reminder-email)
We send a periodic email to our support team where we identify schools that are now closed according to the GIAS school dataset, however they are still marked as on-boarded with School Experience.
Currently we just send a list of the schools without any structure; instead, we want to group the schools under various headings and format them with bullet points (which the GOV.UK notify service will correctly format in emails).
- Improve structure of closed/on-boarded schools email
Example email:
> Improve structure of closed/on-boarded schools email

- app/views/candidates/registrations/placement_requests/show.html.erb
N/A
Agreed as a quick thing we could do to drive additional sign ups. Some placeholder text in here for now.
Add some content to the confirmation page on GSE for TTA sign up.
> Add TTA Sign Up link on GSE completion page

- README.md
- docs/documents/disaster-recovery.md
- docs/documents/release-process.md
[Trello-4559](https://trello.com/c/uyNQzQLv/4559-check-app-api-documentation-is-up-to-date)
Update the README and other technical documentation to make it relevant to how the application is today.
- Update README and documentation
> Update README and documentation

- terraform/aks/config/development.tfvars.json
- terraform/aks/database.tf
**Context**  
Deploy Redis
**Changes proposed in this pull request**  
Add redis resource in aks using terraform-modules  
**Guidance to review**
make development_aks terraform-apply-aks
> Deploy redis

- terraform/aks/application.tf
- terraform/aks/database.tf
Deploy Application
add application  to AKS using terraform modules
make development_aks terraform-apply-aks
> Deploy application

- config/environments/development.rb
- config/environments/staging.rb
> Change url to API

- config/initializers/yabeda.rb
> Add initializer for non vcap application

- .github/workflows/destroy_aks.yml
https://trello.com/c/kPYzi2gv/678-se-delete-aks-review-app-workflow
added the destroy function so that review apps are destroyed after closing PR
added destroy_aks.yml
make ci review_aks terraform-destroy-aks PR_NUMBER=${{github.event.number}}
> Added destroy review apps to workflow

- .github/common_environment.yml
- .github/workflows/actions/deploy_v2/action.yml
- .github/workflows/build.yml
- Makefile
- script/get_next_mapping_aks.sh
- terraform/aks/application.tf
- terraform/aks/output.tf
- terraform/aks/variables.tf
WHY: DFE sign in is a requisite part of the project
HOW: mimic what PAAS is doing with Routes using k8 ingress
https://trello.com/c/8Pz4dmqP/668-enable-dfe-sign-in-on-aks-review-apps
the aim is to create a similar dfe sign in functionality to that of paas on aks
added get_next_mapping_aks.sh which mimcs existing get_next_mapping.sh using ingresses
make review_aks terraform-plan-aks PR_NUMBER=777
> Added DFE sign in to Review apps on AKS

- .github/workflows/actions/deploy_v2/action.yml
- .github/workflows/build.yml
- Makefile
- script/get_next_mapping_aks.sh
- terraform/aks/application.tf
- terraform/aks/config/development.tfvars.json
- terraform/aks/config/production.tfvars.json
- terraform/aks/config/review.tfvars.json
- terraform/aks/config/staging.tfvars.json
- terraform/aks/variables.tf
> testing get_next_mapping_aks.sh

- .github/workflows/actions/deploy_v2/action.yml
https://trello.com/c/nzPVjeyQ/796-fix-school-experience-review-app-url
fix bug in order to exclude k8 setup when environmewnt is not Review
https://github.com/DFE-Digital/schools-experience/actions/runs/7003893611/job/19051079874
if: inputs.environment == "review"
the deployment does not fail
> Skip k8 setup when env is not review

- .github/workflows/build.yml
- Dockerfile
https://trello.com/c/Ge2pVSiA
Fix build: https://github.com/DFE-Digital/schools-experience/actions/runs/7446986156/job/20258365596
- Remove pinned 1.15.3 version which is not in use anymore
- Remove bundle extra platforms to use the default ones from
Gemfile.lock
Also fixed the slack notification when the build fails.
Check the successful build
> [884] Bug school experience build failing

- config/routes.rb
- terraform/aks/application.tf
https://trello.com/c/cgESA7Zy/862-implement-aks-healthcheck-school-experience
add healthcheck endpoint to app
return 200 ok 
visit /check endpoiint
> added healthcheck

- .tool-versions
- config/environments/production.rb
https://trello.com/c/cgESA7Zy/862-implement-aks-healthcheck-school-experience
fix healthcheck buug
> fix routes issues

- .github/workflows/actions/deploy/action.yml
- .github/workflows/build.yml
- tests/confidence/healthcheck.sh
https://trello.com/c/98MCb9lF/873-implement-smoke-test-school-experience
add smoke test to app
pass new endpoint to bash script
curl -o /dev/null -s -w "%{http_code}"  https://get-school-experience-production.teacherservices.cloud/healthcheck
> implement smoke test

- .github/workflows/actions/database-backup/action.yml
- .github/workflows/actions/deploy/action.yml
- .github/workflows/destroy.yml
- Makefile
- terraform/aks/.terraform.lock.hcl
- terraform/aks/terraform.tf
https://trello.com/c/3m8PNLG6/937-enable-azure-rbac-deployment-on-all-services
Replace get-credentials with make get-cluster-credentials 
Update kubernetes Provider make review get-cluster-credentials
Updated done for github actions to use
> RBAC changes implemented

- .github/workflows/actions/database-backup/action.yml
https://trello.com/c/RnXWAXvO/943-bug-school-experience-db-backup-is-failing
Fixed pipeline failures : https://github.com/DFE-Digital/schools-experience/actions/runs/7750044032/job/21135654394
Added set-kubelogin-environment action .
> Fixed DB backup pipeline failures

- .github/workflows/actions/database-backup/action.yml
- .github/workflows/db_backup.yml
Trello card
https://trello.com/c/RnXWAXvO/943-bug-school-experience-db-backup-is-failing
Context
Fix the issue with db backup for school experience
Changes proposed in this pull request
pass in the azure credentials and fix syntax error
Guidance to review
run pipeline successfully
> Fixed db backup failure

- .github/workflows/actions/database-backup/action.yml
- .github/workflows/db_backup.yml
https://trello.com/c/98AVEISc/1640-se-backup-failing
prod db backup step is failing.
Fix to use correct azure credential
also remove code that isn't required
check test run at https://github.com/DFE-Digital/schools-experience/actions/runs/8064213150
> Fix database backup

- app/views/schools/users/_form.html.erb
- app/views/schools/users/index.html.erb
- app/views/schools/users/show.html.erb
- Changes cancel Link to a button 
- Style buttons in user invite page
Before:
After:
Before:
After:
> Invite Update buttons

- app/views/schools/change_schools/show.html.erb
- app/views/schools/dashboards/_help_and_support.html.erb
- app/views/schools/users/index.html.erb
- features/schools/dashboard.feature
Based on this review feedback:
https://github.com/DFE-Digital/schools-experience/pull/3102#issuecomment-2032081928
> Help links update

- app/views/layouts/application.html.erb
- app/views/pages/terms_and_conditions.html.erb
- config/routes.rb
https://trello.com/c/TJYmZZaI
We are creating a terms and conditions page to ensure we have sufficient legal cover for our activities.
Create the Ts and Cs page based on pre-existing draft
- Does this read ok?
- Does it match the draft?
- Do you agree with my comment on a H4 with regards to accessibility?
> Create Ts and Cs page

- data/service_updates/20240402.yml
https://trello.com/c/q07B9Cin
- At some point we're going to remove service updates due to limited usage, but as a stopgap, and because we're shipping some major changes to how we manage users, we're putting a service update out
- This will replace the previous service update that renders on the Manage school experience dashboard, which is from March 2022. Showing that is a poor experience for users.
- Add service update
**Dashboard**
**Update page**
- Does this render once you navigate to a school's dashboard ✅ 
- Does it work if you click the link from the bottom of the school dashboard ✅ 
- Does the content look ok?
> Create new service update

- terraform/aks/config/production.tfvars.json
- terraform/aks/config/staging.tfvars.json
- terraform/aks/statuscake.tf
- terraform/aks/variables.tf
https://trello.com/c/Z6eliKhq/1654-review-statuscake-contact-groups
added infra team contact group
added infra team contact group
make production terraform-plan
> Added infra team group to statuscake

- app/views/schools/change_schools/show.html.erb
- app/views/schools/errors/auth_failed/show.html.erb
- spec/views/schools/change_schools/show.html.erb_spec.rb
> Re add request access button on DSI work

- app/models/candidates/placement_date_option.rb
- app/views/candidates/schools/profile/_placement_dates.html.erb
https://trello.com/c/NOHbwt7v
**Before** - Holland Park with multiple dates added with all subjects ticked
**After**
> Fix placement_date_option.rb to handle nil bookings_subject

- app/services/candidates/registrations/subject_and_date_information.rb
- db/data/subjects.yml
- spec/services/candidates/registrations/subject_and_date_information_spec.rb
Reverts DFE-Digital/schools-experience#3169
> Revert "Refactor `#placement_date_subject`"

- app/views/schools/dashboards/_requests_and_bookings.html.erb
- features/schools/dashboard.feature
> Remove capitalisation on word 'Bookings'

- README.md
- docs/documents/dfe-signin.md
- docs/documents/mse-user-invite.md
https://trello.com/c/S08VmyK0/5913-review-and-update-developer-documentation-for-get-school-experience
Update the dev docs to be more current with the changes in the application.
* Update README.md with updated Ruby and Bundler versions, NodeJS version, and other dependencies
* Update DfE Sign-in integration documentation
* Add documentation for inviting users to school's DFE Sign in via Manage School Dashboard
> Update Dev docs

- app/helpers/application_helper.rb
- app/views/schools/confirmed_bookings/index.html.erb
- app/views/schools/csv_exports/_form.html.erb
- config/initializers/phase_three_release_date.rb
https://trello.com/c/eQUZyVHX
- This copy is incredibly old, and most schools that are now onboarded weren't onboarded 5 years ago.
- We should remove it
_**Before**_
_**After**_
> Remove outdated copy in bookings page.

- app/views/pages/terms_and_conditions.html.erb
- app/views/schools/on_boarding/profiles/onboarding.html.erb
> Update Ts and Cs following further advice

- app/views/schools/change_schools/show.html.erb
- app/views/schools/csv_exports/_form.html.erb
- app/views/schools/csv_exports/show.html.erb
- app/views/schools/placement_requests/show.html.erb
https://trello.com/c/QHKZbml7
- We know that button grouping is not implemented as it should be based on the design system
- This has been fixed in some areas in preious PRs
- This PR covers the final set
- Group button and link on the 'change school' dashboard
- Group button and link on CSV export
- Group buttons on our accept/reject request page 
For the accept/reject request page, go to this page whilst being logged in as Outwood Academy Acklam: https://get-school-experience-review-pr-3.test.teacherservices.cloud/schools/placement_requests/370
> Further improve button grouping

- app/views/schools/on_boarding/profiles/onboarding.html.erb
https://trello.com/c/jxp1EyiP
- An issue we found during demo
- remove duplicative content
> Fix onboarding agreement

- app/views/schools/dashboards/_help_and_support.html.erb
- features/schools/dashboard.feature
- https://trello.com/c/hT6PKCKr
- This copy is not hugely accessible. This change improves the readability of the sentence.
**Before**
**After**
> Improve contact us section content

- terraform/aks/application.tf
- terraform/aks/config/development.tfvars.json
- terraform/aks/config/review.tfvars.json
- terraform/aks/config/staging.tfvars.json
- terraform/aks/variables.tf
https://trello.com/c/bjfo0jo9/1812-onboard-services-to-logitio.
Service Onboard to Logit.io for review and staging.
Add enable_logit:true to aks review and staging environments.
Review App Logs  : 
https://kibana-uk1.logit.io/s/b2876053-0173-44fc-983d-99567292ba31/app/data-explorer/discover#?_a=(discover:(columns:!(_source),isDirty:!f,sort:!()),metadata:(indexPattern:'filebeat-*',view:discover))&_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30m,to:now))&_q=(filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:'8ac115c0-aac1-11e8-88ea-0383c11b333a',key:kubernetes.namespace,negate:!f,params:(query:git-development),type:phrase),query:(match_phrase:(kubernetes.namespace:git-development)))),query:(language:kuery,query:%22get-school-experience-review-pr-3209% …
> Service Onboard to Logit.io

- terraform/aks/config/production.tfvars.json
https://trello.com/c/bjfo0jo9/1812-onboard-services-to-logitio
Push production  logs to logit.io
enabled logit.io for prod
> logit.io enabled on prod

- .github/workflows/actions/database-backup/action.yml
- .github/workflows/actions/deploy/action.yml
Some github workflows are running old versions of actions
Update to current version
Check workflows run successfully
> Update github actions versions

- Dockerfile
I ran into an issue building this on my M1 machine.
https://stackoverflow.com/a/71014474
https://nokogiri.org/tutorials/installing_nokogiri.html#solution_3
Adds the `gcompat` package which resolved my build issues with nokogiri on apple silicon.
> Fix Docker not building with Apple Silicon

- .github/workflows/build.yml
- azure-pipelines.yml
Fix issue with build pipeline - [see this discussion](https://github.com/orgs/community/discussions/116610)
> update docker compose following build errors

- Gemfile
- Gemfile.lock
- app/models/bookings/registration_contact_mapper.rb
[Candidate registers for a school experience](https://trello.com/c/Lqzdt6iX/6285-ensure-that-when-a-candidate-registers-for-a-school-experience-a-qualification-record-is-created-in-the-crm-system)
When candidates register for a school experience, the synchronisation with the CRM was triggering duplicate qualification records. 
Update GiT API version
> Update git api library to 3.4.0 and save degree title

- Gemfile
- Gemfile.lock
- config/analytics_hidden_pii.yml
- config/analytics_pii.yml
https://trello.com/c/ZmOecK5P/6554-upgrade-dfe-analytics-for-get-school-experience-to-support-hidden-pii
The Data and Insights team are doing some work across the whole of Teacher Services to enable sensitive PII to be hidden in Big Query.
1. upgrade dfe-analytics from v1.12.7 to v1.14.2
2. copy the contents of analytics_pii.yml to analytics_hidden_pii.yml
3. update contents of analytics_pii.yml to: :shared: {}
> Updating dfe analytics

- docs/documents/powerbi.md
https://trello.com/c/Q8wSaJR2/2060-update-gse-powerbi-sp-creds
Update powerbi doc with instructions for renewing the Azure App registration secret 
doc update
Check the update makes sense and meets requirements
> Update powerbi doc with SP renewal instructions

- app/views/pages/terms_and_conditions.html.erb
Updated to allow people to publish on GSE on behalf of schools, with the schools authority
> Update terms and conditions to allow authorised people to publish on school's behalf

- terraform/aks/config/development.tfvars.json
https://trello.com/c/YUxcTtXB
Enable Bigquery federated auth in all environments
Enable in AKS development
Same configuration as review
> [2110] Enable Bigquery federated auth in development AKS

- terraform/aks/config/staging.tfvars.json
https://trello.com/c/YUxcTtXB
Enable bigquery federated auth in all environments, one by one
Enable bigquery federated auth in staging
Same configuration as developmemt
> [2110] Enable bigquery federated auth in staging

- terraform/aks/config/production.tfvars.json
https://trello.com/c/YUxcTtXB
Enable bigquery federated auth in all environments, one by one
Enable bigquery federated auth in production
Same configuration as staging
> [2110] Enable bigquery federated auth in production

- .github/workflows/deploy.yml
https://trello.com/c/E83HBQc9/2189-gse-plan-for-dr-test
Fix manual deploy workflow
Add new deploy workflow that doesn't use github releases
Add missing variables to workflow
new workflow: https://github.com/DFE-Digital/schools-experience/actions/runs/12769520729
> Fix manual deploy workflow

- terraform/aks/application.tf
- terraform/aks/config/development.tfvars.json
- terraform/aks/config/production.tfvars.json
- terraform/aks/config/staging.tfvars.json
- terraform/aks/variables.tf
https://trello.com/c/tQZmN3cZ
Application behaviour change should be accomplished via simple config change
Add a tf variables and set its default value to false
When the variable is set the traffic should be routed to the maintenance page
> Add tf variable for sending traffic to maintenance page

- .github/workflows/actions/database-backup/action.yml
- .github/workflows/actions/deploy/action.yml
- .github/workflows/build-no-cache.yml
- .github/workflows/build.yml
- .github/workflows/db_backup.yml
- .github/workflows/deploy.yml
- .github/workflows/destroy.yml
- .github/workflows/maintenance.yml
- .github/workflows/manual.yml
- .github/workflows/postgres-ptr.yml
- .github/workflows/postgres-restore.yml
- .github/workflows/trello.yml
- terraform/aks/.terraform.lock.hcl
- terraform/aks/terraform.tf
- terraform/aks/variables.tf
https://trello.com/c/FWUebqgi/2201-github-actions-oidc-for-all-services
Update github workflows to use OIDC using Azure workload identity federation
workflow updates for schools experience
See build and deploy review app logs.
> Update schools experience workflows to use ga wif

- app/models/bookings/data/school_mass_importer.rb
- app/models/bookings/data/school_updater.rb
- app/models/concerns/edubase_data_helpers.rb
- spec/models/bookings/data/school_mass_importer_spec.rb
- spec/models/bookings/data/school_updater_spec.rb
[Fix sync of school data in GSE](https://trello.com/c/pQPU8Pn9/7510-fix-synch-of-school-data-in-get-school-experience)
The update process ignores website when updating schools data
Add website to list of fields to update
> fix schools data updater

- Makefile
- terraform/aks/terraform.tf
https://trello.com/c/FWUebqgi/2201-github-actions-oidc-for-all-services
Configure kubeconfig for Azure AD authentication AAD_LOGIN_METHOD
makefile updates for schools experience
See build and deploy review app logs.
https://github.com.mcas.ms/DFE-Digital/schools-experience/actions/runs/13546606862/job/37861124618
> Configure kubeconfig for Azure AD authentication AAD_LOGIN_METHOD

- .github/workflows/actions/database-backup/action.yml
- .github/workflows/build-no-cache.yml
- .github/workflows/build.yml
- .github/workflows/db_backup.yml
- .github/workflows/deploy.yml
- .github/workflows/manual.yml
- terraform/domains/environment_domains/output.tf
https://trello.com/c/qyXB3RQA/1972-implement-ci-cd-for-domains-on-all-services
Adding steps for CICD
Adding steps for CICD to build.yml
Have set the slack webhook as a secret at the repo level to remove dependency on fetch slack script to reduce code duplication as part of PR.
Validate workflows for development, staging, production:
Development: https://github.com/DFE-Digital/schools-experience/actions/runs/13765630241/job/38491293167?pr=3379
Staging: https://github.com/DFE-Digital/schools-experience/actions/runs/13765788684/job/38491803369
Production: https://github.com/DFE-Digital/schools-experience/actions/runs/13765796246/job/38491825693
> CICD Domains for GSE

- config/analytics.yml
- config/analytics_blocklist.yml
- config/analytics_hidden_pii.yml
[Update hidden PII for admin contact](https://trello.com/c/Y5B96Hoj/7952-unblock-admin-telephone-number-for-manage-school-experience-contacts)
We need to be able to find out who school admin contacts are for Get school experience
Add admin phone number to hidden PII fields
> Update hidden pii admin contact phone

- .github/workflows/build-no-cache.yml
- .github/workflows/build.yml
- Dockerfile
Updating the build and build-no-cache workflows to use the build docker image action.
Workflow changes required for the updated action, which allows maintaining the current configuration but using the action
build-no-cache: https://github.com/DFE-Digital/schools-experience/actions/runs/16174592917
build: tba
change action branch before merge
> use build-docker-image github action

- .github/workflows/restore-deleted-postgres.yml
- add new functionality: a new workflow to recover a deleted postgres db
- add new workflow to recover a deleted postgres db
https://github.com.mcas.ms/DFE-Digital/schools-experience/actions/runs/17293353544/job/49085643066
https://trello.com/c/QANXFMhR/2447-add-recover-deleted-postgres-workflow
N/A
> feat(2447):  gse: add recover postgres db workflow
